### ISSUE TITLE
Exception from GLBackend when operating with gnupg on /dev/shm

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#1095]
Source: Linux XXXXXX 2.6.32-20-pve #1 SMP Wed May 15 08:23:27 CEST 2013 i686
Version: 2.60.27
OSError OS system call failed.
Traceback (most recent call last):

  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1097, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)

  File "/usr/local/lib/python2.7/dist-packages/twisted/python/failure.py", line 389, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)

  File "/usr/lib/python2.7/dist-packages/globaleaks/jobs/pgp_check_sched.py", line 53, in operation
    yield self.pgp_validation_check()

  File "/usr/local/lib/python2.7/dist-packages/twisted/python/threadpool.py", line 191, in _worker
    result = context.call(ctx, function, *args, **kwargs)

  File "/usr/local/lib/python2.7/dist-packages/twisted/python/context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)

  File "/usr/local/lib/python2.7/dist-packages/twisted/python/context.py", line 81, in callWithContext
    return func(*args,**kw)

  File "/usr/lib/python2.7/dist-packages/globaleaks/settings.py", line 806, in _wrap
    result = function(self.instance, self.store, *args, **kwargs)

  File "/usr/lib/python2.7/dist-packages/globaleaks/jobs/pgp_check_sched.py", line 34, in pgp_validation_check
    gnob = GLBGPG(fake_receiver_dict)

  File "/usr/lib/python2.7/dist-packages/globaleaks/security.py", line 302, in __init__
    raise excep

OSError: [Errno 31] Too many links: \\'/dev/shm/globaleaks/gnupg/2NbJvOFJ\\'

**Comment by vecna** [comment]
soon will be addressed with #1096, is the same

**Comment by evilaliv3** [comment]
mmm @vecna your fix is correct but applied to a different piece of code. i'm going to fix it in devel branch globally.

and in general also please do not put fix like this in branches that are totally unrelated. better if you simply apply the fix directly in devel branch.
