### ISSUE TITLE
Exception triggered re-enabling notification after have kept them disabled

### ISSUE THREAD

**Issue by vecna** [globaleaks/GlobaLeaks#1115]
Traceback (most recent call last):
	  File "/home/qq/.virtualenvs/backend/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 382, in callback
	    self._startRunCallbacks(result)
	  File "/home/qq/.virtualenvs/backend/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 490, in _startRunCallbacks
	    self._runCallbacks()
	  File "/home/qq/.virtualenvs/backend/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 577, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/qq/.virtualenvs/backend/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1155, in gotResult
	    _inlineCallbacks(r, g, deferred)
	--- <exception caught here> ---
	  File "/home/qq/.virtualenvs/backend/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1099, in _inlineCallbacks
	    result = g.send(result)
	  File "/home/qq/Dev/GlobaLeaks/backend/globaleaks/jobs/notification_sched.py", line 368, in operation
	    if any([len(files_events), len(messages_events),
	exceptions.TypeError: object of type 'FileEventLogger' has no len()

**Comment by vecna** [comment]
Managed days ago

**Comment by evilaliv3** [comment]
if you remember the commit just as reference remember to put it somehou in the ticket just as documentation.

and remember to assign as last the mileston of the mount you addressed it so that we have also a way to see what was adressd during a particular month
