### ISSUE TITLE
Exception on alarm.report_disk_usage: TypeError: %d format: a number is required, not str

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#1138]
TypeError Inappropriate argument type.

Traceback (most recent call last):

  File "/usr/lib/python2.7/dist-packages/globaleaks/jobs/base.py", line 22, in _operation
    self.operation()

  File "/usr/lib/python2.7/dist-packages/globaleaks/jobs/statistics_sched.py", line 156, in operation
    alarm.report_disk_usage(free_bytes)

  File "/usr/lib/python2.7/dist-packages/globaleaks/anomaly.py", line 498, in report_disk_usage
    log.info("Warning: free space alarm (MEDIUM): %d" % free_memory_str)

TypeError: %d format: a number is required, not str

**Comment by evilaliv3** [comment]
fixed!
