### ISSUE TITLE
Unhandled unicode exception while checking for file existance in BaseStaticFileHandler

### ISSUE THREAD

**Issue by evilaliv3** [globaleaks/GlobaLeaks#1248]
An Exception has been scattered by the ALAC setup in relation to the request by an user on a unicode file. it seems that when an user explicitly ask for a unicode the system fails in checking it's existance.

the full stack trace follows:

    UnicodeEncodeError Unicode encoding error.

    Traceback (most recent call last):

      File "/usr/local/lib/python2.7/dist-packages/cyclone/web.py", line 1073, in _deferred_handler
        result = function(*args, **kwargs)

      File "/usr/lib/python2.7/dist-packages/globaleaks/handlers/base.py", line 597, in get
        if not os.path.exists(abspath) or not os.path.isfile(abspath):

      File "/usr/lib/python2.7/genericpath.py", line 18, in exists
        os.stat(path)

    UnicodeEncodeError: 'ascii' codec can't encode character u'\xe4' in position 76: ordinal not in range(128)

**Comment by evilaliv3** [comment]
wrong reference in previous commit.

the issue is still to be investigated; going to do it now.

**Comment by evilaliv3** [comment]
while debugging the issue i was able to scatter an other exception:

    TypeError Inappropriate argument type.

    Traceback (most recent call last):

      File "/home/evilaliv3/Devel/GlobaLeaks/backend/glenv/local/lib/python2.7/site-packages/Twisted-13.2.0-py2.7-linux-x86_64.egg/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
        why = selectable.doRead()

      File "/home/evilaliv3/Devel/GlobaLeaks/backend/glenv/local/lib/python2.7/site-packages/Twisted-13.2.0-py2.7-linux-x86_64.egg/twisted/internet/tcp.py", line 215, in doRead
        return self._dataReceived(data)

      File "/home/evilaliv3/Devel/GlobaLeaks/backend/glenv/local/lib/python2.7/site-packages/Twisted-13.2.0-py2.7-linux-x86_64.egg/twisted/internet/tcp.py", line 221, in _dataReceived
        rval = self.protocol.dataReceived(data)

      File "/home/evilaliv3/Devel/GlobaLeaks/backend/glenv/local/lib/python2.7/site-packages/Twisted-13.2.0-py2.7-linux-x86_64.egg/twisted/protocols/basic.py", line 571, in dataReceived
        why = self.lineReceived(line)

      File "/home/evilaliv3/Devel/GlobaLeaks/backend/glenv/local/lib/python2.7/site-packages/cyclone-1.1-py2.7.egg/cyclone/httpserver.py", line 96, in lineReceived
        self._on_headers(buff)

      File "/home/evilaliv3/Devel/GlobaLeaks/backend/globaleaks/handlers/base.py", line 105, in _on_headers
        log.msg("Malformed HTTP request from %s: %s", self._remote_ip, e)

    TypeError: msg() takes exactly 2 arguments (4 given)

**Comment by evilaliv3** [comment]
i've now restricted the chars set accepted by the API handlers so that a strong filter is now in place and is now preventing both the two issues reported in this ticket.

**Comment by fpietrosanti** [comment]
@evilaliv3 Can this break file names being uploaded with chinese charset for example?

**Comment by evilaliv3** [comment]
i've considered that and yes it make not possible to upload files with fancy names but only for what relates to themes/css/additional files.

whistleblowers whould still have the possibility to upload whatever they want
