### ISSUE TITLE
Unhandled unicode exception on unhandled exception handler

### ISSUE THREAD

**Issue by evilaliv3** [globaleaks/GlobaLeaks#1250]
An Exception has been scattered by the ALAC setup in relation to ESMTP network error.

the full stack trace follows:

    Traceback (most recent call last):

      File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
        call.func(*call.args, **call.kw)

      File "/usr/local/lib/python2.7/dist-packages/twisted/protocols/policies.py", line 719, in __timedOut
        self.timeoutConnection()

      File "/usr/local/lib/python2.7/dist-packages/twisted/mail/smtp.py", line 1034, in timeoutConnection
        self.log.str()))

      File "/usr/lib/python2.7/dist-packages/globaleaks/utils/mailutils.py", line 100, in esmtp_sendError
        key = str(exc.code) + " " + error.group(1)

    AttributeError: 'NoneType' object has no attribute 'group'

**Comment by evilaliv3** [comment]
the issue lies in a removed check that was present before https://github.com/globaleaks/GlobaLeaks/commit/7e93f4732618ebaacd7398e90f992410f723ad2c when i merged some code by @origliante.

i'm going to fix not readding the check but with a slightly simplified solution.

**Comment by evilaliv3** [comment]
fixed.
