### ISSUE TITLE
Unhandled exception in notifications "mailutils" 2.60.65

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#1321]
It has been reported by an adopter that he's receiving this kind of unhandled exception error:

Subject: Subject: GlobaLeaks Exception 2.60.65 [1]
To: Admin <info@XXXXX>

AttributeError Attribute not found.

Traceback (most recent call last):

  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
    call.func(*call.args, **call.kw)

  File "/usr/local/lib/python2.7/dist-packages/twisted/protocols/policies.py", line 719, in __timedOut
    self.timeoutConnection()

  File "/usr/local/lib/python2.7/dist-packages/twisted/mail/smtp.py", line 1034, in timeoutConnection
    self.log.str()))

  File "/usr/lib/python2.7/dist-packages/globaleaks/utils/mailutils.py", line 100, in esmtp_sendError
    key = str(exc.code) + " " + error.group(1)

AttributeError: 'NoneType' object has no attribute 'group'

**Comment by evilaliv3** [comment]
it has been already fixed in last month.
