### ISSUE TITLE
Error while resolving creation_date on new file upload notification

### ISSUE THREAD

**Issue by evilaliv3** [globaleaks/GlobaLeaks#1537]
Exception raised on development setup of Regione Toscana:

```
KeyError Mapping key not found.

Traceback (most recent call last):

  File "/usr/lib/python2.7/dist-packages/globaleaks/jobs/base.py", line 105, in _operation
    yield self.operation()

  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1097, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)

  File "/usr/local/lib/python2.7/dist-packages/twisted/python/failure.py", line 389, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)

  File "/usr/lib/python2.7/dist-packages/globaleaks/jobs/notification_sched.py", line 211, in operation
    yield mail_generator.process_data(trigger)

  File "/usr/local/lib/python2.7/dist-packages/twisted/python/threadpool.py", line 191, in _worker
    result = context.call(ctx, function, *args, **kwargs)

  File "/usr/local/lib/python2.7/dist-packages/twisted/python/context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)

  File "/usr/local/lib/python2.7/dist-packages/twisted/python/context.py", line 81, in callWithContext
    return func(*args,**kw)

  File "/usr/lib/python2.7/dist-packages/globaleaks/orm.py", line 110, in _wrap
    result = function(self.instance, self.store, *args, **kwargs)

  File "/usr/lib/python2.7/dist-packages/globaleaks/jobs/notification_sched.py", line 168, in process_data
    getattr(self, 'process_%s' % trigger)(store, element, data)

  File "/usr/lib/python2.7/dist-packages/globaleaks/jobs/notification_sched.py", line 92, in process_ReceiverFile
    self.process_mail_creation(store, data)

  File "/usr/lib/python2.7/dist-packages/globaleaks/jobs/notification_sched.py", line 120, in process_mail_creation
    subject, body = Templating().get_mail_subject_and_body(data)

  File "/usr/lib/python2.7/dist-packages/globaleaks/utils/templating.py", line 338, in get_mail_subject_and_body
    body = self.format_template(body_template, data)

  File "/usr/lib/python2.7/dist-packages/globaleaks/utils/templating.py", line 312, in format_template
    variable_content = getattr(keyword_converter, kw[1:-1])()

  File "/usr/lib/python2.7/dist-packages/globaleaks/utils/templating.py", line 193, in EventTime
    return ISO8601_to_pretty_str(self.data['file']['creation_date'], float(self.data['receiver']['timezone']))

KeyError: 'creation_date'
```

**Comment by evilaliv3** [comment]
Fixed; to be shipped in 2.60.126
