### ISSUE TITLE
Fix broken protractor tests on Travis and Saucelabs

### ISSUE THREAD

**Issue by NSkelsey** [globaleaks/GlobaLeaks#1610]
On both devel and master travis is reporting that 16 out of 46 end2end tests it is running in the `GLTEST='unit' GLREQUIREMENTS='trusty'` job are failing.

This should be fixed. Below is the log output from a recent build of master. As discussed online the errors may be coming from the loading panel making elements unclickable, or from latency introduced by the smaller environments on the build servers. This is not an issue we see on our local machines.

```
[4mRunning "protractor_coverage:local" (protractor_coverage) task[24m
Collector started on port 3001
DEBUG - Running with --troubleshoot
DEBUG - Protractor version: 3.1.1
DEBUG - Your base url for tests is http://127.0.0.1:8082/
Using FirefoxDriver directly...
[launcher] Running 1 instances of WebDriver
DEBUG - WebDriver session successfully started with capabilities { caps_: 
   { cssSelectorsEnabled: true,
     browserName: 'firefox',
     handlesAlerts: true,
     javascriptEnabled: true,
     nativeEvents: false,
     platform: 'Linux',
     rotatable: false,
     takesScreenshot: true,
     version: '31.6.0',
     webStorageEnabled: true,
     applicationCacheEnabled: true,
     databaseEnabled: true,
     locationContextEnabled: true,
     acceptSslCerts: true } }
DEBUG - Running with spec files /tmp/1458635954044.6733,/tmp/1458635954054.0283,/tmp/1458635954063.3508,/tmp/1458635954069.8235,/tmp/1458635954077.1794,/tmp/1458635954081.765,/tmp/1458635954086.163,/tmp/1458635954099.9993
Started
[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0mA Jasmine spec timed out. Resetting the WebDriver Control Flow.
[31mF[0mA Jasmine spec timed out. Resetting the WebDriver Control Flow.
[31mF[0mA Jasmine spec timed out. Resetting the WebDriver Control Flow.
[31mF[0mA Jasmine spec timed out. Resetting the WebDriver Control Flow.
[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0mA Jasmine spec timed out. Resetting the WebDriver Control Flow.
[31mF[0mA Jasmine spec timed out. Resetting the WebDriver Control Flow.
[31mF[0m[31mF[0mA Jasmine spec timed out. Resetting the WebDriver Control Flow.
[31mF[0m[31mF[0m[31mF[0m[31mF[0m[31mF[0m

Failures:
1) globaLeaks process Whistleblowers should be able to submit tips (1)
  Message:
[31m    Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.[0m
  Stack:
    Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.

2) globaLeaks process Whistleblowers should be able to submit tips (2)
  Message:
[31m    Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.[0m
  Stack:
    Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.

3) globaLeaks process Whistleblowers should be able to submit tips (3)
  Message:
[31m    Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.[0m
  Stack:
    Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.

4) globaLeaks process Whistleblower should be able to access the first submission
  Message:
[31m    Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.[0m
  Stack:
    Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.

5) globaLeaks process Recipient should be able to access the first submission
  Message:
[31m    Failed: No element found using locator: By.id("tip-0")[0m
  Stack:
    NoSuchElementError: No element found using locator: By.id("tip-0")
        at process._tickCallback (node.js:368:9)
    Error
        at /tmp/1458635954099.9993:154:37
        at process._tickCallback (node.js:368:9)
    From: Task: Run it("Recipient should be able to access the first submission") in control flow
    From asynchronous test: 
    Error
        at Suite.<anonymous> (/tmp/1458635954099.9993:152:5)
        at Object.<anonymous> (/tmp/1458635954099.9993:5:1)

6) globaLeaks process Recipient should be able to refresh tip page
  Message:
[31m    Failed: No element found using locator: By.id("link-reload")[0m
  Stack:
    NoSuchElementError: No element found using locator: By.id("link-reload")
        at process._tickCallback (node.js:368:9)
    Error
        at Object.<anonymous> (/tmp/1458635954099.9993:161:39)
    From: Task: Run it("Recipient should be able to refresh tip page") in control flow
    From asynchronous test: 
    Error
        at Suite.<anonymous> (/tmp/1458635954099.9993:160:5)
        at Object.<anonymous> (/tmp/1458635954099.9993:5:1)

7) globaLeaks process Recipient should be able to see files and download them
  Message:
[31m    Expected 0 to equal 2.[0m
  Stack:
    Error: Failed expectation
        at Object.<anonymous> (/tmp/1458635954099.9993:168:85)
        at process._tickCallback (node.js:368:9)

8) globaLeaks process Recipient should be able to leave a comment to the whistleblower
  Message:
[31m    Failed: No element found using locator: By.id("tip-0")[0m
  Stack:
    NoSuchElementError: No element found using locator: By.id("tip-0")
        at process._tickCallback (node.js:368:9)
    Error
        at /tmp/1458635954099.9993:183:37
        at process._tickCallback (node.js:368:9)
    From: Task: Run it("Recipient should be able to leave a comment to the whistleblower") in control flow
    From asynchronous test: 
    Error
        at Suite.<anonymous> (/tmp/1458635954099.9993:181:5)
        at Object.<anonymous> (/tmp/1458635954099.9993:5:1)

9) globaLeaks process Whistleblower should be able to read the comment from the receiver and reply
  Message:
[31m    Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.[0m
  Stack:
    Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.

10) globaLeaks process Whistleblower should be able to attach a new file to the first submission
  Message:
[31m    Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.[0m
  Stack:
    Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.

11) globaLeaks process Recipient should be able to start a private discussion with the whistleblower
  Message:
[31m    Failed: No element found using locator: By.id("tip-0")[0m
  Stack:
    NoSuchElementError: No element found using locator: By.id("tip-0")
        at process._tickCallback (node.js:368:9)
    Error
        at /tmp/1458635954099.9993:234:37
        at process._tickCallback (node.js:368:9)
    From: Task: Run it("Recipient should be able to start a private discussion with the whistleblower") in control flow
    From asynchronous test: 
    Error
        at Suite.<anonymous> (/tmp/1458635954099.9993:232:5)
        at Object.<anonymous> (/tmp/1458635954099.9993:5:1)

12) globaLeaks process Whistleblower should be able to read the private message from the receiver and reply
  Message:
[31m    Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.[0m
  Stack:
    Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.

13) globaLeaks process Recipient should be able to export the submission
  Message:
[31m    Failed: No element found using locator: By.id("tip-0")[0m
  Stack:
    NoSuchElementError: No element found using locator: By.id("tip-0")
        at process._tickCallback (node.js:368:9)
    Error
        at /tmp/1458635954099.9993:268:37
        at process._tickCallback (node.js:368:9)
    From: Task: Run it("Recipient should be able to export the submission") in control flow
    From asynchronous test: 
    Error
        at Suite.<anonymous> (/tmp/1458635954099.9993:266:5)
        at Object.<anonymous> (/tmp/1458635954099.9993:5:1)

14) globaLeaks process Recipient should be able to postpone first submission from tip page
  Message:
[31m    Failed: No element found using locator: By.id("tip-0")[0m
  Stack:
    NoSuchElementError: No element found using locator: By.id("tip-0")
        at process._tickCallback (node.js:368:9)
    Error
        at /tmp/1458635954099.9993:282:37
        at process._tickCallback (node.js:368:9)
    From: Task: Run it("Recipient should be able to postpone first submission from tip page") in control flow
    From asynchronous test: 
    Error
        at Suite.<anonymous> (/tmp/1458635954099.9993:280:5)
        at Object.<anonymous> (/tmp/1458635954099.9993:5:1)

15) globaLeaks process Recipient should be able to delete first submission from tip page
  Message:
[31m    Failed: No element found using locator: By.id("tip-0")[0m
  Stack:
    NoSuchElementError: No element found using locator: By.id("tip-0")
        at process._tickCallback (node.js:368:9)
    Error
        at /tmp/1458635954099.9993:296:37
        at process._tickCallback (node.js:368:9)
    From: Task: Run it("Recipient should be able to delete first submission from tip page") in control flow
    From asynchronous test: 
    Error
        at Suite.<anonymous> (/tmp/1458635954099.9993:294:5)
        at Object.<anonymous> (/tmp/1458635954099.9993:5:1)

16) globaLeaks process Recipient should be able to postpone all tips
  Message:
[31m    Failed: No element found using locator: By.id("tip-action-postpone-selected")[0m
  Stack:
    NoSuchElementError: No element found using locator: By.id("tip-action-postpone-selected")
        at process._tickCallback (node.js:368:9)
    Error
        at /tmp/1458635954099.9993:312:64
        at process._tickCallback (node.js:368:9)
    From: Task: Run it("Recipient should be able to postpone all tips") in control flow
    From asynchronous test: 
    Error
        at Suite.<anonymous> (/tmp/1458635954099.9993:309:5)
        at Object.<anonymous> (/tmp/1458635954099.9993:5:1)

30 specs, 16 failures
Finished in 599.473 seconds
[launcher] 0 instance(s) of WebDriver still running
[launcher] firefox #1 failed 16 test(s)
[launcher] overall: 16 failed spec(s)
[launcher] Process exited with error code 1
[31m>> [39m
[32m>> [39mTest failed but keep the grunt process alive.
Shutdown requested
```
[Source](https://s3.amazonaws.com/archive.travis-ci.org/jobs/117653852/log.txt)

**Comment by evilaliv3** [comment]
At the same the code used in the test is instrumented so:
1) does run slower for this reason and beign slower can trigger some race
conditions
2) the instrumented code may be buggy due to something of the changes we
put (Even the commas maybe). I will check later

**Comment by NSkelsey** [comment]
I do not think it is (2) if you look at the jobs in the [current master](https://travis-ci.org/globaleaks/GlobaLeaks/builds/117653850) which is 150 commits behind devel the problem persists.  

I am not sure what is up.

**Comment by evilaliv3** [comment]
I've now seen that in the real the log you are reporting @NSkelsey is not related to saucelabs but to the headless tests performed on travis; the coverage test infact is performed direclty on travis without using the saucelabs service.

With commit https://github.com/globaleaks/GlobaLeaks/commit/b5619179d96106cd96654ce9b0db6be1e5b14dd4 i've raised from 60seconds to 180 seconds the timeout on travis, and to 360 seconds the timeout on coveralls.

Le'ts see what will happen on build: https://travis-ci.org/globaleaks/GlobaLeaks/builds/119642378

**Comment by NSkelsey** [comment]
As far as various tests sauce lab tests that failed on the [last build of master](https://travis-ci.org/globaleaks/GlobaLeaks/builds/117653850). I have documented a few of the reasons below:

```
Job #3238.4 — Success
$ export GLTEST='end2end-1'
$ export BROWSER='ie 10'

Job #3238.5 — Success
$ export GLTEST='end2end-0'
$ export BROWSER='ie 9’

Job #3238.5 — Success
$ export GLTEST='end2end-2'
$ export BROWSER='ie 11'

Job #3238.6 — Failed — Cause: Protractor or Angular failed to initialize:
$ export GLTEST='end2end-3'
$ export BROWSER='edge 20.10240'


[4mRunning "protractor:saucelabs" (protractor) task[24m
Using SauceLabs selenium server at http://ondemand.saucelabs.com:80/wd/hub
[launcher] Running 1 instances of WebDriver

Failures:
1) init should load the app
  Message:
[31m    Failed: Error while running testForAngular: Javascript execution context no longer exists (WARNING: The server did not provide any stacktrace information)
    Command duration or timeout: 687 milliseconds
    Build info: version: '2.52.0', revision: '4c2593c', time: '2016-02-11 19:06:42'
    System info: host: 'WIN-SB3ER6JQ6ME', ip: '172.20.41.191', os.name: 'Windows 10', os.arch: 'x86', os.version: '10.0', java.version: '1.8.0_73'
    Driver info: org.openqa.selenium.edge.EdgeDriver
    Capabilities [{acceptSslCerts=true, browserVersion=25.10586.0.0, platformVersion=10, browserName=MicrosoftEdge, takesScreenshot=true, pageLoadStrategy=normal, takesElementScreenshot=true, platformName=windows, platform=ANY}]
    Session ID: XXXXXXXX-XXXX-XXXX-XXXX-XXXX8143DFDC[0m
  Stack:
    Error: Failed: Error while running testForAngular: Javascript execution context no longer exists (WARNING: The server did not provide any stacktrace information)
    Command duration or timeout: 687 milliseconds
    Build info: version: '2.52.0', revision: '4c2593c', time: '2016-02-11 19:06:42'
    System info: host: 'WIN-SB3ER6JQ6ME', ip: '172.20.41.191', os.name: 'Windows 10', os.arch: 'x86', os.version: '10.0', java.version: '1.8.0_73'
    Driver info: org.openqa.selenium.edge.EdgeDriver
    Capabilities [{acceptSslCerts=true, browserVersion=25.10586.0.0, platformVersion=10, browserName=MicrosoftEdge, takesScreenshot=true, pageLoadStrategy=normal, takesElementScreenshot=true, platformName=windows, platform=ANY}]
    Session ID: XXXXXXXX-XXXX-XXXX-XXXX-XXXX8143DFDC

Job #3238.9 — Failed — Cause: Device unsupported.
$ export GLTEST='end2end-6'
$ export BROWSER='firefox beta'

[4mRunning "protractor:saucelabs" (protractor) task[24m
Using SauceLabs selenium server at http://ondemand.saucelabs.com:80/wd/hub
[launcher] Running 1 instances of WebDriver

/home/travis/build/globaleaks/GlobaLeaks/client/node_modules/protractor/node_modules/selenium-webdriver/lib/atoms/error.js:108
  var template = new Error(this.message);
                 ^
UnknownCommandError: Unsupported OS/browser/version/device combo: OS: 'Linux', Browser: 'firefox', Version: 'beta.', Device: 'unspecified'
    at new bot.Error (/home/travis/build/globaleaks/GlobaLeaks/client/node_modules/protractor/node_modules/selenium-webdriver/lib/atoms/error.js:108:18)
    at Object.bot.response.checkResponse (/home/travis/build/globaleaks/GlobaLeaks/client/node_modules/protractor/node_modules/selenium-webdriver/lib/atoms/response.js:106:11)
…

[launcher] Process exited with error code 1


Job #3238.10 — Failed — Async request took to long.
$ export GLTEST='end2end-7'
$ export BROWSER='chrome 37'

Failures:
1) globaLeaks process Whistleblowers should be able to submit tips (2)
  Message:
[31m    Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.[0m
  Stack:
    Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.

30 specs, 1 failure
Finished in 463.625 seconds


Job #3238.11 — Success
$ export GLTEST='end2end-8'
$ export BROWSER='chrome 47'


Job #3238.12 — Failed — Cause: Unsupported Device

$ export GLTEST='end2end-9'
$ export BROWSER='chrome beta'


[4mRunning "protractor:saucelabs" (protractor) task[24m
Using SauceLabs selenium server at http://ondemand.saucelabs.com:80/wd/hub
[launcher] Running 1 instances of WebDriver

/home/travis/build/globaleaks/GlobaLeaks/client/node_modules/protractor/node_modules/selenium-webdriver/lib/atoms/error.js:108
  var template = new Error(this.message);
                 ^
UnknownCommandError: Unsupported OS/browser/version/device combo: OS: 'Linux', Browser: 'googlechrome', Version: 'beta.', Device: 'unspecified'
    at new bot.Error (/home/travis/build/globaleaks/GlobaLeaks/client/node_modules/protractor/node_modules/selenium-webdriver/lib/atoms/error.js:108:18)
    at Object.bot.response.checkResponse (/home/travis/build/globaleaks/GlobaLeaks/client/node_modules/protractor/node_modules/selenium-webdriver/lib/atoms/response.js:106:11)
    at /home/travis/build/globaleaks/GlobaLeaks/client/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:160:24
    at [object Object].promise.Promise.goog.defineClass.invokeCallback_ (/home/travis/build/globaleaks/GlobaLeaks/client/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/../webdriver/promise.js:1337:14)
    at [object Object].promise.ControlFlow.goog.defineClass.goog.defineClass.abort_.error.executeNext_.execute_ (/home/travis/build/globaleaks/GlobaLeaks/client/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/../webdriver/promise.js:2776:14)
    at [object Object].promise.ControlFlow.goog.defineClass.goog.defineClass.abort_.error.executeNext_ (/home/travis/build/globaleaks/GlobaLeaks/client/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/../webdriver/promise.js:2758:21)
    at goog.async.run.processWorkQueue (/home/travis/build/globaleaks/GlobaLeaks/client/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/async/run.js:124:15)
    at process._tickCallback (node.js:368:9)
From: Task: WebDriver.createSession()
    at Function.webdriver.WebDriver.acquireSession_ (/home/travis/build/globaleaks/GlobaLeaks/client/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:157:22)
    at Function.webdriver.WebDriver.createSession (/home/travis/build/globaleaks/GlobaLeaks/client/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:131:30)
    at [object Object].Builder.build (/home/travis/build/globaleaks/GlobaLeaks/client/node_modules/protractor/node_modules/selenium-webdriver/builder.js:445:22)
    at [object Object].DriverProvider.getNewDriver (/home/travis/build/globaleaks/GlobaLeaks/client/node_modules/protractor/lib/driverProviders/driverProvider.js:42:27)
    at [object Object].Runner.createBrowser (/home/travis/build/globaleaks/GlobaLeaks/client/node_modules/protractor/lib/runner.js:190:37)
    at /home/travis/build/globaleaks/GlobaLeaks/client/node_modules/protractor/lib/runner.js:280:21
    at _fulfilled (/home/travis/build/globaleaks/GlobaLeaks/client/node_modules/protractor/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/home/travis/build/globaleaks/GlobaLeaks/client/node_modules/protractor/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/home/travis/build/globaleaks/GlobaLeaks/client/node_modules/protractor/node_modules/q/q.js:796:13)
    at /home/travis/build/globaleaks/GlobaLeaks/client/node_modules/protractor/node_modules/q/q.js:556:49

Job #3238.18 — Success
$ export GLTEST='end2end-15'
$ export BROWSER='iphone 9.2'

Job #3238.22 — Failed — Cause: Undetermined timeout.
$ export GLTEST='unit'
$ export GLREQUIREMENTS='jessie'

Failures:
1) globaLeaks process Whistleblowers should be able to submit tips (1)
  Message:
[31m    Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.[0m
  Stack:
    Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.

2) globaLeaks process Whistleblowers should be able to submit tips (2)
  Message:
[31m    Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.[0m
  Stack:
    Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.

3) globaLeaks process Whistleblowers should be able to submit tips (3)
  Message:
[31m    Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.[0m
  Stack:
    Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.

4) globaLeaks process Whistleblower should be able to access the first submission
  Message:
[31m    Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.[0m
  Stack:
    Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.

5) globaLeaks process Recipient should be able to access the first submission
  Message:
[31m    Failed: No element found using locator: By.id("tip-0")[0m
  Stack:
    NoSuchElementError: No element found using locator: By.id("tip-0")
        at process._tickCallback (node.js:368:9)
    Error
        at /tmp/1458640909716.0505:154:37
        at process._tickCallback (node.js:368:9)
    From: Task: Run it("Recipient should be able to access the first submission") in control flow
    From asynchronous test: 
    Error
        at Suite.<anonymous> (/tmp/1458640909716.0505:152:5)
        at Object.<anonymous> (/tmp/1458640909716.0505:5:1)
```

**Comment by evilaliv3** [comment]
all is fixed;

IE9 and IE10 sometimes get a failure but they are no more in the grace of god [1]

[1] : https://www.youtube.com/watch?v=Sx7L1aZu698

**Comment by NSkelsey** [comment]
The current devel build reports:

[Job GLTEST='unit' GLREQUIREMENTS='trusty'](https://travis-ci.org/globaleaks/GlobaLeaks/jobs/120609324)
```
Failures:
1) globaLeaks process Whistleblowers should be able to submit tips (1)
  Message:
[31m    Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.[0m
  Stack:
    Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
        at Timer.listOnTimeout (timers.js:92:15)

.
.
.

3) globaLeaks process Whistleblowers should be able to submit tips (3)
  Message:
[31m    Failed: Error while waiting for Protractor to sync with the page: "[ng:test] http://errors.angularjs.org/1.5.3/ng/test"[0m
  Stack:
    Error: Failed: Error while waiting for Protractor to sync with the page: "[ng:test] http://errors.angularjs.org/1.5.3/ng/test"
        at /home/travis/build/globaleaks/GlobaLeaks/client/node_modules/protractor/node_modules/jasminewd2/index.js:101:16
        at Promise.invokeCallback_ (/home/travis/build/globaleaks/GlobaLeaks/client/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:1329:14)
        at TaskQueue.execute_ (/home/travis/build/globaleaks/GlobaLeaks/client/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2790:14)
        at TaskQueue.executeNext_ (/home/travis/build/globaleaks/GlobaLeaks/client/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2773:21)
  Message:
[31m    Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.[0m
  Stack:
    Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
        at Timer.listOnTimeout (timers.js:92:15)
. 
. 
.

32 specs, 18 failures
Finished in 1448.169 seconds
```
