### ISSUE TITLE
last setup_development_environment.sh

### ISSUE THREAD

**Issue by vecna** [globaleaks/GlobaLeaks#1685]
A problem with cryptography don't  compiling (I've used the last one instead of the one hardcoded in requirements.txt), I'll investigate in the small free time. does for you sounds any bell ? is the Ubuntu 16.04. at the end of installation SSL error 

    (glenv) aaѪaa:~/Dev/GlobaLeaks/backend$ !bi
    bin/globaleaks -h
    Starting GlobaLeaks
    sys.excepthook is missing
    Traceback (most recent call last):
      File "bin/globaleaks", line 96, in <module>
        from globaleaks.db import check_db_files
      File "/home/aa/Dev/GlobaLeaks/backend/globaleaks/db/__init__.py", line 14, in <module>
        from globaleaks import models,  __version__, DATABASE_VERSION
      File "/home/aa/Dev/GlobaLeaks/backend/globaleaks/models/__init__.py", line 14, in <module>
        from globaleaks.models.validators import shorttext_v, longtext_v, \
      File "/home/aa/Dev/GlobaLeaks/backend/globaleaks/models/validators.py", line 10, in <module>
        from globaleaks.settings import GLSettings
      File "/home/aa/Dev/GlobaLeaks/backend/globaleaks/settings.py", line 20, in <module>
        from twisted.internet import reactor
      File "/home/aa/Dev/GlobaLeaks/backend/glenv/local/lib/python2.7/site-packages/twisted/internet/reactor.py", line 38, in <module>
        from twisted.internet import default
      File "/home/aa/Dev/GlobaLeaks/backend/glenv/local/lib/python2.7/site-packages/twisted/internet/default.py", line 56, in <module>
        install = _getInstallFunction(platform)
      File "/home/aa/Dev/GlobaLeaks/backend/glenv/local/lib/python2.7/site-packages/twisted/internet/default.py", line 44, in _getInstallFunction
        from twisted.internet.epollreactor import install
      File "/home/aa/Dev/GlobaLeaks/backend/glenv/local/lib/python2.7/site-packages/twisted/internet/epollreactor.py", line 24, in <module>
        from twisted.internet import posixbase
      File "/home/aa/Dev/GlobaLeaks/backend/glenv/local/lib/python2.7/site-packages/twisted/internet/posixbase.py", line 24, in <module>
        from twisted.internet import error, udp, tcp
      File "/home/aa/Dev/GlobaLeaks/backend/glenv/local/lib/python2.7/site-packages/twisted/internet/tcp.py", line 29, in <module>
        from twisted.internet._newtls import (
      File "/home/aa/Dev/GlobaLeaks/backend/glenv/local/lib/python2.7/site-packages/twisted/internet/_newtls.py", line 21, in <module>
        from twisted.protocols.tls import TLSMemoryBIOFactory, TLSMemoryBIOProtocol
      File "/home/aa/Dev/GlobaLeaks/backend/glenv/local/lib/python2.7/site-packages/twisted/protocols/tls.py", line 40, in <module>
        from OpenSSL.SSL import Error, ZeroReturnError, WantReadError
      File "/home/aa/Dev/GlobaLeaks/backend/glenv/local/lib/python2.7/site-packages/pyOpenSSL-0.14-py2.7.egg/OpenSSL/__init__.py", line 8, in <module>
        from OpenSSL import rand, crypto, SSL
      File "/home/aa/Dev/GlobaLeaks/backend/glenv/local/lib/python2.7/site-packages/pyOpenSSL-0.14-py2.7.egg/OpenSSL/rand.py", line 11, in <module>
        from OpenSSL._util import (
      File "/home/aa/Dev/GlobaLeaks/backend/glenv/local/lib/python2.7/site-packages/pyOpenSSL-0.14-py2.7.egg/OpenSSL/_util.py", line 3, in <module>
        from cryptography.hazmat.bindings.openssl.binding import Binding
      File "/home/aa/Dev/GlobaLeaks/backend/glenv/local/lib/python2.7/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 15, in <module>
        from cryptography.hazmat.bindings._openssl import ffi, lib
    AttributeError: 'module' object has no attribute '_init_cffi_1_0_external_module'

**Comment by evilaliv3** [comment]
Halo!

The requirements of Ubuntu 16.04 are under testing but basically what we
are testing on 14.04 to install the same packages versions that are
packaged on that Ubuntu release as Debian package.
The compatibility between the packages exists but yes it is possibile that
compiling on an Ubuntu it wont work and that we need to install some
library.

Let me know if you end in understanding the issue

**Comment by fpietrosanti** [comment]
For later investigation, the bug is documented on https://bugs.launchpad.net/ubuntu/+source/python-pip/+bug/1512792

**Comment by vecna** [comment]
Ok, somehow, solved.

-cffi==0.8.2
-cryptography==0.8.2
-pycparser==2.10

In requirements.txt these version has to be updated to the last one

cryptography 1.3.2 
cffi 1.6.0
pycparser 2.14

**Comment by evilaliv3** [comment]
no we do not have to change them.

now i got what you are facing vecna.

you are trying to use the trusty package on xenial and that surely do not work.

the requirements of xenial are already studied in https://github.com/globaleaks/GlobaLeaks/issues/1515 and are; https://github.com/globaleaks/GlobaLeaks/blob/master/backend/requirements/requirements-xenial.txt

that exact version correspond to what is included in xenial as debian package and so the compatibility is for sure guaranteed (and we are testing it just to be sure on travis).
so when we will release the xenial package it will be a fully debian package using those version and there would be no gcc process as the debian package will include already binaries.


the version written in that requirements.txt file are for the xenial that we are testing are the one that xenial has as already as debian package.

so not, we do not have to change them, but simply finalize the package with that version that are known to be compatible and

**Comment by evilaliv3** [comment]
Closing this for now; See previous comments for details.
