### ISSUE TITLE
Backup script fails if globaleaks is already stopped

### ISSUE THREAD

**Issue by evilaliv3** [globaleaks/GlobaLeaks#1743]
The backup script does currently fail if globaleaks service is already stopped

Evidence of the error:
```bash
gl-admin backup /var/globaleaks

Failed to stop globaleaks.service: Unit globaleaks.service not loaded.
Traceback (most recent call last):
  File "./bin/gl-admin", line 96, in <module>
    r = sp.check_call('service globaleaks stop', shell=True)
  File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'service globaleaks stop' returned non-zero exit status 5
```

**Comment by NSkelsey** [comment]
X_X the script is crap at the moment.
