### ISSUE TITLE
Dependency issues on Precise 12.04

### ISSUE THREAD

**Issue by NSkelsey** [globaleaks/GlobaLeaks#1911]
**Current behavior**

On a fresh install of 2.66.0 on Ubuntu Precise 12.04 the installation script throws the following error:

```bash
> ./install-globaleaks.sh
!!!!!!!!!!!! WARNING !!!!!!!!!!!!
You are attempting to install GlobaLeaks on an unsupported platform.
Supported platform is Ubuntu Trusty (14.04)
Do you wish to continue anyhow? [y|n]?y
Performing GlobaLeaks installation on Ubuntu - precise
Checking preliminary GlobaLeaks requirements
.
.
.
  ----------------------------------------
  Failed building wheel for zope.interface
  Running setup.py clean for zope.interface
Failed to build Parsley Twisted cffi cryptography cyclone enum34 pycparser python-gnupg scrypt storm transaction zope.component zope.event zope.interface
Installing collected packages: Parsley, six, pyparsing, packaging, appdirs, setuptools, zope.interface, Twisted, pycparser, cffi, idna, pyasn1, enum34, ipaddress, cryptography, pyOpenSSL, cyclone, python-gnupg, scrypt, attrs, pyasn1-modul
es, service-identity, storm, transaction, txsocksx, zope.event, zope.component
  Running setup.py install for Parsley ... done
  Found existing installation: zope.interface 3.6.1
    Uninstalling zope.interface-3.6.1:
      Successfully uninstalled zope.interface-3.6.1
  Running setup.py install for zope.interface ... error
    Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-BXGeMy/zope.interface/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(co
mpile(code, __file__, 'exec'))" install --record /tmp/pip-vfI81z-record/install-record.txt --single-version-externally-managed --compile:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-BXGeMy/zope.interface/setup.py", line 145, in <module>
        **extra)
      File "/usr/lib/python2.7/distutils/core.py", line 112, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/local/lib/python2.7/dist-packages/setuptools/dist.py", line 320, in __init__
        _Distribution.__init__(self, attrs)
      File "/usr/lib/python2.7/distutils/dist.py", line 287, in __init__
        self.finalize_options()
      File "/usr/local/lib/python2.7/dist-packages/setuptools/dist.py", line 386, in finalize_options
        ep.require(installer=self.fetch_build_egg)
      File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2324, in require
        items = working_set.resolve(reqs, env, installer, extras=self.extras)
      File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 859, in resolve
        raise VersionConflict(dist, req).with_context(dependent_req)
    pkg_resources.VersionConflict: (six 1.5.2 (/usr/local/lib/python2.7/dist-packages), Requirement.parse('six>=1.6.0'))
    
    ----------------------------------------
  Rolling back uninstall of zope.interface
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-BXGeMy/zope.interface/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'e
xec'))" install --record /tmp/pip-vfI81z-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-BXGeMy/zope.interface/
dpkg: error processing globaleaks (--configure):
 subprocess installed post-installation script returned error exit status 1
Errors were encountered while processing:
 globaleaks
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

If you try to manually install the dependencies before the update the following error (or similar) gets thrown:

```bash
root@ip-172-30-0-64:/home/ubuntu# pip install -r requirements-precise.txt                                                                                                                                                        
Requirement already satisfied: Parsley==1.2 in /usr/local/lib/python2.7/dist-packages (from -r requirements-trusty.txt (line 1))
Collecting six==1.6.0 (from -r requirements-trusty.txt (line 2))
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:318: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. Th
is may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.
html#snimissingwarning.
  SNIMissingWarning
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause cert
ain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
  Downloading six-1.6.0-py2.py3-none-any.whl
Collecting Twisted==16.0.0 (from -r requirements-trusty.txt (line 3))
  Using cached Twisted-16.0.0.tar.bz2
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-PQlJt3/Twisted/setup.py", line 64, in <module>
        main(sys.argv[1:])
      File "/tmp/pip-build-PQlJt3/Twisted/setup.py", line 59, in main
        setup(**setup_args)
      File "./twisted/python/dist.py", line 132, in setup
        return core.setup(**get_setup_args(**kw))
      File "/usr/lib/python2.7/distutils/core.py", line 112, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/local/lib/python2.7/dist-packages/setuptools/dist.py", line 320, in __init__
        _Distribution.__init__(self, attrs)
      File "/usr/lib/python2.7/distutils/dist.py", line 287, in __init__
        self.finalize_options()
      File "/usr/local/lib/python2.7/dist-packages/setuptools/dist.py", line 386, in finalize_options
        ep.require(installer=self.fetch_build_egg)
      File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2324, in require
        items = working_set.resolve(reqs, env, installer, extras=self.extras)
      File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 859, in resolve
        raise VersionConflict(dist, req).with_context(dependent_req)
    pkg_resources.VersionConflict: (six 1.5.2 (/usr/local/lib/python2.7/dist-packages), Requirement.parse('six>=1.6.0'))
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-PQlJt3/Twisted/

```

**Expected behavior**

The installation should be clean.

**Steps to reproduce the problem or feature illustration**

Install or try to update globaleaks to v2.66 series on Precise.

**What is the motivation or use case for changing the behavior?**

We need to continue to support older versions of the platform

**Known work around**

The issue is with several packages' compatibility with the `six` package version installed by default on Precise. Manually updating `six` and retrying the update or install resolves the issue.

```bash
> pip install six==1.6.0
> apt-get install globaleaks
```

The issue here is that the order of dependencies installed is not strongly enforced and the setup of newer packages as they are installed require a version of python `six` greater than or equal to 1.6.0.
We have tabled resolving this issue until there is a demonstrated need for resolution. It is possible that we could modify the pre-install debian script to install the `six` package first, but that is the sort of customized platform silliness we want to avoid.

**Comment by NSkelsey** [comment]
Closing as part of a move to cease support for 12.04
