### ISSUE TITLE
IOError I/O operation failed when a file contain a "/"

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#1917]
GlobaLeaks version: 2.65.19

IOError I/O operation failed.

Traceback (most recent call last):

  File "/usr/local/lib/python2.7/dist-packages/cyclone/web.py", line 1073, in _deferred_handler
    result = function(*args, **kwargs)

  File "/usr/lib/python2.7/dist-packages/globaleaks/handlers/base.py", line 250, in call_handler
    return method_handler(cls, *args, **kwargs)

  File "/usr/local/lib/python2.7/dist-packages/cyclone/web.py", line 1216, in wrapper
    return method(self, *args, **kwargs)

  File "/usr/lib/python2.7/dist-packages/globaleaks/handlers/base.py", line 713, in get
    self.write_file(abspath)

  File "/usr/lib/python2.7/dist-packages/globaleaks/handlers/base.py", line 534, in write_file
    StaticFileProducer(self, open(filepath, "rb")).start()

IOError: [Errno 21] Is a directory: u'/usr/share/globaleaks/client/data'

**Comment by evilaliv3** [comment]
The bug has been already fixed in 2.66.0; before serving the file the file is checked to be an actual file if it is not an HTTP error 404 is returned.
