### ISSUE TITLE
"python setup.py test -s globaleaks.tests.workers" generates error on test_https_process

### ISSUE THREAD

**Issue by germfue** [globaleaks/GlobaLeaks#1918]
**Current behavior**

When I run
`$ python setup.py test -s globaleaks.tests.workers`
test_https_process fails consistently. Here is the output:
```
globaleaks.tests.workers.test_supervisor
  TestProcessSupervisor
    test_init_with_launch ...                                              [OK]
    test_init_with_no_launch ...                                           [OK]
  TestSubprocessRun
    test_https_process ...                                              [ERROR]
                                             [ERROR]

===============================================================================
[ERROR]
Traceback (most recent call last):
  File "/home/user/Projects/GlobaLeaks/backend/glenv/lib/python2.7/site-packages/twisted/internet/defer.py", line 1299, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/home/user/Projects/GlobaLeaks/backend/glenv/lib/python2.7/site-packages/twisted/python/failure.py", line 393, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/home/user/Projects/GlobaLeaks/backend/globaleaks/tests/workers/test_supervisor.py", line 118, in test_https_process
    yield threads.deferToThread(self.fetch_resource)
  File "/home/user/Projects/GlobaLeaks/backend/glenv/lib/python2.7/site-packages/twisted/python/threadpool.py", line 250, in inContext
    result = inContext.theWork()
  File "/home/user/Projects/GlobaLeaks/backend/glenv/lib/python2.7/site-packages/twisted/python/threadpool.py", line 266, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
  File "/home/user/Projects/GlobaLeaks/backend/glenv/lib/python2.7/site-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/home/user/Projects/GlobaLeaks/backend/glenv/lib/python2.7/site-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)
  File "/home/user/Projects/GlobaLeaks/backend/globaleaks/tests/workers/test_supervisor.py", line 130, in fetch_resource
    urllib2.urlopen('https://127.0.0.1:9443/')
  File "/usr/lib64/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib64/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib64/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib64/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 502: Bad Gateway

globaleaks.tests.workers.test_supervisor.TestSubprocessRun.test_https_process
===============================================================================
[ERROR]
Traceback (most recent call last):
Failure: twisted.trial.util.DirtyReactorAggregateError: Reactor was unclean.
Selectables:
<TLSMemoryBIOProtocol #1 on 9443>

globaleaks.tests.workers.test_supervisor.TestSubprocessRun.test_https_process
-------------------------------------------------------------------------------
Ran 3 tests in 1.894s

FAILED (errors=2, successes=2)
```

Problem can be found in `globaleaks/tests/workers/test_supervisor.py`
```
def connectionMade(self):
    self.start_defer.callback(None)
    # You might think that you can accept connections at this point,
    # but actually the subprocess is not ready.
    time.sleep(1)
```
That sleep(1) tries to give enough time to the process being spawned:
`reactor.spawnProcess(self.pp, 'python', args=['python', '-m', 'SimpleHTTPServer', '43434'])`

Depending on how long it takes for SimpleHTTPServer to be able to accept requests, the test case fails. In my machine it takes around 8 seconds

**Expected behavior**

This issue with the test case can be easily fixed to wait till SimpleHTTPServer is ready. When that process is able to receive requests, it prints: 
`Serving HTTP on 0.0.0.0 port 43434 ...`
This means we just need to wait till it prints something to continue with the test case.

This would be the patch:
```
diff --git a/backend/globaleaks/tests/workers/test_supervisor.py b/backend/globaleaks/tests/workers/test_supervisor.py
index 88b80b2..62c6289 100644
--- a/backend/globaleaks/tests/workers/test_supervisor.py
+++ b/backend/globaleaks/tests/workers/test_supervisor.py
@@ -1,7 +1,6 @@
 import gzip
 import json
 import ssl
-import time
 from StringIO import StringIO
 import tempfile
 import urllib2
@@ -111,7 +110,7 @@ class TestSubprocessRun(helpers.TestGL):
 
         # Start the HTTP server proxy requests will be forwarded to.
         self.pp = SimpleServerPP()
-        reactor.spawnProcess(self.pp, 'python', args=['python', '-m', 'SimpleHTTPServer', '43434'])
+        reactor.spawnProcess(self.pp, 'python', args=['python', '-m', 'SimpleHTTPServer', '43434'], usePTY=True)
         yield self.pp.start_defer
 
         # Check that requests are routed successfully
@@ -158,15 +157,19 @@ class TestSubprocessRun(helpers.TestGL):
 
 class SimpleServerPP(ProcessProtocol):
     def __init__(self):
+        self.welcome_msg = False
         self.start_defer = Deferred()
         process.set_pdeathsig(signal.SIGINT)
 
     def connectionMade(self):
-        self.start_defer.callback(None)
-        # You might think that you can accept connections at this point,
-        # but actually the subprocess is not ready.
-        time.sleep(1)
+        # Careful, at this point there is a connection to the process,
+        # but it is not ready to handle requests
         pass
 
     def processEnded(self, reason):
         pass
+
+    def outReceived(self, data):
+        if not self.welcome_msg:
+            self.start_defer.callback(None)
+            self.welcome_msg = True
```
**Steps to reproduce the problem or feature illustration**

If SimpleHTTPServer runs faster on your machine, just remove the `time.sleep(1)` from `globaleaks/tests/workers/test_supervisor.py` and it will fail

**What is the motivation or use case for changing the behavior?**

1 test case is unreliable, as it depends on machine performance to succeed or fail

**GlobaLeaks version:**

Just pulled from master on 13.03.2017 at 16:00

**Browser:**

- [] All browsers
- [ ] Chrome:  v45.0.1
- [ ] Firefox: v55.0.1
- [ ] Safari:
- [ ] Mobile Chrome:
- [ ] Other: 
- [x ] Not Applicable

* **Server Operating System and Version (if appliable):**
 
I found it first in Fedora. Reproduced it later on Ubuntu 14.04

* **Client Operating System and Version (if appliable):**

N/A

**Comment by NSkelsey** [comment]
@germfue thank you for finding this and producing a concise solution!

While writing this I was looking to grab a hook like the one you have used couldn't figure out exactly why I couldn't grab the servers output and moved on. 

I believe the key here is the `spawnProcess` `usePTY=` kwarg. I will integrate this now. Further the second failure is merely the failure of the first cascading into the next UT run, which is not ideal and requires a general solution in `tearDown`.

**Comment by NSkelsey** [comment]
Hey @germfue the ut is now fixed in `devel`. It will merge into master with `2.66.2`

**Comment by germfue** [comment]
@NSkelsey thanks!
