### ISSUE TITLE
Exception on sending email from mailutils.py

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#1920]
AttributeError Attribute not found.

Traceback (most recent call last):

  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
    call.func(*call.args, **call.kw)

  File "/usr/local/lib/python2.7/dist-packages/twisted/protocols/policies.py", line 719, in __timedOut
    self.timeoutConnection()

  File "/usr/local/lib/python2.7/dist-packages/twisted/mail/smtp.py", line 1034, in timeoutConnection
    self.log.str()))

  File "/usr/lib/python2.7/dist-packages/globaleaks/utils/mailutils.py", line 100, in esmtp_sendError
    key = str(exc.code) + " " + error.group(1)

AttributeError: 'NoneType' object has no attribute 'group'

**Comment by NSkelsey** [comment]
@fpietrosanti can you provide more details on this exception like the OS, steps to reproduce, system version, context?

I suspect this exceptions is coming from a much older version of GL. Currently in `utils/mailutils.py` on line 100 we have:

```python
        message = MIME_mail_build(GLSettings.memory_copy.notif.source_name,
                                  GLSettings.memory_copy.notif.source_email,
                                  to_address,
                                  to_address,
                                  subject,
                                  body)
```

**Comment by fpietrosanti** [comment]
2.60.66

**Comment by NSkelsey** [comment]
An update will fix the issue.
