### ISSUE TITLE
If /dev/shm/globaleaks/ does not exist GlobaLeaks trigger an unhanded exception

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#1930]
This ticket is to handle this unhanded exception by properly checking if the directly exists and, if it does not exists, trying to create it dynamically.

GlobaLeaks version: 2.67.1

OSError OS system call failed.

Traceback (most recent call last):

  File "/usr/lib/python2.7/dist-packages/globaleaks/jobs/base.py", line 91, in run
    yield threads.deferToThread(self.operation)

  File "/usr/lib/python2.7/dist-packages/twisted/python/threadpool.py", line 246, in inContext
    result = inContext.theWork()

  File "/usr/lib/python2.7/dist-packages/twisted/python/threadpool.py", line 262, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)

  File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)

  File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 81, in callWithContext
    return func(*args,**kw)

  File "/usr/lib/python2.7/dist-packages/globaleaks/jobs/statistics_sched.py", line 86, in operation
    free_ramdisk_bytes, total_ramdisk_bytes = get_ramdisk_space()

  File "/usr/lib/python2.7/dist-packages/globaleaks/jobs/statistics_sched.py", line 21, in get_ramdisk_space
    statvfs = os.statvfs(GLSettings.ramdisk_path)

OSError: [Errno 2] No such file or directory: '/dev/shm/globaleaks/'

**Comment by NSkelsey** [comment]
The `gl-fix-permissions` script is responsible for creating the `/dev/shm/globaleaks` on install maybe we have introduced a regression there.

The setting `RAM_DISK` can be used to specify this file on startup.

**Comment by NSkelsey** [comment]
The `check_directories` function has been modified to also check for the` ram_disk_path`. On restart of this particular node, the operator will be prompted to run `gl-fix-permission`. The `ram_disk_path` is required for proper operation of the node. We will need to filter out these exceptions in the meantime.
