### ISSUE TITLE
Unhandled "Circuit is CLOSED but still has 1 streams" Tor error

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#2025]
**Current behavior**
Under unknown circuistamces this error comes from GlobaLeaks, related to Tor:

"GlobaLeaks version: 2.67.10

RuntimeError Unspecified run-time error.

RuntimeError: Circuit is CLOSED but still has 1 streams"

The very same error has been experienced by OONI Project:
https://trac.torproject.org/projects/tor/ticket/11995

**Expected behavior**
The condition related to this error should be understood and handled.

**Comment by NSkelsey** [comment]
Exception confirmed present in v2.70.9 as well.

It seems that the issue could be simply the client side of a Tor connection closing its circuit while the server's side is still using it. This could be an issue with our deferred handling as we write out using the SOCKs endpoint.

It is not clear how to reproduce this bug locally, but if this is in fact the case, every instance should produce a few of these exceptions over its lifespan.

Definitely worth investigating further.

**Comment by fpietrosanti** [comment]
even just avoiding triggering an unhanded exception and ignoring it it's a good stuff

**Comment by NSkelsey** [comment]
This exception will throw after a `txtorcon.circuit.Circuit` object is established for an established `txtorcon.controller.Tor` object. The fact that there are still open `txtorcon.stream.Stream`s  when the `Circuit` enters its `CLOSED` state throws the exception. This I believe is triggered by the `OnionService.tor_conn` object after it is created and is watching for state changes.

However, I think that this error only shows itself in txtorcon installs earlier than `0.19.0`, because the exception handling for this specific case has changed. Notice now that the only time this error is thrown in [0.19.3](https://github.com/meejah/txtorcon/blob/v0.19.3/txtorcon/circuit.py#L444-L447) (the version currently tracked as python-txtorcon in the debian universe) occurs when the circuit's state is `'FAILED'`. This is different from how it [used to throw](https://github.com/meejah/txtorcon/commit/080262391d4cf617ccd8b6ad7d72282447cc5c01#diff-0a4d73794a40b57a35bcfb19a4695af3L248).

Further following a [comments](https://github.com/meejah/txtorcon/blob/v0.19.3/txtorcon/circuit.py#L427-L433) recommendation to manually trigger the error by killing an active circuit connected to globaleaks from Tor version `0.3.1.7` does not throw the exception. Instead, on an older node, that does not track deb.torproject.org with tor version `0.2.9.11` and txtorcon `0.15.1` we see the issue about once a day.

To reproduce the test use:

```bash
# Create a circuit from the TBB
# Find it with list
carml --connect=unix:/var/run/tor/control circ --list
# Kill it
carml --connect=unix:/var/run/tor/control circ --delete ID
```

Therefore, I am going to close this issue because as it stands we have no evidence that nodes with updated dependencies throw this exception.

**Comment by NSkelsey** [comment]
On a newer node we are seeing the issue. Interestingly in `ExternNetLoopingJobs` we are catching `RuntimeError` which indicates that another section of the code is generating this exception as well.

Maybe the incidence is lower now than it was, but the exception gives very little information about the possible location of the generated failure.

```
Version: 2.72.7

RuntimeError Unspecified run-time error.

RuntimeError: Circuit is CLOSED but still has 1 streams
```

**Comment by NSkelsey** [comment]
This exception was generated ~14 seconds before the RuntimeError was sent. 15 seconds to me seems like a timeout.

```
Version: 2.72.7

txsocksx.errors.ServerFailure
    General SOCKS server failure ( 1 )


Traceback (most recent call last):

  File "/usr/lib/python2.7/dist-packages/globaleaks/jobs/base.py", line 78, in run
    yield self.operation()

  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1126, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)

  File "/usr/lib/python2.7/dist-packages/twisted/python/failure.py", line 389, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)

  File "/usr/lib/python2.7/dist-packages/globaleaks/jobs/exit_nodes_refresh_sched.py", line 23, in operation
    yield State.tor_exit_set.update(net_agent)

  File "/usr/lib/python2.7/dist-packages/ometa/protocol.py", line 53, in dataReceived
    self._parser.receive(data)

  File "/usr/lib/python2.7/dist-packages/ometa/tube.py", line 41, in receive
    status = self._interp.receive(data)

  File "/usr/lib/python2.7/dist-packages/ometa/interp.py", line 48, in receive
    for x in self.next:

  File "/usr/lib/python2.7/dist-packages/ometa/interp.py", line 166, in apply
    for x in self._apply(f, ruleName, argvals):

  File "/usr/lib/python2.7/dist-packages/ometa/interp.py", line 104, in _apply
    for x in rule():

  File "/usr/lib/python2.7/dist-packages/ometa/interp.py", line 245, in parse_Or
    for x in self._eval(subexpr):

  File "/usr/lib/python2.7/dist-packages/ometa/interp.py", line 230, in parse_And
    for x in self._eval(subexpr):

  File "/usr/lib/python2.7/dist-packages/ometa/interp.py", line 423, in parse_Action
    val = eval(expr.data, self.globals, self._localsStack[-1])

  File "<string>", line 1, in <module>

  File "/usr/lib/python2.7/dist-packages/txsocksx/client.py", line 153, in serverResponse
    raise e.socks5ErrorMap.get(status)()

ServerFailure
```

**Comment by NSkelsey** [comment]
It may be the case that the CircuitClosed failure was raised in a notification_sched job.

If that is true, then the logic in #2111 described [here](https://github.com/globaleaks/GlobaLeaks/issues/2111#issuecomment-336405547) and implemented in 28febc0 should resolve this issue.
