### ISSUE TITLE
Analyze technical requirements to Port GlobaLeaks to Windows

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#2050]
This ticket is to analyze all the technical implementations required to port GlobaLeaks to works on Windows.

Being python software, it shall be possible to run it on Windows, but we're probably using here and there a bunch of non-portable things.

This ticket is to try to setup GlobaLeaks on Windows, identifying all of the functionalities that are "non portable" and that would require a specific Windows implementation or to be rewritten to be entirely-purely python code.

Following that testing a report with TODO of what must be fixed to have it working on Windows must be done, along with a small roadmap to implement the "Windows specific facilities" required (installer, updater, service manager, UAC, etc).

**Comment by NSkelsey** [comment]
- [ ] Some file paths are specified via `os.path.join('path/to/dir', filename)`, these will have to change to: `os.path.join('path', 'to', 'dir', filename)`
- [ ] the usage of libraries like gnupg will need to be analyized

**Comment by n-daniel** [comment]
You can use linux subsystem and target only windows server > 2016

**Comment by fpietrosanti** [comment]
@n-daniel there's a ticket tracking this testing #1991 but it was not yet successful because only development edition seems to support it just now

**Comment by hackbunny** [comment]
@NSkelsey strictly speaking, "/" is a valid path separator on Windows, so that's not necessary (although cleaner).

Anyway, I looked into it. I assumed, from the use of the `__future__` module, that GlobalLeaks runs on Python 2, so I downloaded the Python 2.7.13 documentation, to look for Windows-specific behaviors in the standard Python library (looked for strings like "windows" and "win32"); I skipped the C APIs because I don't see any C code; obviously, I also ignored differences in behavior that are only an issue for porting _from_ Windows.

As far as I can tell, the modules used by GlobaLeaks with documented Windows-specific behaviors are:
- `ctypes`: many differences in behavior but, more importantly, this module provides an escape mechanism to call outside, non-Python code. Only used by `backend/globaleaks/utils/process.py` to access non-portable functionality through the libc. Outside of `disable_swap()`, **none of the functions in this module seem implementable on Windows**, and would be simply stubbed out
- `mimetypes`: differs on `init()`, which GlobaLeaks doesn't use
- `multiprocessing`: GlobaLeaks only used this module to determine the number of CPUs
- `os`:
   - `chmod()`: file modes are largely meaningless on Windows. 
   - `kill()`: see the note on the `signal` module below (in short, so non-portable all related code will have to be redesigned)
   - `listdir()`: behavior differs if a Unicode path is passed, but GlobaLeaks shouldn't be affected
   - `open()`: on Windows, opens files in text mode. **All uses of `open()` should be changed to use binary mode**
`globaleaks.settings.GLSettingsClass.fix_file_permissions` will have to be rewritten for Windows to use ACLs or SDDL strings, or the Windows version of GlobaLeaks won't be as secure
   - `path`: Windows path syntax is superficially similar to UNIX path syntax, but it has several non-obvious differences (that manifest themselves in Python APIs such as `path.isabs()` and `path.join()`) and [a whole load of quirky, often dangerous behavior](https://googleprojectzero.blogspot.it/2016/02/the-definitive-guide-on-win32-to-nt.html). **All path handling should be extensively audited and tested**
   - `remove()`: can't remove a file in use on Windows. **GlobaLeaks might be affected**
   - `stat()`: several differences in the returned data, but GlobaLeaks only uses fully portable fields
    - many, many other functions that GlobaLeaks, thankfully, doesn't use
- `platform`: obvious portability implications, but GlobaLeaks only uses it to determine whether it's running on Linux, and if it is, which distribution
- `shutil`: `copy` and `copy2` don't copy all file metadata, and the kind of metadata that isn't copied differs between Linux and Windows. In GlobaLeaks, only used for **database migration**, so probably not an issue, but it's better to check anyway
- `signal`: Windows has very limited support for signals, and even more limited support for inter-process signals. The **handling of subprocesses** in GlobaLeaks seems extensively based on UNIX signals, and would have to be redesigned for Windows, or rewritten in a portable way
- `socket`: on Windows, `fileno()` returns a pseudo-file descriptor, that won't work in most routines that take a file descriptor. **GlobaLeaks is affected**, see for example `globaleaks.backend.GLService._deferred_start()` and `globaleaks.workers.supervisor.ProcessSupervisor.__init__()`. However, it seems all pseudo-file descriptors are ultimately passed to Twisted (in `globaleaks.utils.sock.listen_tcp_on_sock()`), which may or may not handle them correctly
- `struct`: obvious portability implications. Only used in `globaleaks.utils.zipstream`, which I assume to be already portable, as it's forked from Python's own `zipfile`
- `subprocess`: GlobaLeaks uses this module to portably run... non-portable commands, such as `service`, `tar` and `find`. **The backup/restore feature of `gl-admin` will have to be rewritten for Windows**
- `tempfile`: differs on some behaviors of named temporary files, which GlobaLeaks doesn't use

The above only lists known Python portability issues, and is by far **not** a comprehensive list of all portability issues in the GlobaLeaks codebase. The following categories of issues should be considered too:
- the installer will have to be rewritten, as it's currently a shell script based on `apt`
- all filesystem paths will have to be changed, in fact the whole on-disk layout of GlobaLeaks will have to be rethought - no `/usr` or `/etc` on Windows!
- Windows-specific behavior that's outside of the scope of Python to abstract, such as the case-insensitive filesystem
- hardening/sandboxing will have to be reimplemented
- all external modules should be audited for portability, as well

I'll continue another time
つづく

**Comment by NSkelsey** [comment]
@hackbunny this is a great analysis. Thanks for putting it together.

- The backup/restore functionality is on the short term list for reimplementation #2074. We'll keep in mind the cross-compatibility requirement.

- The HTTPS sub modules usage of signals is certainly one of the larger challenges for cross-compat

- What are the options for packaging python code for windows that produce a workflow most similar to apt?

**Comment by hackbunny** [comment]
I'll answer your packaging/installing question with another question: why isn't pip enough for GlobaLeaks? I ask both because my Linux installer expertise is in rpm and yum, so I don't know the apt workflow at all, and because I have used pip on Windows and it has always worked flawlessly
That said, there's a notorious historical dearth of package management software for Windows: basically, the only realistic options are NuGet and NuGet-based Chocolatey, which sadly I know nothing about. I could research them if you could point me in the general direction of what's required to install/maintain/update GlobaLeaks

**Comment by evilaliv3** [comment]
Thanks @hackbunny here some answers to your new questions; we may be wrong in the following analysis so feel free to provide your suggestions.

The reason why currently on Ubuntu/Debian we are using apt-get are the following:
- as far that we know there is no way in pip to deal with signed packages not authenticated sources repository is minimally verified and so the signatures on the packages therein.
- it is not that particularly easy to freeze the pip packages the same way as it is doable with a a package included in a distribution so that given that currently we were oriented to support only ubuntu/debian we got used to that.

**Comment by NCommander** [comment]
So, due to being ill and not desiring to sit at my desk for extended periods of time, I took a look at this in an effort to try and get GL running on Windows natively.

@hackbunny gave a pretty good list so I'll just fill into what I ran into thus far.

requirements.txt is a symlink. Git exports this file as a text file. It is possible to actually use symlinks on Windows, but that feature is something of a landmine, and a bug requires you to be using an evelated shell if you're an admin, or a GPO to enable symlinks as a non-admin. We only use requirements.txt to check versioning on startup + installation via pip so this is kinda moot unless there are other symlinks I missed.

scrypt needed an update before I could get it to go on Windows, and I had to dig out Visual C++ for Python to compile all the extensions. Node on the other hand completed npm install without issue.

Some minor patching was needed to dynamically import UnixApplicationRunner/WindowsApplicationRunner from Twisted, but it was easy enough to do.

Right now, there's some weirdness with SQLAlchemy and handling of the SQLite paths, specifically, I had to pass in a path like this:

```
return 'sqlite+pysqlite:///C:\\\\Users\\\\mcasadevall\\\\test.db'
````

There's an associated issue that SQLite bindings for Python get unhappy about anything that isn't "C:\\path\\db.db" for reasons I haven't managed to comprehend.

Handling ACL/permissions on Windows is ... interesting. The closest equivalent to a daemon on Windows is a service, but services can be run as a non-elevated account. It's also quite a bit different story on dropping permissions on Windows, in theory, you can use AdjustTokenPrivileges () to drop what you can and can't do, but you can't switch users on a running process; at best you can create a new token under a given user and CreateProcess it.

The best way to handle this is likely have the installer simply create a GlobaLeaks service account, ACL everything to Full Control to said user, and drop the Everybody ACL, and just check we're running as who we expect we are on setup (we can store the user in the registry). As we'll start as a non-privelleged user, this should be roughly equivalent to what we're doing on Linux.

After patching and stubbing out code to get this far, GlobaLeaks successfully builds it's database and falls over trying to rev up Twisted.

Unfortunately, socket fds *do not work* under Windows. The fundamental problem is when the socket is passed back to the reactor, it takes a rather deep trip in twisted, and fundamentally ends at socket.fromfd() which it Unix only according to Python documentation. It seems the only way to handle this is to simply let Twisted open the port directly under it's own control.

I'm not sure why we don't do that to begin with vs the rather complicated state logic with http/https sockets.

Looking long term, I don't think there are any fundamental "fatal" issues that would prevent us from allowing GlobaLeaks from running natively on Windows, and getting dev mode working at least partially should be straightforward.

**Comment by fpietrosanti** [comment]
@NCommander do you think it would be possible following this hacking session to make a first preliminary set of pull request to starts having ifdef WINDOWS into the code, feeding those ifdef with TODO or final fix so the code-structure slowly improve in the windows support direction?

**Comment by NCommander** [comment]
with the exception of the db hack, all the changes i made are ifdef'ed
already using platform to dynamically import whats needed and logs error if
anything is stubbed out. still need to test on Linux to confirm i didnt
accidently break anything though. Config will likely require a refactor to
bring in sane per platform defaults. I can throw up a PR for what i have
though i question how useful it is without getting as far as allowing
Twisted ti start the HTTP socket

On Mar 29, 2018 11:10, "Fabio (naif) Pietrosanti" <notifications@github.com>
wrote:

@NCommander <https://github.com/NCommander> do you think it would be
possible following this hacking session to make a first preliminary set of
pull request to starts having ifdef WINDOWS into the code, feeding those
ifdef with TODO or final fix so the code-structure slowly improve in the
windows support direction?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/globaleaks/GlobaLeaks/issues/2050#issuecomment-377267392>,
or mute the thread

**Comment by fpietrosanti** [comment]
Random link/ref on collateral aspects:

pyuac - elevate a Python process with UAC on Windows 
https://gist.github.com/Preston-Landers/267391562bc96959eb41

Windows create a new local group with a new user inside it. timgolden.me.uk/python/win32_how_do_i/create-a-local-group-with-a-new-user.html

**Comment by NCommander** [comment]
You can't use UAC elevation when you're operating as a system service as services don't (normally) have an attached desktop to work with it. We can use UAC however during installation. The question comes down to do we always want to install as a service or install on a per-user basis. That being said, the conversation there is moot until we actually have things working.

**Comment by NCommander** [comment]
https://github.com/globaleaks/GlobaLeaks/pull/2237

Here's the PR with the work in progress. Currently requires a full developers Python 2.7 (32 bit) installation, Visual C++ for Python, a copy of stdint.h header, and other pain. requirements-win32.txt is a copy of requirements-xenial.txt with the bumped version of scrypt.

I can probably get this working at least partially (Tor support will be challenging) with some effort if this is a high priority objective.

**Comment by NCommander** [comment]
Context: fromfd actually is supported on Python 3.x on Windows, but not 2.7 out of the box. There was a patch for Python 2.6 (which the 3.x patch came from)

So, I eventually got Python 2.7 compiled (which required jumping through a *lot* of hoops), then I had to bang the patch into a usable form. With the other tweaks I got, we now get this

```
(glenv) PS C:\Users\mcasadevall\src\GlobaLeaks\backend> glenv\Scripts\python .\bin\globaleaks -z "Michael Casadevall" -n -l DEBUG
Starting GlobaLeaks ...
WARNING: Windows support is extremely experimental at this time, and should not be used for production environments
WARNING: pip dependency checking not supported on Windows at this time
Enabling development mode for Michael Casadevall
Going in background; log available at C:\Users\mcasadevall\src\GlobaLeaks\backend\workingdir\log\globaleaks.log
Serving the client from directory: C:\Users\mcasadevall\src\GlobaLeaks\client\app
2018-03-29 22:16:14-0400 [-] Log opened.
2018-03-29 22:16:14-0400 [-] twistd 16.0.0 (C:\Users\mcasadevall\src\GlobaLeaks\backend\glenv\Scripts\python.exe 2.7.13) starting up.
2018-03-29 22:16:14-0400 [-] reactor class: twisted.internet.selectreactor.SelectReactor.
2018-03-29 22:16:14-0400 [-] [E] Unable to secure C:\\Users\\mcasadevall\\src\\GlobaLeaks\\backend\\workingdir on Windows
2018-03-29 22:16:14-0400 [-] [E] Unable to secure C:\\Users\\mcasadevall\\src\\GlobaLeaks\\backend\\workingdir\\attachments on Windows
2018-03-29 22:16:14-0400 [-] [E] Unable to secure C:\\Users\\mcasadevall\\src\\GlobaLeaks\\backend\\workingdir\\backups on Windows
2018-03-29 22:16:14-0400 [-] [E] Unable to secure C:\\Users\\mcasadevall\\src\\GlobaLeaks\\backend\\workingdir\\db on Windows
2018-03-29 22:16:14-0400 [-] [E] Unable to secure C:\\Users\\mcasadevall\\src\\GlobaLeaks\\backend\\workingdir\\files on Windows
2018-03-29 22:16:14-0400 [-] [E] Unable to secure C:\\Users\\mcasadevall\\src\\GlobaLeaks\\backend\\workingdir\\log on Windows
2018-03-29 22:16:14-0400 [-] [E] Unable to secure C:\\Users\\mcasadevall\\src\\GlobaLeaks\\backend\\workingdir\\tmp on Windows
2018-03-29 22:16:14-0400 [-] [E] Unable to securely drop permissions on Windows
2018-03-29 22:16:17-0400 [-] Site starting on 8082
2018-03-29 22:16:17-0400 [-] Starting factory <twisted.web.server.Site instance at 0x0535DC38>
2018-03-29 22:16:17-0400 [-] Site starting on 8083
2018-03-29 22:16:17-0400 [-] Site starting on 8080
2018-03-29 22:16:17-0400 [-] [I] Starting process monitor
2018-03-29 22:16:17-0400 [-] [I] Not launching workers
2018-03-29 22:16:18-0400 [-] GlobaLeaks is now running and accessible at the following urls:
2018-03-29 22:16:18-0400 [-] - [LOCAL HTTP]     --> http://127.0.0.1:8082
2018-03-29 22:16:18-0400 [-] - [LOCAL HTTP]     --> http://127.0.0.1:8083
2018-03-29 22:16:18-0400 [-] - [REMOTE HTTP]    --> http://0.0.0.0
2018-03-29 22:16:19-0400 [-] [E] Job Anomalies died with runtime -1.0000 [low: -1.0000, high: -1.0000]
2018-03-29 22:16:19-0400 [-] Traceback (most recent call last):
2018-03-29 22:16:19-0400 [-]   File "C:\Users\mcasadevall\src\GlobaLeaks\backend\globaleaks\jobs\base.py", line 53, in run
2018-03-29 22:16:19-0400 [-]     yield self.operation()
2018-03-29 22:16:19-0400 [-] AttributeError: 'module' object has no attribute 'statvfs'
2018-03-29 22:16:19-0400 [-] [E] Unhandled exception raised:
2018-03-29 22:16:19-0400 [-] [E] AttributeError Attribute not found.\n\nTraceback (most recent call last):\n\n  File "C:\\Users\\mcasadevall\\src\\GlobaLeaks\\backend\\globaleaks\\jobs\\base.py", line 53, in run\n    yield self.operation()\n\nAttributeError: 'module' object has no attribute 'statvfs'\n
2018-03-29 22:16:19-0400 [-] [E] Failed to initialize Tor connection; error: Tor control port not open on /var/run/tor/control; waiting for Tor to become available
2018-03-29 22:16:19-0400 [-] [D] Fetching list of Tor exit nodes
2018-03-29 22:16:19-0400 [-] Starting factory <txsocksx.client.SOCKS5ClientFactory instance at 0x07845058>
2018-03-29 22:16:19-0400 [-] [D] Fetching latest GlobaLeaks version from repository
2018-03-29 22:16:19-0400 [-] Starting factory <txsocksx.client.SOCKS5ClientFactory instance at 0x07746530>
2018-03-29 22:16:19-0400 [-] [D] [1] Sending email to globaleaks-stackexception-devel@globaleaks.org using SMTP server [demo.globaleaks.org:9267] [TLS]
2018-03-29 22:16:19-0400 [-] Starting factory <txsocksx.client.SOCKS5ClientFactory instance at 0x07856B48>
2018-03-29 22:16:20-0400 [-] [E] UpdateCheck job failed on outgoing network connection with: Connection was refused by other side: 10061: No connection could be made because the target machine actively refused it..
2018-03-29 22:16:20-0400 [-] Stopping factory <txsocksx.client.SOCKS5ClientFactory instance at 0x07746530>
(... SNIP repeated error log spam that it can't send email)
2018-03-29 22:16:40-0400 [-] [E] Blocked file operation for: (prefix, attempted_path) : ('C:\\Users\\mcasadevall\\src\\GlobaLeaks\\client\\app/', 'C:\\Users\\mcasadevall\\src\\GlobaLeaks\\client\\app\\index.html')
2018-03-29 22:16:40-0400 [-] [-] [1] 403 GET / 103B 2ms
2018-03-29 22:16:41-0400 [-] [E] Blocked file operation for: (prefix, attempted_path) : ('C:\\Users\\mcasadevall\\src\\GlobaLeaks\\client\\app/', 'C:\\Users\\mcasadevall\\src\\GlobaLeaks\\client\\app\\favicon.ico')
2018-03-29 22:16:41-0400 [-] [-] [1] 403 GET /favicon.ico 103B 4ms
```

Or in short, the entire event loop is now running, Twisted was able to grab the socket, and if I go to 127.0.0.1:8082, I get output.

Specifically:
```
{"error_message": "Blocked file operation out of the expected path", "error_code": 15, "arguments": []}
```

The outbound failure errors is likely being caused by the Windows firewall. Obviously we're still a long way off from having GL *usable* on Windows, but it looks like the concept is fundamental viable. Long-term, since we're going to have to ship Python for Windows as part of any easy to use package, we can just roll our own with the necessary patch, or just wait for Py3+port of GL to finish.

That being said, flushing out the rest of the win32 issues can be done now.

**Comment by NCommander** [comment]
Before going to sleep, I rangled the GnuPG fails out (no code changes required), I reran trial and got:

FAILED (failures=3, errors=8, successes=267)

Needless to say, that's a rather staggering success.

The three failures and the cause is:

globaleaks.tests.test_orm.TestORM.test_pragmas:
 - the SECURE DELETE pragma didn't seem to stick. SQLite docs don't say anything about this being a UNIX-specific pragma so further investigation required.

globaleaks.tests.utils.test_securetempfile.TestSecureTemporaryFiles.test_temporary_file:
 - Not entirely sure what went wrong here, but it failed on the readback. Possibly related how Windows handles files that can lock writing or deletion if they're open exclusively (which is the default)

globaleaks.tests.utils.test_utility.TestUtility.test_is_expired
 - self.assertTrue(utility.is_expired(utility.datetime_now())) exploded. This test looks suspect to me, since if there's any latency between datetime_now() running and when the check is evaluated, this is a false positive? I'll look further.

The eight failures; Same errors are grouped together:
globaleaks.tests.handlers.admin.test_config.TestHostnameConfig.test_put
globaleaks.tests.utils.test_token.TestToken.test_token_usage_limit
 - Died with exceptions.ValueError: Customizing childFDs is not supported on Windows.

Need to look deeper into this to see what this is trying to do. 

globaleaks.tests.utils.test_token.TestToken.test_proof_of_work_right_answer
globaleaks.tests.test_orm.TestORM.test_transaction_with_exception
globaleaks.tests.handlers.admin.test_https.TestConfigHandler.test_all_methods
 - globaleaks.rest.errors.TokenFailure: TokenFailure: <<Unacceptable condition for usage of Token: Too early to use this token>> (4) HTTP:401
(possibly related to the is_expired failure above)

globaleaks.tests.handlers.test_token.Test_TokenInstance.test_put_right_answer
 - exceptions.AttributeError: rootdomain
(I haven't got a clue on this one, will debug further)

globaleaks.tests.workers.test_supervisor.TestProcessSupervisor.test_init_with_launch
 - Dies trying to dlopen libc.so.6 to rename the process

This is kinda a weird case. Windows has no specific equivalent to process renaming, but it's possible to add name objects which can be fished out with stuff like Process Explorer. Unless this exists more than a debug aid, I think we can safely NOP this on Windows. There's a python library that can abstract this behavior if we want to go down that route however.

globaleaks.tests.workers.test_supervisor.TestSubprocessRun.test_https_process
 - Crashes Python, no exception trace generated.

It looks like aside from the token weirdness, we're in relatively good health. There's a fair bit of UNIX specific code where we open libc and do magic which I need to see is if it's actually used or if its dead, and then figure out what to do about it.

**Comment by fpietrosanti** [comment]
@NCommander i was thinking, as a way to complete this major steps, do you think that you have the time and energy to bring this step up to final completion with the building and automated process of building GlobaLeaks for Windows?

**Comment by evilaliv3** [comment]
Discarded for the moment since porting globaleaks to Windows remain for the moment an utopia and our research remain focused on open source system and environments.
