### ISSUE TITLE
Cleaning Sched trigger OverflowError Result too large to be represented.

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#2061]
**Current behavior**
We receive those unhandled exception:
GlobaLeaks version: 2.64.9

OverflowError Result too large to be represented.

Traceback (most recent call last):

  File "/usr/lib/python2.7/dist-packages/globaleaks/jobs/base.py", line 79, in _operation
    yield self.operation()

  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1097, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)

  File "/usr/local/lib/python2.7/dist-packages/twisted/python/failure.py", line 389, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)

  File "/usr/lib/python2.7/dist-packages/globaleaks/jobs/cleaning_sched.py", line 132, in operation
    yield self.check_for_expiring_submissions()

  File "/usr/local/lib/python2.7/dist-packages/twisted/python/threadpool.py", line 191, in _worker
    result = context.call(ctx, function, *args, **kwargs)

  File "/usr/local/lib/python2.7/dist-packages/twisted/python/context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)

  File "/usr/local/lib/python2.7/dist-packages/twisted/python/context.py", line 81, in callWithContext
    return func(*args,**kw)

  File "/usr/lib/python2.7/dist-packages/globaleaks/orm.py", line 106, in _wrap
    result = function(self.instance, self.store, *args, **kwargs)

  File "/usr/lib/python2.7/dist-packages/globaleaks/jobs/cleaning_sched.py", line 68, in check_for_expiring_submissions
    threshold = datetime_now() + timedelta(GLSettings.memory_copy.notif.tip_expiration_threshold)

OverflowError: normalized days too large to fit in a C int

**Expected behavior**
This condition should be handed

**Comment by NSkelsey** [comment]
This issue has been fixed in 967a22e221ef148daecd41567e99ebc56bfbc371, `v2.65.13` Jan 2017.

An update is needed to resolve the issue.
