### ISSUE TITLE
Handle unhandled exception from ACME LetsEncrypt module

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#2069]
**Current behavior**
Handle unhandled exception from ACME LetsEncrypt:
Platform: prova.xxxxx.it ()
Version: 2.71.3

acme.errors.PollError Generic error when polling for authorization fails.

    This might be caused by either timeout (`exhausted` will be non-empty)
    or by some authorization being invalid.

    :ivar exhausted: Set of `.AuthorizationResource` that didn't finish
        within max allowed attempts.
    :ivar updated: Mapping from original `.AuthorizationResource`
        to the most recently updated one

**Comment by evilaliv3** [comment]
I think this is missing detail and shuuld be skipped for the moment until new cases leading to reproducibility.

**Comment by evilaliv3** [comment]
I've verified this on the ICC portal. There it was related to a CCA record.

Already the condition is handled by the client  think we should simply modify the handler to not send an unhandled exception.

**Comment by NSkelsey** [comment]
@evilaliv3 could you provide some logs and/or output to the specific point missing proper handling?

**Comment by NSkelsey** [comment]
Found one

```
Version: 2.72.13

acme.errors.PollError Generic error when polling for authorization fails.

    This might be caused by either timeout (`exhausted` will be non-empty)
    or by some authorization being invalid.

    :ivar exhausted: Set of `.AuthorizationResource` that didn't finish
        within max allowed attempts.
    :ivar updated: Mapping from original `.AuthorizationResource`
        to the most recently updated one

Traceback (most recent call last):

  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1126, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)

  File "/usr/lib/python2.7/dist-packages/twisted/python/failure.py", line 389, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)

  File "/usr/lib/python2.7/dist-packages/globaleaks/handlers/admin/https.py", line 546, in put
    yield deferToThread(acme_cert_issuance)

  File "/usr/lib/python2.7/dist-packages/twisted/python/threadpool.py", line 246, in inContext
    result = inContext.theWork()

  File "/usr/lib/python2.7/dist-packages/twisted/python/threadpool.py", line 262, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)

  File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)

  File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 81, in callWithContext
    return func(*args,**kw)

  File "/usr/lib/python2.7/dist-packages/globaleaks/orm.py", line 75, in __call__
    return self.run(self._wrap, self.method, *args, **kwargs)

  File "/usr/lib/python2.7/dist-packages/globaleaks/orm.py", line 120, in run
    return function(*args, **kwargs)

  File "/usr/lib/python2.7/dist-packages/globaleaks/orm.py", line 97, in _wrap
    result = function(store, *args, **kwargs)

  File "/usr/lib/python2.7/dist-packages/globaleaks/handlers/admin/https.py", line 524, in acme_cert_issuance
    return db_acme_cert_issuance(store)

  File "/usr/lib/python2.7/dist-packages/globaleaks/handlers/admin/https.py", line 514, in db_acme_cert_issuance
    Settings.acme_directory_url)

  File "/usr/lib/python2.7/dist-packages/globaleaks/utils/letsencrypt.py", line 75, in run_acme_reg_to_finish
    cert_res, _ = acme.poll_and_request_issuance(jose.util.ComparableX509(csr), (authzr,))

  File "/usr/lib/python2.7/dist-packages/acme/client.py", line 401, in poll_and_request_issuance
    raise errors.PollError(exhausted, updated)

PollError
```

**Comment by NSkelsey** [comment]
It also can fail here:
```
    cert_res, _ = acme.poll_and_request_issuance(jose.util.ComparableX509(csr), (authzr,))

  File "/usr/lib/python2.7/dist-packages/acme/client.py", line 401, in poll_and_request_issuance
    raise errors.PollError(exhausted, updated)

PollError
```

**Comment by lcicinelli** [comment]
Hi,
we have same issue on new clean instance version 3.10.3. 

`2019-08-06 13:05:21+0200 [-] [E] Unhandled exception raised:
2019-08-06 13:05:21+0200 [-] [E] acme.errors.ValidationError Error for authorization failures. Contains a list of poll_authorizations
    resources, each of which is invalid and should have an error field.poll_authorizations
    poll_authorizations
Traceback (most recent call last):poll_authorizations
File "/usr/lib/python3/dist-packages/twisted/internet/defer.py", line 1384, in inlineCallbackspoll_authorizations
    result = result.throwExceptionIntoGenerator(g)poll_authorizations
  File "/usr/lib/python3/dist-packages/twisted/python/failure.py", line 408, in throwExceptionIntoGeneratorpoll_authorizations
    return g.throw(self.type, self.value, self.tb)poll_authorizations
  File "/usr/lib/python3/dist-packages/globaleaks/handlers/admin/https.py", line 557, in putpoll_authorizations
    yield acme_cert_issuance(self.request.tid)poll_authorizations
  File "/usr/lib/python3/dist-packages/twisted/python/threadpool.py", line 250, in inContextpoll_authorizations
    result = inContext.theWork()poll_authorizations
  File "/usr/lib/python3/dist-packages/twisted/python/threadpool.py", line 266, in <lambda>poll_authorizations
    inContext.theWork = lambda: context.call(ctx, func, args, *kw)poll_authorizations
  File "/usr/lib/python3/dist-packages/twisted/python/context.py", line 122, in callWithContextpoll_authorizations
    return self.currentContext().callWithContext(ctx, func, args, *kw)poll_authorizations
  File "/usr/lib/python3/dist-packages/twisted/python/context.py", line 85, in callWithContextpoll_authorizations
    return func(*args,**kw)poll_authorizations
  File "/usr/lib/python3/dist-packages/globaleaks/orm.py", line 117, in wrappoll_authorizations
    result = function(session, args, *kwargs)poll_authorizations
  File "/usr/lib/python3/dist-packages/globaleaks/handlers/admin/https.py", line 537, in acme_cert_issuancepoll_authorizations
    return db_acme_cert_issuance(session, tid)poll_authorizations
  File "/usr/lib/python3/dist-packages/globaleaks/handlers/admin/https.py", line 500, in db_acme_cert_issuancepoll_authorizations
    Settings.acme_directory_url)poll_authorizations
  File "/usr/lib/python3/dist-packages/globaleaks/utils/letsencrypt.py", line 84, in request_new_certificatepoll_authorizations
    order = client.poll_and_finalize(order)poll_authorizations
  File "/usr/lib/python3/dist-packages/acme/client.py", line 676, in poll_and_finalizepoll_authorizations
    orderr = self.poll_authorizations(orderr, deadline)poll_authorizations
  File "/usr/lib/python3/dist-packages/acme/client.py", line 700, in poll_authorizationspoll_authorizations
    raise errors.ValidationError(failed)poll_authorizations acme.errors.ValidationError`

**Comment by evilaliv3** [comment]
Dear @lcicinelli, would you please confirm to have pointed the domain name to the public IP of the server on which you have installed GlobaLeaks? This is necessary for letsencrypt to work.

**Comment by evilaliv3** [comment]
Closing as outdated.
