### ISSUE TITLE
Unhandled exception TypeError: Cannot safely assume encoding of byte string '{"v": "xxxxxx.onion"}'.

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#2084]
**Current behavior**

Platform:  ()
Version: 2.72.3

TypeError Inappropriate argument type.

Traceback (most recent call last):

  File "/usr/lib/python2.7/dist-packages/twisted/python/threadpool.py", line 246, in inContext
    result = inContext.theWork()

  File "/usr/lib/python2.7/dist-packages/twisted/python/threadpool.py", line 262, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)

  File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)

  File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 81, in callWithContext
    return func(*args,**kw)

  File "/usr/lib/python2.7/dist-packages/globaleaks/orm.py", line 105, in _wrap
    result = function(store, *args, **kwargs)

  File "/usr/lib/python2.7/dist-packages/globaleaks/handlers/public.py", line 394, in get_public_resources
    'node': db_serialize_node(store, language),

  File "/usr/lib/python2.7/dist-packages/globaleaks/handlers/public.py", line 126, in db_serialize_node
    ro_node = NodeFactory(store).public_export()

  File "/usr/lib/python2.7/dist-packages/globaleaks/models/config.py", line 171, in public_export
    return self._export_group_dict(self.public_node)

  File "/usr/lib/python2.7/dist-packages/globaleaks/models/config.py", line 110, in _export_group_dict
    self._query_group()

  File "/usr/lib/python2.7/dist-packages/globaleaks/models/config.py", line 87, in _query_group
    self.res = {c.var_name: c for c in cur}

  File "/usr/lib/python2.7/dist-packages/globaleaks/models/config.py", line 87, in <dictcomp>
    self.res = {c.var_name: c for c in cur}

  File "/usr/lib/python2.7/dist-packages/storm/store.py", line 980, in __iter__
    yield self._load_objects(result, values)

  File "/usr/lib/python2.7/dist-packages/storm/store.py", line 973, in _load_objects
    return self._find_spec.load_objects(self._store, result, values)

  File "/usr/lib/python2.7/dist-packages/storm/store.py", line 1711, in load_objects
    values[values_start:values_end])

  File "/usr/lib/python2.7/dist-packages/storm/store.py", line 711, in _load_object
    replace_unknown_lazy=True)

  File "/usr/lib/python2.7/dist-packages/storm/store.py", line 769, in _set_values
    result.set_variable(variable, value)

  File "/usr/lib/python2.7/dist-packages/storm/databases/sqlite.py", line 83, in set_variable
    variable.set(value, from_db=True)

  File "/usr/lib/python2.7/dist-packages/storm/variables.py", line 588, in set
    super(MutableValueVariable, self).set(value, from_db)

  File "/usr/lib/python2.7/dist-packages/storm/variables.py", line 599, in parse_set
    return self._loads(value)

  File "/usr/lib/python2.7/dist-packages/storm/variables.py", line 638, in _loads
    "Cannot safely assume encoding of byte string %r." % value)

TypeError: Cannot safely assume encoding of byte string '{"v": "gnzz3ao1oqnuc1il.onion"}'.

**Comment by evilaliv3** [comment]
Closing as outdated.
