### ISSUE TITLE
Certificato SSL automatico non rinnovato.

### ISSUE THREAD

**Issue by alepartenza** [globaleaks/GlobaLeaks#2114]
Salve,
con le ultime versioni di Globaleaks i certificati SSL dovrebbero essere rinnovati in automatico? 
Ieri un certificato è scaduto e non è stato rinnovato in automatico (come scritto nella pagina).

Esiste una procedura per rinnovare manualmente?

Allego immagine
![globaleaks](https://user-images.githubusercontent.com/4155187/31606443-67954388-b269-11e7-95a1-1e51b9a22d90.jpg)

**Comment by alepartenza** [comment]
Platform: _url_ ()
Version: 2.72.10

urllib2.HTTPError Raised when HTTP error occurs, but also acts like non-error return

Traceback (most recent call last):

  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1126, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)

  File "/usr/lib/python2.7/dist-packages/twisted/python/failure.py", line 389, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)

  File "/usr/lib/python2.7/dist-packages/globaleaks/handlers/admin/https.py", line 546, in put
    yield deferToThread(acme_cert_issuance)

  File "/usr/lib/python2.7/dist-packages/twisted/python/threadpool.py", line 246, in inContext
    result = inContext.theWork()

  File "/usr/lib/python2.7/dist-packages/twisted/python/threadpool.py", line 262, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)

  File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)

  File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 81, in callWithContext
    return func(*args,**kw)

  File "/usr/lib/python2.7/dist-packages/globaleaks/orm.py", line 75, in __call__
    return self.run(self._wrap, self.method, *args, **kwargs)

  File "/usr/lib/python2.7/dist-packages/globaleaks/orm.py", line 120, in run
    return function(*args, **kwargs)

  File "/usr/lib/python2.7/dist-packages/globaleaks/orm.py", line 97, in _wrap
    result = function(store, *args, **kwargs)

  File "/usr/lib/python2.7/dist-packages/globaleaks/handlers/admin/https.py", line 524, in acme_cert_issuance
    return db_acme_cert_issuance(store)

  File "/usr/lib/python2.7/dist-packages/globaleaks/handlers/admin/https.py", line 514, in db_acme_cert_issuance
    Settings.acme_directory_url)

  File "/usr/lib/python2.7/dist-packages/globaleaks/utils/letsencrypt.py", line 60, in run_acme_reg_to_finish
    resp = urlopen(test_path)

  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)

  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)

  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)

  File "/usr/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)

  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)

  File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)

HTTPError: HTTP Error 401: Unauthorized

**Comment by NSkelsey** [comment]
Hi @alepartenza this issue was resolved as of `v2.72.11` just update and the issue will disappear.
