### ISSUE TITLE
Unhandled AlreadyCalledError in notification_sched

### ISSUE THREAD

**Issue by NSkelsey** [globaleaks/GlobaLeaks#2123]
**Current behavior**

Running globaleaks locally (based on branch 2.72.13) my machine throws the following when the Tor SOCKS proxy is down:

```
2017-11-03 18:35:41+0100 [-] [D] Sending email to globaleaks-stackexception-devel@globaleaks.org using SMTP server [demo.globaleaks.org:9267] [TLS]
2017-11-03 18:35:41+0100 [-] Starting factory <txsocksx.client.SOCKS5ClientFactory instance at 0x7f1fc5e62f38>
2017-11-03 18:35:41+0100 [-] [E] SMTP connection failed (Exception: Connection was refused by other side: 111: Connection refused.)
2017-11-03 18:35:41+0100 [-] [D] [Failure instance: Traceback (failure with no frames): <class 'twisted.internet.error.ConnectionRefusedError'>: Connection was refused by other side: 111: Connection refused.\n]
2017-11-03 18:35:41+0100 [-] [E] SMTP connection failed (Exception: Connection was refused by other side: 111: Connection refused.)
2017-11-03 18:35:41+0100 [-] [D] [Failure instance: Traceback (failure with no frames): <class 'twisted.internet.error.ConnectionRefusedError'>: Connection was refused by other side: 111: Connection refused.\n]
2017-11-03 18:35:41+0100 [-] Stopping factory <txsocksx.client.SOCKS5ClientFactory instance at 0x7f1fc5e62f38>
2017-11-03 18:35:41+0100 [-] [E] Job Notification died with runtime 93.0000 [low: 93.0000, high: 93.0000]
2017-11-03 18:35:41+0100 [-] Traceback (most recent call last):
2017-11-03 18:35:41+0100 [-]   File "/home/nskelsey/projects/globaleaks/backend/globaleaks/jobs/base.py", line 78, in run
2017-11-03 18:35:41+0100 [-]     yield threads.deferToThread(self.operation)
2017-11-03 18:35:41+0100 [-]   File "/home/nskelsey/projects/globaleaks/backend/venv/local/lib/python2.7/site-packages/twisted/python/threadpool.py", line 246, in inContext
2017-11-03 18:35:41+0100 [-]     result = inContext.theWork()
2017-11-03 18:35:41+0100 [-]   File "/home/nskelsey/projects/globaleaks/backend/venv/local/lib/python2.7/site-packages/twisted/python/threadpool.py", line 262, in <lambda>
2017-11-03 18:35:41+0100 [-]     inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
2017-11-03 18:35:41+0100 [-]   File "/home/nskelsey/projects/globaleaks/backend/venv/local/lib/python2.7/site-packages/twisted/python/context.py", line 118, in callWithContext
2017-11-03 18:35:41+0100 [-]     return self.currentContext().callWithContext(ctx, func, *args, **kw)
2017-11-03 18:35:41+0100 [-]   File "/home/nskelsey/projects/globaleaks/backend/venv/local/lib/python2.7/site-packages/twisted/python/context.py", line 81, in callWithContext
2017-11-03 18:35:41+0100 [-]     return func(*args,**kw)
2017-11-03 18:35:41+0100 [-]   File "/home/nskelsey/projects/globaleaks/backend/globaleaks/jobs/notification_sched.py", line 268, in operation
2017-11-03 18:35:41+0100 [-]     self.spool_emails()
2017-11-03 18:35:41+0100 [-]   File "/home/nskelsey/projects/globaleaks/backend/globaleaks/jobs/notification_sched.py", line 263, in spool_emails
2017-11-03 18:35:41+0100 [-]     threads.blockingCallFromThread(reactor, self.sendmail, mail)
2017-11-03 18:35:41+0100 [-]   File "/home/nskelsey/projects/globaleaks/backend/venv/local/lib/python2.7/site-packages/twisted/internet/threads.py", line 122, in blockingCallFromThread
2017-11-03 18:35:41+0100 [-]     result.raiseException()
2017-11-03 18:35:41+0100 [-]   File "/home/nskelsey/projects/globaleaks/backend/venv/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 588, in _runCallbacks
2017-11-03 18:35:41+0100 [-]     current.result = callback(current.result, *args, **kw)
2017-11-03 18:35:41+0100 [-]   File "/home/nskelsey/projects/globaleaks/backend/globaleaks/utils/mailutils.py", line 80, in errback
2017-11-03 18:35:41+0100 [-]     return result_deferred.errback(reason)
2017-11-03 18:35:41+0100 [-]   File "/home/nskelsey/projects/globaleaks/backend/venv/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 434, in errback
2017-11-03 18:35:41+0100 [-]     self._startRunCallbacks(fail)
2017-11-03 18:35:41+0100 [-]   File "/home/nskelsey/projects/globaleaks/backend/venv/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 494, in _startRunCallbacks
2017-11-03 18:35:41+0100 [-]     raise AlreadyCalledError
2017-11-03 18:35:41+0100 [-] AlreadyCalledError
2017-11-03 18:35:41+0100 [-] [E] exception mail suppressed for exception (<class 'twisted.internet.defer.AlreadyCalledError'>) [reason: special exception]

```

Other users have seen similar exceptions on the 2.72 series.

**Expected behavior**

The original connection failure should be handled and the subsequent exception should not throw at all.

**GlobaLeaks version:**

Confirmed v2.72.13

**Comment by evilaliv3** [comment]
Fixed! well done @NSkelsey.

I've integrated the patch with minor corrections; just readded the thread to minimize the number of operation that we perform in the main thread.
