### ISSUE TITLE
the script for setting up a dev env doesn' t work

### ISSUE THREAD

**Issue by humanitiesNerd** [globaleaks/GlobaLeaks#2135]
**Current behavior**
[This page](https://github.com/globaleaks/GlobaLeaks/wiki/setting-up-globaleaks-development-environment) mentions [this script](https://raw.githubusercontent.com/globaleaks/GlobaLeaks/devel/scripts/setup_development_environment.sh) for setting up a development environment on Ubuntu based installations.

I installed Ubuntu 17.10 x86_64 in a virtual machine and run the script straight away

It doesn't finish and ends with this error:

```
...
hl/setuptools/sandbox.py", line 255, in run_setup
  File "/home/catonano/GlobaLeaks/backend/glenv/share/python-wheels/setuptools-32.3.1-py2.py3-none-any.whl/setuptools/sandbox.py", line 285, in run
  File "/home/catonano/GlobaLeaks/backend/glenv/share/python-wheels/setuptools-32.3.1-py2.py3-none-any.whl/setuptools/sandbox.py", line 253, in runner
  File "/home/catonano/GlobaLeaks/backend/glenv/share/python-wheels/setuptools-32.3.1-py2.py3-none-any.whl/setuptools/sandbox.py", line 47, in _execfile
  File "/tmp/easy_install-h9uOGN/mock-2.0.0/temp/easy_install-Km7KVp/pbr-3.1.1/setup.py", line 22, in <module>
    testsuite_runner= runner.TrialRunner(reporter.TreeReporter)
  File "/tmp/easy_install-h9uOGN/mock-2.0.0/temp/easy_install-Km7KVp/pbr-3.1.1/pbr/util.py", line 267, in cfg_to_args
  File "/tmp/easy_install-h9uOGN/mock-2.0.0/temp/easy_install-Km7KVp/pbr-3.1.1/pbr/util.py", line 569, in wrap_commands
  File "/home/catonano/GlobaLeaks/backend/glenv/share/python-wheels/pkg_resources-0.0.0-py2.py3-none-any.whl/pkg_resources/__init__.py", line 2297, in resolve
ImportError: No module named dist_info
```

**Expected behavior**
I expected the script to return the prompt with no error and a dev env ready to be used

**Steps to reproduce the problem or feature illustration**
In a freshly installed Ubuntu 17.10 machine, run the script with sudo

**What is the motivation or use case for changing the behavior?**
either you provide a script or you provide a list of steps
Now I don' t know in which state the machine is and how to recover
I can only hope to achieve the state that was intended to be produced by the script
I should probably discard this machine and create a new one from scratch

**GlobaLeaks version:**
I don' t know the version, I' m writing this on 12th december 2017

**Browser:**
doesn' t apply

**Server Operating System and Version (if applicable):**
doesn' t apply

**Client Operating System and Version (if applicable):**
doesn' t apply

**Comment by evilaliv3** [comment]
Thank you for reporing this @humanitiesNerd.

i'm going to analyze the reasons about the current failure and write here in case of updates.

**Comment by humanitiesNerd** [comment]
2017-12-12 20:26 GMT+01:00 Giovanni Pellerano <notifications@github.com>:

> Thank you for reporing this @humanitiesNerd
> <https://github.com/humanitiesnerd>.
>
> i'm going to analyze the reasons about the current failure and write here
> in case of updates.
>

Thanks

**Comment by evilaliv3** [comment]
@humanitiesNerd i retested the script on ubuntu 16.04 and it is currently working.

I guess the reason of your failure is that you are going to develop on top of ubuntu 17.10.

Support for this platform is not planned as we currently support only Ubuntu LTS versions and the next one after 16.04 will bhe the 18.04.

I would suggest you to just proceed setupping an ubuntu 16.04 and develop on top of it for best support from our community.

In case anyhow you require to develop on top of this distribution you may evaluate to create a requirements-artful.txt as done for the other editions:
- https://github.com/globaleaks/GlobaLeaks/issues/1515
- https://github.com/globaleaks/GlobaLeaks/tree/master/backend/requirements

Feel free to reach out in case of any additional doubt.

**Comment by humanitiesNerd** [comment]
2017-12-12 21:27 GMT+01:00 Giovanni Pellerano <notifications@github.com>:

> @humanitiesNerd <https://github.com/humanitiesnerd> i retested the script
> on ubuntu 16.04 and it is currently working.
>
> I guess the reason of your failure is that you are going to develop on top
> of ubuntu 17.10.
>
> Support for this platform is not planned as we currently support only
> Ubuntu LTS versions and the next one after 16.04 will bhe the 18.04.
>

I see. Thank you very much for your concern


> I would suggest you to just proceed setupping an ubuntu 16.04 and develop
> on top of it for best support from our community.
>
> In case anyhow you require to develop on top of this distribution you may
> evaluate to create a requirements-artful.txt as done for the other editions:
>
Ubuntu 16.04 is ok, I used the last one because the instructions were not
specific about a version

>
>    - #1515 <https://github.com/globaleaks/GlobaLeaks/issues/1515>
>    - https://github.com/globaleaks/GlobaLeaks/tree/master/
>    backend/requirements
>
> Feel free to reach out in case of any additional doubt.
>

Ah I had missed these ! Thanks again !

**Comment by gabrieloandco** [comment]
These are my approaches to get the installation working so far:


I ran [setup_development_environment.sh](https://raw.githubusercontent.com/globaleaks/GlobaLeaks/devel/scripts/setup_development_environment.sh) with a few changes from line 98:

```
rm requirements.txt
cp requirements/requirements-xenial.txt requirements.txt
sudo virtualenv -p python2.7 glenv
source glenv/bin/activate 
```

If I run: `python setup.py develop --always-unzip , since for some reason it wasn't installing twister` or ` pip install -r requirements.txt` I get:

```

$./bin/globaleaks -z "Developer Name" -n
......
  File "./bin/globaleaks", line 41, in <module>
    from twisted.python import usage
ImportError: No module named twisted.python

```
This means that, for some reason, it didn't install the required packages. To fix it I ran:
`sudo -H pip install -r requirements.txt `

Then from `GlobaLeaks/backend` I run: 
`./bin/globaleaks -z "Developer Name" -n`
But I get:
```
Serving the client from directory: /home/bonny/Installs/GlobaLeaks/client/app
Traceback (most recent call last):
  File "./bin/globaleaks", line 131, in <module>
    State.init_environment()
  File "/home/bonny/Installs/GlobaLeaks/backend/globaleaks/state.py", line 73, in init_environment
    self.create_directories()
  File "/home/bonny/Installs/GlobaLeaks/backend/globaleaks/state.py", line 119, in create_directories
    self.create_directory(dirpath)
  File "/home/bonny/Installs/GlobaLeaks/backend/globaleaks/state.py", line 100, in create_directory
    raise excep
OSError: [Errno 13] Permission denied: '/home/bonny/Installs/GlobaLeaks/backend/workingdir'
```

However this can be "patched" by:
```
$mkdir ./workingdir
$sudo chmod -777 .workingdir 
```
But then it will raise another problem:
```
./bin/globaleaks -z "Gabriel" -n
Starting GlobaLeaks…
WARNING: The long term supported platform is Ubuntu Xenial (16.04)
WARNING: It is recommended to use only this platform to ensure stability and security
WARNING: Read about Technical Requirement at: http://globaleaks.readthedocs.io/en/latest/TechnicalRequirements.html
WARNING: If it's an old Ubuntu, read more about updating at: https://github.com/globaleaks/GlobaLeaks/wiki/Upgrade-Guide#platform-update
Enabling development mode for Gabriel
Going in background; log available at /home/bonny/Installs/GlobaLeaks/backend/workingdir/log/globaleaks.log
Serving the client from directory: /home/bonny/Installs/GlobaLeaks/client/app
2018-02-21 17:54:19+0100 [-] Log opened.
2018-02-21 17:54:19+0100 [-] twistd 16.0.0 (/home/bonny/Installs/GlobaLeaks/backend/glenv/bin/python 2.7.14) starting up.
2018-02-21 17:54:19+0100 [-] reactor class: twisted.internet.epollreactor.EPollReactor.
2018-02-21 17:54:19+0100 [-] Unable to start GlobaLeaks: [Errno 1] Operation not permitted: '/home/bonny/Installs/GlobaLeaks/backend/workingdir'
```

**Comment by evilaliv3** [comment]
Hello @gabrieloandco !

The reason of the failure for pip was that pyotbably you didnt have the virtualenv in the python path;
You fixed by yourself installing the libraries globaleally but actually the right local fix was to execute:
```export PYTHONPATH=`pwd```' from inside the GlobaLeaks directory.

In relation instead to the second problem you should not create your working directory manually as globaleaks at initialization time has to create a set of subdirectory that you have not created and this may be the cause of the failure.

Be sure that you are starting globaleaks with 'bonny' the files inside the directory are owned by bonny.
maybe in fact that for error you fetched the files using root or an other user.

For any other doubt feel free to get back here.

**Comment by gabrieloandco** [comment]
Thank you, after installing gnupg1 and rebooting it passed every unit test on Ubuntu 17.10.

**Comment by fpietrosanti** [comment]
@gabrieloandco consider fixing the development environment setup script, in order to get a fully working environment in an automated way

**Comment by gabrieloandco** [comment]
I made just a few changes to the setup script:
```
set -e

DISTRIBUTION=$(lsb_release -c)
TAG="master"

# Redirect stdout ( > ) into a named pipe ( >() ) running "tee"
exec > >(tee -i ./setup_log.txt)

usage() {
  echo "GlobaLeaks Setup Development Environment Script (Ubuntu only)"
  echo "Valid options:"
  echo " -h"
  echo -e " -t tagname (prepare for development on specific release/branch)"
}

while getopts "t:h" opt; do
  case $opt in
    t) TAG="$OPTARG"
    ;;
    h)
        usage
        exit 1
    ;;
    \?) usage
        exit 1
    ;;
  esac
done

DISTRO="unknown"
DISTRO_CODENAME="unknown"
if which lsb_release >/dev/null; then
  DISTRO="$( lsb_release -is )"
  DISTRO_CODENAME="$( lsb_release -cs )"
fi

if [ "$DISTRO" != "Ubuntu" ]; then
 echo "Failure: this script is meant to be used only on Ubuntu"
 exit 1
fi

if [ -d "GlobaLeaks" ]; then
 echo "Failure: found an existing local GlobaLeaks directory"
 exit 1
fi

echo "GlobaLeaks Setup Development Environment Script"

echo "Step 1/8: add universe repository"

if [ "$DISTRO_CODENAME" = "precise" ]; then
  sudo apt-get install python-software-properties -y
else
  sudo apt-get install software-properties-common
fi
sudo add-apt-repository universe

echo "Step 2/8: update"
sudo apt-get update

echo "Step 3/8: apt-get install"
sudo apt-get install build-essential curl git python-pip libssl-dev libffi-dev python-virtualenv python-dev gnupg1

echo "Step 4/8: git clone"
git clone https://github.com/globaleaks/GlobaLeaks.git
if [ "$TAG" != "master"]; then
  cd GlobaLeaks/ && git checkout $TAG && cd ..
fi

echo "Step 5/8: install npm and node"
curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
sudo apt-get install -y nodejs

echo "Step 6/8: install grunt"
sudo npm install -g grunt-cli
sudo npm install -g findup-sync


echo "Step 7/8: setup client dependencies"
cd GlobaLeaks/client
npm install -d
./node_modules/grunt/bin/grunt copy:sources
cd ../../

echo "Step 8/8: prepare backend virtualenv"
cd GlobaLeaks
export PYTHONPATH=pwd
cd ../

cd GlobaLeaks/backend

rm requirements.txt

cp requirements/requirements-xenial.txt requirements/requirements-artful.txt

cp requirements/requirements-$DISTRO_CODENAME.txt requirements.txt

virtualenv -p python2.7 glenv
source glenv/bin/activate
python setup.py develop --always-unzip 

```

The backend test passed sucessfully.

For the front end test I had to install  findup-sync as shown in the script because I was having a [dependency issue](https://stackoverflow.com/questions/15444020/cannot-find-module-findup-sync-when-trying-to-run-grunt). I also had to download the browser's drivers as stated in the documentation.

**Comment by evilaliv3** [comment]
Closing as outdated.
