### ISSUE TITLE
Unhandled exception checking size of /dev/shm/globaleaks

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#2136]
Version: 2.72.24

OSError OS system call failed.

Traceback (most recent call last):

  File "/usr/lib/python2.7/dist-packages/globaleaks/jobs/base.py", line 79, in run
    yield threads.deferToThread(self.operation)

  File "/usr/lib/python2.7/dist-packages/twisted/python/threadpool.py", line 246, in inContext
    result = inContext.theWork()

  File "/usr/lib/python2.7/dist-packages/twisted/python/threadpool.py", line 262, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)

  File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)

  File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 81, in callWithContext
    return func(*args,**kw)

  File "/usr/lib/python2.7/dist-packages/globaleaks/jobs/statistics_sched.py", line 76, in operation
    free_ramdisk_bytes, total_ramdisk_bytes = get_ramdisk_space()

  File "/usr/lib/python2.7/dist-packages/globaleaks/jobs/statistics_sched.py", line 21, in get_ramdisk_space
    statvfs = os.statvfs(Settings.ramdisk_path)

OSError: [Errno 2] No such file or directory: '/dev/shm/globaleaks/'

**Comment by fpietrosanti** [comment]
We may also entirely remove the use of /dev/shm by using an in-memory sqlite db for temporary storage of those information https://www.sqlite.org/inmemorydb.html .

**Comment by fpietrosanti** [comment]
Appened again today

**Comment by evilaliv3** [comment]
i'm for removing the usage of /dev/shm and managing the temporary keys in memory.

they will not survive to a reboot but i would prefer this to simplify the solution that could be even dangerous if /dev/shm would not result to be in ram but mapped on the disk

**Comment by evilaliv3** [comment]
Exact duplicate of https://github.com/globaleaks/GlobaLeaks/issues/1930
