### ISSUE TITLE
Unhandled exception when creating/reading keys stored in /dev/shm/globaleaks/

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#2137]
Consequence of #2136 

IOError I/O operation failed.

Traceback (most recent call last):

  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1128, in _inlineCallbacks
    result = g.send(result)

  File "/usr/lib/python2.7/dist-packages/globaleaks/handlers/files.py", line 102, in post
    uploaded_file = self.get_file_upload()

  File "/usr/lib/python2.7/dist-packages/globaleaks/handlers/base.py", line 452, in get_file_upload
    Uploads.set(flow_identifier, SecureTemporaryFile(Settings.tmp_upload_path))

  File "/usr/lib/python2.7/dist-packages/globaleaks/security.py", line 142, in __init__
    self.create_key()

  File "/usr/lib/python2.7/dist-packages/globaleaks/security.py", line 185, in create_key
    with open(self.keypath, 'w') as kf:

IOError: [Errno 2] No such file or directory: '/dev/shm/globaleaks/aeskey-r69a22Gj4MSWaix1'

**Comment by evilaliv3** [comment]
Strictly related to https://github.com/globaleaks/GlobaLeaks/issues/1930;

A solution will be analyzed and implemented in an uinified manner on that ticket.
