### ISSUE TITLE
Unhandled exception in SQL while using Whistleblower Identity IntegrityError: FOREIGN KEY constraint failed

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#2142]
**Current behavior**
Platform: xxxxxxx.comune.xxxxxxx.it
Version: 2.72.26

sqlite3.IntegrityError None

Traceback (most recent call last):

  File "/usr/lib/python2.7/dist-packages/twisted/python/threadpool.py", line 246, in inContext
    result = inContext.theWork()

  File "/usr/lib/python2.7/dist-packages/twisted/python/threadpool.py", line 262, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)

  File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)

  File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 81, in callWithContext
    return func(*args,**kw)

  File "/usr/lib/python2.7/dist-packages/globaleaks/orm.py", line 97, in _wrap
    result = function(store, *args, **kwargs)

  File "/usr/lib/python2.7/dist-packages/globaleaks/models/__init__.py", line 50, in delete
    return db_delete(store, model, *args, **kwargs)

  File "/usr/lib/python2.7/dist-packages/globaleaks/models/__init__.py", line 45, in db_delete
    return store.find(model, *args, **kwargs).remove()

  File "/usr/lib/python2.7/dist-packages/storm/store.py", line 1183, in remove
    Delete(self._where, self._find_spec.default_cls_info.table))

  File "/usr/lib/python2.7/dist-packages/storm/database.py", line 238, in execute
    raw_cursor = self.raw_execute(statement, params)

  File "/usr/lib/python2.7/dist-packages/storm/databases/sqlite.py", line 154, in raw_execute
    return Connection.raw_execute(self, statement, params)

  File "/usr/lib/python2.7/dist-packages/storm/database.py", line 322, in raw_execute
    self._check_disconnect(raw_cursor.execute, *args)

  File "/usr/lib/python2.7/dist-packages/storm/database.py", line 371, in _check_disconnect
    return function(*args, **kwargs)

IntegrityError: FOREIGN KEY constraint failed

**Comment by evilaliv3** [comment]
Closing as duplicate: https://github.com/globaleaks/GlobaLeaks/issues/2142
