### ISSUE TITLE
Unhandled exception Failed to execute 'readAsText' on 'FileReader': parameter 1 is not of type 'Blob'.

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#2146]
This error is not handled by GlobaLeaks client and shall be prevented or handled with a proper error message

Platform: globaleaks.xxxxxx
Version: 2.72.27

URL: /admin/network

User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36

Error Message: TypeError: Failed to execute 'readAsText' on 'FileReader': parameter 1 is not of type 'Blob'.

Stacktrace:
[
  {
    "source": "    at Object.readFileAsText (http://192.168.1.37/js/scripts.js:10521:16)", 
    "columnNumber": 16, 
    "fileName": "http://192.168.1.37/js/scripts.js", 
    "functionName": "Object.readFileAsText", 
    "lineNumber": 10521
  }, 
  {
    "source": "    at b.$scope.postFile (http://192.168.1.37/js/scripts.js:19362:11)", 
    "columnNumber": 11, 
    "fileName": "http://192.168.1.37/js/scripts.js", 
    "functionName": "b.$scope.postFile", 
    "lineNumber": 19362
  }, 
  {
    "source": "    at fn (http://192.168.1.37/js/scripts.js:253:306", 
    "columnNumber": 306, 
    "fileName": "http://192.168.1.37/js/scripts.js", 
    "functionName": "fn", 
    "lineNumber": 253
  }, 
  {
    "source": "    at m.d.(anonymous function) [as filePickerInput] (http://192.168.1.37/js/scripts.js:99:245)", 
    "columnNumber": 245, 
    "fileName": "http://192.168.1.37/js/scripts.js", 
    "functionName": "m.d.(anonymous function) [as filePickerInput]", 
    "lineNumber": 99
  }, 
  {
    "columnNumber": 17, 
    "fileName": "http://192.168.1.37/js/scripts.js", 
    "source": "    at http://192.168.1.37/js/scripts.js:11238:17", 
    "lineNumber": 11238
  }, 
  {
    "source": "    at m.$eval (http://192.168.1.37/js/scripts.js:162:69)", 
    "columnNumber": 69, 
    "fileName": "http://192.168.1.37/js/scripts.js", 
    "functionName": "m.$eval", 
    "lineNumber": 162
  }, 
  {
    "source": "    at m.$apply (http://192.168.1.37/js/scripts.js:162:294)", 
    "columnNumber": 294, 
    "fileName": "http://192.168.1.37/js/scripts.js", 
    "functionName": "m.$apply", 
    "lineNumber": 162
  }, 
  {
    "source": "    at HTMLInputElement.<anonymous> (http://192.168.1.37/js/scripts.js:11237:15)", 
    "columnNumber": 15, 
    "fileName": "http://192.168.1.37/js/scripts.js", 
    "functionName": "HTMLInputElement.<anonymous>", 
    "lineNumber": 11237
  }, 
  {
    "source": "    at jg (http://192.168.1.37/js/scripts.js:51:8)", 
    "columnNumber": 8, 
    "fileName": "http://192.168.1.37/js/scripts.js", 
    "functionName": "jg", 
    "lineNumber": 51
  }, 
  {
    "source": "    at HTMLInputElement.d (http://192.168.1.37/js/scripts.js:50:462)", 
    "columnNumber": 462, 
    "fileName": "http://192.168.1.37/js/scripts.js", 
    "functionName": "HTMLInputElement.d", 
    "lineNumber": 50
  }
]

**Comment by evilaliv3** [comment]
Closing as outdated.
