### ISSUE TITLE
Exception on dump_field_entry for serialization of dates: "ValueError: invalid literal for int() with base 10: ''

### ISSUE THREAD

**Issue by alepartenza** [globaleaks/GlobaLeaks#2148]
Salve,
quando accedo come ricevente, non è possibile scaricare la segnalazione.

Version: 2.72.28

ValueError Inappropriate argument value (of correct type).

Traceback (most recent call last):

  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1126, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)

  File "/usr/lib/python2.7/dist-packages/twisted/python/failure.py", line 389, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)

  File "/usr/lib/python2.7/dist-packages/globaleaks/handlers/export.py", line 128, in get
    tip_export = yield get_tip_export(self.current_user.user_id, rtip_id, self.request.language)

  File "/usr/lib/python2.7/dist-packages/twisted/python/threadpool.py", line 246, in inContext
    result = inContext.theWork()

  File "/usr/lib/python2.7/dist-packages/twisted/python/threadpool.py", line 262, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)

  File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)

  File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 81, in callWithContext
    return func(*args,**kw)

  File "/usr/lib/python2.7/dist-packages/globaleaks/orm.py", line 97, in _wrap
    result = function(store, *args, **kwargs)

  File "/usr/lib/python2.7/dist-packages/globaleaks/handlers/export.py", line 46, in get_tip_export
    export_template = Templating().format_template(export_dict['notification']['export_template'], export_dict).encode('utf-8')

  File "/usr/lib/python2.7/dist-packages/globaleaks/utils/templating.py", line 472, in format_template
    variable_content = getattr(keyword_converter, kw[1:-1])()

  File "/usr/lib/python2.7/dist-packages/globaleaks/utils/templating.py", line 273, in QuestionnaireAnswers
    return self.dump_questionnaire_answers(self.data['tip']['questionnaire'], self.data['tip']['answers'])

  File "/usr/lib/python2.7/dist-packages/globaleaks/utils/templating.py", line 235, in dump_questionnaire_answers
    output = self.dump_fields(output, step['children'], answers, 1) +'\n'

  File "/usr/lib/python2.7/dist-packages/globaleaks/utils/templating.py", line 218, in dump_fields
    output = self.dump_field_entry(output, field, entries[0], indent_n + 1)

  File "/usr/lib/python2.7/dist-packages/globaleaks/utils/templating.py", line 188, in dump_field_entry
    output += indent(indent_n) + ISO8601_to_pretty_str(entry.get('value', '')) + '\n'

  File "/usr/lib/python2.7/dist-packages/globaleaks/utils/utility.py", line 281, in ISO8601_to_pretty_str
    date = datetime(year=int(isodate[0:4]),

ValueError: invalid literal for int() with base 10: ''

**Comment by evilaliv3** [comment]
The bug is confirmed and i've been able to reproduce it.

The issue happens in the serialization of fields of type date in the situation in which the user did not provide any answer.

**Comment by evilaliv3** [comment]
Fixed, the patch will be included in next release.
