### ISSUE TITLE
Debian 8.10 - issue after upgrade

### ISSUE THREAD

**Issue by PiemP** [globaleaks/GlobaLeaks#2170]
**Current behavior**
when I run apt-get upgrade under my Debian system I update my globaleaks installation, but after that the service doesn't start and I've notice this error in the syslog file: 

Feb 23 11:34:23 globaleaks1 globaleaks[6174]: Unhandled Error
Feb 23 11:34:23 globaleaks1 globaleaks[6174]: Traceback (most recent call last):
Feb 23 11:34:23 globaleaks1 globaleaks[6174]: File "/usr/bin/globaleaks", line 158, in <module>
Feb 23 11:34:23 globaleaks1 globaleaks[6174]: run_backend()
Feb 23 11:34:23 globaleaks1 globaleaks[6174]: File "/usr/bin/globaleaks", line 151, in run_backend
Feb 23 11:34:23 globaleaks1 globaleaks[6174]: UnixApplicationRunner(config).run()
Feb 23 11:34:23 globaleaks1 globaleaks[6174]: File "/usr/local/lib/python2.7/dist-packages/twisted/application/app.py", line 348, in run
Feb 23 11:34:23 globaleaks1 globaleaks[6174]: self.application = self.createOrGetApplication()
Feb 23 11:34:23 globaleaks1 globaleaks[6174]: File "/usr/local/lib/python2.7/dist-packages/twisted/application/app.py", line 413, in createOrGetApplication
Feb 23 11:34:23 globaleaks1 globaleaks[6174]: application = getApplication(self.config, passphrase)
Feb 23 11:34:23 globaleaks1 globaleaks[6174]: --- <exception caught here> ---
Feb 23 11:34:23 globaleaks1 globaleaks[6174]: File "/usr/local/lib/python2.7/dist-packages/twisted/application/app.py", line 424, in getApplication
Feb 23 11:34:23 globaleaks1 globaleaks[6174]: application = service.loadApplication(filename, style, passphrase)
Feb 23 11:34:23 globaleaks1 globaleaks[6174]: File "/usr/local/lib/python2.7/dist-packages/twisted/application/service.py", line 411, in loadApplication
Feb 23 11:34:23 globaleaks1 globaleaks[6174]: passphrase)
Feb 23 11:34:23 globaleaks1 globaleaks[6174]: File "/usr/local/lib/python2.7/dist-packages/twisted/persisted/sob.py", line 224, in loadValueFromFile
Feb 23 11:34:23 globaleaks1 globaleaks[6174]: eval(codeObj, d, d)
Feb 23 11:34:23 globaleaks1 globaleaks[6174]: File "/usr/lib/python2.7/dist-packages/globaleaks/backend.py", line 18, in <module>
Feb 23 11:34:23 globaleaks1 globaleaks[6174]: from globaleaks.rest.api import APIResourceWrapper
Feb 23 11:34:23 globaleaks1 globaleaks[6174]: File "/usr/lib/python2.7/dist-packages/globaleaks/rest/api.py", line 36, in <module>
Feb 23 11:34:23 globaleaks1 globaleaks[6174]: from globaleaks.handlers.admin import https
Feb 23 11:34:23 globaleaks1 globaleaks[6174]: File "/usr/lib/python2.7/dist-packages/globaleaks/handlers/admin/https.py", line 18, in <module>
Feb 23 11:34:23 globaleaks1 globaleaks[6174]: from globaleaks.utils import letsencrypt, tls
Feb 23 11:34:23 globaleaks1 globaleaks[6174]: File "/usr/lib/python2.7/dist-packages/globaleaks/utils/letsencrypt.py", line 10, in <module>
Feb 23 11:34:23 globaleaks1 globaleaks[6174]: from globaleaks.mocks import acme_mocks # pylint: disable=W0611
Feb 23 11:34:23 globaleaks1 globaleaks[6174]: File "/usr/lib/python2.7/dist-packages/globaleaks/mocks/acme_mocks.py", line 6, in <module>
Feb 23 11:34:23 globaleaks1 globaleaks[6174]: from acme import messages, util
Feb 23 11:34:23 globaleaks1 globaleaks[6174]: File "/usr/local/lib/python2.7/dist-packages/acme/messages.py", line 4, in <module>
Feb 23 11:34:23 globaleaks1 globaleaks[6174]: from acme import challenges
Feb 23 11:34:23 globaleaks1 globaleaks[6174]: File "/usr/local/lib/python2.7/dist-packages/acme/challenges.py", line 10, in <module>
Feb 23 11:34:23 globaleaks1 globaleaks[6174]: import requests
Feb 23 11:34:23 globaleaks1 globaleaks[6174]: File "/usr/local/lib/python2.7/dist-packages/requests/__init__.py", line 53, in <module>
Feb 23 11:34:23 globaleaks1 globaleaks[6174]: from .packages.urllib3.contrib import pyopenssl
Feb 23 11:34:23 globaleaks1 globaleaks[6174]: File "/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 62, in <module>
Feb 23 11:34:23 globaleaks1 globaleaks[6174]: ssl.PROTOCOL_SSLv3: OpenSSL.SSL.SSLv3_METHOD,
Feb 23 11:34:23 globaleaks1 globaleaks[6174]: exceptions.AttributeError: 'module' object has no attribute 'PROTOCOL_SSLv3

to fix this issue I've to execute this command: 

pip install requests==2.6.0

found in this post https://stackoverflow.com/questions/28987891/patch-pyopenssl-for-sslv3-issue

**Expected behavior**
clean upgrade

**Steps to reproduce the problem or feature illustration**
upgrade your installation under a Debian 8.10 system

**GlobaLeaks version:**
2.7.32 and 3.0.0

**Browser:**
every browser

**Server Operating System and Version (if applicable):**
Debian 8.10 x64

**Comment by evilaliv3** [comment]
Thank you @PiemP 

I confirm the presence of the bug and the correctness of the solution you proposed.

I've produced a patch that will be included in release 3.0.1

For production setups it's highly suggested to proceed with the an infrastructure based on Ubuntu 16.04 that is the officially supported platform. The benefit that you would find there are an additional apparmor profile and a full debian package instead of a pip based provisioning of the dependencies.
