### ISSUE TITLE
Unhandled exception in OpenSSL.crypto in version 3.0.2

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#2175]
**Current behavior**
Unhandled exception in version 3.0.2 on OpenSSL.crypto

Version: 3.0.2

OpenSSL.crypto.Error 
    An error occurred in an `OpenSSL.crypto` API.
    

Traceback (most recent call last):

  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1126, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)

  File "/usr/lib/python2.7/dist-packages/twisted/python/failure.py", line 389, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)

  File "/usr/lib/python2.7/dist-packages/globaleaks/handlers/admin/https.py", line 564, in put
    yield acme_cert_issuance(self.request.tid)

  File "/usr/lib/python2.7/dist-packages/twisted/python/threadpool.py", line 246, in inContext
    result = inContext.theWork()

  File "/usr/lib/python2.7/dist-packages/twisted/python/threadpool.py", line 262, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)

  File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)

  File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 81, in callWithContext
    return func(*args,**kw)

  File "/usr/lib/python2.7/dist-packages/globaleaks/orm.py", line 103, in _wrap
    result = function(session, *args, **kwargs)

  File "/usr/lib/python2.7/dist-packages/globaleaks/handlers/admin/https.py", line 542, in acme_cert_issuance
    return db_acme_cert_issuance(session, tid)

  File "/usr/lib/python2.7/dist-packages/globaleaks/handlers/admin/https.py", line 521, in db_acme_cert_issuance
    csr = tls.gen_x509_csr(priv_key, csr_fields, 256)

  File "/usr/lib/python2.7/dist-packages/globaleaks/utils/tls.py", line 82, in gen_x509_csr
    setattr(subj, field, value)

  File "/usr/lib/python2.7/dist-packages/OpenSSL/crypto.py", line 469, in __setattr__
    _raise_current_error()

  File "/usr/lib/python2.7/dist-packages/OpenSSL/_util.py", line 48, in exception_from_error_queue
    raise exception_type(errors)

Error: [('asn1 encoding routines', 'ASN1_mbstring_ncopy', 'string too short')]

**Comment by kenavn** [comment]
Hello, is there a know work-around for this one? It effectively blocks using the let's encrypt integration

**Comment by NCommander** [comment]
@kenavn Which platform are you running on, and which version of GL (and is it a production install of GL)

**Comment by fpietrosanti** [comment]
we found out that's a UX bug, because once you write the hostname, it must be manually saved before triggering the LE certificate activation, and it's a backend bug because we're not validating that hostname coming to the backend is empty

@kenavn A you can easily work-around it by clicking "save" on the hostname and then activating LE. 

To fix this we will need to introduce a client-side-fix by first saving automatically the hostname once it's typed (without having to do it) and a backend check that "hostname" being passed to LE REST handler taking care of ACME certificate activation is not empty

/cc @evilaliv3

**Comment by evilaliv3** [comment]
Closing as outdated.
