### ISSUE TITLE
Unhandled error when receving multiple SIGINT signals

### ISSUE THREAD

**Issue by gabrieloandco** [globaleaks/GlobaLeaks#2185]
**Current behavior**

When sending multiple SIGINT signals in a short time we will get the folllowing Unhandled error:
```
^C2018-02-28 00:27:00+0100 [-] Received SIGINT, shutting down.
^C2018-02-28 00:27:00+0100 [-] Received SIGINT, shutting down.
2018-02-28 00:27:00+0100 [-] Unhandled Error
	Traceback (most recent call last):
	  File "/home/bonny/Installs/GlobaLeaks/backend/glenv/local/lib/python2.7/site-packages/Twisted-16.0.0-py2.7-linux-x86_64.egg/twisted/application/app.py", line 364, in startReactor
	    self.config, oldstdout, oldstderr, self.profiler, reactor)
	  File "/home/bonny/Installs/GlobaLeaks/backend/glenv/local/lib/python2.7/site-packages/Twisted-16.0.0-py2.7-linux-x86_64.egg/twisted/application/app.py", line 285, in runReactorWithLogging
	    reactor.run()
	  File "/home/bonny/Installs/GlobaLeaks/backend/glenv/local/lib/python2.7/site-packages/Twisted-16.0.0-py2.7-linux-x86_64.egg/twisted/internet/base.py", line 1194, in run
	    self.mainLoop()
	  File "/home/bonny/Installs/GlobaLeaks/backend/glenv/local/lib/python2.7/site-packages/Twisted-16.0.0-py2.7-linux-x86_64.egg/twisted/internet/base.py", line 1203, in mainLoop
	    self.runUntilCurrent()
	--- <exception caught here> ---
	  File "/home/bonny/Installs/GlobaLeaks/backend/glenv/local/lib/python2.7/site-packages/Twisted-16.0.0-py2.7-linux-x86_64.egg/twisted/internet/base.py", line 798, in runUntilCurrent
	    f(*a, **kw)
	  File "/home/bonny/Installs/GlobaLeaks/backend/glenv/local/lib/python2.7/site-packages/Twisted-16.0.0-py2.7-linux-x86_64.egg/twisted/internet/base.py", line 581, in stop
	    "Can't stop reactor that isn't running.")
	twisted.internet.error.ReactorNotRunning: Can't stop reactor that isn't running.
```

**Expected behavior**

The program should ignore future SIGINT signals after the first one

**Steps to reproduce the problem or feature illustration**

Hitting ^C quickly

**What is the motivation or use case for changing the behavior?**

This is odd because in every case that `reactor.stop` is called in the code it is checked whether the reactor was running first.  Perhaps checking if  ^C was pressed before looping into a shutdown sequence would solve the problem.

**GlobaLeaks version:**

Latest version to this date

**Browser:**

Doesn't apply

**Server Operating System and Version (if applicable):**
 
Doesn't apply

**Client Operating System and Version (if applicable):**

Ubuntu 17.10, Ubuntu 16.04

**Comment by evilaliv3** [comment]
Legit bug reporting and right suggestion! Thank you @gabrieloandco

**Comment by evilaliv3** [comment]
Thank you @gabrieloandco, actually this more of a bug of GlobaLeaks is a bug of twisted.

It is not our code that performs the reactor.stop() but it's twisted.
Inf the code for the shutdown hook we just perform eventual additional activities but the message that you read (```Received SIGINT, shutting down.```) is written by twisted as it receives SIGINT and before colling us it raises the exception that you got.

The issue is a known issue in many twisted projects.

**Comment by evilaliv3** [comment]
To be verified if this is still actual.
