### ISSUE TITLE
AttributeError: 'Query' object has no attribute 'set'

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#2190]
Platform: 
Version: 3.0.2

AttributeError Attribute not found.

Traceback (most recent call last):

  File "/usr/lib/python2.7/dist-packages/twisted/python/threadpool.py", line 246, in inContext
    result = inContext.theWork()

  File "/usr/lib/python2.7/dist-packages/twisted/python/threadpool.py", line 262, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)

  File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)

  File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 81, in callWithContext
    return func(*args,**kw)

  File "/usr/lib/python2.7/dist-packages/globaleaks/orm.py", line 103, in _wrap
    result = function(session, *args, **kwargs)

  File "/usr/lib/python2.7/dist-packages/globaleaks/handlers/admin/field.py", line 255, in delete_field
    models.Questionnaire.id == models.Step.questionnaire_id).set(enable_whistleblower_identity = False)

AttributeError: 'Query' object has no attribute 'set'

**Comment by evilaliv3** [comment]
Bug confirmed, related to the SQLAlchemy refactor.

The bug is not critical and will be fixed as part of release 3.0.7
