### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'type' in serialize_field

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#2208]
Platform: 
Version: 3.0.8

AttributeError Attribute not found.

Traceback (most recent call last):

  File "/usr/lib/python2.7/dist-packages/twisted/python/threadpool.py", line 246, in inContext
    result = inContext.theWork()

  File "/usr/lib/python2.7/dist-packages/twisted/python/threadpool.py", line 262, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)

  File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)

  File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 81, in callWithContext
    return func(*args,**kw)

  File "/usr/lib/python2.7/dist-packages/globaleaks/orm.py", line 103, in _wrap
    result = function(session, *args, **kwargs)

  File "/usr/lib/python2.7/dist-packages/globaleaks/handlers/admin/field.py", line 184, in create_field
    return serialize_field(session, tid, field, language)

  File "/usr/lib/python2.7/dist-packages/globaleaks/handlers/public.py", line 261, in serialize_field
    'type': f_to_serialize.type,

AttributeError: 'NoneType' object has no attribute 'type'

**Comment by evilaliv3** [comment]
The issue seems related to the usage of default questions that are attached to the first tenant.

When users of secondary tenants try to attach them this operation is triggering an exception.

**Comment by evilaliv3** [comment]
The issue should be fixed now.
