### ISSUE TITLE
IntegrityError: UNIQUE constraint failed: user.username

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#2210]
Platform: 
Version: 2.72.31

sqlite3.IntegrityError None

Traceback (most recent call last):

  File "/usr/lib/python2.7/dist-packages/twisted/python/threadpool.py", line 246, in inContext
    result = inContext.theWork()

  File "/usr/lib/python2.7/dist-packages/twisted/python/threadpool.py", line 262, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)

  File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)

  File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 81, in callWithContext
    return func(*args,**kw)

  File "/usr/lib/python2.7/dist-packages/globaleaks/orm.py", line 97, in _wrap
    result = function(store, *args, **kwargs)

  File "/usr/lib/python2.7/dist-packages/globaleaks/handlers/admin/user.py", line 101, in create_receiver_user
    return admin_serialize_receiver(store, receiver, user, language)

  File "/usr/lib/python2.7/dist-packages/globaleaks/handlers/admin/user.py", line 25, in admin_serialize_receiver
    ret_dict = user_serialize_user(store, user, language)

  File "/usr/lib/python2.7/dist-packages/globaleaks/handlers/user.py", line 51, in user_serialize_user
    picture = db_get_model_img(store, models.User, user.id)

  File "/usr/lib/python2.7/dist-packages/globaleaks/handlers/admin/modelimgs.py", line 20, in db_get_model_img
    obj = store.find(model, model.id == obj_id).one()

  File "/usr/lib/python2.7/dist-packages/storm/store.py", line 205, in find
    self.flush()

  File "/usr/lib/python2.7/dist-packages/storm/store.py", line 485, in flush
    self._flush_one(obj_info)

  File "/usr/lib/python2.7/dist-packages/storm/store.py", line 522, in _flush_one
    result = self._connection.execute(expr)

  File "/usr/lib/python2.7/dist-packages/storm/database.py", line 238, in execute
    raw_cursor = self.raw_execute(statement, params)

  File "/usr/lib/python2.7/dist-packages/storm/databases/sqlite.py", line 154, in raw_execute
    return Connection.raw_execute(self, statement, params)

  File "/usr/lib/python2.7/dist-packages/storm/database.py", line 322, in raw_execute
    self._check_disconnect(raw_cursor.execute, *args)

  File "/usr/lib/python2.7/dist-packages/storm/database.py", line 371, in _check_disconnect
    return function(*args, **kwargs)

IntegrityError: UNIQUE constraint failed: user.username

**Comment by evilaliv3** [comment]
The bug is outdated to me and would appear different on 3.0.0.

Let's keep the ticket open in order to manage a proper messaging int the interface for errors related to "unique" failures in order to clarify the user the reason of the failure (e.g. duplicated username)

**Comment by evilaliv3** [comment]
Closing as duplicated of https://github.com/globaleaks/GlobaLeaks/issues/2215
