### ISSUE TITLE
Signup sqlalchemy.exc.IntegrityError Wraps a DB-API IntegrityError.

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#2215]
Platform: try.globaleaks.org (bvidswzoj322engc.onion)
Version: 3.0.10

sqlalchemy.exc.IntegrityError Wraps a DB-API IntegrityError.

Traceback (most recent call last):

  File "/usr/lib/python2.7/dist-packages/twisted/python/threadpool.py", line 246, in inContext
    result = inContext.theWork()

  File "/usr/lib/python2.7/dist-packages/twisted/python/threadpool.py", line 262, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)

  File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)

  File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 81, in callWithContext
    return func(*args,**kw)

  File "/usr/lib/python2.7/dist-packages/globaleaks/orm.py", line 103, in _wrap
    result = function(session, *args, **kwargs)

  File "/usr/lib/python2.7/dist-packages/globaleaks/handlers/signup.py", line 45, in signup
    session.flush()

  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 2027, in flush
    self._flush(objects)

  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 2145, in _flush
    transaction.rollback(_capture_exception=True)

  File "/usr/lib/python2.7/dist-packages/sqlalchemy/util/langhelpers.py", line 60, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)

  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 2109, in _flush
    flush_context.execute()

  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/unitofwork.py", line 373, in execute
    rec.execute(self)

  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/unitofwork.py", line 532, in execute
    uow

  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/persistence.py", line 174, in save_obj
    mapper, table, insert)

  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/persistence.py", line 800, in _emit_insert_statements
    execute(statement, params)

  File "/usr/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 914, in execute
    return meth(self, multiparams, params)

  File "/usr/lib/python2.7/dist-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)

  File "/usr/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1010, in _execute_clauseelement
    compiled_sql, distilled_params

  File "/usr/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1146, in _execute_context
    context)

  File "/usr/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1341, in _handle_dbapi_exception
    exc_info

  File "/usr/lib/python2.7/dist-packages/sqlalchemy/util/compat.py", line 200, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)

  File "/usr/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
    context)

  File "/usr/lib/python2.7/dist-packages/sqlalchemy/engine/default.py", line 450, in do_execute
    cursor.execute(statement, parameters)

IntegrityError: (sqlite3.IntegrityError) UNIQUE constraint failed: signup.subdomain [SQL: u'INSERT INTO signup (tid, subdomain, name, surname, email, use_case, use_case_other, language, activation_token, registration_date) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)'] [parameters: (None, u'provatest', u'xxxxx', u'xxxxxx', u'xxx.xxxx.@gmail.com', u'anticorruption', u'', u'it', u'xxxxxx', '2018-03-12 15:55:43.443541')]

**Comment by evilaliv3** [comment]
This is actually not a bug that causes malfunction but just user misunderstanding.

The proper handling of the condition would be to:
1) notify the user about the unavailability of the value
2) silence the email notification

The difficulty in implementing this stands in the fact that the exceptions is triggered inside a query and the exceptions returned is flat; implementing a check based on a regexp of the situation is a viable solution but would probably become a mess in the long term.

Proper management would probably require to add an additional query in order to check the availability of the unique field before performing the complete query for its configuration.

Related ticket that would benefit of the same approach: https://github.com/globaleaks/GlobaLeaks/issues/2188

**Comment by sicurezzadeimedia** [comment]
As it trigger a bug from and-user perspective, maybe we can categorize "UXBug" vs. "Bug", so that when there's a backend constraint preventing damage but still an error on user-side, it become a UXBug but not a backend Bug?

**Comment by evilaliv3** [comment]
I've reformulated the scope of this ticket in order generically handle the situation on which a user requires to create a resource and the operation is not possible because the resource would result duplicated.

Proper handling of the creation  a resource involving multiple nested resources would require to implement detection for any involved object.

To do that a generic DuplicatedResourceException exception should be created.

The exception could be generated by passing a user message that the interface should show in a specific interface (e.g. a modal).

**Comment by fpietrosanti** [comment]
We should only avoid hiding bugs, so we need to keep receiving any issue related to DuplicatedResourceException (if handled that way) in order to be fixed, because it's still a bug if it happen

**Comment by evilaliv3** [comment]
There is no intent in hiding bugs but just managing special conditions.

Example of the code to be implemented with this pattern is:
```
if username is duplicated:
     raise DuplicatedUsernameException
```

were DuplicatedUsernameException should inherit from DuplicatedUsername and be handled by the client showing that the situation happened.

We could anyway leave it all as it is and have the client make a client make a request to the backend for checking if the username is available or not.

This special checks should be in general specific for any object and would require specific tickets as children of this main ticket.

**Comment by fpietrosanti** [comment]
Related to #2329
