### ISSUE TITLE
sqlalchemy.orm.exc.MultipleResultsFound A single database result was required but more than one were found.

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#2217]
Platform: try.globaleaks.org 
Version: 3.0.11

sqlalchemy.orm.exc.MultipleResultsFound A single database result was required but more than one were found.

Traceback (most recent call last):

  File "/usr/lib/python2.7/dist-packages/twisted/python/threadpool.py", line 246, in inContext
    result = inContext.theWork()

  File "/usr/lib/python2.7/dist-packages/twisted/python/threadpool.py", line 262, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)

  File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)

  File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 81, in callWithContext
    return func(*args,**kw)

  File "/usr/lib/python2.7/dist-packages/globaleaks/orm.py", line 103, in _wrap
    result = function(session, *args, **kwargs)

  File "/usr/lib/python2.7/dist-packages/globaleaks/handlers/signup.py", line 108, in signup_activation
    recipient = session.query(models.User).filter(models.User.tid == signup.tid, models.User.role == u'receiver').one()

  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2702, in one
    "Multiple rows were found for one()")

MultipleResultsFound: Multiple rows were found for one()

**Comment by fpietrosanti** [comment]
Happened again on Version: 3.0.13
/cc @evilaliv3

**Comment by ckeeney** [comment]
I'm getting this error when logging in.  Are there workarounds?

**Comment by evilaliv3** [comment]
@ckeeney: logging in? so on the authentication handler?

can you clarify about your setup?

**Comment by ckeeney** [comment]
I upgraded just now and the problem persists.

```
```

**Comment by evilaliv3** [comment]
@fpietrosanti: coming specificallyto the handler hit here (the signup activation link) the exception is raised on the following condition:
1. the user fill the signup
2. the user perform the activation that leads him to the platform and get the credentials back from the platform
3. the user activate some recipients
4. the user reuse the link got in the first email, where the code do not consider that possibly there will be other users on the platform 

we have many demos with multiple recipients instantiated and this supports this analysis.

**Comment by ckeeney** [comment]
I upgraded just now and the problem persists.
```
GlobaLeaks version: 3.0.15
Database version: 39
```

I am running the docker image here: https://hub.docker.com/r/ckeeney/globaleaks/

I run the docker image with the following `docker-compose.yml` file:

```yaml
  globaleaks:
    container_name: globaleaks
    restart: always
    expose: 
      - 80
      - 443
    image: ckeeney/globaleaks
    volumes: 
      - ./globaleaks/data:/var/globaleaks
    cap_add:
      - NET_ADMIN
```
The YAML file shows globaleaks exposing on port 80 and 443, but SSL termination happens in a Caddy webserver sitting directly in front of Globaleaks.

I can log in as my admin user just fine.  If I try to authenticate as my recipient user, I get the following stacktrace:

```
2018-03-21 18:55:37 0000 [-] [E] sqlalchemy.orm.exc.MultipleResultsFound A single database result was required but more than one were found.

Traceback (most recent call last):

  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1126, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)

  File "/usr/lib/python2.7/dist-packages/twisted/python/failure.py", line 389, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)

  File "/usr/lib/python2.7/dist-packages/globaleaks/handlers/authentication.py", line 125, in post
    request['token'])

  File "/usr/lib/python2.7/dist-packages/twisted/python/threadpool.py", line 246, in inContext
    result = inContext.theWork()

  File "/usr/lib/python2.7/dist-packages/twisted/python/threadpool.py", line 262, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)

  File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)

  File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 81, in callWithContext
    return func(*args,**kw)

  File "/usr/lib/python2.7/dist-packages/globaleaks/orm.py", line 102, in _wrap
    result = function(session, *args, **kwargs)

  File "/usr/lib/python2.7/dist-packages/globaleaks/handlers/authentication.py", line 88, in login
    User.tid == tid).one_or_none()

  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2673, in one_or_none
    "Multiple rows were found for one_or_none()")

MultipleResultsFound: Multiple rows were found for one_or_none()

```

**Comment by ckeeney** [comment]
In my case, I'm following a link from an email about a new comment received.

**Comment by evilaliv3** [comment]
I've edited the title and content of the ticket with the clarification about what the ticket is about and what has been identified:

```
When multiple recipient exists the signup activation link result in exception sqlalchemy.orm.exc.MultipleResultsFound.

The bug has been triggered on the demo infrastructure where probably users are reusing the authentication link for getting a second time onto the platform.
```

**Comment by evilaliv3** [comment]
Closing as outdated.
