### ISSUE TITLE
InvalidRequestError: Could not evaluate current criteria in Python. Specify 'fetch' or False for the synchronize_session parameter.

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#2222]
Platform: try.globaleaks.org (bvidswzoj322engc.onion)
Version: 3.0.11

sqlalchemy.exc.InvalidRequestError SQLAlchemy was asked to do something it can't do.

    This error generally corresponds to runtime state errors.

    

Traceback (most recent call last):

  File "/usr/lib/python2.7/dist-packages/twisted/python/threadpool.py", line 246, in inContext
    result = inContext.theWork()

  File "/usr/lib/python2.7/dist-packages/twisted/python/threadpool.py", line 262, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)

  File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)

  File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 81, in callWithContext
    return func(*args,**kw)

  File "/usr/lib/python2.7/dist-packages/globaleaks/orm.py", line 103, in _wrap
    result = function(session, *args, **kwargs)

  File "/usr/lib/python2.7/dist-packages/globaleaks/handlers/admin/field.py", line 255, in delete_field
    models.Questionnaire.id == models.Step.questionnaire_id).update({'enable_whistleblower_identity': False})

  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 3176, in update
    update_op.exec_()

  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/persistence.py", line 1126, in exec_
    self._do_pre_synchronize()

  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/persistence.py", line 1195, in _do_pre_synchronize
    "Could not evaluate current criteria in Python. "

InvalidRequestError: Could not evaluate current criteria in Python. Specify 'fetch' or False for the synchronize_session parameter.

**Comment by evilaliv3** [comment]
Fixed by commit https://github.com/globaleaks/GlobaLeaks/commit/d841d09b20c8583d63c98e040d3f3ed03fc28c6b

Fix released starting from 3.0.12
