### ISSUE TITLE
sqlalchemy.exc.IntegrityError Wraps a DB-API IntegrityError on fieldoption / questionnaire.py

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#2231]
Platform: Comune di XXXXXX
Host: whistleblower.XXXXXX.comune 
Version: 3.0.17

sqlalchemy.exc.IntegrityError Wraps a DB-API IntegrityError.

Traceback (most recent call last):

  File "/usr/lib/python2.7/dist-packages/twisted/python/threadpool.py", line 246, in inContext
    result = inContext.theWork()

  File "/usr/lib/python2.7/dist-packages/twisted/python/threadpool.py", line 262, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)

  File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)

  File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 81, in callWithContext
    return func(*args,**kw)

  File "/usr/lib/python2.7/dist-packages/globaleaks/orm.py", line 102, in _wrap
    result = function(session, *args, **kwargs)

  File "/usr/lib/python2.7/dist-packages/globaleaks/handlers/admin/questionnaire.py", line 83, in create_questionnaire
    questionnaire = db_create_questionnaire(session, state, tid, request, language)

  File "/usr/lib/python2.7/dist-packages/globaleaks/handlers/admin/questionnaire.py", line 67, in db_create_questionnaire
    db_create_step(session, tid, step, language)

  File "/usr/lib/python2.7/dist-packages/globaleaks/handlers/admin/step.py", line 32, in db_create_step
    db_create_field(session, tid, c, language)

  File "/usr/lib/python2.7/dist-packages/globaleaks/handlers/admin/field.py", line 165, in db_create_field
    db_update_fieldoptions(session, tid, field.id, options, language)

  File "/usr/lib/python2.7/dist-packages/globaleaks/handlers/admin/field.py", line 60, in db_update_fieldoptions
    options_ids = [db_update_fieldoption(session, tid, field_id, option['id'], option, language, idx) for idx, option in enumerate(options)]

  File "/usr/lib/python2.7/dist-packages/globaleaks/handlers/admin/field.py", line 43, in db_update_fieldoption
    o = models.db_forge_obj(session, models.FieldOption, option_dict)

  File "/usr/lib/python2.7/dist-packages/globaleaks/models/__init__.py", line 23, in db_forge_obj
    session.flush()

  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 2027, in flush
    self._flush(objects)

  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 2145, in _flush
    transaction.rollback(_capture_exception=True)

  File "/usr/lib/python2.7/dist-packages/sqlalchemy/util/langhelpers.py", line 60, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)

  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 2109, in _flush
    flush_context.execute()

  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/unitofwork.py", line 373, in execute
    rec.execute(self)

  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/unitofwork.py", line 532, in execute
    uow

  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/persistence.py", line 174, in save_obj
    mapper, table, insert)

  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/persistence.py", line 767, in _emit_insert_statements
    execute(statement, multiparams)

  File "/usr/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 914, in execute
    return meth(self, multiparams, params)

  File "/usr/lib/python2.7/dist-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)

  File "/usr/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1010, in _execute_clauseelement
    compiled_sql, distilled_params

  File "/usr/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1146, in _execute_context
    context)

  File "/usr/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1341, in _handle_dbapi_exception
    exc_info

  File "/usr/lib/python2.7/dist-packages/sqlalchemy/util/compat.py", line 200, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)

  File "/usr/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
    context)

  File "/usr/lib/python2.7/dist-packages/sqlalchemy/engine/default.py", line 450, in do_execute
    cursor.execute(statement, parameters)

IntegrityError: (sqlite3.IntegrityError) FOREIGN KEY constraint failed [SQL: u'INSERT INTO fieldoption (id, field_id, presentation_order, label, score_points, trigger_field) VALUES (?, ?, ?, ?, ?, ?)'] [parameters: (u'94855eda-b97f-42e8-b9a7-42e91b27a2b4', u'9089dbf0-d646-419e-bb0a-46c694f1e7bf', 1, u'{"it": "Segnalazione confidenziale (indicher\\u00f2 in mio nome)"}', 0, u'ccf0a68e-9b83-40b6-aefa-07f4e4d81fba')]

**Comment by evilaliv3** [comment]
I've been able to replicate this issue that can happen on two conditions:
- if a user starts  configuring a trigger but do not save the configuration but instead delete the activated field and then saves the activator.

- if a user has configured an activator and then delete the activated field; a further deletion of the activated of the option would trigger the exception.

Two different patches are requirered to solve the two situations.

**Comment by fpietrosanti** [comment]
@evilaliv3 it's our friend from local municipality testing it for his local public agency, on #gl-profiles chat, so we can also ask him re-testing afterwords

**Comment by evilaliv3** [comment]
After discussing with the user i discovered the issue was also triggerable in relation to import and export.

I've solved the issue of the user by reverting the previous patch and enabling DEFERRABLE foreign keys that are a requirement for the queries to work.

let's keep the ticket as the condition identified are still to be managed and the implementation i proposed is not compatible with the import/export.

**Comment by evilaliv3** [comment]
The issue has been fixed with the previous patch that creates a client status storing ids of deleted fields in order to behave accordingly.

**Comment by evilaliv3** [comment]
Closing as fixed. The fix will be released starting from version 3.0.18.
