### ISSUE TITLE
Unhandled exception key_blob_or_type must be in the formats "NEW:<ALGORITHM>" or "<ALGORITHM>:<KEY>"

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#2235]
Platform: 
Host: 
Version: 3.0.17

ValueError Inappropriate argument value (of correct type).

Traceback (most recent call last):

  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1128, in _inlineCallbacks
    result = g.send(result)

  File "/usr/lib/python2.7/dist-packages/globaleaks/jobs/onion_service.py", line 73, in add_all_hidden_services
    yield self.add_hidden_service(hostname, key, tid)

  File "/usr/lib/python2.7/dist-packages/globaleaks/jobs/onion_service.py", line 86, in add_hidden_service
    ephs = EphemeralHiddenService(hs_loc, key)

  File "/usr/lib/python2.7/dist-packages/globaleaks/mocks/txtorcon_mocks.py", line 42, in __init__
    raise ValueError('key_blob_or_type must be in the formats '

"ValueError: key_blob_or_type must be in the formats "NEW:<ALGORITHM> or <ALGORITHM>:<KEY>"

**Comment by evilaliv3** [comment]
This was me during a migration and reset of a node handled manually.
