### ISSUE TITLE
Uhandled exception on db_admin_update_user AttributeError: 'NoneType' object has no attribute 'update'

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#2250]
Platform: xxxxxx.it
Host: admin.xxxxx.it
Version: 3.0.18

AttributeError Attribute not found.

Traceback (most recent call last):

  File "/usr/lib/python2.7/dist-packages/twisted/python/threadpool.py", line 246, in inContext
    result = inContext.theWork()

  File "/usr/lib/python2.7/dist-packages/twisted/python/threadpool.py", line 262, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)

  File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)

  File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 81, in callWithContext
    return func(*args,**kw)

  File "/usr/lib/python2.7/dist-packages/globaleaks/orm.py", line 102, in _wrap
    result = function(session, *args, **kwargs)

  File "/usr/lib/python2.7/dist-packages/globaleaks/handlers/admin/user.py", line 157, in admin_update_user
    return user_serialize_user(session, db_admin_update_user(session, state, tid, user_id, request, language), language)

  File "/usr/lib/python2.7/dist-packages/globaleaks/handlers/admin/user.py", line 139, in db_admin_update_user
    user.update(request)

AttributeError: 'NoneType' object has no attribute 'update'

**Comment by evilaliv3** [comment]
This bug has been fixed in https://github.com/globaleaks/GlobaLeaks/commit/72aa0af6a9960442081d75d76bd35bc403f64e75 and was related to the query for changing the username of the user.
