### ISSUE TITLE
Unhandled exception in perform_secure_deletion_of_files OSError: [Errno 21] Is a directory: '/var/globaleaks/backups/var'

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#2252]
Platform: XXXX
Host: 
Version: 3.0.16

OSError OS system call failed.

Traceback (most recent call last):

  File "/usr/lib/python2.7/dist-packages/globaleaks/jobs/base.py", line 53, in run
    yield self.operation()

  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1126, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)

  File "/usr/lib/python2.7/dist-packages/twisted/python/failure.py", line 389, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)

  File "/usr/lib/python2.7/dist-packages/globaleaks/jobs/cleaning.py", line 155, in operation
    yield self.perform_secure_deletion_of_files()

  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1128, in _inlineCallbacks
    result = g.send(result)

  File "/usr/lib/python2.7/dist-packages/globaleaks/jobs/cleaning.py", line 143, in perform_secure_deletion_of_files
    os.remove(path)

OSError: [Errno 21] Is a directory: '/var/globaleaks/backups/var'

**Comment by evilaliv3** [comment]
This was me wrongly managing a platform.

I is correct that the code on such this unexpected condition trows an error.
