### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'loseConnection'

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#2265]
Platform: 
Host: 
Version: 3.0.27

AttributeError Attribute not found.

Traceback (most recent call last):

  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 825, in runUntilCurrent
    call.func(*call.args, **call.kw)

  File "/usr/lib/python2.7/dist-packages/twisted/internet/tcp.py", line 479, in connectionLost
    self._commonConnection.connectionLost(self, reason)

  File "/usr/lib/python2.7/dist-packages/twisted/internet/tcp.py", line 293, in connectionLost
    protocol.connectionLost(reason)

  File "/usr/lib/python2.7/dist-packages/twisted/internet/endpoints.py", line 129, in connectionLost
    return self._wrappedProtocol.connectionLost(reason)

  File "/usr/lib/python2.7/dist-packages/twisted/protocols/policies.py", line 125, in connectionLost
    self.wrappedProtocol.connectionLost(reason)

  File "/usr/lib/python2.7/dist-packages/twisted/protocols/tls.py", line 473, in connectionLost
    self._flushReceiveBIO()

  File "/usr/lib/python2.7/dist-packages/twisted/protocols/tls.py", line 386, in _flushReceiveBIO
    self._tlsShutdownFinished(failure)

  File "/usr/lib/python2.7/dist-packages/twisted/protocols/tls.py", line 460, in _tlsShutdownFinished
    self.transport.loseConnection()

  File "/usr/lib/python2.7/dist-packages/twisted/protocols/policies.py", line 90, in loseConnection
    self.transport.loseConnection()

AttributeError: 'NoneType' object has no attribute 'loseConnection'

**Comment by fpietrosanti** [comment]
Still present in 3.3.3

**Comment by evilaliv3** [comment]
Closing as outdated.
