### ISSUE TITLE
unhandled exception in field.py     if attr_dict['type'] == 'bool'

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#2309]
Platform: 
Host:  (
Version: 3.0.29

KeyError Mapping key not found.

Traceback (most recent call last):

  File "/usr/lib/python2.7/dist-packages/twisted/python/threadpool.py", line 246, in inContext
    result = inContext.theWork()

  File "/usr/lib/python2.7/dist-packages/twisted/python/threadpool.py", line 262, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)

  File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)

  File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 81, in callWithContext
    return func(*args,**kw)

  File "/usr/lib/python2.7/dist-packages/globaleaks/orm.py", line 113, in _wrap
    result = function(session, *args, **kwargs)

  File "/usr/lib/python2.7/dist-packages/globaleaks/handlers/admin/step.py", line 71, in update_step
    return serialize_step(session, tid, db_update_step(session, tid, step_id, request, language), language)

  File "/usr/lib/python2.7/dist-packages/globaleaks/handlers/admin/step.py", line 64, in db_update_step
    db_update_field(session, tid, child['id'], child, language)

  File "/usr/lib/python2.7/dist-packages/globaleaks/handlers/admin/field.py", line 200, in db_update_field
    db_update_fieldattrs(session, tid, field.id, field_dict['attrs'], language)

  File "/usr/lib/python2.7/dist-packages/globaleaks/handlers/admin/field.py", line 91, in db_update_fieldattrs
    attrs_ids = [db_update_fieldattr(session, tid, field_id, attr_name, attr, language) for attr_name, attr in field_attrs.items()]

  File "/usr/lib/python2.7/dist-packages/globaleaks/handlers/admin/field.py", line 76, in db_update_fieldattr
    if attr_dict['type'] == 'bool':

KeyError: 'type'

**Comment by fpietrosanti** [comment]
Presente also in
Platform: try.globaleaks.org
Host: try.globaleaks.org (bvidswzoj322engc.onion)
Version: 3.3.12

KeyError Mapping key not found.

**Comment by evilaliv3** [comment]
Closing as outdated and probably solved.
