### ISSUE TITLE
unhandled exception ValueError: need more than 1 value to unpack

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#2322]
Platform:  
Host:  
Version: 3.1.7

ValueError Inappropriate argument value (of correct type).

Traceback (most recent call last):

  File "/usr/lib/python2.7/dist-packages/twisted/internet/posixbase.py", line 597, in _doReadOrWrite
    why = selectable.doRead()

  File "/usr/lib/python2.7/dist-packages/twisted/internet/tcp.py", line 209, in doRead
    return self._dataReceived(data)

  File "/usr/lib/python2.7/dist-packages/twisted/internet/tcp.py", line 215, in _dataReceived
    rval = self.protocol.dataReceived(data)

  File "/usr/lib/python2.7/dist-packages/twisted/protocols/basic.py", line 571, in dataReceived
    why = self.lineReceived(line)

  File "/usr/lib/python2.7/dist-packages/twisted/web/http.py", line 1653, in lineReceived
    self.headerReceived(self.__header)

  File "/usr/lib/python2.7/dist-packages/twisted/web/http.py", line 1686, in headerReceived
    header, data = line.split(b':', 1)

ValueError: need more than 1 value to unpack

**Comment by evilaliv3** [comment]
This seems to be happening on a lot of nodes probably due to a massive scan over Tor hidden services or something like these.

There is not that much we can do, we can eventually improve the parsing of Twisted with some logging about all the requests but this risk to mess it up the security and the resiliency of that code.

I would suggest to just keep this ticket open and track here possible similar issues postponing any remediation.

**Comment by fpietrosanti** [comment]
Twisted bug https://twistedmatrix.com/trac/ticket/8101
Manual patching done by scrapy https://github.com/scrapy/scrapy/issues/1069

**Comment by NCommander** [comment]
This problem is likely fixed when deploying on bionic given it was a twisted bug that should be patched after xenial. There's not much we can do about this one since catching this specific exception is both too general and dangerous. I'm more inclined to closed the ticket as it should be fixed on fully up to date Ubuntu/GL installs.

**Comment by evilaliv3** [comment]
Closing as outdated.
