### ISSUE TITLE
OSError: Response unexpected in   File "/usr/lib/python3/dist-packages/globaleaks/handlers/admin/operation.py", line 77, in verify_hostname

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#2373]
Platform: xxxxxx Whistle-Blowing
Host:  (xxxx.onion)
Version: 3.2.2

OSError Base class for I/O related errors.

Traceback (most recent call last):

  File "/usr/lib/python3/dist-packages/twisted/internet/defer.py", line 1386, in _inlineCallbacks
    result = g.send(result)

  File "/usr/lib/python3/dist-packages/globaleaks/handlers/admin/operation.py", line 83, in verify_hostname
    raise e

  File "/usr/lib/python3/dist-packages/globaleaks/handlers/admin/operation.py", line 77, in verify_hostname
    raise EnvironmentError('Response unexpected')

OSError: Response unexpected

**Comment by evilaliv3** [comment]
Functionality now reimplemented.
