### ISSUE TITLE
try.globaleaks.org signup broken with GlobaLeaks 3.2.3

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#2379]
Platform: try.globaleaks.org
Host: try.globaleaks.org (bvidswzoj322engc.onion)
Version: 3.2.3

sqlalchemy.exc.IntegrityError Wraps a DB-API IntegrityError.

Traceback (most recent call last):

  File "/usr/lib/python2.7/dist-packages/twisted/python/threadpool.py", line 246, in inContext
    result = inContext.theWork()

  File "/usr/lib/python2.7/dist-packages/twisted/python/threadpool.py", line 262, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)

  File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)

  File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 81, in callWithContext
    return func(*args,**kw)

  File "/usr/lib/python2.7/dist-packages/globaleaks/orm.py", line 110, in _wrap
    result = function(session, *args, **kwargs)

  File "/usr/lib/python2.7/dist-packages/globaleaks/handlers/signup.py", line 72, in signup
    'activation_url': 'https://%s/#/activation?token=%s' % (node.get_val(u'rootdomain'), signup.activation_token),

  File "/usr/lib/python2.7/dist-packages/globaleaks/models/config.py", line 38, in get_val
    return self.get_cfg(var_name).get_v()

  File "/usr/lib/python2.7/dist-packages/globaleaks/models/config.py", line 35, in get_cfg
    return self.session.query(Config).filter(Config.tid == self.tid, Config.var_name == var_name).one()

  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2693, in one
    ret = list(self)

  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2735, in __iter__
    self.session._autoflush()

  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 1315, in _autoflush
    util.raise_from_cause(e)

  File "/usr/lib/python2.7/dist-packages/sqlalchemy/util/compat.py", line 200, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)

  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 1305, in _autoflush
    self.flush()

  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 2027, in flush
    self._flush(objects)

  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 2145, in _flush
    transaction.rollback(_capture_exception=True)

  File "/usr/lib/python2.7/dist-packages/sqlalchemy/util/langhelpers.py", line 60, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)

  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 2109, in _flush
    flush_context.execute()

  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/unitofwork.py", line 373, in execute
    rec.execute(self)

  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/unitofwork.py", line 532, in execute
    uow

  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/persistence.py", line 174, in save_obj
    mapper, table, insert)

  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/persistence.py", line 800, in _emit_insert_statements
    execute(statement, params)

  File "/usr/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 914, in execute
    return meth(self, multiparams, params)

  File "/usr/lib/python2.7/dist-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)

  File "/usr/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1010, in _execute_clauseelement
    compiled_sql, distilled_params

  File "/usr/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1146, in _execute_context
    context)

  File "/usr/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1341, in _handle_dbapi_exception
    exc_info

  File "/usr/lib/python2.7/dist-packages/sqlalchemy/util/compat.py", line 200, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)

  File "/usr/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
    context)

  File "/usr/lib/python2.7/dist-packages/sqlalchemy/engine/default.py", line 450, in do_execute
    cursor.execute(statement, parameters)

IntegrityError: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely) (sqlite3.IntegrityError) UNIQUE constraint failed: signup.subdomain [SQL: u'INSERT INTO signup (tid, subdomain, language, name, surname, role, phone, email, use_case, use_case_other, organization_name, organization_type, organization_location1, organization_location2, organization_location3, organization_location4, organization_site, organization_number_employees, organization_number_users, hear_channel, activation_token, password_admin, password_recipient, client_ip_address, client_user_agent, registration_date, tos1, tos2) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)'] [parameters: (382, u'XXXXXXX', u'it', u'XXXXXXX', u'XXXXXXX', u'', u'', u'XXXXXXX', u'corporate_compliance', u'', u'', u'', u'', u'', u'', u'', u'', u'', u'', u'', u'XXXXXXX', u'XXXXXXX', u'XXXXXXX', u'', u'', '2018-07-27 08:10:41.821419', False, False)]

**Comment by fpietrosanti** [comment]
Happening again on 3.4.1
