### ISSUE TITLE
KeyError: '' in handlers/admin/questionnaire.py", line 155, in fix_field_pass_2     option['trigger_field'] = old_to_new_field_ids[option['trigger_field']]

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#2380]
Platform: XXXXXX
Host: XXXXXXX
Version: 3.2.3

KeyError Mapping key not found.

Traceback (most recent call last):

  File "/usr/lib/python3/dist-packages/twisted/python/threadpool.py", line 250, in inContext
    result = inContext.theWork()

  File "/usr/lib/python3/dist-packages/twisted/python/threadpool.py", line 266, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)

  File "/usr/lib/python3/dist-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)

  File "/usr/lib/python3/dist-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)

  File "/usr/lib/python3/dist-packages/globaleaks/orm.py", line 110, in _wrap
    result = function(session, *args, **kwargs)

  File "/usr/lib/python3/dist-packages/globaleaks/handlers/admin/questionnaire.py", line 173, in duplicate_questionnaire
    fix_field_pass_2(field)

  File "/usr/lib/python3/dist-packages/globaleaks/handlers/admin/questionnaire.py", line 155, in fix_field_pass_2
    option['trigger_field'] = old_to_new_field_ids[option['trigger_field']]

KeyError: ''

**Comment by evilaliv3** [comment]
This bug was detected and already fixed 3 days ago in commit https://github.com/globaleaks/GlobaLeaks/commit/cfebd197d05e64bf481c26fcd527f607f12af8d5

Patch will be released starting from version 3.2.4
