### ISSUE TITLE
Unhandled error OSError: [Errno 12] Cannot allocate memory

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#2381]
Platform: xxxx
Host:  
Version: 3.1.9

OSError OS system call failed.

Traceback (most recent call last):

  File "/usr/lib/python2.7/dist-packages/twisted/internet/_baseprocess.py", line 64, in maybeCallProcessEnded
    proto.processEnded(Failure(reason))

  File "/usr/lib/python2.7/dist-packages/globaleaks/workers/process.py", line 86, in processEnded
    self.supervisor.handle_worker_death(self, reason)

  File "/usr/lib/python2.7/dist-packages/globaleaks/workers/supervisor.py", line 104, in handle_worker_death
    self.launch_worker()

  File "/usr/lib/python2.7/dist-packages/globaleaks/workers/supervisor.py", line 83, in launch_worker
    reactor.spawnProcess(pp, executable, [executable, self.worker_path], childFDs=pp.fd_map, env=os.environ)

  File "/usr/lib/python2.7/dist-packages/twisted/internet/posixbase.py", line 340, in spawnProcess
    processProtocol, uid, gid, childFDs)

  File "/usr/lib/python2.7/dist-packages/twisted/internet/process.py", line 731, in __init__
    self._fork(path, uid, gid, executable, args, environment, fdmap=fdmap)

  File "/usr/lib/python2.7/dist-packages/twisted/internet/process.py", line 405, in _fork
    self.pid = os.fork()

OSError: [Errno 12] Cannot allocate memory

**Comment by evilaliv3** [comment]
While this bug is probably outdated it is worth to try to research how to detect similar situations in advince
