### ISSUE TITLE
Unhandled exception in process_file_upload in flowTotalSize 

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#2384]
Platform: xxxxx
Host:  
Version: 3.2.5

ValueError Inappropriate argument value (of correct type).

Traceback (most recent call last):

  File "/usr/lib/python2.7/dist-packages/twisted/web/server.py", line 183, in process
    self.render(resrc)

  File "/usr/lib/python2.7/dist-packages/twisted/web/server.py", line 234, in render
    body = resrc.render(self)

  File "/usr/lib/python2.7/dist-packages/globaleaks/rest/api.py", line 419, in render
    self.handler.process_file_upload()

  File "/usr/lib/python2.7/dist-packages/globaleaks/handlers/base.py", line 444, in process_file_upload
    total_file_size = int(self.request.args[b'flowTotalSize'][0])

ValueError: invalid literal for int() with base 10: "53'+order+by+1+--+"

**Comment by evilaliv3** [comment]
@fpietrosanti: this exception has been triggered while some users were performing the penetration test of IndonesiaLeaks.

I do not think a specific solution for exceptions like these is possible because no handling is possible;
I would continue to both log and mail the exception eventually abstracting the logline in this way:

"Exception in request validation for the argument flowTotalSize" followed by the exact exception

**Comment by evilaliv3** [comment]
Closing as outdated
