### ISSUE TITLE
AttributeError: 'bytes' object has no attribute 'encode' in db_acme_cert_issuance

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#2388]
Platform:  
Host:  
Version: 3.2.5

AttributeError Attribute not found.

Traceback (most recent call last):

  File "/usr/lib/python3/dist-packages/twisted/internet/defer.py", line 1384, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)

  File "/usr/lib/python3/dist-packages/twisted/python/failure.py", line 408, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)

  File "/usr/lib/python3/dist-packages/globaleaks/handlers/admin/https.py", line 557, in put
    yield acme_cert_issuance(self.request.tid)

  File "/usr/lib/python3/dist-packages/twisted/python/threadpool.py", line 250, in inContext
    result = inContext.theWork()

  File "/usr/lib/python3/dist-packages/twisted/python/threadpool.py", line 266, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)

  File "/usr/lib/python3/dist-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)

  File "/usr/lib/python3/dist-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)

  File "/usr/lib/python3/dist-packages/globaleaks/orm.py", line 110, in _wrap
    result = function(session, *args, **kwargs)

  File "/usr/lib/python3/dist-packages/globaleaks/handlers/admin/https.py", line 537, in acme_cert_issuance
    return db_acme_cert_issuance(session, tid)

  File "/usr/lib/python3/dist-packages/globaleaks/handlers/admin/https.py", line 513, in db_acme_cert_issuance
    accnt_key = serialization.load_pem_private_key(raw_accnt_key.encode(),

AttributeError: 'bytes' object has no attribute 'encode'

**Comment by evilaliv3** [comment]
Fixed!

**Comment by evilaliv3** [comment]
The fix seems to be not correct fixed py2 creating an issue on py3.

I've already tested the solution that will work on both, going to commit it now.

**Comment by evilaliv3** [comment]
This issue should be now fixed in release 3.3.4
