### ISSUE TITLE
ValueError: Could not deserialize key data in  in _handle_key_loading_error

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#2390]
Platform:
Host: 
Version: 3.3.1

ValueError Inappropriate argument value (of correct type).

Traceback (most recent call last):

  File "/usr/lib/python3/dist-packages/twisted/internet/defer.py", line 1384, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)

  File "/usr/lib/python3/dist-packages/twisted/python/failure.py", line 408, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)

  File "/usr/lib/python3/dist-packages/globaleaks/handlers/admin/https.py", line 559, in put
    yield acme_cert_issuance(self.request.tid)

  File "/usr/lib/python3/dist-packages/twisted/python/threadpool.py", line 250, in inContext
    result = inContext.theWork()

  File "/usr/lib/python3/dist-packages/twisted/python/threadpool.py", line 266, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)

  File "/usr/lib/python3/dist-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)

  File "/usr/lib/python3/dist-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)

  File "/usr/lib/python3/dist-packages/globaleaks/orm.py", line 109, in _wrap
    result = function(session, *args, **kwargs)

  File "/usr/lib/python3/dist-packages/globaleaks/handlers/admin/https.py", line 539, in acme_cert_issuance
    return db_acme_cert_issuance(session, tid)

  File "/usr/lib/python3/dist-packages/globaleaks/handlers/admin/https.py", line 517, in db_acme_cert_issuance
    backend=default_backend())

  File "/usr/lib/python3/dist-packages/cryptography/hazmat/primitives/serialization.py", line 20, in load_pem_private_key
    return backend.load_pem_private_key(data, password)

  File "/usr/lib/python3/dist-packages/cryptography/hazmat/backends/openssl/backend.py", line 1015, in load_pem_private_key
    password,

  File "/usr/lib/python3/dist-packages/cryptography/hazmat/backends/openssl/backend.py", line 1234, in _load_key
    self._handle_key_loading_error()

  File "/usr/lib/python3/dist-packages/cryptography/hazmat/backends/openssl/backend.py", line 1292, in _handle_key_loading_error
    raise ValueError("Could not deserialize key data.")

ValueError: Could not deserialize key data.

**Comment by evilaliv3** [comment]
This issue should be now fixed in release 3.3.4
