### ISSUE TITLE
Unhandled error AttributeError: 'list' object has no attribute 'items'

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#2408]
During a penetration test those kind unhandled errors has been received.

This ticket is to improve the robustness to prevent those from being generated.

Platform:  
Host:  
Version: 3.1.9

AttributeError Attribute not found.

Traceback (most recent call last):

  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 150, in maybeDeferred
    result = f(*args, **kw)

  File "/usr/lib/python2.7/dist-packages/globaleaks/handlers/base.py", line 160, in wrapper
    return f(self, *args, **kwargs)

  File "/usr/lib/python2.7/dist-packages/globaleaks/handlers/token.py", line 48, in put
    request = self.validate_message(self.request.content.read(), requests.TokenAnswerDesc)

  File "/usr/lib/python2.7/dist-packages/globaleaks/handlers/base.py", line 364, in validate_message
    if BaseHandler.validate_jmessage(jmessage, message_template):

  File "/usr/lib/python2.7/dist-packages/globaleaks/handlers/base.py", line 299, in validate_jmessage
    for key, value in jmessage.items():

AttributeError: 'list' object has no attribute 'items'

**Comment by PrasannaGaneshu** [comment]
@fpietrosanti 
Im facing the same issue while training.Please help me in resolving this
