### ISSUE TITLE
Unhandled exception in verify_hostname AttributeError: 'NoneType' object has no attribute 'lower'

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#2411]
Platform: xxxxx
Host: xxxxx.onion.tor2web.org (xxxx.onion)
Version: 3.3.12

AttributeError Attribute not found.

Traceback (most recent call last):

  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1128, in _inlineCallbacks
    result = g.send(result)

  File "/usr/lib/python2.7/dist-packages/globaleaks/handlers/admin/operation.py", line 83, in verify_hostname
    raise e

AttributeError: 'NoneType' object has no attribute 'lower'

**Comment by evilaliv3** [comment]
Functionality now reimplemented.
