### ISSUE TITLE
Unhandled exception in parse_accept_language_header on tenant_cache[request.tid].default_language

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#2437]
Platform: WhistleblowingPA
Host: registrazione.whistleblowing.it (qpaszzjw5hmgajdu.onion)
Version: 3.4.1

KeyError Mapping key not found.

Traceback (most recent call last):

  File "/usr/lib/python3/dist-packages/twisted/web/server.py", line 195, in process
    self.render(resrc)

  File "/usr/lib/python3/dist-packages/twisted/web/server.py", line 255, in render
    body = resrc.render(self)

  File "/usr/lib/python3/dist-packages/globaleaks/rest/api.py", line 379, in render
    self.preprocess(request)

  File "/usr/lib/python3/dist-packages/globaleaks/rest/api.py", line 362, in preprocess
    request.language = text_type(self.detect_language(request))

  File "/usr/lib/python3/dist-packages/globaleaks/rest/api.py", line 527, in detect_language
    for l in self.parse_accept_language_header(request):

  File "/usr/lib/python3/dist-packages/globaleaks/rest/api.py", line 522, in parse_accept_language_header
    return State.tenant_cache[request.tid].default_language

KeyError: 6

**Comment by fpietrosanti** [comment]
Happened again 3 december 2018 with:
KeyError: 73
