### ISSUE TITLE
Unhandled exception in _print_logline sequence item 0: expected str instance, bytes found

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#2442]
Platform:  
Host:  ()
Version: 3.4.1

TypeError Inappropriate argument type.

Traceback (most recent call last):

  File "/usr/lib/python3/dist-packages/globaleaks/jobs/base.py", line 48, in run
    yield self.operation()

  File "/usr/lib/python3/dist-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)

  File "/usr/lib/python3/dist-packages/twisted/python/failure.py", line 491, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)

  File "/usr/lib/python3/dist-packages/globaleaks/jobs/notification.py", line 302, in operation
    yield self.spool_emails()

  File "/usr/lib/python3/dist-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)

  File "/usr/lib/python3/dist-packages/twisted/python/failure.py", line 491, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)

  File "/usr/lib/python3/dist-packages/globaleaks/jobs/notification.py", line 291, in spool_emails
    yield self.sendmail(mail)

  File "/usr/lib/python3/dist-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)

  File "/usr/lib/python3/dist-packages/twisted/python/failure.py", line 491, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)

  File "/usr/lib/python3/dist-packages/globaleaks/jobs/notification.py", line 283, in sendmail
    success = yield self.state.sendmail(mail['tid'], mail['address'], mail['subject'], mail['body'])

  File "/usr/lib/python3/dist-packages/twisted/internet/defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)

  File "/usr/lib/python3/dist-packages/globaleaks/utils/mail.py", line 116, in failure_cb
    log.err("SMTP connection failed (Exception: %s)", failure.value.subFailure.value, tid=tid)

  File "/usr/lib/python3/dist-packages/globaleaks/utils/log.py", line 123, in err
    self._print_logline('E', msg, *args, **kwargs)

  File "/usr/lib/python3/dist-packages/globaleaks/utils/log.py", line 104, in _print_logline
    msg = (msg % args) if args else msg

  File "/usr/lib/python3/dist-packages/twisted/internet/error.py", line 77, in __str__
    s = '%s: %s' % (s, ' '.join(self.args))

TypeError: sequence item 0: expected str instance, bytes found

**Comment by fpietrosanti** [comment]
Happened on 14 August 2019 again on 3.10.5



Platform: 
Host:  (xxxx.onion)
Version: 3.10.5

TypeError Inappropriate argument type.

Traceback (most recent call last):

  File "/usr/lib/python3/dist-packages/twisted/internet/defer.py", line 1384, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)

  File "/usr/lib/python3/dist-packages/twisted/python/failure.py", line 408, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)

  File "/usr/lib/python3/dist-packages/globaleaks/handlers/admin/notification.py", line 100, in post
    yield self.state.sendmail(tid, user['mail_address'], subject, body)

  File "/usr/lib/python3/dist-packages/twisted/internet/defer.py", line 653, in _runCallbacks
    current.result = callback(current.result, *args, **kw)

  File "/usr/lib/python3/dist-packages/globaleaks/utils/mail.py", line 116, in failure_cb
    log.err("SMTP connection failed (Exception: %s)", failure.value.subFailure.value, tid=tid)

  File "/usr/lib/python3/dist-packages/globaleaks/utils/log.py", line 143, in err
    self._print_logline('E', msg, *args, **kwargs)

  File "/usr/lib/python3/dist-packages/globaleaks/utils/log.py", line 124, in _print_logline
    msg = (msg % args) if args else msg

  File "/usr/lib/python3/dist-packages/twisted/internet/error.py", line 77, in __str__
    s = '%s: %s' % (s, ' '.join(self.args))

TypeError: sequence item 0: expected str instance, bytes found
