### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by belcastron** [globaleaks/GlobaLeaks#2449]
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.1 LTS
Release:        18.04

Platform: Covip
Host:  (z7wg5nwdg77hkrzx.onion)
Version: 3.4.1

sqlalchemy.orm.exc.NoResultFound A database result was required but none was found.

Traceback (most recent call last):

  File "/usr/lib/python3/dist-packages/twisted/python/threadpool.py", line 250, in inContext
    result = inContext.theWork()

  File "/usr/lib/python3/dist-packages/twisted/python/threadpool.py", line 266, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)

  File "/usr/lib/python3/dist-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)

  File "/usr/lib/python3/dist-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)

  File "/usr/lib/python3/dist-packages/globaleaks/orm.py", line 109, in _wrap
    result = function(session, *args, **kwargs)

  File "/usr/lib/python3/dist-packages/globaleaks/handlers/rtip.py", line 359, in get_rtip
    return db_get_rtip(session, tid, user_id, rtip_id, language)

  File "/usr/lib/python3/dist-packages/globaleaks/handlers/rtip.py", line 242, in db_get_rtip
    return serialize_rtip(session, rtip, itip, language)

  File "/usr/lib/python3/dist-packages/globaleaks/handlers/rtip.py", line 134, in serialize_rtip
    ret['comments'] = db_get_itip_comment_list(session, itip.id)

  File "/usr/lib/python3/dist-packages/globaleaks/handlers/rtip.py", line 363, in db_get_itip_comment_list
    return [serialize_comment(session, comment) for comment in session.query(models.Comment).filter(models.Comment.internaltip_id == itip_id)]

  File "/usr/lib/python3/dist-packages/globaleaks/handlers/rtip.py", line 363, in <listcomp>
    return [serialize_comment(session, comment) for comment in session.query(models.Comment).filter(models.Comment.internaltip_id == itip_id)]

  File "/usr/lib/python3/dist-packages/globaleaks/handlers/rtip.py", line 93, in serialize_comment
    .filter(models.User.id == comment.author_id).one().name

  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/query.py", line 2820, in one
    raise orm_exc.NoResultFound("No row was found for one()")

sqlalchemy.orm.exc.NoResultFound: No row was found for one()

**Comment by evilaliv3** [comment]
Closing as duplicated: https://github.com/globaleaks/GlobaLeaks/issues/2450
