### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by belcastron** [globaleaks/GlobaLeaks#2450]
Distributor ID: Ubuntu
Description: Ubuntu 18.04.1 LTS
Release: 18.04

Platform: Covip
Host:  (z7wg5nwdg77hkrzx.onion)
Version: 3.4.1

sqlalchemy.orm.exc.NoResultFound A database result was required but none was found.

Traceback (most recent call last):

  File "/usr/lib/python3/dist-packages/twisted/internet/defer.py", line 1384, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)

  File "/usr/lib/python3/dist-packages/twisted/python/failure.py", line 408, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)

  File "/usr/lib/python3/dist-packages/globaleaks/handlers/export.py", line 129, in get
    self.request.language)

  File "/usr/lib/python3/dist-packages/twisted/python/threadpool.py", line 250, in inContext
    result = inContext.theWork()

  File "/usr/lib/python3/dist-packages/twisted/python/threadpool.py", line 266, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)

  File "/usr/lib/python3/dist-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)

  File "/usr/lib/python3/dist-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)

  File "/usr/lib/python3/dist-packages/globaleaks/orm.py", line 109, in _wrap
    result = function(session, *args, **kwargs)

  File "/usr/lib/python3/dist-packages/globaleaks/handlers/export.py", line 34, in get_tip_export
    rtip_dict = serialize_rtip(session, rtip, itip, language)

  File "/usr/lib/python3/dist-packages/globaleaks/handlers/rtip.py", line 134, in serialize_rtip
    ret['comments'] = db_get_itip_comment_list(session, itip.id)

  File "/usr/lib/python3/dist-packages/globaleaks/handlers/rtip.py", line 363, in db_get_itip_comment_list
    return [serialize_comment(session, comment) for comment in session.query(models.Comment).filter(models.Comment.internaltip_id == itip_id)]

  File "/usr/lib/python3/dist-packages/globaleaks/handlers/rtip.py", line 363, in <listcomp>
    return [serialize_comment(session, comment) for comment in session.query(models.Comment).filter(models.Comment.internaltip_id == itip_id)]

  File "/usr/lib/python3/dist-packages/globaleaks/handlers/rtip.py", line 93, in serialize_comment
    .filter(models.User.id == comment.author_id).one().name

  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/query.py", line 2820, in one
    raise orm_exc.NoResultFound("No row was found for one()")

sqlalchemy.orm.exc.NoResultFound: No row was found for one()

**Comment by evilaliv3** [comment]
Dear @belcastron than you for reporting this exception.

It seems that you are accessing a submission that contains a comment a receiver that has been deleted.

We are now proceeding adding a fix that will be present starting from release 3.5.0

**Comment by belcastron** [comment]
Grazie
Nicola Belcastro

Da: Giovanni Pellerano [mailto:notifications@github.com]
Inviato: martedì 13 novembre 2018 17:14
A: globaleaks/GlobaLeaks <GlobaLeaks@noreply.github.com>
Cc: Belcastro Nicola <belcastro@covip.it>; Mention <mention@noreply.github.com>
Oggetto: Re: [globaleaks/GlobaLeaks] Bug (#2450)


Dear @belcastron<https://github.com/belcastron> than you for reporting this exception.

It seems that you are accessing a submission that contains a comment a receiver that has been deleted.

We are now proceeding adding a fix that will be present starting from release 3.5.0
