### ISSUE TITLE
KeyError in submission.py:448 at token = self.state.tokens.pop(token_id) with GL 3.5.1

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#2457]
Platform: Whistleblowing del Comune di 
Host: whistleblower.comunexxxxxxx.local 
Version: 3.5.1

KeyError Mapping key not found.

Traceback (most recent call last):

  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 150, in maybeDeferred
    result = f(*args, **kw)

  File "/usr/lib/python2.7/dist-packages/globaleaks/handlers/base.py", line 99, in wrapper
    return f(self, *args, **kwargs)

  File "/usr/lib/python2.7/dist-packages/globaleaks/handlers/submission.py", line 448, in put
    token = self.state.tokens.pop(token_id)

  File "/usr/lib/python2.7/collections.py", line 160, in pop
    raise KeyError(key)

KeyError: u'5lna2LV0MmH3E4HKcxtkMZEZcq0QjvBn0EcF3IdWQZ'

**Comment by evilaliv3** [comment]
Closing as recently fixed in https://github.com/globaleaks/GlobaLeaks/commit/b6fef5ceaa8ccac712980acceb7a01c200cf5d92
