### ISSUE TITLE
Unhandled exception in GL 3.5.1 AttributeError: Request instance has no attribute 'channel'

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#2459]
Platform: try.globaleaks.org
Host: try.globaleaks.org (bvidswzoj322engc.onion)
Version: 3.5.1

AttributeError Attribute not found.

Traceback (most recent call last):

  File "/usr/lib/python2.7/dist-packages/twisted/python/log.py", line 101, in callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)

  File "/usr/lib/python2.7/dist-packages/twisted/python/log.py", line 84, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)

  File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)

  File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 81, in callWithContext
    return func(*args,**kw)

  File "/usr/lib/python2.7/dist-packages/twisted/internet/posixbase.py", line 610, in _doReadOrWrite
    self._disconnectSelectable(selectable, why, inRead)

  File "/usr/lib/python2.7/dist-packages/twisted/internet/posixbase.py", line 252, in _disconnectSelectable
    selectable.readConnectionLost(f)

  File "/usr/lib/python2.7/dist-packages/twisted/internet/tcp.py", line 273, in readConnectionLost
    self.connectionLost(reason)

  File "/usr/lib/python2.7/dist-packages/twisted/internet/tcp.py", line 287, in connectionLost
    abstract.FileDescriptor.connectionLost(self, reason)

  File "/usr/lib/python2.7/dist-packages/twisted/internet/abstract.py", line 204, in connectionLost
    self.producer.stopProducing()

  File "/usr/lib/python2.7/dist-packages/globaleaks/handlers/base.py", line 61, in stopProducing
    self.request.finish()

  File "/usr/lib/python2.7/dist-packages/twisted/web/server.py", line 224, in finish
    return http.Request.finish(self)

  File "/usr/lib/python2.7/dist-packages/twisted/web/http.py", line 885, in finish
    self._cleanup()

  File "/usr/lib/python2.7/dist-packages/twisted/web/http.py", line 611, in _cleanup
    self.channel.requestDone(self)

  File "/usr/lib/python2.7/dist-packages/twisted/web/http.py", line 1814, in requestDone
    self.requests[0].noLongerQueued()

  File "/usr/lib/python2.7/dist-packages/twisted/web/http.py", line 650, in noLongerQueued
    self._cleanup()

  File "/usr/lib/python2.7/dist-packages/twisted/web/http.py", line 611, in _cleanup
    self.channel.requestDone(self)

AttributeError: Request instance has no attribute 'channel'

**Comment by martinszy** [comment]
+1, I'm also getting these in version 3.5.4.

**Comment by marvinrouge** [comment]
+1 in version 3.6.5
