### ISSUE TITLE
GL 3.5.1: NameError: global name 'password' is not defined Unhandled exception 

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#2460]
Platform:  
Host: 
Version: 3.5.1

NameError Name not found globally.

Traceback (most recent call last):

  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1126, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)

  File "/usr/lib/python2.7/dist-packages/twisted/python/failure.py", line 389, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)

  File "/usr/lib/python2.7/dist-packages/globaleaks/handlers/authentication.py", line 258, in post
    session = yield login_whistleblower(self.request.tid, receipt, self.request.client_using_tor)

  File "/usr/lib/python2.7/dist-packages/twisted/python/threadpool.py", line 246, in inContext
    result = inContext.theWork()

  File "/usr/lib/python2.7/dist-packages/twisted/python/threadpool.py", line 262, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)

  File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)

  File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 81, in callWithContext
    return func(*args,**kw)

  File "/usr/lib/python2.7/dist-packages/globaleaks/orm.py", line 109, in _wrap
    result = function(session, *args, **kwargs)

  File "/usr/lib/python2.7/dist-packages/globaleaks/handlers/authentication.py", line 65, in login_whistleblower
    _password = password

NameError: global name 'password' is not defined

**Comment by evilaliv3** [comment]
This is an exception triggered during development.
