### ISSUE TITLE
GL 3.5.5: Unhandled exception in process.py in TypeError: a bytes-like object is required, not 'str'

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#2462]
Platform: WhistleBlowing XXXX
Host: whistleblowing.xxxxxx
Version: 3.5.5

TypeError Inappropriate argument type.

Traceback (most recent call last):

  File "/usr/lib/python3/dist-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
    why = selectable.doRead()

  File "/usr/lib/python3/dist-packages/twisted/internet/process.py", line 291, in doRead
    return fdesc.readFromFD(self.fd, self.dataReceived)

  File "/usr/lib/python3/dist-packages/twisted/internet/fdesc.py", line 94, in readFromFD
    callback(output)

  File "/usr/lib/python3/dist-packages/twisted/internet/process.py", line 295, in dataReceived
    self.proc.childDataReceived(self.name, data)

  File "/usr/lib/python3/dist-packages/twisted/internet/process.py", line 961, in childDataReceived
    self.proto.childDataReceived(name, data)

  File "/usr/lib/python3/dist-packages/globaleaks/workers/process.py", line 81, in childDataReceived
    for line in data.split('\n'):

TypeError: a bytes-like object is required, not 'str'

**Comment by evilaliv3** [comment]
Closing as stale and oudtated.
