### ISSUE TITLE
Unable to enable "Subject answer visibility to custodian authorization": "Assoggetta la visibilità della risposta all'autorizzazione da parte del custode"

### ISSUE THREAD

**Issue by gneotel** [globaleaks/GlobaLeaks#2465]
I cannot save the "Subject answer visibility to custodian authorization": "Assoggetta la visibilità della risposta all'autorizzazione da parte del custode" option.
When I save I got no errors but if I logout and login again the option is unchecked again.
I made a small video to show the issue:
[2018-11-16.09-45-03.zip](https://github.com/globaleaks/GlobaLeaks/files/2620805/2018-11-16.09-45-03.zip)
 
When I restart the service I receive this error but then the site looks like running fine:
**************************************************************
TypeError Inappropriate argument type.

Traceback (most recent call last):

  File "/usr/lib/python3/dist-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
    why = selectable.doRead()

  File "/usr/lib/python3/dist-packages/twisted/internet/process.py", line 291, in doRead
    return fdesc.readFromFD(self.fd, self.dataReceived)

  File "/usr/lib/python3/dist-packages/twisted/internet/fdesc.py", line 94, in readFromFD
    callback(output)

  File "/usr/lib/python3/dist-packages/twisted/internet/process.py", line 295, in dataReceived
    self.proc.childDataReceived(self.name, data)

  File "/usr/lib/python3/dist-packages/twisted/internet/process.py", line 961, in childDataReceived
    self.proto.childDataReceived(name, data)

  File "/usr/lib/python3/dist-packages/globaleaks/workers/process.py", line 81, in childDataReceived
    for line in data.split('\n'):

TypeError: a bytes-like object is required, not 'str'
**************************************************************
 

I have the problem since globaleaks 3.5.1,
now I run globaleaks 3.5.5
on Ubuntu 18.04.1 LTS

Thanks for your help.

**Comment by fpietrosanti** [comment]
related to #2462
