### ISSUE TITLE
GL unhandled exception in multi-tenant does not report the tenant hostname

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#2466]
**Current behavior**
Actually in a multi-tenant environment, when backend trigger an unhandled exception due to a software bug, there's no indication in the unhandled exception notification email template of the tenant identifiers (ID and hostname).

Platform: try.globaleaks.org
Host: try.globaleaks.org (bvidswzoj322engc.onion)
Version: 3.5.1

EnvironmentError Base class for I/O related errors.

Traceback (most recent call last):

  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1128, in _inlineCallbacks
    result = g.send(result)

  File "/usr/lib/python2.7/dist-packages/globaleaks/handlers/admin/operation.py", line 83, in verify_hostname
    raise e

EnvironmentError: Response unexpected

**Expected behavior**
The unhandled exception email in a multi-tenant environment, should indicate in the subject and in the body the tenant hostname that's triggering the event (if available).

**Comment by henrynewman** [comment]
Experiencing the same problem, can anyone advice on how to fix!..

**Comment by henrynewman** [comment]
This is what I got--->

Version: 3.9.11 

EnvironmentError Base class for I/O related errors. 

Traceback (most recent call last): 

File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1299, in _inlineCallbacks 
result = g.send(result) 

File "/usr/lib/python2.7/dist-packages/globaleaks/handlers/admin/operation.py", line 85, in verify_hostname 
raise EnvironmentError('Response unexpected') 

EnvironmentError: Response unexpected

**Comment by fpietrosanti** [comment]
Ref #2193

**Comment by evilaliv3** [comment]
Closing as this has been handled probably long time ago.
