### ISSUE TITLE
GL 3.5.7: OverflowError: normalized days too large to fit in a C int in db_check_for_expiring_submissions

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#2474]
Platform: try.globaleaks.org
Host: try.globaleaks.org (bvidswzoj322engc.onion)
Version: 3.5.7

OverflowError Result too large to be represented.

Traceback (most recent call last):

  File "/usr/lib/python2.7/dist-packages/globaleaks/jobs/base.py", line 48, in run
    yield self.operation()

  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1126, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)

  File "/usr/lib/python2.7/dist-packages/twisted/python/failure.py", line 389, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)

  File "/usr/lib/python2.7/dist-packages/globaleaks/jobs/daily.py", line 179, in operation
    yield self.daily_clean()

  File "/usr/lib/python2.7/dist-packages/twisted/python/threadpool.py", line 246, in inContext
    result = inContext.theWork()

  File "/usr/lib/python2.7/dist-packages/twisted/python/threadpool.py", line 262, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)

  File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)

  File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 81, in callWithContext
    return func(*args,**kw)

  File "/usr/lib/python2.7/dist-packages/globaleaks/orm.py", line 107, in _wrap
    result = function(self.instance, session, *args, **kwargs)

  File "/usr/lib/python2.7/dist-packages/globaleaks/jobs/daily.py", line 171, in daily_clean
    self.db_check_for_expiring_submissions(session)

  File "/usr/lib/python2.7/dist-packages/globaleaks/jobs/daily.py", line 63, in db_check_for_expiring_submissions
    threshold = datetime_now() + timedelta(hours=State.tenant_cache[tid].notification.tip_expiration_threshold)

OverflowError: normalized days too large to fit in a C int

**Comment by evilaliv3** [comment]
Closing as stale and outdated.
