### ISSUE TITLE
Transaction failed with too many retries

### ISSUE THREAD

**Issue by andy650429** [globaleaks/GlobaLeaks#2484]
Unable to login with the Receiver or Custodian account. 
The system goes into time-out and the logs show the following:

**Current behavior**

2019-01-15 16:11:37+0100 [-] [E] [1] Handler [AuthenticationHandler] exceeded execution threshold (of 120 secs) with an execution time of 206.00 seconds
2019-01-15 16:11:37+0100 [-] [E] Unhandled exception raised:
2019-01-15 16:11:37+0100 [-] [E] Exception Common base class for all non-exit exceptions.\n\nTraceback (most recent call last):\n\n  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context\n    context)\n\n  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/default.py", line 470, in do_execute\n    cursor.execute(statement, parameters)\n\nsqlite3.OperationalError: database is locked\n\n\nThe above exception was the direct cause of the following exception:\n\n\nTraceback (most recent call last):\n\n  File "/usr/lib/python3/dist-packages/globaleaks/orm.py", line 127, in _wrap\n    session.commit()\n\n  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/session.py", line 906, in commit\n    self.transaction.commit()\n\n  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/session.py", line 461, in commit\n    self._prepare_impl()\n\n  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/session.py", line 441, in _prepare_impl\n    self.session.flush()\n\n  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/session.py", line 2171, in flush\n    self._flush(objects)\n\n  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/session.py", line 2291, in _flush\n    transaction.rollback(_capture_exception=True)\n\n  File "/usr/lib/python3/dist-packages/sqlalchemy/util/langhelpers.py", line 66, in __exit__\n    compat.reraise(exc_type, exc_value, exc_tb)\n\n  File "/usr/lib/python3/dist-packages/sqlalchemy/util/compat.py", line 187, in reraise\n    raise value\n\n  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/session.py", line 2255, in _flush\n    flush_context.execute()\n\n  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/unitofwork.py", line 389, in execute\n    rec.execute(self)\n\n  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/unitofwork.py", line 548, in execute\n    uow\n\n  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/persistence.py", line 177, in save_obj\n    mapper, table, update)\n\n  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/persistence.py", line 737, in _emit_update_statements\n    execute(statement, multiparams)\n\n  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 945, in execute\n    return meth(self, multiparams, params)\n\n  File "/usr/lib/python3/dist-packages/sqlalchemy/sql/elements.py", line 263, in _execute_on_connection\n    return connection._execute_clauseelement(self, multiparams, params)\n\n  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1053, in _execute_clauseelement\n    compiled_sql, distilled_params\n\n  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1189, in _execute_context\n    context)\n\n  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1402, in _handle_dbapi_exception\n    exc_info\n\n  File "/usr/lib/python3/dist-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause\n    reraise(type(exception), exception, tb=exc_tb, cause=cause)\n\n  File "/usr/lib/python3/dist-packages/sqlalchemy/util/compat.py", line 186, in reraise\n    raise value.with_traceback(tb)\n\n  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context\n    context)\n\n  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/default.py", line 470, in do_execute\n    cursor.execute(statement, parameters)\n\nsqlalchemy.exc.OperationalError: (sqlite3.OperationalError) database is locked [SQL: 'UPDATE user SET last_login=? WHERE user.id = ?'] [parameters: ('2019-01-15 15:11:37.421377', '3a6dde69-659f-4ace-99f0-91ea81c9e416')]\n\n\nDuring handling of the above exception, another exception occurred:\n\n\nTraceback (most recent call last):\n\n  File "/usr/lib/python3/dist-packages/twisted/internet/defer.py", line 1384, in _inlineCallbacks\n    result = result.throwExceptionIntoGenerator(g)\n\n  File "/usr/lib/python3/dist-packages/twisted/python/failure.py", line 408, in throwExceptionIntoGenerator\n    return g.throw(self.type, self.value, self.tb)\n\n  File "/usr/lib/python3/dist-packages/globaleaks/handlers/authentication.py", line 199, in post\n    self.request.client_ip)\n\n  File "/usr/lib/python3/dist-packages/twisted/python/threadpool.py", line 250, in inContext\n    result = inContext.theWork()\n\n  File "/usr/lib/python3/dist-packages/twisted/python/threadpool.py", line 266, in <lambda>\n    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)\n\n  File "/usr/lib/python3/dist-packages/twisted/python/context.py", line 122, in callWithContext\n    return self.currentContext().callWithContext(ctx, func, *args, **kw)\n\n  File "/usr/lib/python3/dist-packages/twisted/python/context.py", line 85, in callWithContext\n    return func(*args,**kw)\n\n  File "/usr/lib/python3/dist-packages/globaleaks/orm.py", line 137, in _wrap\n    raise Exception("Transaction failed with too many retries")\n\nException: Transaction failed with too many retries\n

**Steps to reproduce the problem or feature illustration**

Attempt to login from /#/admin

**GlobaLeaks version:**

GL 3.6.0

**Browser:**

All browser (Chrome, Firefox)

**Server Operating System and Version (if applicable):**
 

Ubuntu Server 18.04.1 LTS 

Thanks for the help!

Andrea

**Comment by andy650429** [comment]
p.s.

the strange thing is that the admin can enter and change the configuration without problems.
Yet for the recipients the DB appears to be blocked

**Comment by andy650429** [comment]
Thank you Giovanni,

no ... I did not make any changes to the program.
Since TOR also stopped working, I try to reinstall the system with this method, hoping to solve the problem.

I update you as soon as possible

Hello

Andrew

**Comment by evilaliv3** [comment]
@andy650429: Ths issue on tor is a known issue, you do not need to reainstall.

We are issuing now a release 3.6.1 that will contain the fix.

**Comment by andy650429** [comment]
Hi Giovanni,

this morning I tried to create a new receiver with the same installation updated to 3.6.0 and again time out. 
Below is the error.
I confirm that I have not modified anything in the distribution files.

2019-01-16 08:54:38+0100 [-] [E] [1] Handler [UsersCollection] exceeded execution threshold (of 120 secs) with an execution time of 228.00 seconds
2019-01-16 08:54:38+0100 [-] [E] Unhandled exception raised:
2019-01-16 08:54:38+0100 [-] [E] Exception Common base class for all non-exit exceptions.\n\nTraceback (most recent call last):\n\n  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context\n    context)\n\n  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/default.py", line 470, in do_execute\n    cursor.execute(statement, parameters)\n\nsqlite3.OperationalError: database is locked\n\n\nThe above exception was the direct cause of the following exception:\n\n\nTraceback (most recent call last):\n\n  File "/usr/lib/python3/dist-packages/globaleaks/orm.py", line 125, in _wrap\n    result = function(session, *args, **kwargs)\n\n  File "/usr/lib/python3/dist-packages/globaleaks/handlers/admin/user.py", line 40, in create_user\n    return user_serialize_user(session, db_create_user(session, tid, request, language), language)\n\n  File "/usr/lib/python3/dist-packages/globaleaks/handlers/admin/user.py", line 84, in db_create_user\n    session.flush()\n\n  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/session.py", line 2171, in flush\n    self._flush(objects)\n\n  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/session.py", line 2291, in _flush\n    transaction.rollback(_capture_exception=True)\n\n  File "/usr/lib/python3/dist-packages/sqlalchemy/util/langhelpers.py", line 66, in __exit__\n    compat.reraise(exc_type, exc_value, exc_tb)\n\n  File "/usr/lib/python3/dist-packages/sqlalchemy/util/compat.py", line 187, in reraise\n    raise value\n\n  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/session.py", line 2255, in _flush\n    flush_context.execute()\n\n  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/unitofwork.py", line 389, in execute\n    rec.execute(self)\n\n  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/unitofwork.py", line 548, in execute\n    uow\n\n  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/persistence.py", line 181, in save_obj\n    mapper, table, insert)\n\n  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/persistence.py", line 835, in _emit_insert_statements\n    execute(statement, params)\n\n  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 945, in execute\n    return meth(self, multiparams, params)\n\n  File "/usr/lib/python3/dist-packages/sqlalchemy/sql/elements.py", line 263, in _execute_on_connection\n    return connection._execute_clauseelement(self, multiparams, params)\n\n  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1053, in _execute_clauseelement\n    compiled_sql, distilled_params\n\n  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1189, in _execute_context\n    context)\n\n  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1402, in _handle_dbapi_exception\n    exc_info\n\n  File "/usr/lib/python3/dist-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause\n    reraise(type(exception), exception, tb=exc_tb, cause=cause)\n\n  File "/usr/lib/python3/dist-packages/sqlalchemy/util/compat.py", line 186, in reraise\n    raise value.with_traceback(tb)\n\n  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context\n    context)\n\n  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/default.py", line 470, in do_execute\n    cursor.execute(statement, parameters)\n\nsqlalchemy.exc.OperationalError: (sqlite3.OperationalError) database is locked [SQL: 'INSERT INTO user (id, tid, creation_date, username, salt, hash_alg, password, name, description, role, state, last_login, mail_address, language, password_change_needed, password_change_date, crypto_prv_key, crypto_pub_key, change_email_address, change_email_token, change_email_date, reset_password_token, reset_password_date, notification, recipient_configuration, can_delete_submission, can_postpone_expiration, can_grant_permissions, can_edit_general_settings, pgp_key_fingerprint, pgp_key_public, pgp_key_expiration) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)'] [parameters: ('10d693e2-f0e8-4e57-a78d-dcc5c44518d9', 1, '2019-01-16 07:54:38.754422', 'PROVA', 'GltElXJ3N1DS4gRb5bFe5Q==', 'ARGON2', "b'YbnWg3BjF1jsTV41Rg8+yAOMZd4iQBm0jpiY0VDc3q8='", 'PROVA', '{"it": {"it": {"it": {"it": {"it": {"it": {"it": {"it": {"it": {"it": ""}}}}}}}}}}', 'receiver', 'enabled', '1970-01-01 00:00:00.000000', 'gddblo@libero.it', 'it', 1, '1970-01-01 00:00:00.000000', <memory at 0x7f7599f0a348>, <memory at 0x7f7599f0a408>, '', None, '1970-01-01 00:00:00.000000', None, datetime.datetime(1970, 1, 1, 0, 0), 1, 'default', 0, 0, 0, 0, '', '', '1970-01-01 00:00:00.000000')]\n\n\nDuring handling of the above exception, another exception occurred:\n\n\nTraceback (most recent call last):\n\n  File "/usr/lib/python3/dist-packages/twisted/python/threadpool.py", line 250, in inContext\n    result = inContext.theWork()\n\n  File "/usr/lib/python3/dist-packages/twisted/python/threadpool.py", line 266, in <lambda>\n    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)\n\n  File "/usr/lib/python3/dist-packages/twisted/python/context.py", line 122, in callWithContext\n    return self.currentContext().callWithContext(ctx, func, *args, **kw)\n\n  File "/usr/lib/python3/dist-packages/twisted/python/context.py", line 85, in callWithContext\n    return func(*args,**kw)\n\n  File "/usr/lib/python3/dist-packages/globaleaks/orm.py", line 137, in _wrap\n    raise Exception("Transaction failed with too many retries")\n\nException: Transaction failed with too many retries\n

**Comment by evilaliv3** [comment]
Thank you @andy650429 

If you have currently not customized anything that has a value may i ask you to proceed with the following?

stop globaleaks: /etc/init.d/globaleaks stop
save /var/globaleaks if you need a copy
delete /var/globaleaks
restart globaleaks: /etc/init.d/globaleaks start

then perform the wizard and try to reproduce the issue.

It would be valuable for me if you can pass me details of the setup (cores, ram, if it is a phisical server or a vps and which characteristics); eventually would be valuable for me to access an make some debug.
if valuable for you log on slack.hermescenter.org where you can reach me directly.

thank you!

**Comment by andy650429** [comment]
Thank you Giovanni

I have completed what you have indicated.
My server is on phisical (remote) server: 2 core, 8 Gb Ram, 500Gb (Atom Server), Ubuntu Server 18.04.1 LTS. Version GL 3.5.8 worked perfectly. 

The globaleaks.log not show TOR address... so I can not access the wizard (the server has no GUI) and of course Lynx does not work by not supporting Javascript. 

I'll contact you directly on slack

**Comment by MrYBer** [comment]
When will the binaries be available on the software repository ?

**Comment by evilaliv3** [comment]
Closing the ticket as the issue has been fixed with the support of @andy650429 and the release of version 3.6.2.

@mryber: what do you mean with your question?
