### ISSUE TITLE
Argon2 error: nacl.exceptions.ValueError: salt must be exactly 16 bytes long

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#2498]
Platform:
Host:  
Version: 3.6.5

nacl.exceptions.ValueError None

Traceback (most recent call last):

  File "/usr/lib/python3/dist-packages/twisted/python/threadpool.py", line 250, in inContext
    result = inContext.theWork()

  File "/usr/lib/python3/dist-packages/twisted/python/threadpool.py", line 266, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)

  File "/usr/lib/python3/dist-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)

  File "/usr/lib/python3/dist-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)

  File "/usr/lib/python3/dist-packages/globaleaks/orm.py", line 117, in _wrap
    result = function(session, *args, **kwargs)

  File "/usr/lib/python3/dist-packages/globaleaks/handlers/submission.py", line 415, in create_submission
    return db_create_submission(session, tid, request, token, client_using_tor)

  File "/usr/lib/python3/dist-packages/globaleaks/handlers/submission.py", line 339, in db_create_submission
    wbtip.receipt_hash = GCE.hash_password(receipt, receipt_salt)

  File "/usr/lib/python3/dist-packages/globaleaks/utils/crypto.py", line 230, in hash_password
    return GCE.HASH_FUNCTIONS[algorithm](password, salt)

  File "/usr/lib/python3/dist-packages/globaleaks/utils/crypto.py", line 90, in _hash_argon2
    memlimit=GCE.ALGORITM_CONFIGURATION['HASH']['ARGON2']['MEMLIMIT'])

  File "/usr/lib/python3/dist-packages/nacl/pwhash/argon2id.py", line 109, in kdf
    ALG)

  File "/usr/lib/python3/dist-packages/nacl/bindings/crypto_pwhash.py", line 379, in crypto_pwhash_alg
    crypto_pwhash_SALTBYTES))

nacl.exceptions.ValueError: salt must be exactly 16 bytes long

**Comment by evilaliv3** [comment]
The fix will be released by today with 3.5.8
