### ISSUE TITLE
Recurrent error message after upgarde from 3.1.9 to 3.6.2

### ISSUE THREAD

**Issue by guyonj** [globaleaks/GlobaLeaks#2501]
**Current behavior**

twisted.web._newclient.ResponseNeverReceived
    A L{ResponseFailed} that knows no response bytes at all have been received.
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/globaleaks/jobs/job.py", line 49, in run
    yield self.operation()
ResponseNeverReceived: []

**Expected behavior**

Not such a mail should be received

**Steps to reproduce the problem or feature illustration**

Recurrent job error

**What is the motivation or use case for changing the behavior?**

disturb Platform admin

**GlobaLeaks version:**

root@globaleaks-31-r:~# dpkg -l | grep -i globaleaks
ii  globaleaks                          3.6.5                                      all          Opensource whistleblowing platform.

**Browser:**

N/A

**Server Operating System and Version (if applicable):**
 
root@globaleaks-31-r:~# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.5 LTS
Release:        16.04
Codename:       xenial

**Client Operating System and Version (if applicable):**

**Comment by guyonj** [comment]
Log error message
2019-01-25 11:00:00+0100 [-] Starting factory <twisted.web.client._HTTP11ClientFactory instance at 0x7f4b10068098>
2019-01-25 11:00:00+0100 [-] [E] Job ExitNodesRefresh died with runtime 67.7102 [low: 57.0000, high: 4488.0000]
2019-01-25 11:00:00+0100 [-] Traceback (most recent call last):
2019-01-25 11:00:00+0100 [-]   File "/usr/lib/python2.7/dist-packages/globaleaks/jobs/job.py", line 49, in run
2019-01-25 11:00:00+0100 [-]     yield self.operation()
2019-01-25 11:00:00+0100 [-] ResponseNeverReceived: [<twisted.python.failure.Failure OpenSSL.SSL.Error: [('SSL routines', 'ssl23_read', 'ssl handshake failure')]>]
2019-01-25 11:00:00+0100 [-] [E] Unhandled exception raised:
2019-01-25 11:00:00+0100 [-] [E] twisted.web._newclient.ResponseNeverReceived \n    A L{ResponseFailed} that knows no response bytes at all have been received.\n    \n\nTraceback (most recent call last):\n\n  File "/usr/lib/python2.7/dist-packages/globaleaks/jobs/job.py", line 49, in run\n    yield self.operation()\n\nResponseNeverReceived: [<twisted.python.failure.Failure OpenSSL.SSL.Error: [('SSL routines', 'ssl23_read', 'ssl handshake failure')]>]\n
2019-01-25 11:00:00+0100 [-] Stopping factory <twisted.web.client._HTTP11ClientFactory instance at 0x7f4b10068098>

**Comment by guyonj** [comment]
Solved after upgrade thank you
