### ISSUE TITLE
Unhandled exception UnicodeDecodeError: 'ascii' codec can't decode byte 0x80 in position 240: ordinal not in range(128)

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#2584]
Platform: xxxxxx
Host: whistleblowing.xxxxx.com (xxxxx)
Version: 3.9.2

UnicodeDecodeError Unicode decoding error.

Traceback (most recent call last):

 File "/usr/lib/python3/dist-packages/twisted/web/server.py", line 195, in process
   self.render(resrc)

 File "/usr/lib/python3/dist-packages/twisted/web/server.py", line 255, in render
   body = resrc.render(self)

 File "/usr/lib/python3/dist-packages/globaleaks/rest/api.py", line 357, in render
   self.redirect_https(request)

 File "/usr/lib/python3/dist-packages/globaleaks/rest/api.py", line 249, in redirect_https
   _, _, path, query, frag = urlsplit(request.uri)

 File "/usr/lib/python3.6/urllib/parse.py", line 400, in urlsplit
   url, scheme, _coerce_result = _coerce_args(url, scheme)

 File "/usr/lib/python3.6/urllib/parse.py", line 123, in _coerce_args
   return _decode_args(args) + (_encode_result,)

 File "/usr/lib/python3.6/urllib/parse.py", line 107, in _decode_args
   return tuple(x.decode(encoding, errors) if x else '' for x in args)

 File "/usr/lib/python3.6/urllib/parse.py", line 107, in <genexpr>
   return tuple(x.decode(encoding, errors) if x else '' for x in args)

UnicodeDecodeError: 'ascii' codec can't decode byte 0x80 in position 240: ordinal not in range(128)

**Comment by evilaliv3** [comment]
I just found the reason of the problem that is in the handling of https/onion redirects when the starting url contains utf-8 characters; this i probably happening on platforms indexed by some crawlers that for some reasons is adding additional query to the URL.

To fix the issue we should change some of the inner functions that we are using with their respective bugfixed version supporting unicode.

**Comment by evilaliv3** [comment]
Bug fixed and fix released starting from version 3.9.6
