### ISSUE TITLE
Unhandled Exception in AttributeError: module 'lib' has no attribute 'NID_X9_62_prime256v1'

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#2638]
Platform: yyyyy
Host: xxxx
Version: 3.9.11

AttributeError Attribute not found.

Traceback (most recent call last):

  File "/usr/lib/python3/dist-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)

  File "/usr/lib/python3/dist-packages/twisted/python/failure.py", line 491, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)

  File "/usr/lib/python3/dist-packages/globaleaks/handlers/admin/https.py", line 385, in post
    yield try_to_enable_https(self.request.tid)

  File "/usr/lib/python3/dist-packages/twisted/python/threadpool.py", line 250, in inContext
    result = inContext.theWork()

  File "/usr/lib/python3/dist-packages/twisted/python/threadpool.py", line 266, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)

  File "/usr/lib/python3/dist-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)

  File "/usr/lib/python3/dist-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)

  File "/usr/lib/python3/dist-packages/globaleaks/orm.py", line 117, in _wrap
    result = function(session, *args, **kwargs)

  File "/usr/lib/python3/dist-packages/globaleaks/handlers/admin/https.py", line 352, in try_to_enable_https
    State.snimap.load(tid, tls_config)

  File "/usr/lib/python3/dist-packages/globaleaks/utils/sni.py", line 145, in load
    conf['ssl_dh'])

  File "/usr/lib/python3/dist-packages/globaleaks/utils/tls.py", line 185, in __init__
    ecdh = _lib.EC_KEY_new_by_curve_name(_lib.NID_X9_62_prime256v1)  # pylint: disable=no-member

AttributeError: module 'lib' has no attribute 'NID_X9_62_prime256v1'

**Comment by evilaliv3** [comment]
Closing as probably outdated.
