### ISSUE TITLE
Unhandled exception: nacl.exceptions.RuntimeError failure in key derivation 3.9.11

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#2641]
Platform: Prova
Host: segnalazioni.xxxxx
Version: 3.9.11

nacl.exceptions.RuntimeError None

Traceback (most recent call last):

  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1297, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)

  File "/usr/lib/python2.7/dist-packages/twisted/python/failure.py", line 389, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)

  File "/usr/lib/python2.7/dist-packages/globaleaks/handlers/authentication.py", line 208, in post
    self.request.client_ip)

  File "/usr/lib/python2.7/dist-packages/twisted/python/threadpool.py", line 246, in inContext
    result = inContext.theWork()

  File "/usr/lib/python2.7/dist-packages/twisted/python/threadpool.py", line 262, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)

  File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)

  File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 81, in callWithContext
    return func(*args,**kw)

  File "/usr/lib/python2.7/dist-packages/globaleaks/orm.py", line 117, in _wrap
    result = function(session, *args, **kwargs)

  File "/usr/lib/python2.7/dist-packages/globaleaks/handlers/authentication.py", line 112, in login
    if GCE.check_password(u.hash_alg, password, u.salt, u.password):

  File "/usr/lib/python2.7/dist-packages/globaleaks/utils/crypto.py", line 248, in check_password
    x = _convert_to_bytes(GCE.HASH_FUNCTIONS[algorithm](password, salt))

  File "/usr/lib/python2.7/dist-packages/globaleaks/utils/crypto.py", line 99, in _hash_argon2
    memlimit=GCE.ALGORITM_CONFIGURATION['HASH']['ARGON2']['MEMLIMIT'])

  File "/usr/lib/python2.7/dist-packages/nacl/pwhash/argon2id.py", line 109, in kdf
    ALG)

  File "/usr/lib/python2.7/dist-packages/nacl/bindings/crypto_pwhash.py", line 399, in crypto_pwhash_alg
    raising=exc.RuntimeError)

  File "/usr/lib/python2.7/dist-packages/nacl/exceptions.py", line 68, in ensure
    raise raising(*args)

RuntimeError: Unexpected failure in key derivation

**Comment by evilaliv3** [comment]
Closing as outdated and probably fixed
