### ISSUE TITLE
Unhandled exception in field.py on field_dict['template_id']).one()

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#2650]
Platform: xxxx demo
Host:  (xxxx.onion)
Version: 3.9.5

sqlalchemy.orm.exc.NoResultFound A database result was required but none was found.

Traceback (most recent call last):

  File "/usr/lib/python3/dist-packages/twisted/python/threadpool.py", line 250, in inContext
    result = inContext.theWork()

  File "/usr/lib/python3/dist-packages/twisted/python/threadpool.py", line 266, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)

  File "/usr/lib/python3/dist-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)

  File "/usr/lib/python3/dist-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)

  File "/usr/lib/python3/dist-packages/globaleaks/orm.py", line 117, in _wrap
    result = function(session, *args, **kwargs)

  File "/usr/lib/python3/dist-packages/globaleaks/handlers/admin/questionnaire.py", line 89, in create_questionnaire
    questionnaire = db_create_questionnaire(session, tid, request, language)

  File "/usr/lib/python3/dist-packages/globaleaks/handlers/admin/questionnaire.py", line 73, in db_create_questionnaire
    db_create_step(session, tid, step, language)

  File "/usr/lib/python3/dist-packages/globaleaks/handlers/admin/step.py", line 36, in db_create_step
    db_create_field(session, tid, c, language)

  File "/usr/lib/python3/dist-packages/globaleaks/handlers/admin/field.py", line 140, in db_create_field
    template = session.query(models.Field).filter(models.Field.id == field_dict['template_id']).one()

  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/query.py", line 2820, in one
    raise orm_exc.NoResultFound("No row was found for one()")

sqlalchemy.orm.exc.NoResultFound: No row was found for one()

**Comment by evilaliv3** [comment]
Closing as outdated and probably fixed.
