### ISSUE TITLE
Failure in the renewal of Letsencrypt certificates: too many registrations for this IP

### ISSUE THREAD

**Issue by evilaliv3** [globaleaks/GlobaLeaks#2652]
The following error is being reported in many projects.

It seems related to rate limits  imposed by letsencrypt: https://letsencrypt.org/docs/rate-limits/

Error:

```python
acme.messages.Error ACME error.

    https://tools.ietf.org/html/draft-ietf-appsawg-http-problem-00

    :ivar unicode typ:
    :ivar unicode title:
    :ivar unicode detail:

Traceback (most recent call last):

  File "/usr/lib/python3/dist-packages/twisted/internet/defer.py", line 1384, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)

  File "/usr/lib/python3/dist-packages/twisted/python/failure.py", line 408, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)

  File "/usr/lib/python3/dist-packages/globaleaks/handlers/admin/https.py", line 558, in put
    yield acme_cert_issuance(self.request.tid)

  File "/usr/lib/python3/dist-packages/twisted/python/threadpool.py", line 250, in inContext
    result = inContext.theWork()

  File "/usr/lib/python3/dist-packages/twisted/python/threadpool.py", line 266, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)

  File "/usr/lib/python3/dist-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)

  File "/usr/lib/python3/dist-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)

  File "/usr/lib/python3/dist-packages/globaleaks/orm.py", line 117, in _wrap
    result = function(session, *args, **kwargs)

  File "/usr/lib/python3/dist-packages/globaleaks/handlers/admin/https.py", line 538, in acme_cert_issuance
    return db_acme_cert_issuance(session, tid)

  File "/usr/lib/python3/dist-packages/globaleaks/handlers/admin/https.py", line 501, in db_acme_cert_issuance
    Settings.acme_directory_url)

  File "/usr/lib/python3/dist-packages/globaleaks/utils/letsencrypt.py", line 65, in request_new_certificate
    terms_of_service_agreed=True

  File "/usr/lib/python3/dist-packages/acme/client.py", line 587, in new_account
    response = self._post(self.directory['newAccount'], new_account)

  File "/usr/lib/python3/dist-packages/acme/client.py", line 94, in _post
    return self.net.post(*args, **kwargs)

  File "/usr/lib/python3/dist-packages/acme/client.py", line 1130, in post
    return self._post_once(*args, **kwargs)

  File "/usr/lib/python3/dist-packages/acme/client.py", line 1147, in _post_once
    response = self._check_response(response, content_type=content_type)

  File "/usr/lib/python3/dist-packages/acme/client.py", line 999, in _check_response
    raise messages.Error.from_json(jobj)

acme.messages.Error: urn:ietf:params:acme:error:rateLimited :: There were too many requests of a given type :: Error creating new account :: too many registrations for this IP https://letsencrypt.org/docs/rate-limits/
```

**Comment by evilaliv3** [comment]
For my understanding it is not clear why our implementation should be hitting this error.

It is true that the previous implementation was implementing a new account registration for each certificate renewal but anyway the renewal was performed once every month.

**Comment by evilaliv3** [comment]
@bmw @pde: what do you recommend to debug such an enconvenience?

Is there a raw log that a domain owner can download to get understanding of what could be wrong in the implementation?

thank you!

**Comment by bmw** [comment]
The rate limit you're hitting is one described in the paragraph:

> You can create a maximum of 10 Accounts per IP Address per 3 hours. You can create a maximum of 500 Accounts per IP Range within an IPv6 /48 per 3 hours. Hitting either account rate limit is very rare, and we recommend that large integrators prefer a design [using one account for many customers](https://letsencrypt.org/docs/integration-guide).

For ideas on how to resolve the issue:

1. Our `acme` library uses [Python's logging module](https://docs.python.org/3/library/logging.html). It doesn't output the logs anywhere itself, but it registers many messages in that module at the `DEBUG` level or higher. If you add a handler for Python's logging module to output these logs somewhere, they would be available for you to look at them to get more info about what our ACME module did.
2. You could make a post at https://community.letsencrypt.org. There is a large community there who can help with issues using Let's Encrypt as well as some people at Let's Encrypt itself who may be able to look into your specific problem for you. I can't promise the latter though.
3. Update your project to reuse the account between issuances. To do this, you have to save/reload both the account and its private key. The code in Certbot that does this can be seen at

* https://github.com/certbot/certbot/blob/e6bf3fe7f81ff7651b3e8be3d530be725090ed2c/certbot/account.py#L133
* https://github.com/certbot/certbot/blob/e6bf3fe7f81ff7651b3e8be3d530be725090ed2c/certbot/client.py#L44

Most of the code in the first link you wouldn't have to write. It's additional features/complexity in Certbot on top of simply saving/loading the account.

I hope that helps!

**Comment by evilaliv3** [comment]
@bmw: thank you!

Actually i've read the rule that you mention but a platform performs a single retry per day near the expiration deadline of the certificate. For this reason i do not undertand why a signle new registration could be hitting this failure.

**Comment by evilaliv3** [comment]
The is now solved in current implementation.
