### ISSUE TITLE
Confirmation of Activation following a EAT project signup gives an error

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#2657]
Note: The error does not seems to be "blocking" but it gives an error that will be surely reported by the partners

Platform: EAT Project
Host: platform.disclosers.eu (vpq54vflyskkdle4.onion)
Version: 3.9.11

sqlalchemy.exc.IntegrityError Wraps a DB-API IntegrityError.

Traceback (most recent call last):

  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1159, in _execute_context
    context)

  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/default.py", line 467, in do_executemany
    cursor.executemany(statement, parameters)

sqlite3.IntegrityError: UNIQUE constraint failed: config.tid, config.var_name

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "/usr/lib/python3/dist-packages/twisted/python/threadpool.py", line 250, in inContext
    result = inContext.theWork()

  File "/usr/lib/python3/dist-packages/twisted/python/threadpool.py", line 266, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)

  File "/usr/lib/python3/dist-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)

  File "/usr/lib/python3/dist-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)

  File "/usr/lib/python3/dist-packages/globaleaks/orm.py", line 117, in _wrap
    result = function(session, *args, **kwargs)

  File "/usr/lib/python3/dist-packages/globaleaks/handlers/signup.py", line 134, in signup_activation
    db_wizard(session, signup.tid, wizard, False, language)

  File "/usr/lib/python3/dist-packages/globaleaks/handlers/wizard.py", line 27, in db_wizard
    if node.get_val(u'wizard_done'):

  File "/usr/lib/python3/dist-packages/globaleaks/models/config.py", line 43, in get_val
    return self.get_cfg(var_name).value

  File "/usr/lib/python3/dist-packages/globaleaks/models/config.py", line 40, in get_cfg
    return self.session.query(Config).filter(Config.tid == self.tid, Config.var_name == var_name).one()

  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/query.py", line 2814, in one
    ret = self.one_or_none()

  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/query.py", line 2784, in one_or_none
    ret = list(self)

  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/query.py", line 2854, in __iter__
    self.session._autoflush()

  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/session.py", line 1407, in _autoflush
    util.raise_from_cause(e)

  File "/usr/lib/python3/dist-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)

  File "/usr/lib/python3/dist-packages/sqlalchemy/util/compat.py", line 187, in reraise
    raise value

  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/session.py", line 1397, in _autoflush
    self.flush()

  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/session.py", line 2171, in flush
    self._flush(objects)

  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/session.py", line 2291, in _flush
    transaction.rollback(_capture_exception=True)

  File "/usr/lib/python3/dist-packages/sqlalchemy/util/langhelpers.py", line 66, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)

  File "/usr/lib/python3/dist-packages/sqlalchemy/util/compat.py", line 187, in reraise
    raise value

  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/session.py", line 2255, in _flush
    flush_context.execute()

  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/unitofwork.py", line 389, in execute
    rec.execute(self)

  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/unitofwork.py", line 548, in execute
    uow

  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/persistence.py", line 181, in save_obj
    mapper, table, insert)

  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/persistence.py", line 799, in _emit_insert_statements
    execute(statement, multiparams)

  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 945, in execute
    return meth(self, multiparams, params)

  File "/usr/lib/python3/dist-packages/sqlalchemy/sql/elements.py", line 263, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)

  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1053, in _execute_clauseelement
    compiled_sql, distilled_params

  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1189, in _execute_context
    context)

  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1402, in _handle_dbapi_exception
    exc_info

  File "/usr/lib/python3/dist-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)

  File "/usr/lib/python3/dist-packages/sqlalchemy/util/compat.py", line 186, in reraise
    raise value.with_traceback(tb)

  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1159, in _execute_context
    context)

  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/default.py", line 467, in do_executemany
    cursor.executemany(statement, parameters)

sqlalchemy.exc.IntegrityError: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely) (sqlite3.IntegrityError) UNIQUE constraint failed: config.tid, config.var_name [SQL: 'INSERT INTO config (tid, var_name, value, update_date) VALUES (?, ?, ?, ?)'] [parameters: ((7, 'id', '"1e6c21a7-bf0f-484d-86ce-c9791699d009"', '1970-01-01 00:00:00.000000'), (7, 'creation_date', '1564503916', '1970-01-01 00:00:00.000000'), (7, 'receipt_salt', '"Atnum+uoI+izCta6hqvvWw=="', '1970-01-01 00:00:00.000000'), (7, 'version', '"3.9.11"', '1970-01-01 00:00:00.000000'), (7, 'version_db', '49', '1970-01-01 00:00:00.000000'), (7, 'latest_version', '"3.9.11"', '1970-01-01 00:00:00.000000'), (7, 'acme', 'false', '1970-01-01 00:00:00.000000'), (7, 'acme_accnt_key', '""', '1970-01-01 00:00:00.000000')  ... displaying 10 of 112 total bound parameter sets ...  (7, 'multisite', 'false', '1970-01-01 00:00:00.000000'), (7, 'adminonly', 'false', '1970-01-01 00:00:00.000000'))]

**Comment by fpietrosanti** [comment]
Possible to reproduce it by following this procedure on Mozilla Firefox, on Mac Os X, using my own Hermes Center email. Reproduced 3 times consecutively.
<img width="1107" alt="Screen Shot 2019-07-30 at 18 33 29" src="https://user-images.githubusercontent.com/770363/62149980-33615e80-b2fd-11e9-8d19-0645669984d2.png">
<img width="614" alt="Screen Shot 2019-07-30 at 18 33 22" src="https://user-images.githubusercontent.com/770363/62149981-33615e80-b2fd-11e9-81f6-cace3fa7a49a.png">
<img width="769" alt="Screen Shot 2019-07-30 at 18 33 06" src="https://user-images.githubusercontent.com/770363/62149982-33615e80-b2fd-11e9-956a-9ed88110c2fc.png">
<img width="851" alt="Screen Shot 2019-07-30 at 18 33 01" src="https://user-images.githubusercontent.com/770363/62149983-33615e80-b2fd-11e9-9bad-369f0ca374b1.png">
