### ISSUE TITLE
Unhandled exception in self.request.headers[b"authorization"].split()

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#2711]
Platform: anticorruzione
Host: anticorruzione.
Version: 3.11.27

ValueError Inappropriate argument value (of correct type).

Traceback (most recent call last):

  File "/usr/lib/python3/dist-packages/twisted/internet/defer.py", line 150, in maybeDeferred
    result = f(*args, **kw)

  File "/usr/lib/python3/dist-packages/globaleaks/rest/decorators.py", line 14, in wrapper
    self.basic_auth()

  File "/usr/lib/python3/dist-packages/globaleaks/handlers/base.py", line 69, in basic_auth
    auth_type, data = self.request.headers[b"authorization"].split()

ValueError: not enough values to unpack (expected 2, got 1)

**Comment by evilaliv3** [comment]
I wonder what to do in this case;

fixing with an other try/catch just logging and silently stopping the processing  would be not that much different of the current status.

Will try to see in twisted what other partns are followed for typical parsing.

**Comment by evilaliv3** [comment]
Closing as outdated.
