### ISSUE TITLE
Unhandled exception in  request.client_mobile = re.match(b'Mobi|Android', request.client_ua, re.IGNORECASE) is not None

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#2717]
Platform: try.globaleaks.org
Host: try.globaleaks.org (xu5vj5wlucy46qropyeunoh5osaipichqs4yf2h4a3ew325juww5sdad.onion)
Version: 3.11.30

TypeError Inappropriate argument type.

Traceback (most recent call last):

  File "/usr/lib/python3/dist-packages/twisted/web/server.py", line 199, in process
    self.render(resrc)

  File "/usr/lib/python3/dist-packages/twisted/web/server.py", line 259, in render
    body = resrc.render(self)

  File "/usr/lib/python3/dist-packages/globaleaks/rest/api.py", line 349, in render
    self.preprocess(request)

  File "/usr/lib/python3/dist-packages/globaleaks/rest/api.py", line 330, in preprocess
    request.client_mobile = re.match(b'Mobi|Android', request.client_ua, re.IGNORECASE) is not None

  File "/usr/lib/python3.7/re.py", line 173, in match
    return _compile(pattern, flags).match(string)

TypeError: cannot use a bytes pattern on a string-like object

**Comment by evilaliv3** [comment]
Bug confirmed and fixed; It was happening when the request was not including a user agent.
