### ISSUE TITLE
Unhandled exception in tor_exit_set.py "   for ip in re.findall(r'ExitAddress ([^ ]*) ', data):"

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#2756]
Platform: 
Host:  
Version: 3.11.56

TypeError Inappropriate argument type.

Traceback (most recent call last):

  File "/usr/lib/python3/dist-packages/globaleaks/jobs/job.py", line 49, in run
    yield self.operation()

  File "/usr/lib/python3/dist-packages/twisted/internet/defer.py", line 1384, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)

  File "/usr/lib/python3/dist-packages/twisted/python/failure.py", line 408, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)

  File "/usr/lib/python3/dist-packages/globaleaks/jobs/exit_nodes_refresh.py", line 18, in operation
    yield State.tor_exit_set.update(net_agent)

  File "/usr/lib/python3/dist-packages/twisted/internet/defer.py", line 653, in _runCallbacks
    current.result = callback(current.result, *args, **kw)

  File "/usr/lib/python3/dist-packages/globaleaks/utils/tor_exit_set.py", line 16, in processData
    for ip in re.findall(r'ExitAddress ([^ ]*) ', data):

  File "/usr/lib/python3.6/re.py", line 222, in findall
    return _compile(pattern, flags).findall(string)

TypeError: cannot use a string pattern on a bytes-like object

**Comment by evilaliv3** [comment]
This bug has been introduced in commit b23950768b and affects the detection of Tor users.

**Comment by evilaliv3** [comment]
Fix released in version 3.11.57
