### ISSUE TITLE
Error when trying to import questionnaire 

### ISSUE THREAD

**Issue by elbill** [globaleaks/GlobaLeaks#2760]
I have two installations that behave quite differently. My test installation can import and export questionnaires, however teh operational can not import questionnaires whatsoever. I think it can import only questionaires that have been exported by itself.

The two installations are completely different and live on different VMs with identical parameters.
and version 3.11.62.

In the primary installation I never managed to import questionnaires. 
I have reported issue #2421 and was attributed to question templates bug.
However this time there are no question templates. 

try.glopableaks.org instance can also import the questionnaire
I'm attaching the questionnaire and the output
I received the following error log by email

Version: 3.11.62

sqlalchemy.exc.IntegrityError Wraps a DB-API IntegrityError.

Traceback (most recent call last):

  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
    context)

  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/default.py", line 470, in do_execute
    cursor.execute(statement, parameters)

sqlite3.IntegrityError: UNIQUE constraint failed: questionnaire.id

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "/usr/lib/python3/dist-packages/twisted/python/threadpool.py", line 250, in inContext
    result = inContext.theWork()

  File "/usr/lib/python3/dist-packages/twisted/python/threadpool.py", line 266, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)

  File "/usr/lib/python3/dist-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)

  File "/usr/lib/python3/dist-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)

  File "/usr/lib/python3/dist-packages/globaleaks/orm.py", line 108, in _wrap
    result = function(session, *args, **kwargs)

  File "/usr/lib/python3/dist-packages/globaleaks/handlers/admin/questionnaire.py", line 87, in create_questionnaire
    questionnaire = db_create_questionnaire(session, tid, request, language)

  File "/usr/lib/python3/dist-packages/globaleaks/handlers/admin/questionnaire.py", line 67, in db_create_questionnaire
    q = models.db_forge_obj(session, models.Questionnaire, questionnaire_dict)

  File "/usr/lib/python3/dist-packages/globaleaks/models/__init__.py", line 18, in db_forge_obj
    session.flush()

  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/session.py", line 2171, in flush
    self._flush(objects)

  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/session.py", line 2291, in _flush
    transaction.rollback(_capture_exception=True)

  File "/usr/lib/python3/dist-packages/sqlalchemy/util/langhelpers.py", line 66, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)

  File "/usr/lib/python3/dist-packages/sqlalchemy/util/compat.py", line 187, in reraise
    raise value

  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/session.py", line 2255, in _flush
    flush_context.execute()

  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/unitofwork.py", line 389, in execute
    rec.execute(self)

  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/unitofwork.py", line 548, in execute
    uow

  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/persistence.py", line 181, in save_obj
    mapper, table, insert)

  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/persistence.py", line 799, in _emit_insert_statements
    execute(statement, multiparams)

  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 945, in execute
    return meth(self, multiparams, params)

  File "/usr/lib/python3/dist-packages/sqlalchemy/sql/elements.py", line 263, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)

  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1053, in _execute_clauseelement
    compiled_sql, distilled_params

  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1189, in _execute_context
    context)

  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1402, in _handle_dbapi_exception
    exc_info

  File "/usr/lib/python3/dist-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)

  File "/usr/lib/python3/dist-packages/sqlalchemy/util/compat.py", line 186, in reraise
    raise value.with_traceback(tb)

  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
    context)

  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/default.py", line 470, in do_execute
    cursor.execute(statement, parameters)

sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) UNIQUE constraint failed: questionnaire.id [SQL: 'INSERT INTO questionnaire (id, tid, name, enable_whistleblower_identity, editable) VALUES (?, ?, ?, ?, ?)'] [parameters: ('92d8b5a8-f0ea-4993-b3bb-095d844d6751', 7, 'gifts', 0, 1)]

[gifts.zip](https://github.com/globaleaks/GlobaLeaks/files/4053911/gifts.zip)
![test1 - Home - Google Chrome 1_13_2020 3_54_17 PM](https://user-images.githubusercontent.com/23246886/72261794-34254d00-361e-11ea-977a-e8c7c5678816.png)

**Current behavior**

**Expected behavior**

**Steps to reproduce the problem or feature illustration**

**What is the motivation or use case for changing the behavior?**

**GlobaLeaks version:**

**Browser:**

**Server Operating System and Version (if applicable):**
 

**Client Operating System and Version (if applicable):**

**Comment by evilaliv3** [comment]
@elbill: I think you are importing a questionnaire on a secondary tenant and that questionnaire is already imported in an other tenant or in the root tenant. This results currently in a conflict for duplication.

To go around this current bug:
- log in the original tenant that contains the questionnaire
- dublicate the questioonanire with the correspoding duplicate function
- export the questionnaire
- delete the questionnaire
- log on the tentant where you want to load the questionnaire

Please let me know if this is the case and the above instructions solve your situation

Giovanni

**Comment by elbill** [comment]
@evilaliv3 it worked fine!
Thanks
