### ISSUE TITLE
TypeError: sequence item 0: expected str instance, bytes found from notification job

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#2761]
Platform:  
Host: 
Version: 3.11.55

TypeError Inappropriate argument type.

Traceback (most recent call last):

  File "/usr/lib/python3/dist-packages/globaleaks/jobs/job.py", line 49, in run
    yield self.operation()

  File "/usr/lib/python3/dist-packages/twisted/internet/defer.py", line 1384, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)

  File "/usr/lib/python3/dist-packages/twisted/python/failure.py", line 408, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)

  File "/usr/lib/python3/dist-packages/globaleaks/jobs/notification.py", line 298, in operation
    yield self.spool_emails()

  File "/usr/lib/python3/dist-packages/twisted/internet/defer.py", line 1384, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)

  File "/usr/lib/python3/dist-packages/twisted/python/failure.py", line 408, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)

  File "/usr/lib/python3/dist-packages/globaleaks/jobs/notification.py", line 287, in spool_emails
    yield self.sendmail(mail)

  File "/usr/lib/python3/dist-packages/twisted/internet/defer.py", line 1384, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)

  File "/usr/lib/python3/dist-packages/twisted/python/failure.py", line 408, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)

  File "/usr/lib/python3/dist-packages/globaleaks/jobs/notification.py", line 279, in sendmail
    success = yield self.state.sendmail(mail['tid'], mail['address'], mail['subject'], mail['body'])

  File "/usr/lib/python3/dist-packages/twisted/internet/defer.py", line 653, in _runCallbacks
    current.result = callback(current.result, *args, **kw)

  File "/usr/lib/python3/dist-packages/globaleaks/utils/mail.py", line 116, in failure_cb
    failure.value.subFailure.value, tid=tid)

  File "/usr/lib/python3/dist-packages/globaleaks/utils/log.py", line 135, in err
    self._print_logline('E', msg, *args, **kwargs)

  File "/usr/lib/python3/dist-packages/globaleaks/utils/log.py", line 116, in _print_logline
    msg = (msg % args) if args else msg

  File "/usr/lib/python3/dist-packages/twisted/internet/error.py", line 77, in __str__
    s = '%s: %s' % (s, ' '.join(self.args))

TypeError: sequence item 0: expected str instance, bytes found

**Comment by evilaliv3** [comment]
This has been probably already fixed in a more updated release.

**Comment by evilaliv3** [comment]
Closing as outdated
