### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'writeHeaders'

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#2762]
Platform: WhistleblowingPA
Host: registrazione.whistleblowing.it (qpaszzjw5hmgajdu.onion)
Version: 3.11.36

AttributeError Attribute not found.

Traceback (most recent call last):

  File "/usr/lib/python3/dist-packages/twisted/internet/defer.py", line 1384, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)

  File "/usr/lib/python3/dist-packages/twisted/python/failure.py", line 408, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)

  File "/usr/lib/python3/dist-packages/globaleaks/handlers/authentication.py", line 181, in post
    self.request.client_ip)

  File "/usr/lib/python3/dist-packages/twisted/python/threadpool.py", line 250, in inContext
    result = inContext.theWork()

  File "/usr/lib/python3/dist-packages/twisted/python/threadpool.py", line 266, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)

  File "/usr/lib/python3/dist-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)

  File "/usr/lib/python3/dist-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)

  File "/usr/lib/python3/dist-packages/globaleaks/orm.py", line 117, in _wrap
    result = function(session, *args, **kwargs)

  File "/usr/lib/python3/dist-packages/globaleaks/handlers/authentication.py", line 125, in login
    raise errors.InvalidAuthentication

globaleaks.rest.errors.InvalidAuthentication: InvalidAuthentication: <<Authentication Failed>> (9) HTTP:401

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/usr/lib/python3/dist-packages/twisted/internet/defer.py", line 1386, in _inlineCallbacks
    result = g.send(result)

  File "/usr/lib/python3/dist-packages/globaleaks/rest/api.py", line 415, in concludeHandlerFailure
    self.handle_exception(err, request)

  File "/usr/lib/python3/dist-packages/globaleaks/rest/api.py", line 282, in handle_exception
    request.write(response.encode())

  File "/usr/lib/python3/dist-packages/twisted/web/server.py", line 234, in write
    http.Request.write(self, data)

  File "/usr/lib/python3/dist-packages/twisted/web/http.py", line 1069, in write
    self.channel.writeHeaders(version, code, reason, headers)

AttributeError: 'NoneType' object has no attribute 'writeHeaders'

**Comment by evilaliv3** [comment]
By the current release the bug should be solved.
