### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'registerProducer'

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#2768]
Platform: WhistleblowingPA
Host: registrazione.whistleblowing.it (qpaszzjw5hmgajdu.onion)
Version: 3.11.36

AttributeError Attribute not found.

Traceback (most recent call last):

  File "/usr/lib/python3/dist-packages/twisted/internet/defer.py", line 1386, in _inlineCallbacks
    result = g.send(result)

  File "/usr/lib/python3/dist-packages/globaleaks/handlers/file.py", line 55, in get
    yield self.write_file(name, path)

  File "/usr/lib/python3/dist-packages/globaleaks/handlers/base.py", line 270, in write_file
    return self.write_file_fo(filename, fo)

  File "/usr/lib/python3/dist-packages/globaleaks/handlers/base.py", line 266, in write_file_fo
    return serve_file(self.request, fo)

  File "/usr/lib/python3/dist-packages/globaleaks/handlers/base.py", line 39, in serve_file
    filesender = FileSender().beginFileTransfer(fo, request)

  File "/usr/lib/python3/dist-packages/twisted/protocols/basic.py", line 922, in beginFileTransfer
    self.consumer.registerProducer(self, False)

  File "/usr/lib/python3/dist-packages/twisted/web/http.py", line 907, in registerProducer
    self.channel.registerProducer(producer, streaming)

AttributeError: 'NoneType' object has no attribute 'registerProducer'

**Comment by evilaliv3** [comment]
Closing as duplicated: https://github.com/globaleaks/GlobaLeaks/issues/2425

**Comment by evilaliv3** [comment]
Reopening as actually only partially related with #2425
