### ISSUE TITLE
Globaleaks 3.11.69 fresh install fail to start 

### ISSUE THREAD

**Issue by zazzati** [globaleaks/GlobaLeaks#2769]
**Current behavior**
Globaleaks 3.11.69 fresh install fail to start 

**Expected behavior**
Globaleaks 3.11.69 that start !

**What is the motivation or use case for changing the behavior?**

**GlobaLeaks version:**
GlobaLeaks version: 3.11.69
Database version: 51
fresh install 

**Server Operating System and Version (if applicable):**
Ubuntu 18.04.4 LTS (GNU/Linux 4.15.0-46-generic x86_64)
fresh install 

**Log after install**
```
Running: "/etc/init.d/globaleaks stop"... SUCCESS
Running: "apt-get -y update"... SUCCESS
 + curl requirement met
 + netstat requirement met
Running: "is_tcp_sock_free_check 0.0.0.0:80"... SUCCESS
Running: "is_tcp_sock_free_check 0.0.0.0:443"... SUCCESS
Running: "is_tcp_sock_free_check 127.0.0.1:8082"... SUCCESS
Running: "is_tcp_sock_free_check 127.0.0.1:8083"... SUCCESS
 + required TCP sockets open
Adding GlobaLeaks PGP key to trusted APT keys
Running: "apt-key add /tmp/tmp.J2bFzBoSg7/globaleaks_key"... SUCCESS
Running: "rm /tmp/tmp.J2bFzBoSg7/globaleaks_key"... SUCCESS
Installing software-properties-common
Running: "apt-get -y install software-properties-common"... SUCCESS
Updating GlobaLeaks apt source.list in /etc/apt/sources.list.d/globaleaks.list .                                                                                        ..
Running: "apt-get update -y"... SUCCESS
Running: "apt-get install globaleaks -y"... SUCCESS
Ouch! The installation is complete but GlobaLeaks failed to start.
```

**service globaleaks status**
```
● globaleaks.service - LSB: Start the GlobaLeaks server.
   Loaded: loaded (/etc/init.d/globaleaks; generated)
   Active: active (exited) since Thu 2020-02-13 15:39:29 CET; 3min 31s ago
     Docs: man:systemd-sysv-generator(8)
    Tasks: 0 (limit: 2347)
   CGroup: /system.slice/globaleaks.service

Feb 13 15:39:26 dev-webfarm-leaks01-devweb.site02.domain.it systemd[1]:
Feb 13 15:39:26 dev-webfarm-leaks01-devweb.site02.domain.it globaleaks[2
Feb 13 15:39:28 dev-webfarm-leaks01-devweb.site02.domain.it globaleaks[2
Feb 13 15:39:28 dev-webfarm-leaks01-devweb.site02.domain.it globaleaks[2
Feb 13 15:39:28 dev-webfarm-leaks01-devweb.site02.domain.it globaleaks[2
Feb 13 15:39:28 dev-webfarm-leaks01-devweb.site02.domain.it globaleaks[2
Feb 13 15:39:28 dev-webfarm-leaks01-devweb.site02.domain.it globaleaks[2
Feb 13 15:39:29 dev-webfarm-leaks01-devweb.site02.domain.it globaleaks[2
Feb 13 15:39:29 dev-webfarm-leaks01-devweb.site02.domain.it systemd[1]:
```

**globaleaks.log**

```
2020-02-13 15:43:25+0100 [-] [E] Exception while running OnionService
2020-02-13 15:43:25+0100 [-] Traceback (most recent call last):
2020-02-13 15:43:25+0100 [-]   File "/usr/lib/python3/dist-packages/globaleaks/services/service.py", line 25, in run
2020-02-13 15:43:25+0100 [-]     yield self.operation()
2020-02-13 15:43:25+0100 [-] twisted.internet.error.ConnectionLost: Connection to the other side was lost in a non-clean fashion: Connection lost.
2020-02-13 15:43:25+0100 [-] [E] Unhandled exception raised:
2020-02-13 15:43:25+0100 [-] [E] twisted.internet.error.ConnectionLost Connection to the other side was lost in a non-clean fashion\n\nTraceback (most recent call last):\n\n  File "/usr/lib/python3/dist-packages/globaleaks/services/service.py", line 25, in run\n    yield self.operation()\n\ntwisted.internet.error.ConnectionLost: Connection to the other side was lost in a non-clean fashion: Connection lost.\n
2020-02-13 15:43:25+0100 [-] Stopping factory <Site object at 0x7f32d81bcf98>
2020-02-13 15:43:25+0100 [-] Server Shut Down.
```

**Comment by evilaliv3** [comment]
Thank you for reporting this @zazzati 

Will try a fresh install and check it out.

do you have by any chance any error in dmesg? (e.g in relation to apparmor)

If i may suggest for new setups best recommended distribution is Debian Buster (but Bionic is a good choice anyway)

**Comment by evilaliv3** [comment]
@zazzati: I just runned a test installing on a fresh vps on Scaleway and all seems to work fine.

Please le me know if you notice any error inside the dmesg log.

**Comment by Hartick** [comment]
I tried to install GL in a Debian 10 VPS.

access.log

**Comment by zazzati** [comment]
> @zazzati: I just runned a test installing on a fresh vps on Scaleway and all seems to work fine.
> 
> Please le me know if you notice any error inside the dmesg log.

```
+SECCOMP +BLKID +ELFUTILS +KMOD -IDN2 +IDN -PCRE2 default-hierarchy=hybrid)
[ 6721.100734] systemd[1]: Detected virtualization kvm.
[ 6721.100739] systemd[1]: Detected architecture x86-64.
[ 6721.489690] systemd[1]: Stopping Journal Service...
[ 6721.492548] systemd-journald[565]: Received SIGTERM from PID 1 (systemd).
[ 6721.502239] systemd[1]: Started Hostname Service.
[ 6721.513283] systemd[1]: Stopped Journal Service.
[ 6721.515171] systemd[1]: Starting Journal Service...
[ 6721.539653] systemd[1]: Started Journal Service.
[ 6848.473189] audit: type=1400 audit(1581604388.974:23): apparmor="STATUS" operation="profile_replace" info="same as current profile, skipping" profile="unconfined" name="/usr/sbin/tcpdump" pid=29882 comm="apparmor_parser"
[ 6850.279538] audit: type=1400 audit(1581604390.778:24): apparmor="STATUS" operation="profile_replace" profile="unconfined" name="/usr/lib/snapd/snap-confine" pid=29962 comm="apparmor_parser"
[ 6850.280839] audit: type=1400 audit(1581604390.782:25): apparmor="STATUS" operation="profile_replace" info="same as current profile, skipping" profile="unconfined" name="/usr/lib/snapd/snap-confine//mount-namespace-capture-helper" pid=29962 comm="apparmor_parser"
[ 6876.493308] audit: type=1400 audit(1581604416.994:26): apparmor="STATUS" operation="profile_replace" info="same as current profile, skipping" profile="unconfined" name="/sbin/dhclient" pid=31765 comm="apparmor_parser"
[ 6876.495020] audit: type=1400 audit(1581604416.994:27): apparmor="STATUS" operation="profile_replace" info="same as current profile, skipping" profile="unconfined" name="/usr/lib/NetworkManager/nm-dhcp-client.action" pid=31765 comm="apparmor_parser"
[ 6876.495668] audit: type=1400 audit(1581604416.994:28): apparmor="STATUS" operation="profile_replace" info="same as current profile, skipping" profile="unconfined" name="/usr/lib/NetworkManager/nm-dhcp-helper" pid=31765 comm="apparmor_parser"
[ 6876.497338] audit: type=1400 audit(1581604416.998:29): apparmor="STATUS" operation="profile_replace" info="same as current profile, skipping" profile="unconfined" name="/usr/lib/connman/scripts/dhclient-script" pid=31765 comm="apparmor_parser"
[ 7224.706182] audit: type=1400 audit(1581604765.208:30): apparmor="STATUS" operation="profile_replace" info="same as current profile, skipping" profile="unconfined" name="usr.bin.globaleaks" pid=20537 comm="apparmor_parser"
[ 7226.632788] audit: type=1400 audit(1581604767.132:31): apparmor="DENIED" operation="exec" profile="usr.bin.globaleaks" name="/bin/dash" pid=20678 comm="globaleaks" requested_mask="x" denied_mask="x" fsuid=0 ouid=0
[ 7228.453431] audit: type=1400 audit(1581604768.956:32): apparmor="DENIED" operation="open" profile="usr.bin.globaleaks" name="/usr/local/lib/python3.6/dist-packages/pkg_resources/" pid=20668 comm="globaleaks" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
[ 7683.150438] audit: type=1400 audit(1581605223.656:33): apparmor="DENIED" operation="exec" profile="usr.bin.globaleaks" name="/bin/dash" pid=21376 comm="globaleaks" requested_mask="x" denied_mask="x" fsuid=0 ouid=0
[ 7683.687980] audit: type=1400 audit(1581605224.192:34): apparmor="DENIED" operation="open" profile="usr.bin.globaleaks" name="/usr/local/lib/python3.6/dist-packages/pkg_resources/" pid=21365 comm="globaleaks" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
[ 9940.566990] audit: type=1400 audit(1581607481.088:35): apparmor="DENIED" operation="exec" profile="usr.bin.globaleaks" name="/bin/dash" pid=21936 comm="globaleaks" requested_mask="x" denied_mask="x" fsuid=0 ouid=0
[ 9941.073871] audit: type=1400 audit(1581607481.596:36): apparmor="DENIED" operation="open" profile="usr.bin.globaleaks" name="/usr/local/lib/python3.6/dist-packages/pkg_resources/" pid=21925 comm="globaleaks" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
```

**Comment by zazzati** [comment]
> Please le me know if you notice any error inside the dmesg log.

@evilaliv3 
3rd attempt, on hetzner , globaleaks works ok
http://94.130.148.152/#/wizard 

But... our  working test/production enterprise installation, done by my on Ubuntu LTS and my coworker @Hartick on Debian 10, are behind enterprise  http/https proxy. 

Older release og Globaleaks works correcty under our proxy... may be newer release 
new versions have problems behind http/https proxy  ?

thanks

**Comment by evilaliv3** [comment]
@zazzati: would It be possible for you to give me ssh access to one of your development setup behind a proxy? I may try to identify the bug and fix It into the software. You can write me credentials with a PGP encrypted email at giovanni.pellerano@evilaliv3.org or reach me on our slack channel at https://slack.globaleaks.org

**Comment by evilaliv3** [comment]
Closing as the issue was solved with the user; bug related to the specific user setup.
