### ISSUE TITLE
Bug in cert_expiration_checks

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#2778]
Platform:  
Host:  
Version: 3.10.4

OpenSSL.crypto.Error 
    An error occurred in an `OpenSSL.crypto` API.
    

Traceback (most recent call last):

  File "/usr/lib/python2.7/dist-packages/globaleaks/jobs/job.py", line 49, in run
    yield self.operation()

  File "/usr/lib/python2.7/dist-packages/twisted/python/threadpool.py", line 246, in inContext
    result = inContext.theWork()

  File "/usr/lib/python2.7/dist-packages/twisted/python/threadpool.py", line 262, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)

  File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)

  File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 81, in callWithContext
    return func(*args,**kw)

  File "/usr/lib/python2.7/dist-packages/globaleaks/orm.py", line 115, in _wrap
    result = function(self.instance, session, *args, **kwargs)

  File "/usr/lib/python2.7/dist-packages/globaleaks/jobs/certificate_check.py", line 43, in check_tenants_for_cert_expiration
    self.cert_expiration_checks(session, tenant[0])

  File "/usr/lib/python2.7/dist-packages/globaleaks/jobs/certificate_check.py", line 51, in cert_expiration_checks
    cert = load_certificate(FILETYPE_PEM, priv_fact.get_val(u'https_cert'))

  File "/usr/lib/python2.7/dist-packages/OpenSSL/crypto.py", line 1541, in load_certificate
    _raise_current_error()

  File "/usr/lib/python2.7/dist-packages/OpenSSL/_util.py", line 48, in exception_from_error_queue
    raise exception_type(errors)

Error: [('PEM routines', 'PEM_read_bio', 'no start line')]

**Comment by evilaliv3** [comment]
Closing as probably outdated.
