### ISSUE TITLE
Identity template filling error - Identity not shown 

### ISSUE THREAD

**Issue by larrykind** [globaleaks/GlobaLeaks#2810]
**Current behavior**

1. Whistleblower Identity is never visible to the receiver. Receiver sees every record as anonymous. 
2. In case of anonymous record, filling identity template form (default or customized) by accessing with ticket-id in a later time thows an error (Exception Unhandled). From the globaleaks.log file:

`2020-04-08 13:32:16+0200 [-] [E] Unhandled exception raised:
2020-04-08 13:32:16+0200 [-] [E] NameError Name not found globally.\n\nTraceback (most recent call last):\n\n  File "/usr/lib/python3/dist-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks\n    result = result.throwExceptionIntoGenerator(g)\n\n  File "/usr/lib/python3/dist-packages/twisted/python/failure.py", line 491, in throwExceptionIntoGenerator\n    return g.throw(self.type, self.value, self.tb)\n\n  File "/usr/lib/python3/dist-packages/globaleaks/handlers/wbtip.py", line 190, in get\n    tip = yield deferToThread(decrypt_tip, self.current_user.cc, crypto_tip_prv_key, tip)\n\n  File "/usr/lib/python3/dist-packages/twisted/python/threadpool.py", line 250, in inContext\n    result = inContext.theWork()\n\n  File "/usr/lib/python3/dist-packages/twisted/python/threadpool.py", line 266, in <lambda>\n    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)\n\n  File "/usr/lib/python3/dist-packages/twisted/python/context.py", line 122, in callWithContext\n    return self.currentContext().callWithContext(ctx, func, *args, **kw)\n\n  File "/usr/lib/python3/dist-packages/twisted/python/context.py", line 85, in callWithContext\n    return func(*args,**kw)\n\n  File "/usr/lib/python3/dist-packages/globaleaks/handlers/submission.py", line 33, in decrypt_tip\n    ret['data']['whistleblower_identity_provided'] = True\n\nNameError: name 'ret' is not defined\n`

**Expected behavior**

1. Receiver should see the whistleblower identity
2. Identity form shoud be filled without errors from the whistleblower who accesses to his record with ticket-id

**Steps to reproduce the problem or feature illustration**

1.1. Insert a record on a questionnaire with default identity template or a customized one
1.1 When on identity step, fill the form
1.3 Save the ticket
1.4 Access as a receiver user: ticket is shown as anonymous

2.1. Insert a record on a questionnaire with default identity template or a customized one
2.2. When on identity step, choose to not provide identity
2.3. Access the ticket just created with ticket-id released by the system
2.4. Fill identity form and save --> ERROR
2.5 Access as a receiver user: ticket is shown as anonymous

**What is the motivation or use case for changing the behavior?**

**GlobaLeaks version:**

v4.0.9

**Browser:**

Firefox 74.0.1, Chrome 80.0.3987.163

**Server Operating System and Version (if applicable):**
 
Debian 10.3 buster

**Client Operating System and Version (if applicable):**

Windows 7

**Comment by evilaliv3** [comment]
Thank you for notifying this @larrykind.

I'm already retesting this possible regression to see if i can put a fix in next 4.0.10

**Comment by evilaliv3** [comment]
Fixed @larrykind !

I'm about to include this patch in the release 4.0.10 that will be issued by today. Thank you again!

**Comment by larrykind** [comment]
Hi, 
I'm testing v4.0.10, point 1 of this issue is not fixed in this release. Every record is shown as anonymous to the receiver.
