### ISSUE TITLE
Exception on fieldattr model while moving questions up/down/right/left

### ISSUE THREAD

**Issue by globalnovo-it** [globaleaks/GlobaLeaks#2814]
Hi,
when i try to move a question using the arrows near the questions i received "server error" and after refresh the question not move from original destination 
Follow the exception:

`Version: 4.0.11

sqlalchemy.exc.IntegrityError Wraps a DB-API IntegrityError.

Traceback (most recent call last):

  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
    context)

  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/default.py", line 470, in do_execute
    cursor.execute(statement, parameters)

sqlite3.IntegrityError: UNIQUE constraint failed: fieldattr.id

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "/usr/lib/python3/dist-packages/twisted/python/threadpool.py", line 250, in inContext
    result = inContext.theWork()

  File "/usr/lib/python3/dist-packages/twisted/python/threadpool.py", line 266, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)

  File "/usr/lib/python3/dist-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)

  File "/usr/lib/python3/dist-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)

  File "/usr/lib/python3/dist-packages/globaleaks/orm.py", line 109, in _wrap
    result = function(session, *args, **kwargs)

  File "/usr/lib/python3/dist-packages/globaleaks/handlers/admin/field.py", line 326, in update_field
    field = db_update_field(session, tid, field_id, field, language)

  File "/usr/lib/python3/dist-packages/globaleaks/handlers/admin/field.py", line 286, in db_update_field
    db_update_fieldattrs(session, field.id, request['attrs'], language)

  File "/usr/lib/python3/dist-packages/globaleaks/handlers/admin/field.py", line 144, in db_update_fieldattrs
    attrs_ids = [db_update_fieldattr(session, field_id, attr_name, attr, language) for attr_name, attr in field_attrs.items()]

  File "/usr/lib/python3/dist-packages/globaleaks/handlers/admin/field.py", line 144, in <listcomp>
    attrs_ids = [db_update_fieldattr(session, field_id, attr_name, attr, language) for attr_name, attr in field_attrs.items()]

  File "/usr/lib/python3/dist-packages/globaleaks/handlers/admin/field.py", line 125, in db_update_fieldattr
    o = session.query(models.FieldAttr).filter(models.FieldAttr.field_id == field_id, models.FieldAttr.name == attr_name).one_or_none()

  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/query.py", line 2784, in one_or_none
    ret = list(self)

  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/query.py", line 2854, in __iter__
    self.session._autoflush()

  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/session.py", line 1407, in _autoflush
    util.raise_from_cause(e)

  File "/usr/lib/python3/dist-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)

  File "/usr/lib/python3/dist-packages/sqlalchemy/util/compat.py", line 187, in reraise
    raise value

  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/session.py", line 1397, in _autoflush
    self.flush()

  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/session.py", line 2171, in flush
    self._flush(objects)

  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/session.py", line 2291, in _flush
    transaction.rollback(_capture_exception=True)

  File "/usr/lib/python3/dist-packages/sqlalchemy/util/langhelpers.py", line 66, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)

  File "/usr/lib/python3/dist-packages/sqlalchemy/util/compat.py", line 187, in reraise
    raise value

  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/session.py", line 2255, in _flush
    flush_context.execute()

  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/unitofwork.py", line 389, in execute
    rec.execute(self)

  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/unitofwork.py", line 548, in execute
    uow

  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/persistence.py", line 177, in save_obj
    mapper, table, update)

  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/persistence.py", line 737, in _emit_update_statements
    execute(statement, multiparams)

  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 945, in execute
    return meth(self, multiparams, params)

  File "/usr/lib/python3/dist-packages/sqlalchemy/sql/elements.py", line 263, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)

  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1053, in _execute_clauseelement
    compiled_sql, distilled_params

  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1189, in _execute_context
    context)

  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1402, in _handle_dbapi_exception
    exc_info

  File "/usr/lib/python3/dist-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)

  File "/usr/lib/python3/dist-packages/sqlalchemy/util/compat.py", line 186, in reraise
    raise value.with_traceback(tb)

  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
    context)

  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/default.py", line 470, in do_execute
    cursor.execute(statement, parameters)

sqlalchemy.exc.IntegrityError: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely) (sqlite3.IntegrityError) UNIQUE constraint failed: fieldattr.id [SQL: 'UPDATE fieldattr SET id=? WHERE fieldattr.id = ?'] [parameters: ('0f827c06-3d54-4ca0-8adf-df9d046164a7', '4f37c36c-615a-46ab-b3dd-2d69c2c78b4f')]
`

GlobaLeaks version: 4.0.11
Browser:Chrome 80

Server Operating System: Ubuntu(18.04)

Client Windows 10 

Italian language

**Comment by evilaliv3** [comment]
Thank you for reporting this @globalnovo-it 

I just tried to replicate your issue with your success.

Would you please try to understand which is the peculiarity in your questionnaire and or provide us a copy of it? We invite you to join us on our slack channel: https://slack.globaleaks.org

**Comment by globalnovo-it** [comment]
I try to move template question inside a group of questions.
Where I can send the copy, on git or via slack?
Thanks

**Comment by evilaliv3** [comment]
It would be perfect also via slack, thank you.

**Comment by evilaliv3** [comment]
Issue fixed and patch included in release 4.0.12

Thank you again @globalnovo-it
