### ISSUE TITLE
Error when trying to export submission

### ISSUE THREAD

**Issue by elbill** [globaleaks/GlobaLeaks#2896]
**Current behavior**
Getting error message when trying to export submission. 
I believe this has to do with date type of question. When not filled in seems to work fine.

**Expected behavior**
I would expect to be able to export the submission 

**Steps to reproduce the problem or feature illustration**

**Exception error:**

AttributeError Attribute not found.

Traceback (most recent call last):

  File "/usr/lib/python3/dist-packages/twisted/internet/defer.py", line 1386, in _inlineCallbacks
    result = g.send(result)

  File "/usr/lib/python3/dist-packages/globaleaks/handlers/export.py", line 127, in get
    export_template = Templating().format_template(tip_export['notification']['export_template'], tip_export).encode()

  File "/usr/lib/python3/dist-packages/globaleaks/utils/templating.py", line 724, in format_template
    variable_content = getattr(keyword_converter, kw[1:-1])()

  File "/usr/lib/python3/dist-packages/globaleaks/utils/templating.py", line 352, in QuestionnaireAnswers
    return self.dump_questionnaire_answers(self.data['tip']['questionnaires'][0]['steps'], self.data['tip']['questionnaires'][0]['answers'])

  File "/usr/lib/python3/dist-packages/globaleaks/utils/templating.py", line 298, in dump_questionnaire_answers
    output = self.dump_fields(output, step['children'], answers, 1) + '\n'

  File "/usr/lib/python3/dist-packages/globaleaks/utils/templating.py", line 281, in dump_fields
    output = self.dump_field_entry(output, field, entries[0], indent_n + 1)

  File "/usr/lib/python3/dist-packages/globaleaks/utils/templating.py", line 246, in dump_field_entry
    output += indent(indent_n) + datetime_to_pretty_str(entry.get('value')) + '\n'

  File "/usr/lib/python3/dist-packages/globaleaks/utils/utility.py", line 140, in datetime_to_pretty_str
    return date.strftime("%A %d %B %Y %H:%M (UTC)")

AttributeError: 'str' object has no attribute 'strftime'

**GlobaLeaks version:**
v4.00.45

**Browser:**
Chrome

**Server Operating System and Version (if applicable):**

Ubuntu(18.04LTS)

**Client Operating System and Version (if applicable):**
Windows 10

**Comment by elbill** [comment]
@evilaliv3 just to confirm that when no date question exists in the questionaire it works fine. So this must be causing it.

**Comment by evilaliv3** [comment]
Thank you for the feedback @elbill, i will get sure this is fixed within the next  update.
