### ISSUE TITLE
Unable to create New  recipient after upgrade from 4.0.8 to 4.1.6 

### ISSUE THREAD

**Issue by riyesh** [globaleaks/GlobaLeaks#2945]
**Current behavior**

allowed to create only one recipient after  the upgrade after that its giving internal error for new recipient.  Also for created Recipent ID is creating but Username with same id is not creating.  

**Expected behavior**

recipient will get id and username as same
recipient will get login option in the admin panel. 
welcome email recipient username is missing (usually it will mention)

**Steps to reproduce the problem or feature illustration**

upgrade to the latest version of 4.1.6
try to create the new recipents and try to login with that recipient id and password

**What is the motivation or use case for changing the behavior?**

without this its not useful. 

**GlobaLeaks version:**

**Browser:**

**Server Operating System and Version (if applicable):**
 

**Client Operating System and Version (if applicable):**

**Comment by evilaliv3** [comment]
Thank you @riyesh for reporting this.
 
Would you pleasea attach a copy of your log file: /var/globaleaks/globaleaks.log?

It may contain valuable information to identify the reason of the failure.

Is your setup public? if yes and you would like to provide me the addressi may try to look at the public configuration in order to understand well your configuration. Thank you

**Comment by riyesh** [comment]
2020-12-08 18:58:21+0000 [-] [E] Unhandled exception raised:
2020-12-08 18:58:21+0000 [-] [E] sqlalchemy.exc.IntegrityError Wraps a DB-API IntegrityError.\n\nTraceback (most recent call last):\n\n  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1245, in _execute_context\n    self.dialect.do_execute(\n\n  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/default.py", line 581, in do_execute\n    cursor.execute(statement, parameters)\n\nsqlite3.IntegrityError: UNIQUE constraint failed: user.tid, user.username\n\n\nThe above exception was the direct cause of the following exception:\n\n\nTraceback (most recent call last):\n\n  File "/usr/lib/python3/dist-packages/twisted/python/threadpool.py", line 250, in inContext\n    result = inContext.theWork()\n\n  File "/usr/lib/python3/dist-packages/twisted/python/threadpool.py", line 266, in <lambda>\n    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)\n\n  File "/usr/lib/python3/dist-packages/twisted/python/context.py", line 122, in callWithContext\n    return self.currentContext().callWithContext(ctx, func, *args, **kw)\n\n  File "/usr/lib/python3/dist-packages/twisted/python/context.py", line 85, in callWithContext\n    return func(*args,**kw)\n\n  File "/usr/lib/python3/dist-packages/globaleaks/orm.py", line 140, in _wrap\n    result = function(session, *args, **kwargs)\n\n  File "/usr/lib/python3/dist-packages/globaleaks/handlers/admin/user.py", line 67, in create_user\n    return user_serialize_user(session, db_create_user(session, tid, request, language), language)\n\n  File "/usr/lib/python3/dist-packages/globaleaks/handlers/admin/user.py", line 48, in db_create_user\n    session.flush()\n\n  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/session.py", line 2479, in flush\n    self._flush(objects)\n\n  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/session.py", line 2617, in _flush\n    transaction.rollback(_capture_exception=True)\n\n  File "/usr/lib/python3/dist-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__\n    compat.reraise(exc_type, exc_value, exc_tb)\n\n  File "/usr/lib/python3/dist-packages/sqlalchemy/util/compat.py", line 153, in reraise\n    raise value\n\n  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/session.py", line 2577, in _flush\n    flush_context.execute()\n\n  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/unitofwork.py", line 422, in execute\n    rec.execute(self)\n\n  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/unitofwork.py", line 586, in execute\n    persistence.save_obj(\n\n  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/persistence.py", line 239, in save_obj\n    _emit_insert_statements(\n\n  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/persistence.py", line 1136, in _emit_insert_statements\n    result = cached_connections[connection].execute(\n\n  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 982, in execute\n    return meth(self, multiparams, params)\n\n  File "/usr/lib/python3/dist-packages/sqlalchemy/sql/elements.py", line 287, in _execute_on_connection\n    return connection._execute_clauseelement(self, multiparams, params)\n\n  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1095, in _execute_clauseelement\n    ret = self._execute_context(\n\n  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1249, in _execute_context\n    self._handle_dbapi_exception(\n\n  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1476, in _handle_dbapi_exception\n    util.raise_from_cause(sqlalchemy_exception, exc_info)\n\n  File "/usr/lib/python3/dist-packages/sqlalchemy/util/compat.py", line 398, in raise_from_cause\n    reraise(type(exception), exception, tb=exc_tb, cause=cause)\n\n  File "/usr/lib/python3/dist-packages/sqlalchemy/util/compat.py", line 152, in reraise\n    raise value.with_traceback(tb)\n\n  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1245, in _execute_context\n    self.dialect.do_execute(\n\n  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/default.py", line 581, in do_execute\n    cursor.execute(statement, parameters)\n\nsqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) UNIQUE constraint failed: user.tid, user.username\n[SQL: INSERT INTO user (id, tid, creation_date, username, salt, hash_alg, password, name, description, public_name, role, state, last_login, mail_address, language, password_change_needed, password_change_date, crypto_prv_key, crypto_pub_key, crypto_rec_key, crypto_bkp_key, crypto_escrow_prv_key, crypto_escrow_bkp1_key, crypto_escrow_bkp2_key, change_email_address, change_email_token, change_email_date, reset_password_token, reset_password_date, notification, forcefully_selected, can_delete_submission, can_postpone_expiration, can_edit_general_settings, readonly, two_factor_enable, two_factor_secret, reminder_date, pgp_key_fingerprint, pgp_key_public, pgp_key_expiration, clicked_recovery_key) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]\n[parameters: ('2dd833fc-d398-48b2-9cd9-b1f98a445e26', 1, '2020-12-08 18:58:21.442372', '', 'm3DeKZ8I7cbDoMd98OjN/Q==', 'ARGON2', '', 'asasd', '{"en": ""}', 'asasd', 1, 1, '1970-01-01 00:00:00.000000', 'asdadas@gnmacci.com', 'en', 1, '1970-01-01 00:00:00.000000', '', '', '', '', '', '', '', '', None, '1970-01-01 00:00:00.000000', None, datetime.datetime(1970, 1, 1, 0, 0), 1, 0, 0, 0, 0, 0, 0, '', '1970-01-01 00:00:00.000000', '', '', '1970-01-01 00:00:00.000000', 0)]\n(Background on this error at: http://sqlalche.me/e/gkpj)\n
2020-12-08 18:58:29+0000 [-] Starting factory <twisted.mail.smtp.ESMTPSenderFactory object at 0x7f3bd234a1f0>
2020-12-08 18:58:34+0000 [-] Stopping factory <twisted.mail.smtp.ESMTPSenderFactory object at 0x7f3bd234a1f0>
2020-12-08 19:00:00+0000 [-] Starting factory _HTTP11ClientFactory(<function HTTPConnectionPool._newConnection.<locals>.quiescentCallback at 0x7f3bd245aca0>, <twisted.internet.endpoints._WrapperEndpoint object at 0x7f3bd2fece80>)
2020-12-08 19:00:00+0000 [-] Starting factory _HTTP11ClientFactory(<function HTTPConnectionPool._newConnection.<locals>.quiescentCallback at 0x7f3bd18cbb80>, <twisted.internet.endpoints._WrapperEndpoint object at 0x7f3bd249f1f0>)

**Comment by riyesh** [comment]
yes its public.. wb.masaood.abudhabi 

( also noticed that the new recipients not able to see old whisleblows.. I don't know is it part of feature)

**Comment by evilaliv3** [comment]
Thank you @riyesh we will try to verify the issue and get back to you. 

At the moment we are unfortunately unable to reproduce the issue that seems related to the outdated and reprecated feature for simplified logins. When was this system setupped? is it used in production?

In relation to your second doubt, yes i confirm that new recipients by design could not see new reports. We are implementing a feature that would make this possible but it will be released in 2021.

**Comment by riyesh** [comment]
Yeah, its setup in production environment :(. And the previous version loaded on last July 2020.  My bad, I have run apt-get update globalLeaks with the latest release.

**Comment by evilaliv3** [comment]
Do not worry we could probably solve it easily. I will be back to you shortly.

**Comment by evilaliv3** [comment]
@riyesh : The bug has been fixed with the commit above and the patch will be added in the next days to release 4.1.7

If you would like to manually apply the patch you should just change one line in file /usr/lib/python3/dist-packages/globaleaks/handlers/admin/user.py and restart globaleaks

**Comment by riyesh** [comment]
hi, Please let me know, what i have to edit in user.py file ?

**Comment by riyesh** [comment]
Hi,, 


thank  you,,, Its working perfect :)
