### ISSUE TITLE
sqlalchemy.orm.exc.NoResultFound A database result was required but none was found

### ISSUE THREAD

**Issue by KevKugler** [globaleaks/GlobaLeaks#2972]
**Current behavior**
Sometimes I get this mails from globalleaks but i can't found any problem.

has someone the same problems?

We update the always to the newest versions

i think it's an error while requesting some entries which were deleted after the period

here the error message:
```sqlalchemy.orm.exc.NoResultFound A database result was required but none was found.

Traceback (most recent call last):

File "/usr/lib/python3/dist-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
result = result.throwExceptionIntoGenerator(g)

File "/usr/lib/python3/dist-packages/twisted/python/failure.py", line 491, in throwExceptionIntoGenerator
return g.throw(self.type, self.value, self.tb)

File "/usr/lib/python3/dist-packages/globaleaks/handlers/rtip.py", line 713, in get
tip, crypto_tip_prv_key = yield get_rtip(self.request.tid, self.current_user.user_id, tip_id, self.request.language)

File "/usr/lib/python3/dist-packages/twisted/python/threadpool.py", line 250, in inContext
result = inContext.theWork()

File "/usr/lib/python3/dist-packages/twisted/python/threadpool.py", line 266, in <lambda>
inContext.theWork = lambda: context.call(ctx, func, *args, **kw)

File "/usr/lib/python3/dist-packages/twisted/python/context.py", line 122, in callWithContext
return self.currentContext().callWithContext(ctx, func, *args, **kw)

File "/usr/lib/python3/dist-packages/twisted/python/context.py", line 85, in callWithContext
return func(args,*kw)

File "/usr/lib/python3/dist-packages/globaleaks/orm.py", line 140, in _wrap
result = function(session, *args, **kwargs)

File "/usr/lib/python3/dist-packages/globaleaks/handlers/rtip.py", line 382, in get_rtip
return db_get_rtip(session, tid, user_id, rtip_id, language)

File "/usr/lib/python3/dist-packages/globaleaks/handlers/rtip.py", line 360, in db_get_rtip
rtip, itip = db_access_rtip(session, tid, user_id, rtip_id)

File "/usr/lib/python3/dist-packages/globaleaks/handlers/rtip.py", line 214, in db_access_rtip
models.InternalTip.tid == tid))

File "/usr/lib/python3/dist-packages/globaleaks/orm.py", line 96, in db_get
return db_query(session, selector, filter).one()

File "/usr/lib/python3/dist-packages/sqlalchemy/orm/query.py", line 3046, in one
raise orm_exc.NoResultFound("No row was found for one()")

sqlalchemy.orm.exc.NoResultFound: No row was found for one()```

**GlobaLeaks version:**
4.1.16



**Server Operating System and Version (if applicable):**
Debian 10

**Comment by evilaliv3** [comment]
Thank you for reporting this @KevKugler 

Actually this is a know issue of current release that do not causes any failure if not the delivery of the email that you receive.

Suppose the following
- a report is received
- the user access the report via the direct link that is delivered via email
- the user access again the direct link to the deleted report; this will trigger an error because the submissions do not exists anymore and this error would result in sending an email to administators.

This may happening more frequently if the report is accessed by more than one users and one check the mail when the report has been already deleted by the others.
