### ISSUE TITLE
Error when trying to set users' passwords 

### ISSUE THREAD

**Issue by elbill** [globaleaks/GlobaLeaks#2982]
**Describe the bug**
Error when trying to set users' passwords.
In the scenario that a user have lost their recovery key, trying to set a password for the user results in error, either from sites management admin console, as well as the individual sites admin consoles.

**To Reproduce**
1. go to users admin tab
2. select user
3. change password
4. set password
5. save
This results in an error.

**Expected behavior**
would expect to be able to set user passwords.
**Screenshots**
in the screenshots you can see the grayed checkbox:
![whistleblowing platform - Advanced settings - Google Chrome 1_4_2021 5_25_24 μμ](https://user-images.githubusercontent.com/23246886/113308995-64ced080-930f-11eb-9967-73f056c87f30.png)
![whistleblowing platform - Advanced settings - Google Chrome 1_4_2021 5_24_42 μμ](https://user-images.githubusercontent.com/23246886/113309005-65fffd80-930f-11eb-88d4-5364bbafbd63.png)

**Comment by evilaliv3** [comment]
This is actually very uncommo, i could currently could not replicate this.

I will try again.

When you see it in gray it means that the user that you are using to operate is not enabled to reset user password, so could not downgrade the system as well. only very priviledged users that can reset users password could eventually disable the feature.

i suspect the bug could be that you do not have this feature enabled on the root tenant, while you enabled it on the secondary tenant. I will werify this scenario.

**Comment by elbill** [comment]
Try this. Disable the "enable administrators ..." feature on the secondary tenant and then reenable it. I had a test secondary tenant site working fine and when did this is change password gives an error

**Comment by evilaliv3** [comment]
Thank you for the suggestion, let me see this right away.

**Comment by evilaliv3** [comment]
If you this what should happen is the the root tenant admin should still be able to change password while the administrators of the secondary tenant should not see anymore the possibility to change the password.

In which conditions are you? when you get the error, which user are you using?

**Comment by elbill** [comment]
I get an error message for both root and tenant.

**Comment by evilaliv3** [comment]
I think to have understood the issue @elbill!

You disabled the possibilty to change password while operating as admin user on secondary tenant, then still with this user you vidited the users page and tried to change the password. due to caching you saw the button change password and you probably got an error.

Then you logged in as root tenant admin, you switched to the secondary tenant and you have re-enabled this setting.

Since then again the root tenant admin will be able to change user password.

But then you logged in as secondary tenant admin and you are currently not able to see the possibility to change the password. This is because by using the root tenant administrator you need first to re-enable this priviledge on the secondary tenant user.

Please retry what i describe to check the situation and get back to me if you notice other situations that i've not figured out.

Thank you!

**Comment by elbill** [comment]
No luck.
Did some tests trying not to be logged in both root and tenant admin
Working just from root admin entered the tenant admin, tried everything, enabled disabled the "enable administrators .." however in all cases I got an error.
I tried more or less all cases.
In some cases while the "enable administrators ..." checkbox was disabled, the set password button was there.
Then while on the tenant admin the box is checked (grayed) the change password button is missing :-(

**Comment by elbill** [comment]
One more element. When I make a new user, I am able to change their password. I suspect that users that have gone through the "enable administrator .." checkbox changes do not respond to password change. I was counting on the ability to set user password and was not stressing enough to keep their recovery code. Is there risk of locking users out of their service and  loosing access to data?

**Comment by evilaliv3** [comment]
Few clarifications.

1) the feature for changing password is ON by default on the initial system and on a new tenant if ON on the root tenant
2) the first administrator of the root tenant and the first administrator of the secondary tenant are automatically enabled to change the password
3) admin users after the first need to be enabled by an admin that has the capability to change password that could be enabled on a specific user in the User configuration section

In my condition:
1) when you say that you see the button but the feature is disabled is a matter of caching; you get the failure because if the feature is disabled the user could not change the password
2) when you do not see the button is because that specific user is not enabled to change the password.

This should probably help you understanding what i explained in my previous message; i invite you to re-read it and get back to me if you notice and understand better the malfunction. thank you.

**Comment by elbill** [comment]
@evilaliv3 I thing I get your point and everything makes sense. However after all the testing I have 2 users, for one user I am able to change the password for the other user I get an error. On both root and tenant. Is there an explanation for this?

**Comment by evilaliv3** [comment]
Would you please clarify the specificity of each of these two users?
1) root tenant / secondary tenant?
2) are they both enabled to change passwords?
3) can you upload here the extract of the log error that you get in /var/globaleaks/globaleaks.log?

thank you

**Comment by elbill** [comment]
root/secondary both enabled to change passwords
log error
2021-04-01 18:39:39+0000 [-] [E] Unhandled exception raised:
2021-04-01 18:39:39+0000 [-] [E] ValueError Inappropriate argument value (of correct type).\n\nTraceback (most recent call last):\n\n  File "/usr/lib/python3/dist-packages/twisted/python/threadpool.py", line 250, in inContext\n    result = inContext.theWork()\n\n  File "/usr/lib/python3/dist-packages/twisted/python/threadpool.py", line 266, in <lambda>\n    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)\n\n  File "/usr/lib/python3/dist-packages/twisted/python/context.py", line 122, in callWithContext\n    return self.currentContext().callWithContext(ctx, func, *args, **kw)\n\n  File "/usr/lib/python3/dist-packages/twisted/python/context.py", line 85, in callWithContext\n    return func(*args,**kw)\n\n  File "/usr/lib/python3/dist-packages/globaleaks/orm.py", line 140, in _wrap\n    result = function(session, *args, **kwargs)\n\n  File "/usr/lib/python3/dist-packages/globaleaks/orm.py", line 171, in tw\n    return f(session, *args, **kwargs)\n\n  File "/usr/lib/python3/dist-packages/globaleaks/handlers/admin/user.py", line 97, in db_admin_update_user\n    user_cc = GCE.asymmetric_decrypt(crypto_escrow_prv_key, Base64Encoder.decode(user.crypto_escrow_bkp2_key))\n\n  File "/usr/lib/python3/dist-packages/globaleaks/utils/crypto.py", line 301, in asymmetric_decrypt\n    return SealedBox(prv_key).decrypt(data)\n\n  File "/usr/lib/python3/dist-packages/nacl/public.py", line 361, in decrypt\n    self._private_key,\n\n  File "/usr/lib/python3/dist-packages/nacl/bindings/crypto_box.py", line 307, in crypto_box_seal_open\n    plaintext = ffi.new("unsigned char[]", _mlen)\n\nValueError: negative array length\n
2021-04-01 18:39:39+0000 [-] [E] Exception mail suppressed for (b'391eb1cd62208396d1b8b925c1469948c905c640c4d9b495708282ecfc5e8288') [reason: threshold exceeded]

**Comment by elbill** [comment]
@evilaliv3 actually the file extract  is from /var/globaleaks/log/globaleaks.log and not /var/globaleaks/globaleaks.log. I suppose it is the same file, isn't it?

**Comment by evilaliv3** [comment]
Yes it is, i actually wrote a wrong path.

If this system is a testing system and do not contain any sensible data or configuration do you mind to share it to me reaching me directly on slack?

thank you.
