### ISSUE TITLE
Globaleaks fails to install properly. After manual start ACME error messages appear

### ISSUE THREAD

**Issue by oeleaks** [globaleaks/GlobaLeaks#2989]
Lets encrypt does not work.

Storing graphics for contexts does not work.

Error message after installation:

Ouch! The installation is complete but GlobaLeaks failed to start

Error Message after manual start:

acme.errors.ValidationError Error for authorization failures. Contains a list of authorization\n    resources, each of which is invalid and should have an error field.\n    \n\nTraceback (most recent call last):\n\n  File "/usr/lib/python3/dist-packages/twisted/python/threadpool.py", line 250, in inContext\n    result = inContext.theWork()\n\n  File "/usr/lib/python3/dist-packages/twisted/python/threadpool.py", line 266, in <lambda>\n    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)\n\n  File "/usr/lib/python3/dist-packages/twisted/python/context.py", line 122, in callWithContext\n    return self.currentContext().callWithContext(ctx, func, *args, **kw)\n\n  File "/usr/lib/python3/dist-packages/twisted/python/context.py", line 85, in callWithContext\n    return func(*args,**kw)\n\n  File "/usr/lib/python3/dist-packages/globaleaks/orm.py", line 140, in _wrap\n    result = function(session, *args, **kwargs)\n\n  File "/usr/lib/python3/dist-packages/globaleaks/orm.py", line 171, in tw\n    return f(session, *args, **kwargs)\n\n  File "/usr/lib/python3/dist-packages/globaleaks/handlers/admin/https.py", line 463, in db_acme_cert_request\n    Settings.acme_directory_url)\n\n  File "/usr/lib/python3/dist-packages/globaleaks/utils/letsencrypt.py", line 101, in request_new_certificate\n    order = client.poll_and_finalize(order)\n\n  File "/usr/lib/python3/dist-packages/acme/client.py", line 714, in poll_and_finalize\n    orderr = self.poll_authorizations(orderr, deadline)\n\n  File "/usr/lib/python3/dist-packages/acme/client.py", line 738, in poll_authorizations\n    raise errors.ValidationError(failed)\n\nacme.errors.ValidationError\n
2021-04-18T00:20:11+0200 [twisted.python.log#info] 5lsfz6n4qwzpxkd34sfl23ity7qft4jht7mtngb7fav6n7iqcsbgafid.onion [REMOVED_IP_ADDRESS] - - [17/Apr/2021:22:20:11 +0000] "PUT /api/admin/config/acme/run HTTP/1.1" 500 99 3086ms - "[REMOVED_USER_AGENT]"
2021-04-18T00:20:14+0200 [twisted.mail.smtp.ESMTPSenderFactory#info] Starting factory <twisted.mail.smtp.ESMTPSenderFactory object at 0x7f99d77d6ba8>
2021-04-18T00:20:15+0200 [twisted.mail.smtp.ESMTPSenderFactory#info] Stopping factory <twisted.mail.smtp.ESMTPSenderFactory object at 0x7f99d77d6ba8>

**Comment by evilaliv3** [comment]
Thank you for reporting this.

Would you please complete, if possible, the ticket with the following
information?

1) the url of the site so that we could eventually check proper dns
configuration
2) the operating system version
3) if the install is from scratch or if this is a system migrated from a
previous system and in case would you please the initial software version
and os version

Thank you

**Comment by oeleaks** [comment]
Thank you, that you take care of this incident:

To answer your questions

1) www.oe-korruption.at
2) Debian GNU/Linux 10 \n \l
3) Install was from scratch

I additionally saw this errors
 [E] Blocked file operation for: (prefix, attempted_path) : ('/usr/share/globaleaks/client', '/login_sid.lua')

**Comment by evilaliv3** [comment]
I see thank you.

All seems to work to me now, probably the first time let's encrypt tried to
verify your domain ownership maybe to you had still not configured the DNS
or it was still not propagated?

Please let us know if you still have any issue.

In relation to the logged error it is just related to an automatic attempt
of a bot to attack the system and there is no need to worry about. Are bots
trying to break into every computers worldwide trying every possible
software breach.

Giovanni

**Comment by oeleaks** [comment]
Unfortunately, the errors continue: Therfore: Could you maybe advice, how to completely reinstall Globaleaks and all associated Debian resources (including deletion of all user specific data)?

1. The Lets Encrpyt error still occurs ("internal server error"), even after several re-installations of Globaleaks.

2. Addiitonally as I wrote, I can not store any jpgs or pngs as symbols for contexts. Here the following error is appearing

2021-04-17 17:37:35+0200 [-] [E] sqlalchemy.exc.IntegrityError Wraps a DB-API IntegrityError.\n\nTraceback (most recent call last):\n\n  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1236, in _execute_context\n    cursor, statement, parameters, context\n\n  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/default.py", line 536, in do_execute\n    cursor.execute(statement, parameters)\n\nsqlite3.IntegrityError: UNIQUE constraint failed: file.tid, file.name\n\n\nThe above exception was the direct cause of the following exception:\n\n\nTraceback (most recent call last):\n\n  File "/usr/lib/python3/dist-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks\n    result = result.throwExceptionIntoGenerator(g)\n\n  File "/usr/lib/python3/dist-packages/twisted/python/failure.py", line 491, in throwExceptionIntoGenerator\n    return g.throw(self.type, self.value, self.tb)\n\n  File "/usr/lib/python3/dist-packages/globaleaks/handlers/admin/file.py", line 108, in post\n    yield tw(db_add_file, self.request.tid, id, self.uploaded_file['name'], path)\n\n  File "/usr/lib/python3/dist-packages/twisted/python/threadpool.py", line 250, in inContext\n    result = inContext.theWork()\n\n  File "/usr/lib/python3/dist-packages/twisted/python/threadpool.py", line 266, in <lambda>\n    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)\n\n  File "/usr/lib/python3/dist-packages/twisted/python/context.py", line 122, in callWithContext\n    return self.currentContext().callWithContext(ctx, func, *args, **kw)\n\n  File "/usr/lib/python3/dist-packages/twisted/python/context.py", line 85, in callWithContext\n    return func(*args,**kw)\n\n  File "/usr/lib/python3/dist-packages/globaleaks/orm.py", line 142, in _wrap\n    session.commit()\n\n  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/session.py", line 1023, in commit\n    self.transaction.commit()\n\n  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/session.py", line 487, in commit\n    self._prepare_impl()\n\n  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/session.py", line 466, in _prepare_impl\n    self.session.flush()\n\n  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/session.py", line 2446, in flush\n    self._flush(objects)\n\n  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/session.py", line 2584, in _flush\n    transaction.rollback(_capture_exception=True)\n\n  File "/usr/lib/python3/dist-packages/sqlalchemy/util/langhelpers.py", line 67, in __exit__\n    compat.reraise(exc_type, exc_value, exc_tb)\n\n  File "/usr/lib/python3/dist-packages/sqlalchemy/util/compat.py", line 277, in reraise\n    raise value\n\n  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/session.py", line 2544, in _flush\n    flush_context.execute()\n\n  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/unitofwork.py", line 416, in execute\n    rec.execute(self)\n\n  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/unitofwork.py", line 583, in execute\n    uow,\n\n  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/persistence.py", line 245, in save_obj\n    insert,\n\n  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/persistence.py", line 1063, in _emit_insert_statements\n    c = cached_connections[connection].execute(statement, multiparams)\n\n  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 980, in execute\n    return meth(self, multiparams, params)\n\n  File "/usr/lib/python3/dist-packages/sqlalchemy/sql/elements.py", line 273, in _execute_on_connection\n    return connection._execute_clauseelement(self, multiparams, params)\n\n  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1099, in _execute_clauseelement\n    distilled_params,\n\n  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1240, in _execute_context\n    e, statement, parameters, cursor, context\n\n  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1458, in _handle_dbapi_exception\n    util.raise_from_cause(sqlalchemy_exception, exc_info)\n\n  File "/usr/lib/python3/dist-packages/sqlalchemy/util/compat.py", line 296, in raise_from_cause\n    reraise(type(exception), exception, tb=exc_tb, cause=cause)\n\n  File "/usr/lib/python3/dist-packages/sqlalchemy/util/compat.py", line 276, in reraise\n    raise value.with_traceback(tb)\n\n  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1236, in _execute_context\n    cursor, statement, parameters, context\n\n  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/default.py", line 536, in do_execute\n    cursor.execute(statement, parameters)\n\nsqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) UNIQUE constraint failed: file.tid, file.name [SQL: 'INSERT INTO file (tid, id, name) VALUES (?, ?, ?)'] [parameters: (1, '116a1443-1329-4a24-861b-08b659c71733', 'Korruption.jpg')] (Background on this error at: http://sqlalche.me/e/gkpj)\n

**Comment by evilaliv3** [comment]
Dear @oeleaks thank you for your feedback.

Please if you can keep idfferent topics on different tickets as it more easy to follow and manage

1) in relation to the letsencrypt error as i think you may have installed a web server in front of globaleaks (like apache or nginx and you may have setupp https with that. this step is not needed and what you just need is a plain server with installed a base Debian and on top of it you just need to install globaleaks.

2) in relation to the error in loading context images this could be a bug of the release 4.2.0; we will try to debug this soon and issue a patch

**Comment by oeleaks** [comment]
Dear is no websearver installed. Neither Apache nor NGINX. I took plain Debian and installed Globaleaks as first application.

Could you pls. let me know, how I could check the configuration and reset it properly.

As I wrote: I reinstalled Globaleaks now many times, and always this error with Lets Encrypt occurs.

Maybe the Python database is corrupt?

**Comment by evilaliv3** [comment]
Actually i exclude that the database is corrupt as all seems to work correctly from my side.

Accessing from my network i see that HTTPS is already setup by using ZeroSSL RSA Domain Secure Site CS as certificate.

This do not appear to be setup on globaleaks but probably by your provider and this is what in my opinion is preventing letsencrypt to work. 

Your server signature states "GIX 1.32FMR" as web server.

![WhatsApp Image 2021-04-18 at 2 55 47 PM](https://user-images.githubusercontent.com/217034/115146386-95747100-a056-11eb-999d-52ccb1f25d41.jpeg)

**Comment by oeleaks** [comment]
I was setting up Zero SSL BECAUSE Lets Encrypt does not work. Therefor I would like to ask again, how I can make it work!

**Comment by evilaliv3** [comment]
I think the whole issue is due to DNS misconfiguration.

On some servers i reseolve correctly the IP of the server and on others i instead see the default:
```; <<>> DiG 9.11.5-P4-5.1+deb10u3-Debian <<>> www.oe-korruption.at
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 39422
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 5, ADDITIONAL: 11

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
; COOKIE: befd6279c129feae56be7735607c33f6b610a8188dbf6d70 (good)
;; QUESTION SECTION:
;www.oe-korruption.at.		IN	A

;; ANSWER SECTION:
www.oe-korruption.at.	1665	IN	A	88.99.70.111

;; AUTHORITY SECTION:
oe-korruption.at.	4065	IN	NS	ns81.internic.at.
oe-korruption.at.	4065	IN	NS	ns501.internic.at.
oe-korruption.at.	4065	IN	NS	ns6.internic.at.
oe-korruption.at.	4065	IN	NS	ns57.internic.at.
oe-korruption.at.	4065	IN	NS	ns49.internic.at.

;; ADDITIONAL SECTION:
ns6.internic.at.	4065	IN	A	212.126.64.6
ns49.internic.at.	4065	IN	A	172.104.141.191
ns57.internic.at.	2968	IN	A	198.58.114.171
ns81.internic.at.	4065	IN	A	172.104.73.237
ns501.internic.at.	2968	IN	A	66.175.216.204
ns6.internic.at.	4065	IN	AAAA	2001:4100:0:64::6
ns49.internic.at.	4065	IN	AAAA	2a01:7e01::f03c:91ff:fe0f:4607
ns57.internic.at.	2968	IN	AAAA	2600:3c00::f03c:91ff:feae:d53d
ns81.internic.at.	4065	IN	AAAA	2400:8902::f03c:91ff:febd:3cca
ns501.internic.at.	2968	IN	AAAA	2600:3c01::f03c:91ff:feae:7907
```

Probably letsencrypt as well is incurring this  issue, as soon that you will resolve this all will work right away!

**Comment by oeleaks** [comment]
The configuration that you sent me looks fine! Where do you see a problem? Please could you hightlight the entry?

**Comment by evilaliv3** [comment]
Unfortunately I'm out now and i will be back working tomorrow.

if I try to reach this ip i get an answer from a server that is not
globaleaks.

Is this a shared ip address on which sits a proxy? It's seems to me so and
i receive an answer from a software that is not GlobaLeaks

**Comment by evilaliv3** [comment]
@oeleaks : i finally understood the issue.

you have as well ipv6 records that points to different default records.

Remove those records or correct them with the correct ipv6 record of the server.

Right know that is happening is that any ipv6 enabled client ends in reaching a wrong server and this is probably what is happening for letsencrypt as well.

**Comment by oeleaks** [comment]
Thank you - the IPV6 update solved the problem!
