### ISSUE TITLE
LE cert generation - opnessl crypto api Error

### ISSUE THREAD

**Issue by larrykind** [globaleaks/GlobaLeaks#3008]
**Describe the bug**
On GL 4.0.54 I am trying to generate the openssl LE certificate, I got this red unhandled error, never had this before:

That's the globaleaks.log output:

 _Unhandled exception raised:
2021-05-13 12:42:06+0200 [-] [E] OpenSSL.crypto.Error \n    An error occurred in an `OpenSSL.crypto` API.\n    \n\nTraceback (most recent call last):\n\n  File "/usr/lib/python3/dist-packages/twisted/python/threadpool.py", line 250, in inContext\n    result = inContext.theWork()\n\n  File "/usr/lib/python3/dist-packages/twisted/python/threadpool.py", line 266, in <lambda>\n    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)\n\n  File "/usr/lib/python3/dist-packages/twisted/python/context.py", line 122, in callWithContext\n    return self.currentContext().callWithContext(ctx, func, *args, **kw)\n\n  File "/usr/lib/python3/dist-packages/twisted/python/context.py", line 85, in callWithContext\n    return func(*args,**kw)\n\n  File "/usr/lib/python3/dist-packages/globaleaks/orm.py", line 109, in _wrap\n    result = function(session, *args, **kwargs)\n\n  File "/usr/lib/python3/dist-packages/globaleaks/handlers/admin/https.py", line 312, in serialize_https_config_summary\n    file_summaries[key] = file_res_cls.db_serialize(session, tid)\n\n  File "/usr/lib/python3/dist-packages/globaleaks/handlers/admin/https.py", line 231, in db_serialize\n    x509 = crypto.load_certificate(crypto.FILETYPE_PEM, c)\n\n  File "/usr/lib/python3/dist-packages/OpenSSL/crypto.py", line 1824, in load_certificate\n    _raise_current_error()\n\n  File "/usr/lib/python3/dist-packages/OpenSSL/_util.py", line 54, in exception_from_error_queue\n    raise exception_type(errors)\n\nOpenSSL.crypto.Error: [('PEM routines', 'get_header_and_data', 'bad end line')]_

- The domain DNS record is correctly pointing to globaleaks instance
- Tried also with a wildcard platform domain name, same problem

**To Reproduce**
1. go to netowrk settings
2. insert the domain name and save
3. trying to generate LE certificate -> got error

**Expected behavior**
LE Certificate should be generated

**Desktop (please complete the following information):**
 - OS: ubuntu bionic
 - Browser : firefox 88

**Comment by evilaliv3** [comment]
This is a duplicate ticket discussed in https://github.com/globaleaks/GlobaLeaks/issues/3006

Letsencrypt has changed how it provide the intermediate certificate that currently provides multiple certificates and has opened to a bug previously not known. This has been fixed in 4.2.8

**Comment by larrykind** [comment]
Thank you so much fo the quick answer!!
