### ISSUE TITLE
Let's encrypt Automatic Configuration - Unexpected server internal error

### ISSUE THREAD

**Issue by emanuelegreco** [globaleaks/GlobaLeaks#3018]
Actually my Production Globaleaks website is unreachable, due to **ERR_SSL_VERSION_OR_CIPHER_MISMATCH** error.  

I cant'renew SSL certificate, using the Automatic Configuration provided in Globaleaks Network Configuration.

I own two Globaleaks apps:

**Production website**
- https://speakup.nadoitalia.it/
- http://sov5af2zd3dn4dz66gxw443vse7v6zuorvyxkzhpeqmjzb35d5zikmid.onion
- Version 4.1.17 

and **Test website**
- https://nadoitalia.opentech.it/
- http://2lwr2lvt5fmucax745532yhiijdb4y3c4ae2jsaztxufjqxaquzbzayd.onion/
- Version 4.0.58

In both websites, I do:

1. Click "Network settings"
2. Choose "HTTPS" tab
3. Click "Proceed" butto inside "Automatic configuration"
4. Check "I agree to the Terms of Service"
5. Click "Proceed" again.

After 5 seconds I recieve "**Error! Internal server error (Unexpected)**" in a red bubble.

"Anomalies" list into "Audit log" page is empty.

I can see [this was a 2018 issue](https://forum.globaleaks.org/t/error-when-using-lets-encrypt-in-automatic-configuration/250/3), and it's strange that it's the same problem I'm facing now.

How can I solve this problem?

**Comment by evilaliv3** [comment]
Duplicated issue discussed in https://github.com/globaleaks/GlobaLeaks/issues/3006 and solved in release 4.2.6.

You can update to latest version (suggested) or temporarely backport the patch.

**Comment by emanuelegreco** [comment]
@evilaliv3 thanks for the answer; i missed issue #3006.

Just upgraded GL to the latest version (4.2.10) and then repeated the same procedure.
Same result **Error! Internal server error (Unexpected)** in a red bubble.

I also tried changing the host name and reset button inside Manual Configuration.

Any suggestions?

**Comment by evilaliv3** [comment]
Can you look at the file globaleaks.log and load here the error that is logged when this failure happen?

I suspect that letsencrypt may be currently be blocking you for to many failed attempts and you have just to wait for some timeouts to happen.

**Comment by emanuelegreco** [comment]
@evilaliv3, today still "**Internal Error**" in both Test and Production. 

Letsencrypt has some limit to issuing attempts, but it should be resetted in an hour.
I also tried to open log file in  **/var/globaleaks/logs/globaleaks.log**,  but recieved as an answer that such path doesn't exist.
What am I doing wrong?

**Comment by evilaliv3** [comment]
The correct path is: ```/var/globaleaks/log/globaleaks.log```

**Comment by emanuelegreco** [comment]
@evilaliv3 thanks for the answer.
 **/var/globaleaks/log/globaleaks.log** works prefcetly. Maybe in [documentation](https://docs.globaleaks.org/_/downloads/en/main/pdf/) and in [troubleshooting](https://docs.globaleaks.org/en/main/user/admin/TroubleShooting.html) is reported a wrong path.

Anyway, this is the text found into globaleaks.log

2021-06-19 12:25:20+0000 [-] [E] Unhandled exception raised:
2021-06-19 12:25:20+0000 [-] [E] acme.messages.Error ACME error.\n\n    https://tools.ietf.org/html/draft-ietf-appsawg-http-problem-00\n\n    :ivar unicode typ:\n    :ivar unicode title:\n    :ivar unicode deta$
2021-06-19 12:25:23+0000 [-] Starting factory <twisted.mail.smtp.ESMTPSenderFactory object at 0x7f3bbe04d748>
2021-06-19 12:25:23+0000 [-] Stopping factory <twisted.mail.smtp.ESMTPSenderFactory object at 0x7f3bbe04d748>

Does it have any meaning to you?

**Comment by emanuelegreco** [comment]
Thanks @evilaliv3 after many fails for automatic procedure I tried the manual one. 
Pem, Csr, ACME.. and got this error:

`Failed to create order: Error creating new order :: too many certificates (5) already issued for this exact set of domains in the last 168 hours: speakup.nadoitalia.it: see https://letsencrypt.org/docs/rate-limits/`

[Renewals are treated specially: they don’t count against your Certificates per Registered Domain limit, but they are subject to a Duplicate Certificate limit of 5 per week.](https://letsencrypt.org/docs/rate-limits/)

You were right; I have to wait a few days or to buy the certificate somewhere else. 

Greetings.

**Comment by emanuelegreco** [comment]
I can confirm that after the limit to issuing attempts has expired, the automatic renewal procedure has worked properly. 
So the issue is definitely solved.

**Comment by wasimkaj** [comment]
Hi @evilaliv3 
even we are facing issues in auto renewal of ssl certs ; 
tried to reset the ssl current config and perform fresh setup but it returned "Unexpected server internal error"

error log /var/globaleaks/log/globaleaks.log :

2021-07-07 05:21:49+0000 [-] [E] Unhandled exception raised:
2021-07-07 05:21:49+0000 [-] [E] acme.messages.Error ACME error.\n\n    https://tools.ietf.org/html/draft-ietf-appsawg-http-problem-00\n\n    :ivar unicode typ:\n    :ivar unicode title:\n    :ivar unicode detail:\n\n    \n\nTraceback (most recent call last):\n\n  File "/usr/lib/python3/dist-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks\n    result = result.throwExceptionIntoGenerator(g)\n\n  File "/usr/lib/python3/dist-packages/twisted/python/failure.py", line 491, in throwExceptionIntoGenerator\n    return g.throw(self.type, self.value, self.tb)\n\n  File "/usr/lib/python3/dist-packages/globaleaks/handlers/admin/https.py", line 479, in post\n    yield tw(db_acme_cert_request, self.request.tid)\n\n  File "/usr/lib/python3/dist-packages/twisted/python/threadpool.py", line 250, in inContext\n    result = inContext.theWork()\n\n  File "/usr/lib/python3/dist-packages/twisted/python/threadpool.py", line 266, in <lambda>\n    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)\n\n  File "/usr/lib/python3/dist-packages/twisted/python/context.py", line 122, in callWithContext\n    return self.currentContext().callWithContext(ctx, func, *args, **kw)\n\n  File "/usr/lib/python3/dist-packages/twisted/python/context.py", line 85, in callWithContext\n    return func(*args,**kw)\n\n  File "/usr/lib/python3/dist-packages/globaleaks/orm.py", line 140, in _wrap\n    result = function(session, *args, **kwargs)\n\n  File "/usr/lib/python3/dist-packages/globaleaks/orm.py", line 171, in tw\n    return f(session, *args, **kwargs)\n\n  File "/usr/lib/python3/dist-packages/globaleaks/handlers/admin/https.py", line 461, in db_acme_cert_request\n    cert_str, chain_str = letsencrypt.request_new_certificate(hostname,\n\n  File "/usr/lib/python3/dist-packages/globaleaks/utils/letsencrypt.py", line 75, in request_new_certificate\n    client.net.account = client.new_account(\n\n  File "/usr/lib/python3/dist-packages/acme/client.py", line 601, in new_account\n    response = self._post(self.directory['newAccount'], new_account)\n\n  File "/usr/lib/python3/dist-packages/acme/client.py", line 95, in _post\n    return self.net.post(*args, **kwargs)\n\n  File "/usr/lib/python3/dist-packages/acme/client.py", line 1171, in post\n    return self._post_once(*args, **kwargs)\n\n  File "/usr/lib/python3/dist-packages/acme/client.py", line 1184, in _post_once\n    response = self._check_response(response, content_type=content_type)\n\n  File "/usr/lib/python3/dist-packages/acme/client.py", line 1042, in _check_response\n    raise messages.Error.from_json(jobj)\n\nacme.messages.Error: urn:ietf:params:acme:error:rateLimited :: There were too many requests of a given type :: Error creating new account :: too many registrations for this IP: see https://letsencrypt.org/docs/rate-limits/\n

any help is really appreciated.

**Comment by evilaliv3** [comment]
@wasimkaj : from the error, i suspect that you may have updated to latest globaleaks only today and that due to failures in the automatic update failures letsencrypt is banning you.

Please wait some time before retrying (a day) and probably the problem will solve automatically.

**Comment by wasimkaj** [comment]
@evilaliv3 Thanks a lot for your quick response. Sure i will retry it post 1 day.

software version on host.
---------
$ globaleaks --version

GlobaLeaks version: 4.2.10
Database version: 54

**Comment by evilaliv3** [comment]
When did you update to this version ? Which version where you running before updating ?

**Comment by wasimkaj** [comment]
we did the update 2 hr back from now ; but letsencrypt cert renew error seen before that.
I think it was 4.2.3 as per apt output.

# apt-get update && apt-get install globaleaks
Hit:1 http://us-west-2.ec2.archive.ubuntu.com/ubuntu focal InRelease
Get:2 http://us-west-2.ec2.archive.ubuntu.com/ubuntu focal-updates InRelease [114 kB]
Get:3 http://us-west-2.ec2.archive.ubuntu.com/ubuntu focal-backports InRelease [101 kB]
Get:4 http://security.ubuntu.com/ubuntu focal-security InRelease [114 kB]
Get:5 http://us-west-2.ec2.archive.ubuntu.com/ubuntu focal-updates/main amd64 Packages [1081 kB]
Get:6 http://us-west-2.ec2.archive.ubuntu.com/ubuntu focal-updates/main amd64 c-n-f Metadata [13.6 kB]
Ign:7 https://deb.globaleaks.org focal/ InRelease
Hit:8 https://deb.globaleaks.org focal/ Release
Fetched 1423 kB in 2s (906 kB/s)
Reading package lists... Done
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following package was automatically installed and is no longer required:
  python3-pyotp
Use 'apt autoremove' to remove it.
The following packages will be upgraded:
  globaleaks
1 upgraded, 0 newly installed, 0 to remove and 47 not upgraded.
Need to get 2251 kB of archives.
After this operation, 736 kB of additional disk space will be used.
Get:1 https://deb.globaleaks.org focal/ globaleaks 4.2.10 [2251 kB]
Fetched 2251 kB in 2s (1020 kB/s)
(Reading database ... 124393 files and directories currently installed.)
Preparing to unpack .../globaleaks_4.2.10_all.deb ...
Unpacking globaleaks (4.2.10) over (4.2.3) ...
Setting up globaleaks (4.2.10) ...
Processing triggers for systemd (245.4-4ubuntu3.6) ...

**Comment by evilaliv3** [comment]
Ok if this is the case the issue is caused from the fact that for long time you missed to update to 4.2.7 that fixed a bug in the letsencrypt update, and due to the failure you are currently banned.

I confirm that you can just wait and all will be solved tomorrow

**Comment by iradiddeus** [comment]
Hello,
I have the same issue, but the cause seems different.
My globaleaks versione is
GlobaLeaks version: 4.13.18
Database version: 66
The log:
2023-12-07 12:30:30+0100 [-] Starting factory _HTTP11ClientFactory(<function HTTPConnectionPool._newConnection.<locals>.quiescentCallback at 0x7f2d6ca40f40>, <twisted.internet.endpoints._WrapperEndpoint object at 0x7f2d6cafef90>)
2023-12-07 12:30:30+0100 [-] Stopping factory _HTTP11ClientFactory(<function HTTPConnectionPool._newConnection.<locals>.quiescentCallback at 0x7f2d6ca40f40>, <twisted.internet.endpoints._WrapperEndpoint object at 0x7f2d6cafef90>)
2023-12-07 12:43:43+0100 [-] [E] exception mail suppressed for exception (<class 'acme.errors.ValidationError'>) [reason: special exception]

the event is the last one, at 12:43:43
Can you help?
Thank you
Francesco

**Comment by evilaliv3** [comment]
Which domain are you trying to activate?
