### ISSUE TITLE
Error when admin tries to set password for a user

### ISSUE THREAD

**Issue by alexfrab** [globaleaks/GlobaLeaks#3045]
**Describe the bug**
Error when trying to set users' passwords by Admin.
The user has lost his recovery key and would like to reset the password for the user via the admin panel.
Currently, there is a Whistleblower Tip associated with the user who cannot log in and we do not know how to recover it.

**To Reproduce**
- go to users admin tab
- select user
- set new password
- save
This results in an error (see the "Additional context" section for the log)

**Expected behavior**
would expect to be able to set user passwords.

**Screenshots**

**Additional context**
2021-09-01 10:02:01+0000 [-] [E] Unhandled exception raised:
2021-09-01 10:02:01+0000 [-] [E] ValueError Inappropriate argument value (of correct type).\n\nTraceback (most recent call last):\n\n  File "/usr/lib/python3/dist-packages/twisted/python/threadpool.py", line 250, in inContext\n    result = inContext.theWork()\n\n  File "/usr/lib/python3/dist-packages/twisted/python/threadpool.py", line 266, in <lambda>\n    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)\n\n  File "/usr/lib/python3/dist-packages/twisted/python/context.py", line 122, in callWithContext\n    return self.currentContext().callWithContext(ctx, func, *args, **kw)\n\n  File "/usr/lib/python3/dist-packages/twisted/python/context.py", line 85, in callWithContext\n    return func(*args,**kw)\n\n  File "/usr/lib/python3/dist-packages/globaleaks/orm.py", line 109, in _wrap\n    result = function(session, *args, **kwargs)\n\n  File "/usr/lib/python3/dist-packages/globaleaks/orm.py", line 140, in tw\n    return f(session, *args, **kwargs)\n\n  File "/usr/lib/python3/dist-packages/globaleaks/handlers/admin/user.py", line 120, in db_admin_update_user\n    user_cc = GCE.asymmetric_decrypt(crypto_escrow_prv_key, Base64Encoder.decode(user.crypto_escrow_bkp1_key))\n\n  File "/usr/lib/python3/dist-packages/globaleaks/utils/crypto.py", line 310, in asymmetric_decrypt\n    return SealedBox(prv_key).decrypt(data)\n\n  File "/usr/lib/python3/dist-packages/nacl/public.py", line 358, in decrypt\n    plaintext = nacl.bindings.crypto_box_seal_open(\n\n  File "/usr/lib/python3/dist-packages/nacl/bindings/crypto_box.py", line 307, in crypto_box_seal_open\n    plaintext = ffi.new("unsigned char[]", _mlen)\n\nValueError: negative array length\n

**Comment by evilaliv3** [comment]
Thank you for reporting this @alexfrab 

Password can be reseteede by:
- 1. users: if they saved their own escrow recovery key.
- 2. administators of the root tenant (first tenant) that have the priviledge to access users
- 3. administrators of the secondary tenants

Options 1 and 2 should work always correctly. We are investigating a failure on 3. that scatter on some conditions and we will issue a patch.

Would you please clarify the following:
- which version of the system are you running?
- is your system is multitenant or single tenant?
- in case the system is multitenant to which tenant do the admin user and the recipient user belong?

**Comment by alexfrab** [comment]
The current version is 4.0.54

**Comment by alexfrab** [comment]
The error persists even after updating to the latest version (4.4.3)
This is the log:

2021-10-13 18:06:17+0200 [-] [E] ValueError Inappropriate argument value (of correct type).\n\nTraceback (most recent call last):\n\n  
File "/usr/lib/python3/dist-packages/twisted/python/threadpool.py", line 250, in inContext\n    
result = inContext.theWork()\n\n  File "/usr/lib/python3/dist-packages/twisted/python/threadpool.py", line 266, in <lambda>\n    
inContext.theWork = lambda: context.call(ctx, func, *args, **kw)\n\n  File "/usr/lib/python3/dist-packages/twisted/python/context.py", line 122, 
in callWithContext\n    return self.currentContext().callWithContext(ctx, func, *args, **kw)\n\n  
File "/usr/lib/python3/dist-packages/twisted/python/context.py", line 85, in callWithContext\n    
return func(*args,**kw)\n\n  File "/usr/lib/python3/dist-packages/globaleaks/orm.py", line 152, in _wrap\n    
result = function(session, *args, **kwargs)\n\n  File "/usr/lib/python3/dist-packages/globaleaks/orm.py", line 183, in tw\n    
return f(session, *args, **kwargs)\n\n  File "/usr/lib/python3/dist-packages/globaleaks/handlers/admin/user.py", line 98, in db_admin_update_user\n    
user_cc = GCE.asymmetric_decrypt(crypto_escrow_prv_key, Base64Encoder.decode(user.crypto_escrow_bkp1_key))\n\n  
File "/usr/lib/python3/dist-packages/globaleaks/utils/crypto.py", line 321, in asymmetric_decrypt\n    
return SealedBox(prv_key).decrypt(data)\n\n  File "/usr/lib/python3/dist-packages/nacl/public.py", line 358, in decrypt\n    
plaintext = nacl.bindings.crypto_box_seal_open(\n\n  File "/usr/lib/python3/dist-packages/nacl/bindings/crypto_box.py", line 307, in crypto_box_seal_open\n    
plaintext = ffi.new("unsigned char[]", _mlen)\n\nValueError: negative array length\n

**Comment by alexfrab** [comment]
I have a question:

If a recipient changes their password on first login and "Enable administrators to change user passwords" is not selected in the settings, are the escrow keys for that recipient not generated?
It is possible to regenerate them after setting "Enable administrators to change user passwords" item?
