### ISSUE TITLE
Error 500 when ordering submission substatuses

### ISSUE THREAD

**Issue by aetdr** [globaleaks/GlobaLeaks#3066]
The error is reproducable in two different environments.

```
Version: 4.4.1

NameError Name not found globally.

Traceback (most recent call last):

  File "/usr/lib/python3/dist-packages/twisted/python/threadpool.py", line 250, in inContext
    result = inContext.theWork()

  File "/usr/lib/python3/dist-packages/twisted/python/threadpool.py", line 266, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)

  File "/usr/lib/python3/dist-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)

  File "/usr/lib/python3/dist-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)

  File "/usr/lib/python3/dist-packages/globaleaks/orm.py", line 152, in _wrap
    result = function(session, *args, **kwargs)

  File "/usr/lib/python3/dist-packages/globaleaks/handlers/admin/submission_statuses.py", line 143, in order_substatus_elements
    .filter(models.SubmissionSubStatus.tid == self.request.tid,

NameError: name 'self' is not defined

```

**Comment by evilaliv3** [comment]
Thank you for reporting this @aetdr; These seems actually a regression introduced since 4.3.0.

Let me fix this right away.
