### ISSUE TITLE
error after upgrade to v4.5.3

### ISSUE THREAD

**Issue by aetdr** [globaleaks/GlobaLeaks#3104]
Hi

After upgrade to v4.5.3 admins recieve mails with following error.

I believe the issue is triggered when a session is invalidated and the user clicks on some link. 
In the WebUI the red error alert is shown after clicking on a link when session is expired.

```
Version: 4.5.3

URL: /login

Error Message: TypeError: Cannot read properties of undefined (reading 'charAt')

Stacktrace:
[
  {
    "columnNumber": 258303,
    "lineNumber": 64,
    "fileName": "https://test.test.org/js/scripts.min.js",
    "functionName": "Object.role_l10n",
    "source": "    at Object.role_l10n (https://test.test.org/js/scripts.min.js:64:258303)"
  },
  {
    "columnNumber": 114534,
    "lineNumber": 8,
    "fileName": "https://test.test.org/js/scripts.min.js",
    "source": "    at https://test.test.org/js/scripts.min.js:8:114534"
  },
  {
    "columnNumber": 93074,
    "lineNumber": 8,
    "fileName": "https://test.test.org/js/scripts.min.js",
    "source": "    at https://test.test.org/js/scripts.min.js:8:93074"
  },
  {
    "columnNumber": 101305,
    "lineNumber": 8,
    "fileName": "https://test.test.org/js/scripts.min.js",
    "functionName": "d.$digest",
    "source": "    at d.$digest (https://test.test.org/js/scripts.min.js:8:101305)"
  },
  {
    "columnNumber": 103102,
    "lineNumber": 8,
    "fileName": "https://test.test.org/js/scripts.min.js",
    "functionName": "d.$apply",
    "source": "    at d.$apply (https://test.test.org/js/scripts.min.js:8:103102)"
  },
  {
    "columnNumber": 66695,
    "lineNumber": 8,
    "fileName": "https://test.test.org/js/scripts.min.js",
    "functionName": "_",
    "source": "    at _ (https://test.test.org/js/scripts.min.js:8:66695)"
  },
  {
    "columnNumber": 68929,
    "lineNumber": 8,
    "fileName": "https://test.test.org/js/scripts.min.js",
    "functionName": "C",
    "source": "    at C (https://test.test.org/js/scripts.min.js:8:68929)"
  },
  {
    "columnNumber": 68276,
    "lineNumber": 8,
    "fileName": "https://test.test.org/js/scripts.min.js",
    "functionName": "XMLHttpRequest.b.onload",
    "source": "    at XMLHttpRequest.b.onload (https://test.test.org/js/scripts.min.js:8:68276)"
  }
]

```

**Comment by evilaliv3** [comment]
Thank you,

I'm not able to reproduce it but yes probably its exactly happening what you describe and i'm able to fix the issue at least getting sure the exception is not triggered.
