### ISSUE TITLE
problem with deb.globaleaks.org

### ISSUE THREAD

**Issue by OvrAp3x** [globaleaks/GlobaLeaks#3141]
**Describe the bug**
Getting mail with this message every 1 hour.
```
Version: 4.7.6

twisted.internet.error.DNSLookupError DNS lookup failed

Traceback (most recent call last):

  File "/usr/lib/python3/dist-packages/globaleaks/jobs/job.py", line 49, in run
    yield self.operation()

  File "/usr/lib/python3/dist-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)

  File "/usr/lib/python3/dist-packages/twisted/python/failure.py", line 491, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)

  File "/usr/lib/python3/dist-packages/globaleaks/jobs/update_check.py", line 63, in operation
    packages_file = yield self.fetch_packages_file()

  File "/usr/lib/python3/dist-packages/twisted/internet/defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)

  File "/usr/lib/python3/dist-packages/twisted/internet/endpoints.py", line 974, in startConnectionAttempts
    raise error.DNSLookupError(

twisted.internet.error.DNSLookupError: DNS lookup failed: no results for hostname lookup: deb.globaleaks.org.

```
Looks like there is a n issue with the dns record for the deb.globaleaks.org server.
I have also tried this from a diffrent computer, and it also is not able to lookup the address.

**Comment by elbill** [comment]
When trying to update i received message "Failed to fetch http://deb.globaleaks.org/bionic/InRelease  Could not resolve 'deb.globaleaks.org'". This should be related.

**Comment by evilaliv3** [comment]
Thank you, we just migrated part of the infrastructure. It should be all working now.

**Comment by OvrAp3x** [comment]
Lookup still fails via google dns and cloudflare dns...
```
nslookup deb.globaleaks.org 1.1.1.1
Server:  one.one.one.one
Address:  1.1.1.1

DNS request timed out.
    timeout was 2 seconds.
DNS request timed out.
    timeout was 2 seconds.
*** one.one.one.one can't find deb.globaleaks.org: Non-existent domain
```
```
nslookup deb.globaleaks.org 8.8.8.8
Server:  dns.google
Address:  8.8.8.8

DNS request timed out.
    timeout was 2 seconds.
DNS request timed out.
    timeout was 2 seconds.
*** dns.google can't find deb.globaleaks.org: Non-existent domain
```

**Comment by evilaliv3** [comment]
Thank you @OvrAp3x; it should be fully propagated now, would you please recheck?

We are implemening DNSSEC! :)

**Comment by OvrAp3x** [comment]
yup! 
All ok it looks like :-)
