### ISSUE TITLE
Error on onion generation

### ISSUE THREAD

**Issue by frayber** [globaleaks/GlobaLeaks#3249]
globaleaks 4.9.9

When I try to enable custodian I got an error in email:

ValueError Inappropriate argument value (of correct type).

Traceback (most recent call last):

  File "/usr/lib/python3/dist-packages/globaleaks/services/onion.py", line 62, in load_onion_service
    from txtorcon.onion import EphemeralOnionServices

ModuleNotFoundError: No module named 'txtorcon.onion'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/usr/lib/python3/dist-packages/twisted/internet/defer.py", line 1384, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)

  File "/usr/lib/python3/dist-packages/twisted/python/failure.py", line 408, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)

  File "/usr/lib/python3/dist-packages/globaleaks/handlers/admin/node.py", line 197, in put
    self.request.language)

  File "/usr/lib/python3/dist-packages/twisted/python/threadpool.py", line 250, in inContext
    result = inContext.theWork()

  File "/usr/lib/python3/dist-packages/twisted/python/threadpool.py", line 266, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)

  File "/usr/lib/python3/dist-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)

  File "/usr/lib/python3/dist-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)

  File "/usr/lib/python3/dist-packages/globaleaks/orm.py", line 178, in _wrap
    result = function(session, *args, **kwargs)

  File "/usr/lib/python3/dist-packages/globaleaks/orm.py", line 209, in tw
    return f(session, *args, **kwargs)

  File "/usr/lib/python3/dist-packages/globaleaks/handlers/admin/node.py", line 149, in db_update_node
    db_refresh_tenant_cache(session, [tid])

  File "/usr/lib/python3/dist-packages/globaleaks/db/__init__.py", line 264, in db_refresh_tenant_cache
    State.onion_service.load_all_onion_services()

  File "/usr/lib/python3/dist-packages/globaleaks/services/onion.py", line 76, in load_all_onion_services
    self.load_onion_service(tid, self.state.tenants[tid].cache.onionservice, self.state.tenants[tid].cache.tor_onion_key)

  File "/usr/lib/python3/dist-packages/globaleaks/services/onion.py", line 67, in load_onion_service
    onion_service = EphemeralHiddenService(hs_loc, key)

  File "/usr/lib/python3/dist-packages/txtorcon/torconfig.py", line 477, in __init__
    'key_blob_or_type must be a string in the formats '

ValueError: key_blob_or_type must be a string in the formats "NEW:<ALGORITHM>" or "<ALGORITHM>:<KEY>"

**Comment by evilaliv3** [comment]
Thank you @frayber 

Actually this error is not related with the custodian user role but to a malfunctioning int the Tor management

We are aware of this issue that will be fixed in few days with the next release.

**Comment by frayber** [comment]
Thank you very much Giovanni.

**Comment by evilaliv3** [comment]
This should be fixed in release 4.10.0
