### ISSUE TITLE
error trying to save/export submission

### ISSUE THREAD

**Issue by zangels** [globaleaks/GlobaLeaks#3256]
**Describe the bug**
'Save/Export' submission function returns error

**To Reproduce**
1. Recipient login
2. Go to 'Submissions'
3. Click on 'save/export' in the list of submissions
![image](https://user-images.githubusercontent.com/109809253/182865014-916b22e1-b59d-4696-9ccb-0980fe92a019.png)
4. Error showned in a new page:` {"error_message": "InternalServerError [Unexpected]", "error_code": 1, "arguments": ["Unexpected"]}`
5. Enter the specific Submission
7. Click on 'save/export' on the top of the page report
8. Error showned in a new page:` {"error_message": "InternalServerError [Unexpected]", "error_code": 1, "arguments": ["Unexpected"]}`

**Expected behavior**
Zip file to be dowloaded.

**Desktop:**
 - OS: windows 10
 - Browser: Edge
 - Version [103.0.1264.77]

**Additional context**
Email sent to admin with this content:

Version: 4.9.9

KeyError Mapping key not found.

Traceback (most recent call last):

  File "/usr/lib/python3/dist-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)

  File "/usr/lib/python3/dist-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)

  File "/usr/lib/python3/dist-packages/globaleaks/handlers/export.py", line 130, in get
    files = yield prepare_tip_export(self.session.cc, tip_export)

  File "/usr/lib/python3/dist-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)

  File "/usr/lib/python3/dist-packages/globaleaks/handlers/export.py", line 109, in prepare_tip_export
    export_template = Templating().format_template(tip_export['notification']['export_template'], tip_export).encode()

KeyError: 'export_template'

**Comment by evilaliv3** [comment]
Thank you for reporting this.

Actually we are not able to reproduce this bug.

Would you please let us know:
- the langauge of the platform
- the language configured in the user preferences of the user that tried to export the data

Thank you

**Comment by zangels** [comment]
Hi!

They are both in PT-pt.

The user (recipient) doesn't have the hability to chose a language since I deleted the EN option.

Thank you

**Comment by zangels** [comment]
Yes, that's it!

I reinstalled the English option and the error does not happen

**Comment by evilaliv3** [comment]
Thank you for confirming that this is the case.

**Comment by zangels** [comment]
just to add that the user did not change the language, only the admin re-installed it and became available to any user (registered or not)

**Comment by evilaliv3** [comment]
Correct. When a user is created the language in their preference is being set to the defualt of the system.

At the time you probably created the system you probably had english enabled and english was set as the default

**Comment by zangels** [comment]
ok, noticed, thank you!

If you think it can help, and since I have a multi-site installation, I can test the creation of users on a platform where the EN language has already been excluded

**Comment by zangels** [comment]
Hi @evilaliv3 

What did I do:
- create sub-site (all new sub-sites created are in English by default, even if the main site only has PT-pt installed)
(in this new sub-site:)
- enable and set PT language as default, and deleted EN language
- create a test user, and configure it as the recipient of the submissions
- submit an anonymous submission
- access the submission through the recipient
- test save/export functionality => error
- as admin, include the EN language, but didn't set as default
- access the submission through the recipient user
- test the save/export functionality => download the zip file

When you say that EN was enabled and set by default when the system was created, do you mean that it could be different?
Should I do a fresh root install of the whole system? and opt for PT at that stage?

Thank you

**Comment by evilaliv3** [comment]
To be verfied if the problem still applies.
