### ISSUE TITLE
GlobaLeaks Exception -> KeyError Mapping key not found

### ISSUE THREAD

**Issue by peterknapp** [globaleaks/GlobaLeaks#3276]
We received two "GlobaLeaks Exception" emails with error "KeyError Mapping key not found."

After receiving these Emails the User-Passwords were not set or not valid anymore. The Admin could login to the system and we were able to send links to reset the user passwords.

This happened without any action from our side.

We are clueless what caused this errors...

**First Email**

Version: 4.10.10

KeyError Mapping key not found.

Traceback (most recent call last):

  File "/usr/lib/python3/dist-packages/twisted/internet/defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)

  File "/usr/lib/python3/dist-packages/globaleaks/rest/decorators.py", line 104, in errback
    raise err

  File "/usr/lib/python3/dist-packages/twisted/internet/defer.py", line 151, in maybeDeferred
    result = f(*args, **kw)

  File "/usr/lib/python3/dist-packages/globaleaks/handlers/operation.py", line 25, in put
    return func(self, request['args'], *args, **kwargs)

  File "/usr/lib/python3/dist-packages/globaleaks/handlers/admin/operation.py", line 264, in set_user_password
    req_args['password'])

KeyError: 'password'

**Second Email**

Version: 4.10.10

KeyError Mapping key not found.

Traceback (most recent call last):

  File "/usr/lib/python3/dist-packages/twisted/internet/defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)

  File "/usr/lib/python3/dist-packages/globaleaks/rest/decorators.py", line 104, in errback
    raise err

  File "/usr/lib/python3/dist-packages/twisted/internet/defer.py", line 151, in maybeDeferred
    result = f(*args, **kw)

  File "/usr/lib/python3/dist-packages/globaleaks/handlers/operation.py", line 25, in put
    return func(self, request['args'], *args, **kwargs)

  File "/usr/lib/python3/dist-packages/globaleaks/handlers/admin/operation.py", line 264, in set_user_password
    req_args['password'])

KeyError: 'password'

**Comment by evilaliv3** [comment]
Thank you @peterknapp for reporting this.

I will try to replicate the situation but i think the this exception seems to have been triggered by an user while changing the password of a user and seems to me related to the fact that the administrator was using probably a previous version of the client; I think the admin had the previous client loaded in the tab already.

**Comment by peterknapp** [comment]
Hi, thank you for coming back to this issue so fast.

Perhaps to clarify a bit more: Since we have until now a very limited installation with only 1 Admin and 2 Users, I can say, that there was no action from a User or Admin generating this error. The passwords of both Users were "suddenly" not valid anymore, only for the Admin.

Can I kindly ask you to look into this issue too?
https://github.com/globaleaks/GlobaLeaks/issues/3275
