### ISSUE TITLE
Exception when selecting Automatic HTTPS configuration on verions 4.10.11 top 4.10.12

### ISSUE THREAD

**Issue by DanWin** [globaleaks/GlobaLeaks#3295]
**Describe the bug**
After installing the latest version 4.10.12 (had the same issue with 4.10.11) on Debian 11 and completing the setup wizard, I got an exception when setting up the SSL certificate for HTTPS.

**To Reproduce**
1. Install globaleaks on Debian 11
2. Complete setup wizard
3. Go to network settings
4. Add Hostname
5. Select automatic configuration

**Expected behavior**
SSL certificate should be setup

**Screenshots**
![image](https://user-images.githubusercontent.com/3327912/195563011-8fac4385-ef9c-4831-851b-47a2c9b04c78.png)

**Desktop (please complete the following information):**
 - OS: Debian 11
 - Browser TorBrowser / Firefox
 - Version 11.5.2 / 106

**Additional context**
2022-10-13 09:25:06+0000 [-] twistd 20.3.0 (/usr/bin/python3 3.9.2) starting up.
2022-10-13 09:25:06+0000 [-] reactor class: twisted.internet.epollreactor.EPollReactor.
2022-10-13 09:25:07+0000 [-] Starting factory <Site object at 0x7fb8d2a49880>
2022-10-13 09:25:07+0000 [-] GlobaLeaks is now running and accessible at the following urls:
2022-10-13 09:25:07+0000 [-] - [HTTP]	--> http://0.0.0.0
2022-10-13 09:25:07+0000 [-] - [Tor]:	--> http://xxxx.onion
2022-10-13 09:25:07+0000 [-] Starting factory _HTTP11ClientFactory(<function HTTPConnectionPool._newConnection.<locals>.quiescentCallback at 0x7fb8d2952700>, <twisted.internet.endpoints._WrapperEndpoint object at 0x7fb8d2a49b50>)
2022-10-13 09:25:07+0000 [-] [E] Successfully connected to Tor control port
2022-10-13 09:25:07+0000 [-] [E] [1] Setting up the onion service xxxx.onion
2022-10-13 09:25:07+0000 [-] Stopping factory _HTTP11ClientFactory(<function HTTPConnectionPool._newConnection.<locals>.quiescentCallback at 0x7fb8d2952700>, <twisted.internet.endpoints._WrapperEndpoint object at 0x7fb8d2a49b50>)
2022-10-13 09:25:12+0000 [-] [E] [1] Initialization of onion-service xxxx.onion completed.
2022-10-13 09:32:16+0000 [-] [E] Unhandled exception raised:
2022-10-13 09:32:16+0000 [-] [E] AttributeError Attribute not found.\n\nTraceback (most recent call last):\n\n  File "/usr/lib/python3/dist-packages/twisted/python/threadpool.py", line 250, in inContext\n    result = inContext.theWork()\n\n  File "/usr/lib/python3/dist-packages/twisted/python/threadpool.py", line 266, in <lambda>\n    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)\n\n  File "/usr/lib/python3/dist-packages/twisted/python/context.py", line 122, in callWithContext\n    return self.currentContext().callWithContext(ctx, func, *args, **kw)\n\n  File "/usr/lib/python3/dist-packages/twisted/python/context.py", line 85, in callWithContext\n    return func(*args,**kw)\n\n  File "/usr/lib/python3/dist-packages/globaleaks/orm.py", line 178, in _wrap\n    result = function(session, *args, **kwargs)\n\n  File "/usr/lib/python3/dist-packages/globaleaks/orm.py", line 209, in tw\n    return f(session, *args, **kwargs)\n\n  File "/usr/lib/python3/dist-packages/globaleaks/handlers/admin/https.py", line 61, in db_acme_cert_request\n    acme_accnt_key = db_generate_acme_key(session, tid)\n\n  File "/usr/lib/python3/dist-packages/globaleaks/handlers/admin/https.py", line 47, in db_generate_acme_key\n    key = tls.generate_rsa_key(Settings.rsa_key_bits)\n\nAttributeError: module 'globaleaks.utils.tls' has no attribute 'generate_rsa_key'\n
2022-10-13 09:32:17+0000 [-] Starting factory <twisted.mail.smtp.ESMTPSenderFactory object at 0x7fb8d2886e80>
2022-10-13 09:32:18+0000 [-] Stopping factory <twisted.mail.smtp.ESMTPSenderFactory object at 0x7fb8d2886e80>
2022-10-13 09:32:19+0000 [-] Starting factory <twisted.mail.smtp.ESMTPSenderFactory object at 0x7fb8c3569520>
2022-10-13 09:32:19+0000 [-] Stopping factory <twisted.mail.smtp.ESMTPSenderFactory object at 0x7fb8c3569520>
2022-10-13 09:32:20+0000 [-] Starting factory <twisted.mail.smtp.ESMTPSenderFactory object at 0x7fb8c34805b0>
2022-10-13 09:32:21+0000 [-] Stopping factory <twisted.mail.smtp.ESMTPSenderFactory object at 0x7fb8c34805b0>

**Comment by evilaliv3** [comment]
Thank you for reporting this @DanWin 

We are aware of the bug and we are emitting a patch that will be released with a minor uptate 4.10.13

**Comment by DanWin** [comment]
Thanks for the quick fix. I can confirm this solves the issue.
