### ISSUE TITLE
Exception UnicodeDecodeError Unicode decoding error.

### ISSUE THREAD

**Issue by MarcoAppleby** [globaleaks/GlobaLeaks#3312]
Hi,

I've received this email from my globaleaks platform.

How can I fix this?

====================
Version: 4.10.14

UnicodeDecodeError Unicode decoding error.

Traceback (most recent call last):

  File "/usr/lib/python3/dist-packages/twisted/web/server.py", line 199, in process
    self.render(resrc)

  File "/usr/lib/python3/dist-packages/twisted/web/server.py", line 259, in render
    body = resrc.render(self)

  File "/usr/lib/python3/dist-packages/globaleaks/rest/api.py", line 373, in render
    self.preprocess(request)

  File "/usr/lib/python3/dist-packages/globaleaks/rest/api.py", line 363, in preprocess
    request.language = self.detect_language(request)

  File "/usr/lib/python3/dist-packages/globaleaks/rest/api.py", line 553, in detect_language
    for language in request.headers.get(b'accept-language', b'').decode().split(","):

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xbf in position 9: invalid start byte

**Comment by evilaliv3** [comment]
Thank you @MarcoAppleby for reporting this.

GlobaLeaks leaves unfiltered any exception generated in the software so we could get to know it hand improve the software.

In this specific case you could ignore this exception as long as it do not repeat and we will proceed analyzing it.
