### ISSUE TITLE
No reports list and error mail: GlobaLeaks Exception

### ISSUE THREAD

**Issue by stefan-h3** [globaleaks/GlobaLeaks#3324]
After the editor logs in, an empty list appears and submitted reports cannot be seen. However, if I click on the link in the notification email, I go directly to the report, which I can then view. However, the overview remains empty. 
After logging in and trying to view the list of reports, we receive an error mail from the system with the following content:

Platform: Flüsterbox
Host: [fluesterbox.h3-digital.de](http://fluesterbox.h3-digital.de/) (ctruele55rz2zwqvb2ttptnb7pjpasyul7pznzu4vlt6txmgzvtnuzyd.onion)
Version: 4.9.9

URL: /recipient/reports

User Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 16_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) CriOS/108.0.5359.112 Mobile/15E148 Safari/604.1

Error Message: TypeError: undefined is not an object (evaluating '[t.context.name](http://t.context.name/)')

Stacktrace:
[
  {
    "columnNumber": 611259,
    "lineNumber": 64,
    "fileName": "https://fluesterbox.h3-digital.de/js/scripts.min.js",
    "source": "@https://fluesterbox.h3-digital.de/js/scripts.min.js:64:611259"
  },
  {
    "columnNumber": 1545,
    "lineNumber": 8,
    "fileName": "https://fluesterbox.h3-digital.de/js/scripts.min.js",
    "functionName": "x",
    "source": "~~~~~~@~~~~~~://[fluesterbox.h3-digital.de/js/scripts.min.js:8:1545](http://fluesterbox.h3-digital.de/js/scripts.min.js:8:1545)"
  },
  {
    "columnNumber": 611156,
    "lineNumber": 64,
    "fileName": "https://fluesterbox.h3-digital.de/js/scripts.min.js",
    "source": "@https://fluesterbox.h3-digital.de/js/scripts.min.js:64:611156"
  },
  {
    "fileName": "[native code]",
    "source": "@[native code]"
  },
  {
    "columnNumber": 26578,
    "lineNumber": 8,
    "fileName": "https://fluesterbox.h3-digital.de/js/scripts.min.js",
    "functionName": "instantiate",
    "source": "~~~~~~@~~~~~~://[fluesterbox.h3-digital.de/js/scripts.min.js:8:26578](http://fluesterbox.h3-digital.de/js/scripts.min.js:8:26578)"
  },
  {
    "columnNumber": 60596,
    "lineNumber": 8,
    "fileName": "https://fluesterbox.h3-digital.de/js/scripts.min.js",
    "source": "@https://fluesterbox.h3-digital.de/js/scripts.min.js:8:60596"
  },
  {
    "columnNumber": 5239,
    "lineNumber": 33,
    "fileName": "https://fluesterbox.h3-digital.de/js/scripts.min.js",
    "functionName": "link",
    "source": "~~~~~~@~~~~~~://[fluesterbox.h3-digital.de/js/scripts.min.js:33:5239](http://fluesterbox.h3-digital.de/js/scripts.min.js:33:5239)"
  },
  {
    "columnNumber": 57272,
    "lineNumber": 8,
    "fileName": "https://fluesterbox.h3-digital.de/js/scripts.min.js",
    "functionName": "Re",
    "source": "~~~~~~@~~~~~~://[fluesterbox.h3-digital.de/js/scripts.min.js:8:57272](http://fluesterbox.h3-digital.de/js/scripts.min.js:8:57272)"
  },
  {
    "columnNumber": 52063,
    "lineNumber": 8,
    "fileName": "https://fluesterbox.h3-digital.de/js/scripts.min.js",
    "functionName": "re",
    "source": "~~~~~~@~~~~~~://[fluesterbox.h3-digital.de/js/scripts.min.js:8:52063](http://fluesterbox.h3-digital.de/js/scripts.min.js:8:52063)"
  },
  {
    "columnNumber": 44919,
    "lineNumber": 8,
    "fileName": "https://fluesterbox.h3-digital.de/js/scripts.min.js",
    "source": "@https://fluesterbox.h3-digital.de/js/scripts.min.js:8:44919"
  },
  {
    "columnNumber": 44132,
    "lineNumber": 8,
    "fileName": "https://fluesterbox.h3-digital.de/js/scripts.min.js",
    "source": "@https://fluesterbox.h3-digital.de/js/scripts.min.js:8:44132"
  },
  {
    "columnNumber": 4849,
    "lineNumber": 33,
    "fileName": "https://fluesterbox.h3-digital.de/js/scripts.min.js",
    "functionName": "m",
    "source": "~~~~~~@~~~~~~://[fluesterbox.h3-digital.de/js/scripts.min.js:33:4849](http://fluesterbox.h3-digital.de/js/scripts.min.js:33:4849)"
  },
  {
    "columnNumber": 104254,
    "lineNumber": 8,
    "fileName": "https://fluesterbox.h3-digital.de/js/scripts.min.js",
    "functionName": "$broadcast",
    "source": "$~~~~~~@~~~~~~://[fluesterbox.h3-digital.de/js/scripts.min.js:8:104254](http://fluesterbox.h3-digital.de/js/scripts.min.js:8:104254)"
  },
  {
    "columnNumber": 2975,
    "lineNumber": 33,
    "fileName": "https://fluesterbox.h3-digital.de/js/scripts.min.js",
    "source": "@https://fluesterbox.h3-digital.de/js/scripts.min.js:33:2975"
  },
  {
    "columnNumber": 95609,
    "lineNumber": 8,
    "fileName": "https://fluesterbox.h3-digital.de/js/scripts.min.js",
    "source": "@https://fluesterbox.h3-digital.de/js/scripts.min.js:8:95609"
  },
  {
    "columnNumber": 95746,
    "lineNumber": 8,
    "fileName": "https://fluesterbox.h3-digital.de/js/scripts.min.js",
    "source": "@https://fluesterbox.h3-digital.de/js/scripts.min.js:8:95746"
  },
  {
    "columnNumber": 101109,
    "lineNumber": 8,
    "fileName": "https://fluesterbox.h3-digital.de/js/scripts.min.js",
    "functionName": "$digest",
    "source": "$~~~~~~@~~~~~~://[fluesterbox.h3-digital.de/js/scripts.min.js:8:101109](http://fluesterbox.h3-digital.de/js/scripts.min.js:8:101109)"
  },
  {
    "columnNumber": 103109,
    "lineNumber": 8,
    "fileName": "https://fluesterbox.h3-digital.de/js/scripts.min.js",
    "functionName": "$apply",
    "source": "$~~~~~~@~~~~~~://[fluesterbox.h3-digital.de/js/scripts.min.js:8:103109](http://fluesterbox.h3-digital.de/js/scripts.min.js:8:103109)"
  },
  {
    "columnNumber": 66701,
    "lineNumber": 8,
    "fileName": "https://fluesterbox.h3-digital.de/js/scripts.min.js",
    "functionName": "_",
    "source": "~~~~~~@~~~~~~://[fluesterbox.h3-digital.de/js/scripts.min.js:8:66701](http://fluesterbox.h3-digital.de/js/scripts.min.js:8:66701)"
  },
  {
    "columnNumber": 68930,
    "lineNumber": 8,
    "fileName": "https://fluesterbox.h3-digital.de/js/scripts.min.js",
    "functionName": "C",
    "source": "~~~~~~@~~~~~~://[fluesterbox.h3-digital.de/js/scripts.min.js:8:68930](http://fluesterbox.h3-digital.de/js/scripts.min.js:8:68930)"
  },
  {
    "columnNumber": 68277,
    "lineNumber": 8,
    "fileName": "https://fluesterbox.h3-digital.de/js/scripts.min.js",
    "source": "@https://fluesterbox.h3-digital.de/js/scripts.min.js:8:68277"
  }
]

How can we solve the problem?
Thanks in advance

**Comment by evilaliv3** [comment]
Thank you for reporting this @stefan-h3

Is there any reconfiguration of contexts or questionnaires that you applied recently?

Since you are running an old version i invite you to update to the current stable release (4.10.14)

Then i invite you to retry and eventually check if you have any error in the javascript console of the browser.

**Comment by stefan-h3** [comment]
Hi evilaviv,

yes, we have created a new questionnaire and included it in the context. When we noticed the problem, we undid it, but unfortunately it didn't change the problem.
I have updated the software, but unfortunately the problem persists. 
Do you have any other idea how we can fix it? Here is the console message when I am on the report list:

scripts.min.js:8 TypeError: Cannot read properties of undefined (reading 'name')
    at scripts.min.js:64:574186
    at Object.x [as forEach] (scripts.min.js:8:1541)
    at new <anonymous> (scripts.min.js:64:574075)
    at Object.instantiate (scripts.min.js:8:26541)
    at scripts.min.js:8:60587
    at Object.link (scripts.min.js:33:5238)
    at scripts.min.js:8:7410
    at Le (scripts.min.js:8:57273)
    at re (scripts.min.js:8:52063)
    at scripts.min.js:8:44920 `<main id="Content" data-ng-class="{'col-md-10': sidebar, 'col-md-12': !sidebar}" data-ng-view="">`
(anonym) @ scripts.min.js:8
(anonym) @ scripts.min.js:8
Le @ scripts.min.js:8
re @ scripts.min.js:8
(anonym) @ scripts.min.js:8
(anonym) @ scripts.min.js:8
(anonym) @ scripts.min.js:8
a @ scripts.min.js:8
v @ scripts.min.js:8
m @ scripts.min.js:33
$broadcast @ scripts.min.js:8
(anonym) @ scripts.min.js:33
(anonym) @ scripts.min.js:8
(anonym) @ scripts.min.js:8
$digest @ scripts.min.js:8
$apply @ scripts.min.js:8
_ @ scripts.min.js:8
C @ scripts.min.js:8
b.onload @ scripts.min.js:8
load (async)
(anonym) @ scripts.min.js:8
(anonym) @ scripts.min.js:8
(anonym) @ scripts.min.js:8
(anonym) @ scripts.min.js:8
(anonym) @ scripts.min.js:8
$digest @ scripts.min.js:8
$apply @ scripts.min.js:8
_ @ scripts.min.js:8
C @ scripts.min.js:8
b.onload @ scripts.min.js:8
load (async)
(anonym) @ scripts.min.js:8
(anonym) @ scripts.min.js:8
(anonym) @ scripts.min.js:8
(anonym) @ scripts.min.js:8
(anonym) @ scripts.min.js:8
$digest @ scripts.min.js:8
(anonym) @ scripts.min.js:8
t.completeTask @ scripts.min.js:8
(anonym) @ scripts.min.js:8
setTimeout (async)
r.defer @ scripts.min.js:8
$evalAsync @ scripts.min.js:8
(anonym) @ scripts.min.js:8
u @ scripts.min.js:8
f @ scripts.min.js:8
p @ scripts.min.js:8
resolve @ scripts.min.js:8
d @ scripts.min.js:64
Promise.then (async)
i @ scripts.min.js:64
d @ scripts.min.js:64
Promise.then (async)
i @ scripts.min.js:64
d @ scripts.min.js:64
Promise.then (async)
i @ scripts.min.js:64
d @ scripts.min.js:64
Promise.then (async)
i @ scripts.min.js:64
d @ scripts.min.js:64
Promise.then (async)
i @ scripts.min.js:64
d @ scripts.min.js:64
Promise.then (async)
i @ scripts.min.js:64
d @ scripts.min.js:64
Promise.then (async)
i @ scripts.min.js:64
d @ scripts.min.js:64
Promise.then (async)
i @ scripts.min.js:64
d @ scripts.min.js:64
Promise.then (async)
i @ scripts.min.js:64
d @ scripts.min.js:64
Promise.then (async)
i @ scripts.min.js:64
d @ scripts.min.js:64
Promise.then (async)
i @ scripts.min.js:64
d @ scripts.min.js:64
Promise.then (async)
i @ scripts.min.js:64
d @ scripts.min.js:64
Promise.then (async)
i @ scripts.min.js:64
d @ scripts.min.js:64
Promise.then (async)
i @ scripts.min.js:64
d @ scripts.min.js:64
Promise.then (async)
i @ scripts.min.js:64
d @ scripts.min.js:64
Promise.then (async)
i @ scripts.min.js:64
d @ scripts.min.js:64
Promise.then (async)
i @ scripts.min.js:64
d @ scripts.min.js:64
Promise.then (async)
i @ scripts.min.js:64
d @ scripts.min.js:64
Promise.then (async)
i @ scripts.min.js:64
d @ scripts.min.js:64
Promise.then (async)
i @ scripts.min.js:64
d @ scripts.min.js:64
Promise.then (async)
i @ scripts.min.js:64
d @ scripts.min.js:64
Promise.then (async)
i @ scripts.min.js:64
d @ scripts.min.js:64
Promise.then (async)
i @ scripts.min.js:64
d @ scripts.min.js:64
Promise.then (async)
i @ scripts.min.js:64
d @ scripts.min.js:64
Promise.then (async)
i @ scripts.min.js:64
d @ scripts.min.js:64
Promise.then (async)
i @ scripts.min.js:64
d @ scripts.min.js:64
Promise.then (async)
i @ scripts.min.js:64
d @ scripts.min.js:64
Promise.then (async)
i @ scripts.min.js:64
d @ scripts.min.js:64
Promise.then (async)
i @ scripts.min.js:64
d @ scripts.min.js:64

**Comment by evilaliv3** [comment]
Thank you  @stefan-h3  for the feedback.

Is it possible for you to share me a copy of the questionnaire that caused the problem ? 


I invite you as well to join our community space where we could chat and try to find a solution together: https://community.globaleaks.org

**Comment by yevon** [comment]
Hi excatly same issue here, same javascript error and unable to see any report list, but following the email link it works just fine.

**Comment by yevon** [comment]
Is it possible that it is due to special characters issue? We do use it in catalan, and we use ' and accents quite often. As far as I understand the report custom config should not affect this as this report just shows rows with titles, dates and descriptions

**Comment by evilaliv3** [comment]
Thank you @stefan-h3 actually i've answered to you on the other ticket that contains already the solution.
