### ISSUE TITLE
Grant/revoke access error when performed through case management system list

### ISSUE THREAD

**Issue by elbill** [globaleaks/GlobaLeaks#3412]
### What version of GlobaLeaks are you using?

4.11.1

### What browser(s) are you seeing the problem on?

Chrome, Microsoft Edge

### What operating system(s) are you seeing the problem on?

Windows

### Describe the issue

Grant access feature gives an error when used through the cms list. (check one or more checkboxes and press grant access icon)
It works properly when viewing individual reports and grant access from that screen.

**Comment by elbill** [comment]
also received this error:
PermissionError Not enough permissions.

Traceback (most recent call last):

  File "/usr/lib/python3/dist-packages/twisted/internet/defer.py", line 151, in maybeDeferred
    result = f(*args, **kw)

  File "/usr/lib/python3/dist-packages/globaleaks/rest/decorators.py", line 57, in wrapper
    return f(self, *args, **kwargs)

  File "/usr/lib/python3/dist-packages/globaleaks/handlers/script.py", line 29, in get
    return self.write_file('script.js', path)

  File "/usr/lib/python3/dist-packages/globaleaks/handlers/base.py", line 298, in write_file
    fp = self.open_file(fp)

  File "/usr/lib/python3/dist-packages/globaleaks/handlers/base.py", line 294, in open_file
    return open(filepath, 'rb')

PermissionError: [Errno 13] Permission denied: '/var/globaleaks/scripts/20'

**Comment by evilaliv3** [comment]
Bug confirmed and fixed. The fix will be included in release 4.11.2.

Regarding the exception you received it is not related to this issue. You have probably a javascript script with wrong permissions; probably you should fix them with chmod assigning the file to the user 'globaleaks'
