### ISSUE TITLE
Possible bug in version 4.11.5  - KeyError Mapping key not found.

### ISSUE THREAD

**Issue by aetdr** [globaleaks/GlobaLeaks#3450]
### What version of GlobaLeaks are you using?

Version: 4.11.5

### What browser(s) are you seeing the problem on?

All

### What operating system(s) are you seeing the problem on?

Windows

### Describe the issue

Hi @evilaliv3 

We have seen a few of these since upgrade to v4.11.5

```
Version: 4.11.5

KeyError Mapping key not found.

Traceback (most recent call last):

  File "/usr/lib/python3/dist-packages/twisted/internet/defer.py", line 151, in maybeDeferred
    result = f(*args, **kw)

  File "/usr/lib/python3/dist-packages/globaleaks/handlers/operation.py", line 25, in put
    return func(self, request['args'], *args, **kwargs)

  File "/usr/lib/python3/dist-packages/globaleaks/handlers/admin/operation.py", line 263, in set_user_password
    req_args['password'])

KeyError: 'password'

```

**Comment by evilaliv3** [comment]
Hello @aetdr, do you know which operation where you performing when you got this exception?

**Comment by aetdr** [comment]
Hi @evilaliv3 

I don't know what triggered the exception. Now I am seeing something similar, maybe related?


```
Version: 4.11.5

KeyError Mapping key not found.

Traceback (most recent call last):

  File "/usr/lib/python3/dist-packages/twisted/internet/defer.py", line 151, in maybeDeferred
    result = f(*args, **kw)

  File "/usr/lib/python3/dist-packages/globaleaks/rest/decorators.py", line 58, in wrapper
    return f(self, *args, **kwargs)

  File "/usr/lib/python3/dist-packages/globaleaks/rest/decorators.py", line 32, in wrapper
    return f(self, *args, **kwargs)

  File "/usr/lib/python3/dist-packages/globaleaks/rest/decorators.py", line 44, in wrapper
    return f(self, *args, **kwargs)

  File "/usr/lib/python3/dist-packages/globaleaks/handlers/operation.py", line 25, in put
    return func(self, request['args'], *args, **kwargs)

  File "/usr/lib/python3/dist-packages/globaleaks/handlers/rtip.py", line 633, in grant_tip_access
    return tw(db_grant_tip_access, self.request.tid, self.session.user_id, self.session.cc, rtip_id, req_args['receiver'])

KeyError: 'receiver'
```

**Comment by evilaliv3** [comment]
@aetdr: Are you running the official client or is it possible that you have edited the javascript application?

**Comment by aetdr** [comment]
Hi @evilaliv3 

There is a simple custom script that modifies some UI elements.
Other than that, it is the standard, unmodified js client.

**Comment by evilaliv3** [comment]
Thank you for the update. We will try to do some tests of configuration to see if we manage to replicate the problem.
