### ISSUE TITLE
Migration issue from 4.1.16 to 4.2.0 and above

### ISSUE THREAD

**Issue by daniego** [globaleaks/GlobaLeaks#3457]
### What version of GlobaLeaks are you using?

4.1.16

### What operating system(s) are you seeing the problem on?

Linux

### Describe the issue

Hi,
while upgrading from version 4.0.5 to the latest available we encounter a migration issue and by upgrading version by version I've found that the problem happens between 4.1.16 to 4.2.0 and above giving us this error
```
2023-05-03 11:13:24+0000 [-] twistd 18.9.0 (/usr/bin/python3 3.8.10) starting up.
2023-05-03 11:13:24+0000 [-] reactor class: twisted.internet.epollreactor.EPollReactor.
2023-05-03 11:13:26+0000 [-] [E] Found an already initialized database version: 52
2023-05-03 11:13:26+0000 [-] [E] Performing schema migration from version 52 to version 64
2023-05-03 11:13:26+0000 [-] [I] Updating DB from version 52 to version 53
2023-05-03 11:13:27+0000 [-] [I] Migrating table:
2023-05-03 11:13:27+0000 [-] [I]  * ArchivedSchema [#13]
2023-05-03 11:13:27+0000 [-] [I]  * Comment [#170]
2023-05-03 11:13:27+0000 [-] [I]  * Config [#116]
2023-05-03 11:13:27+0000 [-] [I]  * ConfigL10N [#77]
2023-05-03 11:13:27+0000 [-] [I]  * Context [#1]
2023-05-03 11:13:27+0000 [-] [I]  * ContextImg [#1]
2023-05-03 11:13:27+0000 [-] [I]  * EnabledLanguage [#1]
2023-05-03 11:13:27+0000 [-] [I]  * Field [#81]
2023-05-03 11:13:27+0000 [-] [I]  * FieldAttr [#289]
2023-05-03 11:13:27+0000 [-] [I]  * FieldOption [#38]
2023-05-03 11:13:27+0000 [-] [I]  * FieldOptionTriggerField [#8]
2023-05-03 11:13:27+0000 [-] [I]  * File [#5]
2023-05-03 11:13:27+0000 [-] [I]  * InternalFile [#42]
2023-05-03 11:13:27+0000 [-] [I]  * InternalTip [#276]
2023-05-03 11:13:28+0000 [-] [I]  * InternalTipAnswers [#276]
2023-05-03 11:13:28+0000 [-] [I]  * Questionnaire [#4]
2023-05-03 11:13:28+0000 [-] [I]  * ReceiverContext [#2]
2023-05-03 11:13:28+0000 [-] [I]  * ReceiverFile [#41]
2023-05-03 11:13:28+0000 [-] [I]  * ReceiverTip [#296]
2023-05-03 11:13:28+0000 [-] [I]  * SubmissionStatus [#3]
2023-05-03 11:13:28+0000 [-] [I]  * SubmissionStatusChange [#269]
2023-05-03 11:13:28+0000 [-] [I]  * Step [#4]
2023-05-03 11:13:28+0000 [-] [I]  * Tenant [#1]
2023-05-03 11:13:28+0000 [-] [I]  * User [#6]
2023-05-03 11:13:28+0000 [-] [I]  * WhistleblowerTip [#276]
2023-05-03 11:13:28+0000 [-] [I] Migration stats:
2023-05-03 11:13:28+0000 [-] [I]  * ArchivedSchema table migrated (13 entry(s))
2023-05-03 11:13:28+0000 [-] [I]  * Comment table migrated (170 entry(s))
2023-05-03 11:13:28+0000 [-] [I]  * Config table migrated (117 entry(s))
2023-05-03 11:13:28+0000 [-] [I]  * ConfigL10N table migrated (77 entry(s))
2023-05-03 11:13:28+0000 [-] [I]  * Context table migrated (1 entry(s))
2023-05-03 11:13:28+0000 [-] [I]  * ContextImg table migrated (1 entry(s))
2023-05-03 11:13:28+0000 [-] [I]  * CustomTexts table migrated (0 entry(s))
2023-05-03 11:13:28+0000 [-] [I]  * EnabledLanguage table migrated (1 entry(s))
2023-05-03 11:13:28+0000 [-] [I]  * Field table migrated (81 entry(s))
2023-05-03 11:13:28+0000 [-] [I]  * FieldAttr table migrated (289 entry(s))
2023-05-03 11:13:28+0000 [-] [I]  * FieldOption table migrated (38 entry(s))
2023-05-03 11:13:28+0000 [-] [I]  * FieldOptionTriggerField table migrated (8 entry(s))
2023-05-03 11:13:28+0000 [-] [I]  * FieldOptionTriggerStep table migrated (0 entry(s))
2023-05-03 11:13:28+0000 [-] [I]  * File table migrated (5 entry(s))
2023-05-03 11:13:28+0000 [-] [I]  * IdentityAccessRequest table migrated (0 entry(s))
2023-05-03 11:13:28+0000 [-] [I]  * InternalFile table migrated (42 entry(s))
2023-05-03 11:13:28+0000 [-] [I]  * InternalTip table migrated (276 entry(s))
2023-05-03 11:13:28+0000 [-] [I]  * InternalTipAnswers table migrated (276 entry(s))
2023-05-03 11:13:28+0000 [-] [I]  * InternalTipData table migrated (0 entry(s))
2023-05-03 11:13:28+0000 [-] [I]  * Mail table migrated (0 entry(s))
2023-05-03 11:13:28+0000 [-] [I]  * Message table migrated (0 entry(s))
2023-05-03 11:13:28+0000 [-] [I]  * Questionnaire table migrated (4 entry(s))
2023-05-03 11:13:28+0000 [-] [I]  * ReceiverContext table migrated (2 entry(s))
2023-05-03 11:13:28+0000 [-] [I]  * ReceiverFile table migrated (41 entry(s))
2023-05-03 11:13:28+0000 [-] [I]  * ReceiverTip table migrated (296 entry(s))
2023-05-03 11:13:28+0000 [-] [I]  * Redirect table migrated (0 entry(s))
2023-05-03 11:13:28+0000 [-] [I]  * SubmissionStatus table migrated (3 entry(s))
2023-05-03 11:13:28+0000 [-] [I]  * SubmissionSubStatus table migrated (0 entry(s))
2023-05-03 11:13:28+0000 [-] [I]  * SubmissionStatusChange table migrated (269 entry(s))
2023-05-03 11:13:28+0000 [-] [I]  * Step table migrated (4 entry(s))
2023-05-03 11:13:28+0000 [-] [I]  * Subscriber table migrated (0 entry(s))
2023-05-03 11:13:28+0000 [-] [I]  * Tenant table migrated (1 entry(s))
2023-05-03 11:13:28+0000 [-] [I]  * User table migrated (6 entry(s))
2023-05-03 11:13:28+0000 [-] [I]  * UserImg table migrated (0 entry(s))
2023-05-03 11:13:28+0000 [-] [I]  * WhistleblowerFile table migrated (0 entry(s))
2023-05-03 11:13:28+0000 [-] [I]  * WhistleblowerTip table migrated (276 entry(s))
2023-05-03 11:13:28+0000 [-] [I] Updating DB from version 53 to version 54
2023-05-03 11:13:28+0000 [-] [I] Migrating table:
2023-05-03 11:13:28+0000 [-] [I]  * ArchivedSchema [#13]
2023-05-03 11:13:28+0000 [-] [I]  * Comment [#170]
2023-05-03 11:13:28+0000 [-] [I]  * Config [#117]
2023-05-03 11:13:28+0000 [-] [I]  * ConfigL10N [#77]
2023-05-03 11:13:28+0000 [-] [I]  * Context [#1]
2023-05-03 11:13:28+0000 [-] [I]  * EnabledLanguage [#1]
2023-05-03 11:13:28+0000 [-] [I]  * Field [#81]
2023-05-03 11:13:28+0000 [-] [I]  * FieldAttr [#289]
2023-05-03 11:13:28+0000 [-] [I]  * FieldOption [#38]
2023-05-03 11:13:28+0000 [-] [I]  * FieldOptionTriggerField [#8]
2023-05-03 11:13:28+0000 [-] [I]  * File [#5]
2023-05-03 11:13:28+0000 [-] [E] Failure while migrating table File: (sqlite3.IntegrityError) UNIQUE constraint failed: file.tid, file.name\n[SQL: INSERT INTO file (tid, id, name) VALUES (?, ?, ?)]\n[parameters: ((1, '861d22b4-3204-4561-8573-cc2a607d9780', 'favicon'), (1, '290cdca8-ad6e-4c48-b933-5a50452f4f61', 'css'), (1, 'cf41230e-efe0-4cca-98aa-9a10f9f6745a', 'logo'), (1, 'd85377d6-8ddc-4b8f-a2b6-49e71b7443c0', 'InformativaPrivacy.pdf'), (1, '8d10c16b-4676-4587-9c33-bad3f4d7550e', 'InformativaPrivacy.pdf'), (1, 'fcaad5a9-4611-4215-a4ed-8910fa0d4d37', 'fcaad5a9-4611-4215-a4ed-8910fa0d4d37'))]\n(Background on this error at: http://sqlalche.me/e/gkpj)
2023-05-03 11:13:28+0000 [-] [E] Failure: (sqlite3.IntegrityError) UNIQUE constraint failed: file.tid, file.name\n[SQL: INSERT INTO file (tid, id, name) VALUES (?, ?, ?)]\n[parameters: ((1, '861d22b4-3204-4561-8573-cc2a607d9780', 'favicon'), (1, '290cdca8-ad6e-4c48-b933-5a50452f4f61', 'css'), (1, 'cf41230e-efe0-4cca-98aa-9a10f9f6745a', 'logo'), (1, 'd85377d6-8ddc-4b8f-a2b6-49e71b7443c0', 'InformativaPrivacy.pdf'), (1, '8d10c16b-4676-4587-9c33-bad3f4d7550e', 'InformativaPrivacy.pdf'), (1, 'fcaad5a9-4611-4215-a4ed-8910fa0d4d37', 'fcaad5a9-4611-4215-a4ed-8910fa0d4d37'))]\n(Background on this error at: http://sqlalche.me/e/gkpj)
2023-05-03 11:13:28+0000 [-] [E] Verbose exception traceback:
2023-05-03 11:13:28+0000 [-] [I] Traceback (most recent call last):\n\n  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1225, in _execute_context\n    self.dialect.do_executemany(\n\n  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/default.py", line 578, in do_executemany\n    cursor.executemany(statement, parameters)\n\nsqlite3.IntegrityError: UNIQUE constraint failed: file.tid, file.name\n\n\nThe above exception was the direct cause of the following exception:\n\n\nTraceback (most recent call last):\n\n  File "/usr/lib/python3/dist-packages/globaleaks/db/__init__.py", line 94, in update_db\n    migration.perform_migration(db_version)\n\n  File "/usr/lib/python3/dist-packages/globaleaks/db/migration.py", line 250, in perform_migration\n    raise exception\n\n  File "/usr/lib/python3/dist-packages/globaleaks/db/migration.py", line 247, in perform_migration\n    migration_script.commit()\n\n  File "/usr/lib/python3/dist-packages/globaleaks/db/migrations/update.py", line 45, in commit\n    self.session_new.commit()\n\n  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/session.py", line 1036, in commit\n    self.transaction.commit()\n\n  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/session.py", line 503, in commit\n    self._prepare_impl()\n\n  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/session.py", line 482, in _prepare_impl\n    self.session.flush()\n\n  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/session.py", line 2479, in flush\n    self._flush(objects)\n\n  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/session.py", line 2617, in _flush\n    transaction.rollback(_capture_exception=True)\n\n  File "/usr/lib/python3/dist-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__\n    compat.reraise(exc_type, exc_value, exc_tb)\n\n  File "/usr/lib/python3/dist-packages/sqlalchemy/util/compat.py", line 153, in reraise\n    raise value\n\n  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/session.py", line 2577, in _flush\n    flush_context.execute()\n\n  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/unitofwork.py", line 422, in execute\n    rec.execute(self)\n\n  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/unitofwork.py", line 586, in execute\n    persistence.save_obj(\n\n  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/persistence.py", line 239, in save_obj\n    _emit_insert_statements(\n\n  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/persistence.py", line 1084, in _emit_insert_statements\n    c = cached_connections[connection].execute(statement, multiparams)\n\n  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 982, in execute\n    return meth(self, multiparams, params)\n\n  File "/usr/lib/python3/dist-packages/sqlalchemy/sql/elements.py", line 287, in _execute_on_connection\n    return connection._execute_clauseelement(self, multiparams, params)\n\n  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1095, in _execute_clauseelement\n    ret = self._execute_context(\n\n  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1249, in _execute_context\n    self._handle_dbapi_exception(\n\n  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1476, in _handle_dbapi_exception\n    util.raise_from_cause(sqlalchemy_exception, exc_info)\n\n  File "/usr/lib/python3/dist-packages/sqlalchemy/util/compat.py", line 398, in raise_from_cause\n    reraise(type(exception), exception, tb=exc_tb, cause=cause)\n\n  File "/usr/lib/python3/dist-packages/sqlalchemy/util/compat.py", line 152, in reraise\n    raise value.with_traceback(tb)\n\n  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1225, in _execute_context\n    self.dialect.do_executemany(\n\n  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/default.py", line 578, in do_executemany\n    cursor.executemany(statement, parameters)\n\nsqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) UNIQUE constraint failed: file.tid, file.name\n[SQL: INSERT INTO file (tid, id, name) VALUES (?, ?, ?)]\n[parameters: ((1, '861d22b4-3204-4561-8573-cc2a607d9780', 'favicon'), (1, '290cdca8-ad6e-4c48-b933-5a50452f4f61', 'css'), (1, 'cf41230e-efe0-4cca-98aa-9a10f9f6745a', 'logo'), (1, 'd85377d6-8ddc-4b8f-a2b6-49e71b7443c0', 'InformativaPrivacy.pdf'), (1, '8d10c16b-4676-4587-9c33-bad3f4d7550e', 'InformativaPrivacy.pdf'), (1, 'fcaad5a9-4611-4215-a4ed-8910fa0d4d37', 'fcaad5a9-4611-4215-a4ed-8910fa0d4d37'))]\n(Background on this error at: http://sqlalche.me/e/gkpj)\n
2023-05-03 11:13:28+0000 [-] Server Shut Down.
```
It seems that these two values are violating the constraint
```
    (1, 'd85377d6-8ddc-4b8f-a2b6-49e71b7443c0', 'InformativaPrivacy.pdf'), 
    (1, '8d10c16b-4676-4587-9c33-bad3f4d7550e', 'InformativaPrivacy.pdf'), 
```

Is there any way to solve this?
Thanks

**Comment by evilaliv3** [comment]
Hello @daniego.

Thank you for reporting this.

I consider that what you could do is simply:
- download the files before updating
- deleted them
- update
- reload the files

In this way you will have a fully working update and a fully working system.

Ths issue is probably related to this additional constraint on the file names that was added in the mentioned version. As soon that we will have the time we will eventually try to fix the migration taking in consideration this situation.
