### ISSUE TITLE
Provide a generaAdding "sleeping user" fails

### ISSUE THREAD

**Issue by schris-dk** [globaleaks/GlobaLeaks#3585]
### What version of GlobaLeaks are you using?

4.12.18

### What browser(s) are you seeing the problem on?

Chrome

### What operating system(s) are you seeing the problem on?

Windows

### Describe the issue

When trying to add a "sleeping user", the system replies with an Internal Server error

Mail with following Exceptions received:

Platform: BDO - PROD - Whistleblower
Host: whistleportal.net (s3qotymb2rz5mcwrc5lpa5yrmjcsh2si7c3ebd3xwj32bi4ch5ynntyd.onion)
Version: 4.12.8

ValueError Inappropriate argument value (of correct type).

Traceback (most recent call last):

  File "/usr/lib/python3/dist-packages/twisted/python/threadpool.py", line 250, in inContext
    result = inContext.theWork()

  File "/usr/lib/python3/dist-packages/twisted/python/threadpool.py", line 266, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)

  File "/usr/lib/python3/dist-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)

  File "/usr/lib/python3/dist-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)

  File "/usr/lib/python3/dist-packages/globaleaks/orm.py", line 185, in _wrap
    result = function(session, *args, **kwargs)

  File "/usr/lib/python3/dist-packages/globaleaks/orm.py", line 216, in tw
    return f(session, *args, **kwargs)

  File "/usr/lib/python3/dist-packages/globaleaks/handlers/recipient/rtip.py", line 101, in db_grant_tip_access
    _files_key = GCE.asymmetric_decrypt(user_cc, base64.b64decode(rtip.deprecated_crypto_files_prv_key))

  File "/usr/lib/python3/dist-packages/globaleaks/utils/crypto.py", line 293, in asymmetric_decrypt
    return SealedBox(prv_key).decrypt(data)

  File "/usr/lib/python3/dist-packages/nacl/public.py", line 361, in decrypt
    self._private_key,

  File "/usr/lib/python3/dist-packages/nacl/bindings/crypto_box.py", line 307, in crypto_box_seal_open
    plaintext = ffi.new("unsigned char[]", _mlen)

ValueError: negative array length

The particular user that I want to add can sucessfuly be added to other case

What to do?

**Comment by evilaliv3** [comment]
Thank you @schris-dk 

Have you identified any way to reproduce this issue?

**Comment by schris-dk** [comment]
Hi Giovanni!

Currently it is only on a specific report it is generating the error when trying to add the user. Another report to same client has successfully been added a sleeping user

Med venlig hilsen
Søren Christensen
Senior Manager
Telefon: +4539159901
Mobil: +4530934933
***@***.******@***.***>

BDO Statsautoriseret revisionsaktieselskab
CVR: 20222670
Havneholmen 29
1561 København V
Tlf.: +4539155200
www.bdo.dk<https://www.bdo.dk/da-dk/bdo-danmark>

BDO Statsautoriseret revisionsaktieselskab, danskejet rådgivnings- og revisionsvirksomhed, er medlem af BDO International Limited - et UK-baseret selskab med begrænset hæftelse - og del af det internationale BDO netværk bestående af uafhængige medlemsfirmaer. BDO er varemærke for både BDO netværket og for alle BDO medlemsfirmaerne. BDO i Danmark beskæftiger mere end 1.400 medarbejdere, mens det verdensomspændende BDO netværk har over 111.000 medarbejdere i mere end 164 lande.

Denne e-mail og enhver vedhæftet fil er fortrolig. Hvis du ikke er rette modtager, bedes du venligst omgående underrette os og derefter slette e-mailen og enhver vedhæftet fil uden at beholde kopi og uden at videregive oplysninger om indholdet.

Tænk på miljøet - er det nødvendigt at printe mailen?



Fra: Giovanni Pellerano ***@***.***>
Sendt: 25. august 2023 12:30
Til: globaleaks/GlobaLeaks ***@***.***>
Cc: Søren Christensen ***@***.***>; Mention ***@***.***>
Emne: Re: [globaleaks/GlobaLeaks] Provide a generaAdding "sleeping user" fails (Issue #3585)


Ekstern afsender

Thank you @schris-dk<https://github.com/schris-dk>

Have you identified any way to reproduce this issue?

**Comment by schris-dk** [comment]
As additional info I can add, that the report in question has had it's expiry date prolonged - could this have an influence on the matter?

**Comment by schris-dk** [comment]
Error - stating that latest install is present

 The following signatures were invalid: BADSIG 32E6792624045008 GlobaLeaks software signing key <info@globaleaks.org>
Fetched 833 B in 2s (513 B/s)
Reading package lists... Done
Building dependency tree
Reading state information... Done
All packages are up to date.
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: https://deb.globaleaks.org buster/ Release: The following signatures were invalid: BADSIG 32E6792624045008 GlobaLeaks software signing key <info@globaleaks.org>
W: Failed to fetch http://deb.globaleaks.org/buster/Release.gpg  The following signatures were invalid: BADSIG 32E6792624045008 GlobaLeaks software signing key <info@globaleaks.org>
W: Some index files failed to download. They have been ignored, or old ones used instead.
Reading package lists... Done
Building dependency tree
Reading state information... Done
globaleaks is already the newest version (4.12.8).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
root@azp-whbl-glo01:/home/bdowhbladmin#

**Comment by schris-dk** [comment]
Hi After upgrading to 4.13.1 the ability to add sleeping users returned - but also our issue with one particular case, where the system fails to add a user (server error).

This particular case has had its expiry date prolonged, as well as had a reminder date set. I don't know if these circumstances have any influende on the issue. Ive attached the latest Globaleaks.log as well as the last error message received by mail
[ERROR SENT BY MAIL.txt](https://github.com/globaleaks/GlobaLeaks/files/12482519/ERROR.SENT.BY.MAIL.txt)
[globaleaks (1).log](https://github.com/globaleaks/GlobaLeaks/files/12482520/globaleaks.1.log)
