### ISSUE TITLE
Possible bug in v4.13.2 - ValueError Inappropriate argument value (of correct type)

### ISSUE THREAD

**Issue by aetdr** [globaleaks/GlobaLeaks#3601]
### What version of GlobaLeaks are you using?

 4.13.2

### What browser(s) are you seeing the problem on?

All

### What operating system(s) are you seeing the problem on?

Linux

### Describe the issue

Hi @evilaliv3 

We have seen many of these since upgrade to v 4.13.2

```
Version: 4.13.2

ValueError Inappropriate argument value (of correct type).

Traceback (most recent call last):

  File "/usr/lib/python3/dist-packages/twisted/python/threadpool.py", line 250, in inContext
    result = inContext.theWork()

  File "/usr/lib/python3/dist-packages/twisted/python/threadpool.py", line 266, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)

  File "/usr/lib/python3/dist-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)

  File "/usr/lib/python3/dist-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)

  File "/usr/lib/python3/dist-packages/globaleaks/orm.py", line 185, in _wrap
    result = function(session, *args, **kwargs)

  File "/usr/lib/python3/dist-packages/globaleaks/handlers/recipient/rtip.py", line 140, in grant_tip_access
    if db_grant_tip_access(session, tid, user, user_cc, itip, rtip, receiver_id):

  File "/usr/lib/python3/dist-packages/globaleaks/handlers/recipient/rtip.py", line 92, in db_grant_tip_access
    _files_key = GCE.asymmetric_decrypt(user_cc, base64.b64decode(rtip.deprecated_crypto_files_prv_key))

  File "/usr/lib/python3/dist-packages/globaleaks/utils/crypto.py", line 293, in asymmetric_decrypt
    return SealedBox(prv_key).decrypt(data)

  File "/usr/lib/python3/dist-packages/nacl/public.py", line 358, in decrypt
    plaintext = nacl.bindings.crypto_box_seal_open(

  File "/usr/lib/python3/dist-packages/nacl/bindings/crypto_box.py", line 307, in crypto_box_seal_open
    plaintext = ffi.new("unsigned char[]", _mlen)

ValueError: negative array length

```

**Comment by evilaliv3** [comment]
Thank you @aetdr 

I'm looking into this to undertstand the situation. 

Is it the first time you try this feature or you are using it since a lot and you are noticing a regression?

**Comment by aetdr** [comment]
Hello @evilaliv3 

We have been using this feature for a while. 
I can now see that the end users are complaining about not beeing able to assign submissions to others.

**Comment by evilaliv3** [comment]
Okay, do you confirm that both this ticket and https://github.com/globaleaks/GlobaLeaks/issues/3594 are related to the same operation: trying to assign reports to others?

This is the same case of what reported by @schris-dk here: https://github.com/globaleaks/GlobaLeaks/issues/3585

In this case i will close 2 of the tickets and keep one where to analyze and track a fix

**Comment by schris-dk** [comment]
This issue is a new one – I do not think it is related to the older ones – these still persists.

#3585 relates to one specific report, where we cannot add the sleeping user. The particular case is a little special, as it has had its deletion date postponed and a reminder date has been set – I don’t know if these circumstances has had any influence on the matter.

Med venlig hilsen
Søren Christensen


Fra: Giovanni Pellerano ***@***.***>
Sendt: 4. september 2023 10:26
Til: globaleaks/GlobaLeaks ***@***.***>
Cc: Søren Christensen ***@***.***>; Mention ***@***.***>
Emne: Re: [globaleaks/GlobaLeaks] Possible bug in v4.13.2 - ValueError Inappropriate argument value (of correct type) (Issue #3601)


Ekstern afsender

Okay, do you confirm that both this ticket and #3594<https://github.com/globaleaks/GlobaLeaks/issues/3594> are related to the same operation: trying to assign reports to others?

This is the same case of what reported by @schris-dk<https://github.com/schris-dk> here: #3585<https://github.com/globaleaks/GlobaLeaks/issues/3585>

In this case i will close 2 of the tickets and keep one where to analyze and track a fix

**Comment by evilaliv3** [comment]
Thank you @schris-dk; actually the circumstances you mention are ininfluent and i continue to think the issues could be the same.

The excepion scatters in fact when one try to grant a user access to one or multiple reports.

I will be doing some test in this regard and give you an update.

**Comment by aetdr** [comment]
Hi @evilaliv3 

I am not sure if this issue is related to #3594
We are experiencing both since upgrade.
