### ISSUE TITLE
Failure on recipient access to identities loaded before update to 4.11.X

### ISSUE THREAD

**Issue by larrykind** [globaleaks/GlobaLeaks#3628]
### What version of GlobaLeaks are you using?

4.9.5 updated to 4.13.8

### What browser(s) are you seeing the problem on?

All

### What operating system(s) are you seeing the problem on?

Windows

### Describe the issue

This is the flow of this test

1. Open a report with identity template on GL v.4.9.5
2. Update to GL 4.13.8
3. On 4.13.8 perform a identity access request to the custodian on the previously generated report 
4. Error - unmanaged (red ticket on client)

- - - 

`Platform: WBISWEB SaS -- Piattaforma generale
Host: [mickey.mouse.it](http://[mickey.mouse.it/) (7q6osqf4g7i5xttlpvcce2ayctlj4kvzayantanig6seuh4gdokad.onion)
Version: 4.13.8

nacl.exceptions.TypeError None

Traceback (most recent call last):

  File "/usr/lib/python3/dist-packages/twisted/python/threadpool.py", line 244, in inContext
    result = inContext.theWork()  # type: ignore[attr-defined]
             ^^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3/dist-packages/twisted/python/threadpool.py", line 260, in <lambda>
    inContext.theWork = lambda: context.call(  # type: ignore[attr-defined]
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3/dist-packages/twisted/python/context.py", line 117, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3/dist-packages/twisted/python/context.py", line 82, in callWithContext
    return func(*args, **kw)
           ^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3/dist-packages/globaleaks/orm.py", line 185, in _wrap
    result = function(session, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3/dist-packages/globaleaks/handlers/recipient/rtip.py", line 535, in create_identityaccessrequest
    crypto_tip_prv_key = GCE.asymmetric_decrypt(user_cc, base64.b64decode(rtip.crypto_tip_prv_key))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3/dist-packages/globaleaks/utils/crypto.py", line 291, in asymmetric_decrypt
    prv_key = PrivateKey(prv_key, Base64Encoder)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3/dist-packages/nacl/public.py", line 98, in __init__
    raise exc.TypeError(

nacl.exceptions.TypeError: PrivateKey must be created from a 32 bytes long raw secret key`

**Comment by evilaliv3** [comment]
Thank you @larrykind 

Actually yeasterday i tried to reproduce this situation but at the moment i'm not able to reproduce it.

**Comment by larrykind** [comment]
hello, 
ubuntu bionic ---> debian12
gl 4.9.5 ---> GL 4.13.8, 
I'm actually testing on 4.13.10

**Comment by larrykind** [comment]
Hello @evilaliv3 i retried to migrate from 4.9.5 to 4.13.12, but i have the same problem. Update seems successfully done, but when I try to access on a pre-update submission i cannot see any report's content and get red ticket error (unexpected). 
Error sent via mail is this one:

`Platform: Paperone SaS -- Piattaforma generale
Host: [topolino.minnie.io](http://topolino.minnie.io/) (7q6osqf4g7i5xttlpvcce2ayctlj4kvsblindaioznwug6seuh4gdokad.onion)
Version: 4.13.11  **<------this is 4.13.12**

binascii.Error None

Traceback (most recent call last):

  File "/usr/lib/python3/dist-packages/twisted/internet/defer.py", line 1656, in _inlineCallbacks
    result = current_context.run(
             ^^^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3/dist-packages/twisted/python/failure.py", line 517, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3/dist-packages/globaleaks/handlers/recipient/rtip.py", line 622, in get
    tip = yield deferToThread(decrypt_tip, [self.session.cc](http://self.session.cc/), crypto_tip_prv_key, tip)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3/dist-packages/twisted/python/threadpool.py", line 244, in inContext
    result = inContext.theWork()  # type: ignore[attr-defined]
             ^^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3/dist-packages/twisted/python/threadpool.py", line 260, in <lambda>
    inContext.theWork = lambda: context.call(  # type: ignore[attr-defined]
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3/dist-packages/twisted/python/context.py", line 117, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3/dist-packages/twisted/python/context.py", line 82, in callWithContext
    return func(*args, **kw)
           ^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3/dist-packages/globaleaks/handlers/whistleblower/submission.py", line 38, in decrypt_tip
    tip['iar']['request_motivation'] = GCE.asymmetric_decrypt(tip_key, base64.b64decode(tip['iar']['request_motivation'])).decode()
                                                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3.11/base64.py", line 88, in b64decode
    return binascii.a2b_base64(s, strict_mode=validate)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

binascii.Error: Incorrect padding`

**Comment by evilaliv3** [comment]
Thank you @larrykind

> Message ID: ***@***.***>
>

We will retest your exact configuration by the weekend and get the update
about this aspects is correct

**Comment by larrykind** [comment]
In the gloabelaks.log I got also this:



2023-09-29 16:52:54+0200 [-] [E] Unhandled exception raised:
2023-09-29 16:52:54+0200 [-] [E] binascii.Error None\n\nTraceback (most recent call last):\n\n  File "/usr/lib/python3/dist-packages/twisted/internet/defer.py", line 1656, in _inlineCallbacks\n    result = current_context.run(\n             ^^^^^^^^^^^^^^^^^^^^\n\n  File "/usr/lib/python3/dist-packages/twisted/python/failure.py", line 517, in throwExceptionIntoGenerator\n    return g.throw(self.type, self.value, self.tb)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n\n  File "/usr/lib/python3/dist-packages/globaleaks/handlers/recipient/rtip.py", line 622, in get\n    tip = yield deferToThread(decrypt_tip, self.session.cc, crypto_tip_prv_key, tip)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n\n  File "/usr/lib/python3/dist-packages/twisted/python/threadpool.py", line 244, in inContext\n    result = inContext.theWork()  # type: ignore[attr-defined]\n             ^^^^^^^^^^^^^^^^^^^\n\n  File "/usr/lib/python3/dist-packages/twisted/python/threadpool.py", line 260, in <lambda>\n    inContext.theWork = lambda: context.call(  # type: ignore[attr-defined]\n                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n\n  File "/usr/lib/python3/dist-packages/twisted/python/context.py", line 117, in callWithContext\n    return self.currentContext().callWithContext(ctx, func, *args, **kw)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n\n  File "/usr/lib/python3/dist-packages/twisted/python/context.py", line 82, in callWithContext\n    return func(*args, **kw)\n           ^^^^^^^^^^^^^^^^^\n\n  File "/usr/lib/python3/dist-packages/globaleaks/handlers/whistleblower/submission.py", line 38, in decrypt_tip\n    tip['iar']['request_motivation'] = GCE.asymmetric_decrypt(tip_key, base64.b64decode(tip['iar']['request_motivation'])).decode()\n                                                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n\n  File "/usr/lib/python3.11/base64.py", line 88, in b64decode\n    return binascii.a2b_base64(s, strict_mode=validate)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n\nbinascii.Error: Invalid base64-encoded string: number of data characters (17) cannot be 1 more than a multiple of 4\n

**Comment by evilaliv3** [comment]
Issue confirmed and is basically just a visualization issue.

We are going to emit a patch and include it in a release by today.
