### ISSUE TITLE
Error when a Recipient tries to give access to a report to another Recipient

### ISSUE THREAD

**Issue by eleibr** [globaleaks/GlobaLeaks#3655]
### What version of GlobaLeaks are you using?

4.12.9

### What browser(s) are you seeing the problem on?

All

### What operating system(s) are you seeing the problem on?

Windows

### Describe the issue

On a sub-site, when every Recipient tries to give access to a report to another one, gets the error 'Internal server error' (Unexpected) 

![error_message](https://github.com/globaleaks/GlobaLeaks/assets/113996868/7993ae29-69c4-48d6-ba5d-f7e15aed3f9f)

Platform: xdnwbprod01
Host: xdnwbprod01.whistletech.online (n2uje6fvnsas37ufwgm73flaas7j2a2tms4afxkvbgmzr2ez6k6yiiqd.onion)
Version: 4.12.9

nacl.exceptions.TypeError None

Traceback (most recent call last):

  File "/usr/lib/python3/dist-packages/twisted/python/threadpool.py", line 250, in inContext
    result = inContext.theWork()

  File "/usr/lib/python3/dist-packages/twisted/python/threadpool.py", line 266, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)

  File "/usr/lib/python3/dist-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)

  File "/usr/lib/python3/dist-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)

  File "/usr/lib/python3/dist-packages/globaleaks/orm.py", line 185, in _wrap
    result = function(session, *args, **kwargs)

  File "/usr/lib/python3/dist-packages/globaleaks/orm.py", line 216, in tw
    return f(session, *args, **kwargs)

  File "/usr/lib/python3/dist-packages/globaleaks/handlers/recipient/rtip.py", line 101, in db_grant_tip_access
    _files_key = GCE.asymmetric_decrypt(user_cc, base64.b64decode(rtip.deprecated_crypto_files_prv_key))

  File "/usr/lib/python3/dist-packages/globaleaks/utils/crypto.py", line 293, in asymmetric_decrypt
    return SealedBox(prv_key).decrypt(data)

  File "/usr/lib/python3/dist-packages/nacl/public.py", line 358, in decrypt
    plaintext = nacl.bindings.crypto_box_seal_open(

  File "/usr/lib/python3/dist-packages/nacl/bindings/crypto_box.py", line 306, in crypto_box_seal_open
    ensure(_clen >= crypto_box_SEALBYTES,

  File "/usr/lib/python3/dist-packages/nacl/exceptions.py", line 81, in ensure
    raise raising(*args)

nacl.exceptions.TypeError: Input cyphertext must be at least 48 long

Every Recipient that gets this error has the capability to give access to the report to anoher one

![image](https://github.com/globaleaks/GlobaLeaks/assets/113996868/9e5166b7-63d8-4a67-ace1-5d9bda9132c7)
 
and every one of them gets the same error on different Channels.

**Comment by evilaliv3** [comment]
Hello @eleibr 

May i ask you when did you update to version 4.12.9?
By updating to 4.12.9 you may have incurred in a bug discussed in https://github.com/globaleaks/GlobaLeaks/issues/3606.

This comment contains the possible solutions: https://github.com/globaleaks/GlobaLeaks/issues/3606#issuecomment-1706685069

**Comment by eleibr** [comment]
Hello @evilaliv3, the platform was updated on 25/08

**Comment by evilaliv3** [comment]
Ok.

If you have a few report you are good to go just updating to current version.

If you have a lot of reports, maybe you can restore the old backup or apply one of the strategies discussed in the linked ticket.

**Comment by eleibr** [comment]
Hello @evilaliv3 , we have an instance with several sub-sites: how it's better to proceed?

**Comment by evilaliv3** [comment]
Thank you for the question.

All depends on the existance of reports or not.

As told an update would solve the problem for everybody in case there are no reports or it is acceptable to not restore the data because recipients already accessed to all. Alternatively to restore the data the procedure is described in the linked ticket.

If you need more direct assistance you may reach me on community.globaleaks.org

**Comment by eleibr** [comment]
Hello @evilaliv3 and thanks for your reply.
Since that one described in #3606 it's a 'currently manual fix' , maybe will be possibile to have it automatically correct in a new release, such as 4.13.12?

**Comment by evilaliv3** [comment]
No actually; we created a script, loaded on the ticket to assist with the procedure but the fix is manual and requires access to a backup copy of the system before the update.

**Comment by evilaliv3** [comment]
Closing as outdated and not applicable on current release 5.0.71
