### ISSUE TITLE
Unexpected server error on certain reports

### ISSUE THREAD

**Issue by Sgarambon** [globaleaks/GlobaLeaks#3672]
### What version of GlobaLeaks are you using?

4.3.12

### What browser(s) are you seeing the problem on?

All

### What operating system(s) are you seeing the problem on?

Linux

### Describe the issue

When clicking on a report on the report list page of a recipient's account, the server throws a unexpected server error.
Log file (globaleaks.log) shows:

2023-09-29 11:21:52+0200 [-] [E] Unhandled exception raised:
2023-09-29 11:21:52+0200 [-] [E] ValueError Inappropriate argument value (of correct type).\n\nTraceback (most recent call last):\n\n  File "/usr/lib/python3.10/base64.py", line 37, in _bytes_from_decode_data\n    return s.encode('ascii')\n\nUnicodeEncodeError: 'ascii' codec can't encode character '\\xe0' in position 27: ordinal not in range(128)\n\n\nDuring handling of the above exception, another exception occurred:\n\n\nTraceback (most recent call last):\n\n  File "/usr/lib/python3/dist-packages/twisted/internet/defer.py", line 1656, in _inlineCallbacks\n    result = current_context.run(\n\n  File "/usr/lib/python3/dist-packages/twisted/python/failure.py", line 489, in throwExceptionIntoGenerator\n    return g.throw(self.type, self.value, self.tb)\n\n  File "/usr/lib/python3/dist-packages/globaleaks/handlers/recipient/rtip.py", line 622, in get\n    tip = yield deferToThread(decrypt_tip, self.session.cc, crypto_tip_prv_key, tip)\n\n  File "/usr/lib/python3/dist-packages/twisted/python/threadpool.py", line 244, in inContext\n    result = inContext.theWork()  # type: ignore[attr-defined]\n\n  File "/usr/lib/python3/dist-packages/twisted/python/threadpool.py", line 260, in <lambda>\n    inContext.theWork = lambda: context.call(  # type: ignore[attr-defined]\n\n  File "/usr/lib/python3/dist-packages/twisted/python/context.py", line 117, in callWithContext\n    return self.currentContext().callWithContext(ctx, func, *args, **kw)\n\n  File "/usr/lib/python3/dist-packages/twisted/python/context.py", line 82, in callWithContext\n    return func(*args, **kw)\n\n  File "/usr/lib/python3/dist-packages/globaleaks/handlers/whistleblower/submission.py", line 38, in decrypt_tip\n    tip['iar']['request_motivation'] = GCE.asymmetric_decrypt(tip_key, base64.b64decode(tip['iar']['request_motivation'])).decode()\n\n  File "/usr/lib/python3.10/base64.py", line 80, in b64decode\n    s = _bytes_from_decode_data(s)\n\n  File "/usr/lib/python3.10/base64.py", line 39, in _bytes_from_decode_data\n    raise ValueError('string argument should contain only ASCII characters')\n\nValueError: string argument should contain only ASCII characters\n

A partial content of the report is presented on its page, and operations like "Mark as important", "Set a reminder" and so on are not possible on that report.

Same problem was found with 4.3.11. Switching the interface language between English and Italian does not change this behaviour.

Language of the failing report is Italian, which is the default for my installation. English is the only other available language.

The failing report's state is "Closed" but still unexpired. The report is fully accessible without errors to the signalling person with the receipt code.

Thank you for your attention.

**Comment by Sgarambon** [comment]
Language of the failing report is Italian, which is the default for my installation. English is the only other available language.

**Comment by evilaliv3** [comment]
Thank you @Sgarambon for your questions.

I'm going to to answers your two questions but please keep topics separated by opening multiple tickets next time.

1. About the exception we will proceed trying to analyze the situation: which browser are you using and on which poperating system?
2. Regarding closed reports, if not delete, they are intentionally kept available  to whistleblowers for transparency purpose. Do you have any doubt ir question about this?

**Comment by Sgarambon** [comment]
> Thank you @Sgarambon for your questions.
> 
> I'm going to to answers your two questions but please keep topics separated by opening multiple tickets next time.
> 
> 1. About the exception we will proceed trying to analyze the situation: which browser are you using and on which poperating system?

Browsers are: MS Edge, Firefox, Google Chrome, Tor Browser on Windows 11. Google Chrome on Android.

> 2. Regarding closed reports, if not delete, they are intentionally kept available  to whistleblowers for transparency purpose. Do you have any doubt ir question about this?

No, I think there is no need to open a issue for this question. I have no doubts about it, and this is really a fair and expected behaviour for transparency. Sorry but I was just trying to give you some information about the contour conditions of the specific report on which I'm experiencing this issue. 


Thank you @evilaliv3

**Comment by evilaliv3** [comment]
Is the exception happening on all the mentioned browsers or only on a specific one?

**Comment by Sgarambon** [comment]
> Is the exception happening on all the mentioned browsers or only on a specific one?

On all browsers

**Comment by evilaliv3** [comment]
Which motivation are you typing when you get the error?

Are you able to reproduce this on try.globaleaks.org?

**Comment by evilaliv3** [comment]
Bug identified. 

The issue is on the opening of the identity access requests and is https://github.com/globaleaks/GlobaLeaks/issues/3628

The issue will be solved with release 4.13.13

**Comment by Sgarambon** [comment]
Top top top!
:)
