### ISSUE TITLE
Provide a general summary of the issue

### ISSUE THREAD

**Issue by connectnet** [globaleaks/GlobaLeaks#3676]
### What version of GlobaLeaks are you using?

1. Compiled with ./build.sh up to 4.13.12 but the start site shows over Tor Browser:
An update is available: [4.13.12 (Changelog)](https://github.com/globaleaks/GlobaLeaks/blob/main/CHANGELOG)

### What browser(s) are you seeing the problem on?

Tor Browser

### What operating system(s) are you seeing the problem on?

Linux

### Describe the issue

I cant get an Automatic configuration for https. This is the part from /var/globaleaks/log/globaleaks.log 
`2023-09-30 14:19:40+0200 [-] [E] Unhandled exception raised:
2023-09-30 14:19:40+0200 [-] [E] AttributeError Attribute not found.\n\nTraceback (most recent call last):\n\n  File "/usr/local/lib/python3.10/dist-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks\n    result = g.send(result)\n\n  File "/usr/lib/python3/dist-packages/globaleaks/rest/api.py", line 429, in concludeHandlerFailure\n    self.handle_exception(err, request)\n\n  File "/usr/lib/python3/dist-packages/globaleaks/rest/api.py", line 257, in handle_exception\n    e.tid = request.tid\n\n  File "/usr/lib/python3/dist-packages/josepy/util.py", line 191, in __setattr__\n    raise AttributeError("can't set attribute")\n\nAttributeError: can't set attribute\n
2023-09-30 14:19:40+0200 [-] Unhandled Error
	Traceback (most recent call last):
	  File "/usr/local/lib/python3.10/dist-packages/twisted/internet/defer.py", line 568, in _startRunCallbacks
	    self._runCallbacks()
	  File "/usr/local/lib/python3.10/dist-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/usr/local/lib/python3.10/dist-packages/twisted/internet/defer.py", line 1613, in unwindGenerator
	    return _cancellableInlineCallbacks(gen)
	  File "/usr/local/lib/python3.10/dist-packages/twisted/internet/defer.py", line 1529, in _cancellableInlineCallbacks
	    _inlineCallbacks(None, g, status)
	--- <exception caught here> ---
	  File "/usr/local/lib/python3.10/dist-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
	    result = g.send(result)
	  File "/usr/lib/python3/dist-packages/globaleaks/rest/api.py", line 429, in concludeHandlerFailure
	    self.handle_exception(err, request)
	  File "/usr/lib/python3/dist-packages/globaleaks/rest/api.py", line 257, in handle_exception
	    e.tid = request.tid
	  File "/usr/lib/python3/dist-packages/josepy/util.py", line 191, in __setattr__
	    raise AttributeError("can't set attribute")
	builtins.AttributeError: can't set attribute
`

**Comment by evilaliv3** [comment]
Hello

I see that without titling the ticket you have tackled many unrelated topics.

1. the issue with the browser version is just cosmetic and will be solved in the next release.
2. the exception you pasted is actually an exception within the exception that prevent you to read the original exception; it will be solved as well in the next release; in the meantime do you confirm that your system is publicly exposed on a a public IP on port 80 and 44?

**Comment by connectnet** [comment]
**mea culpa!**
After deleting iptables everything works fine.
Thank you very much!
