### ISSUE TITLE
Internal server error on network settings

### ISSUE THREAD

**Issue by angelosefs** [globaleaks/GlobaLeaks#3689]
### What version of GlobaLeaks are you using?

4.13.13

### What browser(s) are you seeing the problem on?

Chrome

### What operating system(s) are you seeing the problem on?

Windows

### Describe the issue

Everytime i click on Network settings through the website I get Internal server error:
Request URL:
https://<organization_domain>/api/admin/config/tls
Request Method:
GET
Status Code:
500 Internal Server Error

Response:
{
    "error_message": "InternalServerError [Unexpected]",
    "error_code": 1,
    "arguments": [
        "Unexpected"
    ]
}

Checking the logs in the /var/globaleaks/log/globaleaks.log, I see:
2023-10-10 14:08:34+0300 [-] [E] Unhandled exception raised:
2023-10-10 14:08:34+0300 [-] [E] IndexError Sequence index out of range.\n\nTraceback (most recent call last):\n\n  File "/usr/lib/python3/dist-packages/twisted/python/threadpool.py", line 244, in inContext\n    result = inContext.theWork()  # type: ignore[attr-defined]\n             ^^^^^^^^^^^^^^^^^^^\n\n  File "/usr/lib/python3/dist-packages/twisted/python/threadpool.py", line 260, in <lambda>\n    inContext.theWork = lambda: context.call(  # type: ignore[attr-defined]\n                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n\n  File "/usr/lib/python3/dist-packages/twisted/python/context.py", line 117, in callWithContext\n    return self.currentContext().callWithContext(ctx, func, *args, **kw)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n\n  File "/usr/lib/python3/dist-packages/twisted/python/context.py", line 82, in callWithContext\n    return func(*args, **kw)\n           ^^^^^^^^^^^^^^^^^\n\n  File "/usr/lib/python3/dist-packages/globaleaks/orm.py", line 185, in _wrap\n    result = function(session, *args, **kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n\n  File "/usr/lib/python3/dist-packages/globaleaks/orm.py", line 216, in tw\n    return f(session, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n\n  File "/usr/lib/python3/dist-packages/globaleaks/handlers/admin/https.py", line 140, in db_serialize_https_config_summary\n    file_summaries[key] = file_res_cls.db_serialize(session, tid)\n                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n\n  File "/usr/lib/python3/dist-packages/globaleaks/handlers/admin/https.py", line 280, in db_serialize\n    c = tls.split_pem_chain(c)[0]\n        ~~~~~~~~~~~~~~~~~~~~~~^^^\n\nIndexError: list index out of range\n
2023-10-10 14:09:00+0300 [-] [E] Unhandled exception raised:
2023-10-10 14:09:00+0300 [-] [E] IndexError Sequence index out of range.\n\nTraceback (most recent call last):\n\n  File "/usr/lib/python3/dist-packages/twisted/python/threadpool.py", line 244, in inContext\n    result = inContext.theWork()  # type: ignore[attr-defined]\n             ^^^^^^^^^^^^^^^^^^^\n\n  File "/usr/lib/python3/dist-packages/twisted/python/threadpool.py", line 260, in <lambda>\n    inContext.theWork = lambda: context.call(  # type: ignore[attr-defined]\n                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n\n  File "/usr/lib/python3/dist-packages/twisted/python/context.py", line 117, in callWithContext\n    return self.currentContext().callWithContext(ctx, func, *args, **kw)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n\n  File "/usr/lib/python3/dist-packages/twisted/python/context.py", line 82, in callWithContext\n    return func(*args, **kw)\n           ^^^^^^^^^^^^^^^^^\n\n  File "/usr/lib/python3/dist-packages/globaleaks/orm.py", line 185, in _wrap\n    result = function(session, *args, **kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n\n  File "/usr/lib/python3/dist-packages/globaleaks/orm.py", line 216, in tw\n    return f(session, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n\n  File "/usr/lib/python3/dist-packages/globaleaks/handlers/admin/https.py", line 140, in db_serialize_https_config_summary\n    file_summaries[key] = file_res_cls.db_serialize(session, tid)\n                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n\n  File "/usr/lib/python3/dist-packages/globaleaks/handlers/admin/https.py", line 280, in db_serialize\n    c = tls.split_pem_chain(c)[0]\n        ~~~~~~~~~~~~~~~~~~~~~~^^^\n\nIndexError: list index out of range\n

This started to happen after I tried to set https settings... I've upgraded to latest globaleaks version (4.13.13), I restarted the service, I restarted the machine, still the same thing...
Any ideas?

**Comment by evilaliv3** [comment]
Hello @angelosefs 

Could you please upload the certificate/chain file that you are trying to upload (not the private key).

I would like to check it because i think that could be not in the correct pem format or contains errors.

**Comment by angelosefs** [comment]
Hello @evilaliv3,

Thanks for the prompt response.
I can provide that, but the thing is that I disabled the https configuration after I saw that https wasn't working.
So now there is no https configuration.
I've got the issue after I've disabled/reset the https configuration.

Also mind, that the website for now is only accessible within organization's network as it is in testing mode.
I've just tried to enable https using self-signed certificate to check the email functionality.

[key-20231010-111819.zip](https://github.com/globaleaks/GlobaLeaks/files/12856998/key-20231010-111819.zip)

**Comment by evilaliv3** [comment]
Thank you for the update. 

When using a custom smtp server if your server uses a self signed cetificate you should add the certificate to the trust store.

I'm closing the ticket as the original problem is somehow resolved. Please use sepatated tickets or discussions by topic when making different questions.
