### ISSUE TITLE
4.13.17 "nacl.exceptions.CryptoError Base exception for all nacl related errors" accessing reports with attachments

### ISSUE THREAD

**Issue by rodolfomatos** [globaleaks/GlobaLeaks#3772]
### What version of GlobaLeaks are you using?

4.13.17

### What browser(s) are you seeing the problem on?

All

### What operating system(s) are you seeing the problem on?

Windows, Linux

### Describe the issue

When updating to the latest version (4.13.17), we noticed that some attachments submitted in previous reports were no longer available!
Administrators receive an error email with the following content wherever any of those reports are accessed:

Version: 4.13.17

nacl.exceptions.CryptoError 
    Base exception for all nacl related errors
    

Traceback (most recent call last):

  File "/usr/lib/python3/dist-packages/twisted/internet/defer.py", line 1660, in _inlineCallbacks
    result = current_context.run(gen.send, result)

  File "/usr/lib/python3/dist-packages/globaleaks/handlers/recipient/rtip.py", line 721, in get
    filelocation = GCE.streaming_encryption_open('DECRYPT', tip_prv_key, filelocation)

  File "/usr/lib/python3/dist-packages/globaleaks/utils/crypto.py", line 309, in streaming_encryption_open
    return _StreamingEncryptionObject(mode, user_key, filepath)

  File "/usr/lib/python3/dist-packages/globaleaks/utils/crypto.py", line 139, in __init__
    self.key = _GCE.asymmetric_decrypt(self.user_key, x)

  File "/usr/lib/python3/dist-packages/globaleaks/utils/crypto.py", line 305, in asymmetric_decrypt
    return SealedBox(prv_key).decrypt(data)

  File "/usr/lib/python3/dist-packages/nacl/public.py", line 417, in decrypt
    plaintext = nacl.bindings.crypto_box_seal_open(

  File "/usr/lib/python3/dist-packages/nacl/bindings/crypto_box.py", line 318, in crypto_box_seal_open
    ensure(

  File "/usr/lib/python3/dist-packages/nacl/exceptions.py", line 88, in ensure
    raise raising(*args)

nacl.exceptions.CryptoError: An error occurred trying to decrypt the message

**Comment by evilaliv3** [comment]
Thank you @rodolfomatos 

This does not seems to be an error related to the last update since no changes has been made on the referred functionalities.

You issue seems related by an old bug already resolved time ago here: https://github.com/globaleaks/GlobaLeaks/issues/3594

Wold you please check if this is the case?
Do you experience the issue on new reports or only on old reports?

**Comment by rodolfomatos** [comment]
Thank you for your prompt reply, @evilaliv3 

We had installed version 4.13.3. Started receiving some emails "nacl.exceptions.CryptoError". So, we updated from 4.13.3 to 4.13.17. We needed to apply those patches first?

**Comment by evilaliv3** [comment]
Thank you for your question.
We are not aware of any bug on this matter between releae 4.13.3 and release 4.13.17.
The issue i referred is related to a bug incurred  migrating systems 4.11.* to 4.12.* but if you never runned these versions your issue is probably different and not known.

**Comment by rodolfomatos** [comment]
Ouch... now I'm sweating...
File "backend/globaleaks/db/migrations/update_65/__init__.py" seems to have the patch applied:
```
class MigrationScript(MigrationBase):
    renamed_attrs = {
        'ReceiverTip': {'deprecated_crypto_files_prv_key': 'crypto_files_prv_key'},
    }

    skip_count_check = {
        'Config': True
    }

    def migrate_User(self):
```

and file "backend/globaleaks/handlers/recipient/rtip.py" seems also to have that patch applied:

  ```
 new_rtip = db_create_receivertip(session, new_receiver, itip, _tip_key)
    new_rtip.new = False
    if itip.deprecated_crypto_files_pub_key:
        _files_key = GCE.asymmetric_decrypt(user_cc, base64.b64decode(rtip.deprecated_crypto_files_prv_key))
        new_rtip.deprecated_crypto_files_prv_key = base64.b64encode(GCE.asymmetric_encrypt(new_receiver.crypto_pub_key, _files_key))
```

**Comment by rodolfomatos** [comment]
Actually there is another thing that could made this "strange things happen"... Due to some problems we rolled back to version 4.11.3 (as you sugested in 11/4):

> If it possible for you to test with the release 4.11.3?
> [14h28](https://globaleaks.slack.com/archives/C7MFH6GTT/p1681219724467729)
> To roll back to this minor release you could simply run: apt-get install globaleaks==4.11.3

**Comment by evilaliv3** [comment]
@rodolfomatos: As explained in the referenced ticket the issue incurred when you updated from 4.11.* to 4.12.* .

The issue can be solved either with a rollback or with the script that is loaded on the ticket.

If you already managed to rollback, now all is safe and you can update to 4.13.18 without issues.
