### ISSUE TITLE
Cannot import questionnaire with template question "Would you like to tell us who you are?"

### ISSUE THREAD

**Issue by TechPrivacyLab** [globaleaks/GlobaLeaks#3775]
### What version of GlobaLeaks are you using?

4.13.18

### What browser(s) are you seeing the problem on?

All

### What operating system(s) are you seeing the problem on?

Linux

### Describe the issue

Cannot import questionnaire with template question "Would you like to tell us who you are?".

To avoid issue #2902, I create a questionnaire, duplicate it, export the duplicate, delete the duplicate, and then import the exported JSON (even on a different tenant) without issue. ✔️

Everything works fine unless I add the template question "Would you like to tell us who you are?". Adding any other template question I've created doesn't throw the error, only the default template "Would you like to tell us who you are?". ❌

This is the exported JSON that throws the error (a very simple one-step questionnaire with the template question in it): [DUPLICATE.json](https://github.com/globaleaks/GlobaLeaks/files/13338000/DUPLICATE.json)

And this is the exception:
```python
Platform: [redacted]
Host: [redacted]
Version: 4.13.18

sqlalchemy.exc.IntegrityError Wraps a DB-API IntegrityError.

Traceback (most recent call last):

  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(

  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/default.py", line 609, in do_execute
    cursor.execute(statement, parameters)

sqlite3.IntegrityError: UNIQUE constraint failed: field.id


The above exception was the direct cause of the following exception:


Traceback (most recent call last):

  File "/usr/lib/python3/dist-packages/twisted/python/threadpool.py", line 250, in inContext
    result = inContext.theWork()

  File "/usr/lib/python3/dist-packages/twisted/python/threadpool.py", line 266, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)

  File "/usr/lib/python3/dist-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)

  File "/usr/lib/python3/dist-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)

  File "/usr/lib/python3/dist-packages/globaleaks/orm.py", line 185, in _wrap
    result = function(session, *args, **kwargs)

  File "/usr/lib/python3/dist-packages/globaleaks/handlers/admin/questionnaire.py", line 65, in create_questionnaire
    questionnaire = db_create_questionnaire(session, tid, user_session, request, language)

  File "/usr/lib/python3/dist-packages/globaleaks/handlers/admin/questionnaire.py", line 46, in db_create_questionnaire
    db_create_step(session, tid, step, language)

  File "/usr/lib/python3/dist-packages/globaleaks/handlers/admin/step.py", line 32, in db_create_step
    db_create_field(session, tid, c, language)

  File "/usr/lib/python3/dist-packages/globaleaks/handlers/admin/field.py", line 268, in db_create_field
    db_create_field(session, tid, c, language)

  File "/usr/lib/python3/dist-packages/globaleaks/handlers/admin/field.py", line 220, in db_create_field
    field = db_add(session, models.Field, request)

  File "/usr/lib/python3/dist-packages/globaleaks/orm.py", line 108, in db_add
    session.flush()

  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/session.py", line 2540, in flush
    self._flush(objects)

  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/session.py", line 2682, in _flush
    transaction.rollback(_capture_exception=True)

  File "/usr/lib/python3/dist-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
    compat.raise_(

  File "/usr/lib/python3/dist-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception

  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/session.py", line 2642, in _flush
    flush_context.execute()

  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/unitofwork.py", line 422, in execute
    rec.execute(self)

  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/unitofwork.py", line 586, in execute
    persistence.save_obj(

  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/persistence.py", line 239, in save_obj
    _emit_insert_statements(

  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/persistence.py", line 1083, in _emit_insert_statements
    c = cached_connections[connection].execute(statement, multiparams)

  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1011, in execute
    return meth(self, multiparams, params)

  File "/usr/lib/python3/dist-packages/sqlalchemy/sql/elements.py", line 298, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)

  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1124, in _execute_clauseelement
    ret = self._execute_context(

  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1316, in _execute_context
    self._handle_dbapi_exception(

  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1510, in _handle_dbapi_exception
    util.raise_(

  File "/usr/lib/python3/dist-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception

  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(

  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/default.py", line 609, in do_execute
    cursor.execute(statement, parameters)

sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) UNIQUE constraint failed: field.id
[SQL: INSERT INTO field (id, tid, x, y, width, label, description, hint, placeholder, required, multi_entry, triggered_by_score, step_id, fieldgroup_id, type, instance, template_id, template_override_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]
[parameters: ('question_whistleblower_identity_name', 1, 0, 0, 6, '{"en": "First name", "am": "\\u12e8\\u122b\\u1236\\u1275 \\u1235\\u121d", "ar": "\\u0627\\u0644\\u0627\\u0633\\u0645", "az": "Ad", "ba": "\\u0418\\u0 ... (2152 characters truncated) ... ": "\\u067e\\u06c1\\u0644\\u0627 \\u0646\\u0627\\u0645", "uz": "Ismi", "vi": "T\\u00ean", "zh_CN": "\\u540d", "zh_HK": "\\u540d", "zh_TW": "\\u540d"}', '{"en": ""}', '{"en": ""}', '{"en": ""}', 1, 0, 0, None, '070899d7-3215-4bc9-acfa-d7a635bd1606', 'inputbox', 1, None, None)] (Background on this error at:  http://sqlalche.me/e/13/gkpj )
```

**Comment by evilaliv3** [comment]
Thank you for reporting this @TechPrivacyLab 

I notice that the template attached includes duplicated IDs like the id "question_whistleblower_identity_name". 
How have you generated this file?

Please feel free to reac out to me on community.globaleaks.org to dig in with some debugging.

**Comment by TechPrivacyLab** [comment]
Steps to reproduce (I used a freshly created demo instance):
1. Create a new questionnaire (I called it "ORIGINAL")
2. Add a step
3. Inside the step, add the template question "Would you like to tell us who you are?"
4. Duplicate the original questionnaire into another one (I called it "DUPLICATE") using the "Duplicate" button
5. Export the questionnaire with the "Export" button

Interestingly, the 2 exported JSON files are very different: the original has an `"instance": "reference"` to the template question, the duplicate has an `"instance": "instance"` of the template question...
[ORIGINAL.json](https://github.com/globaleaks/GlobaLeaks/files/13346728/ORIGINAL.json)
[DUPLICATE.json](https://github.com/globaleaks/GlobaLeaks/files/13346724/DUPLICATE.json)

Our goal is to export a questionnaire with the template question "Would you like to tell us who you are?" and import it into another instance.
