### ISSUE TITLE
Voice message - Unable to submit

### ISSUE THREAD

**Issue by denisp76** [globaleaks/GlobaLeaks#3813]
### What version of GlobaLeaks are you using?

Version 4.13.18

### What browser(s) are you seeing the problem on?

Chrome, Safari

### What operating system(s) are you seeing the problem on?

Windows, macOS

### Describe the issue

I have created a simple questionnaire containing a Voice question. I'm able to register the voice message, but when I'm try to submit it I receive the follow error.

![image](https://github.com/globaleaks/GlobaLeaks/assets/64093982/3f17a3f0-8810-45d3-aeda-288010dd9344)

I'm not sure but maybe the error it could be caused by the creation of question type Voice. I'm able to create it, save it, but when I come back in edit mode I see that the Validation input filed is empty. If I try to set it  'Nessuno' (I think 'None' in english), during the saving stap I receive this error:

```
Platform: 
Host: 3.126.71.136 (fbfzeqkdyztyslyf5qxpzhdxrc4mxijpraj24js5ksqjpnorzl2km6id.onion)
Version: 4.13.18

KeyError Mapping key not found.

Traceback (most recent call last):

 File "/usr/lib/python3/dist-packages/twisted/python/threadpool.py", line 244, in inContext
   result = inContext.theWork()  # type: ignore[attr-defined]
            ^^^^^^^^^^^^^^^^^^^

 File "/usr/lib/python3/dist-packages/twisted/python/threadpool.py", line 260, in <lambda>
   inContext.theWork = lambda: context.call(  # type: ignore[attr-defined]
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

 File "/usr/lib/python3/dist-packages/twisted/python/context.py", line 117, in callWithContext
   return self.currentContext().callWithContext(ctx, func, *args, **kw)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

 File "/usr/lib/python3/dist-packages/twisted/python/context.py", line 82, in callWithContext
   return func(*args, **kw)
          ^^^^^^^^^^^^^^^^^

 File "/usr/lib/python3/dist-packages/globaleaks/orm.py", line 185, in _wrap
   result = function(session, *args, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

 File "/usr/lib/python3/dist-packages/globaleaks/handlers/admin/field.py", line 351, in update_field
   field = db_update_field(session, tid, field_id, field, language)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

 File "/usr/lib/python3/dist-packages/globaleaks/handlers/admin/field.py", line 310, in db_update_field
   db_update_fieldattrs(session, [field.id](http://field.id/), request['attrs'], language)

 File "/usr/lib/python3/dist-packages/globaleaks/handlers/admin/field.py", line 152, in db_update_fieldattrs
   attrs_names = [db_update_fieldattr(session, field_id, attr_name, attr, language) for attr_name, attr in field_attrs.items()]
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

 File "/usr/lib/python3/dist-packages/globaleaks/handlers/admin/field.py", line 152, in <listcomp>
   attrs_names = [db_update_fieldattr(session, field_id, attr_name, attr, language) for attr_name, attr in field_attrs.items()]
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

 File "/usr/lib/python3/dist-packages/globaleaks/handlers/admin/field.py", line 128, in db_update_fieldattr
   if attr_dict['type'] == 'localized' and language is not None:
      ~~~~~~~~~^^^^^^^^

KeyError: 'type'
```

Thanks in advance,
Denis.

**Comment by evilaliv3** [comment]
Thank you.

Actually this error has nothing to do with the voice messaging.

You are probably missing to add at least one recipient to the channel.

Add one recipient to the channel and the issue will be resolved!

**Comment by denisp76** [comment]
Omg! Sorry for your post time! All works perfectly!
Thx

**Comment by evilaliv3** [comment]
Perfect. Thank you for this feedback! Closing the issue then!
