### ISSUE TITLE
Add channel doesn't work

### ISSUE THREAD

**Issue by mauriziobulgarini** [globaleaks/GlobaLeaks#3911]
### What version of GlobaLeaks are you using?

4.13.18

### What browser(s) are you seeing the problem on?

All

### What operating system(s) are you seeing the problem on?

macOS

### Describe the issue

When i try to save a new chanell I get an error:
Error!
Internal server error (Unexpected)

Platform: TeamSystem Whistleblowing
Host: portal.smartleaks.cloud (xyjv7ongwq7yeo6stdviznonof2rogfwr67sdphb256kp2llhghuh3id.onion)
Version: 4.13.18

sqlalchemy.exc.IntegrityError Wraps a DB-API IntegrityError.

Traceback (most recent call last):

 File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 771, in _commit_impl
   self.engine.dialect.do_commit(self.connection)

 File "/usr/lib/python3/dist-packages/sqlalchemy/engine/default.py", line 562, in do_commit
   dbapi_connection.commit()

sqlite3.IntegrityError: FOREIGN KEY constraint failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

 File "/usr/lib/python3/dist-packages/twisted/python/threadpool.py", line 250, in inContext
   result = inContext.theWork()

 File "/usr/lib/python3/dist-packages/twisted/python/threadpool.py", line 266, in <lambda>
   inContext.theWork = lambda: context.call(ctx, func, *args, **kw)

 File "/usr/lib/python3/dist-packages/twisted/python/context.py", line 122, in callWithContext
   return self.currentContext().callWithContext(ctx, func, *args, **kw)

 File "/usr/lib/python3/dist-packages/twisted/python/context.py", line 85, in callWithContext
   return func(*args,**kw)

 File "/usr/lib/python3/dist-packages/globaleaks/orm.py", line 187, in _wrap
   session.commit()

 File "/usr/lib/python3/dist-packages/sqlalchemy/orm/session.py", line 1046, in commit
   self.transaction.commit()

 File "/usr/lib/python3/dist-packages/sqlalchemy/orm/session.py", line 508, in commit
   t[1].commit()

 File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1762, in commit
   self._do_commit()

 File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1793, in _do_commit
   self.connection._commit_impl()

 File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 773, in _commit_impl
   self._handle_dbapi_exception(e, None, None, None, None)

 File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1510, in _handle_dbapi_exception
   util.raise_(

 File "/usr/lib/python3/dist-packages/sqlalchemy/util/compat.py", line 182, in raise_
   raise exception

 File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 771, in _commit_impl
   self.engine.dialect.do_commit(self.connection)

 File "/usr/lib/python3/dist-packages/sqlalchemy/engine/default.py", line 562, in do_commit
   dbapi_connection.commit()

sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) FOREIGN KEY constraint failed
(Background on this error at: http://sqlalche.me/e/13/gkpj)

**Comment by mauriziobulgarini** [comment]
From a couple of days I'm not able to create new channels

**Comment by evilaliv3** [comment]
@mauriziobulgarini : I invite you to check the Site settings to verify which questinnaire is set to be used as default when a new platform or channel is created.

I expect you issue could like there where you have probably set to activate a questionnaire that no longer exists.
