### ISSUE TITLE
Unhandled exception on startup 

### ISSUE THREAD

**Issue by brassy-endomorph** [globaleaks/GlobaLeaks#3927]
### What version of GlobaLeaks are you using?

GlobaLeaks version: 4.13.18
Database version: 66

### What operating system(s) are you seeing the problem on?

Linux

### Describe the issue

```
2024-01-04 09:43:23+0000 [-] Unhandled error in Deferred:
2024-01-04 09:43:23+0000 [-] [E] Unhandled exception raised:
2024-01-04 09:43:23+0000 [-] [E] TypeError Inappropriate argument type.\n\nTraceback (most recent call last):\n\n  File "/usr/lib/python3/dist-packages/globaleaks/backend.py", line 139, in deferred_start\n    yield self._deferred_start()\n\n  File "/usr/lib/python3/dist-packages/globaleaks/backend.py", line 116, in _deferred_start\n    sync_refresh_tenant_cache()\n\n  File "/usr/lib/python3/dist-packages/globaleaks/orm.py", line 158, in __call__\n    return self.run(self._wrap, self.method, *args, **kwargs)\n\n  File "/usr/lib/python3/dist-packages/globaleaks/orm.py", line 211, in run\n    return function(*args, **kwargs)\n\n  File "/usr/lib/python3/dist-packages/globaleaks/orm.py", line 185, in _wrap\n    result = function(session, *args, **kwargs)\n\n  File "/usr/lib/python3/dist-packages/globaleaks/db/__init__.py", line 280, in sync_refresh_tenant_cache\n    return db_refresh_tenant_cache(session, tid)\n\n  File "/usr/lib/python3/dist-packages/globaleaks/db/__init__.py", line 215, in db_refresh_tenant_cache\n    for cfg in session.query(Config).filter(Config.tid.in_(tids)):\n\n  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/result.py", line 368, in iterrows\n    for row in self._fetchiter_impl():\n\n  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/loading.py", line 147, in chunks\n    fetch = cursor._raw_all_rows()\n\n  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/result.py", line 392, in _raw_all_rows\n    return [make_row(row) for row in rows]\n\n  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/result.py", line 392, in <listcomp>\n    return [make_row(row) for row in rows]\n\n  File "/usr/lib/python3/dist-packages/sqlalchemy/sql/type_api.py", line 1686, in process\n    return process_value(value, dialect)\n\n  File "/usr/lib/python3/dist-packages/globaleaks/models/properties.py", line 30, in process_result_value\n    return json.loads(value)\n\n  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads\n    return _default_decoder.decode(s)\n\n  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode\n    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n\n  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode\n    raise JSONDecodeError("Expecting value", s, err.value) from None\n\njson.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n\n\nDuring handling of the above exception, another exception occurred:\n\n\nTraceback (most recent call last):\n\n  File "/usr/lib/python3/dist-packages/twisted/internet/defer.py", line 1660, in _inlineCallbacks\n    result = current_context.run(gen.send, result)\n\n  File "/usr/lib/python3/dist-packages/globaleaks/backend.py", line 141, in deferred_start\n    fail_startup(excep)\n\n  File "/usr/lib/python3/dist-packages/globaleaks/backend.py", line 32, in fail_startup\n    log.debug('TRACE: %s', traceback.format_exc(excep))\n\n  File "/usr/lib/python3.10/traceback.py", line 183, in format_exc\n    return "".join(format_exception(*sys.exc_info(), limit=limit, chain=chain))\n\n  File "/usr/lib/python3.10/traceback.py", line 135, in format_exception\n    te = TracebackException(type(value), value, tb, limit=limit, compact=True)\n\n  File "/usr/lib/python3.10/traceback.py", line 502, in __init__\n    self.stack = StackSummary.extract(\n\n  File "/usr/lib/python3.10/traceback.py", line 357, in extract\n    if limit >= 0:\n\nTypeError: '>=' not supported between instances of 'JSONDecodeError' and 'int'\n
2024-01-04 09:43:23+0000 [-] Unhandled Error
        Traceback (most recent call last):
          File "/usr/lib/python3/dist-packages/twisted/internet/base.py", line 1325, in mainLoop
            reactorBaseSelf.runUntilCurrent()
          File "/usr/lib/python3/dist-packages/twisted/internet/base.py", line 991, in runUntilCurrent
            call.func(*call.args, **call.kw)
          File "/usr/lib/python3/dist-packages/twisted/internet/defer.py", line 1905, in unwindGenerator
            return _cancellableInlineCallbacks(gen)
          File "/usr/lib/python3/dist-packages/twisted/internet/defer.py", line 1815, in _cancellableInlineCallbacks
            _inlineCallbacks(None, gen, status)
        --- <exception caught here> ---
          File "/usr/lib/python3/dist-packages/twisted/internet/defer.py", line 1660, in _inlineCallbacks
            result = current_context.run(gen.send, result)
          File "/usr/lib/python3/dist-packages/globaleaks/backend.py", line 141, in deferred_start
            fail_startup(excep)
          File "/usr/lib/python3/dist-packages/globaleaks/backend.py", line 32, in fail_startup
            log.debug('TRACE: %s', traceback.format_exc(excep))
          File "/usr/lib/python3.10/traceback.py", line 183, in format_exc
            return "".join(format_exception(*sys.exc_info(), limit=limit, chain=chain))
          File "/usr/lib/python3.10/traceback.py", line 135, in format_exception
            te = TracebackException(type(value), value, tb, limit=limit, compact=True)
          File "/usr/lib/python3.10/traceback.py", line 502, in __init__
            self.stack = StackSummary.extract(
          File "/usr/lib/python3.10/traceback.py", line 357, in extract
            if limit >= 0:
        builtins.TypeError: '>=' not supported between instances of 'JSONDecodeError' and 'int'
```

**Comment by evilaliv3** [comment]
Thank you @brassy-endomorph 

As far that i remember i encountered this issue long time ago and i should have already fixed it.

Is it possible for you to update to release 4.14.3 and see if it is confirmed that on that version the bug is resolved?

**Comment by evilaliv3** [comment]
Closing as stale.
