### ISSUE TITLE
Update to version 4.14.0 does not allow reporting statuses to be updated

### ISSUE THREAD

**Issue by Natii9898** [globaleaks/GlobaLeaks#3934]
### Discussed in https://github.com/orgs/globaleaks/discussions/3931

<div type='discussions-op-text'>

<sup>Originally posted by **Natii9898** January  5, 2024</sup>
Good morning,

Today I skipped the update to version 4.14.0, everything seems correct, until I start checking what I changed.
Firstly, I get an internal error when trying to change the statuses of a complaint.

I attach emails that I received regarding the subject:

1:
Platform: Demo
Host: denunciantes.******.es
Version: 4.14.0

KeyError Mapping key not found.

Traceback (most recent call last):

File "/usr/lib/python3/dist-packages/twisted/internet/defer.py", line 190, in maybeDeferred
result = f(*args, **kwargs)

File "/usr/lib/python3/dist-packages/globaleaks/rest/decorators.py", line 66, in wrapper
return f(self, *args, **kwargs)

File "/usr/lib/python3/dist-packages/globaleaks/rest/decorators.py", line 39, in wrapper
return f(self, *args, **kwargs)

File "/usr/lib/python3/dist-packages/globaleaks/rest/decorators.py", line 52, in wrapper
return f(self, *args, **kwargs)

File "/usr/lib/python3/dist-packages/globaleaks/handlers/operation.py", line 25, in put
return func(self, request['args'], *args, **kwargs)

File "/usr/lib/python3/dist-packages/globaleaks/handlers/recipient/rtip.py", line 1151, in update_submission_status
req_args['status'], req_args['substatus'], req_args['motivation'])

KeyError: 'status'

2:

Platform: Demo
Host: denunciantes.****.es
Version: 4.14.0

KeyError Mapping key not found.

Traceback (most recent call last):

File "/usr/lib/python3/dist-packages/twisted/internet/defer.py", line 190, in maybeDeferred
result = f(*args, **kwargs)

File "/usr/lib/python3/dist-packages/globaleaks/rest/decorators.py", line 66, in wrapper
return f(self, *args, **kwargs)

File "/usr/lib/python3/dist-packages/globaleaks/rest/decorators.py", line 39, in wrapper
return f(self, *args, **kwargs)

File "/usr/lib/python3/dist-packages/globaleaks/rest/decorators.py", line 52, in wrapper
return f(self, *args, **kwargs)

File "/usr/lib/python3/dist-packages/globaleaks/handlers/operation.py", line 25, in put
return func(self, request['args'], *args, **kwargs)

File "/usr/lib/python3/dist-packages/globaleaks/handlers/recipient/rtip.py", line 1151, in update_submission_status
req_args['status'], req_args['substatus'], req_args['motivation'])

KeyError: 'motivation'

I wanted to know if this happened to anyone else, if it is because I have some incorrect configuration, or if in any case it is because of the update?
I clarify that all this worked perfectly before updating to version 4.14.0

Thank you</div>

**Comment by evilaliv3** [comment]
Thank you.

This is a know defect of release 4.14.0 that you find already resolved in current release 4.14.3

**Comment by Natii9898** [comment]
Thank you for responding, I updated to version 4.14.3 as you mentioned and if it allows me to change the status of a complaint.
 But for example it lets me change it if I give it a reason. If I don't write for any reason it gives me a server error.

THIS: Error! Internal server error (Unexpected)

If I want to change any state without a reason, it gives that error, shouldn't it be possible to change it without having to give a reason for that change? Or in any case there is an obligation to provide a reason without a server error.

Millions of thanks
