### ISSUE TITLE
Submission status change triggers an error

### ISSUE THREAD

**Issue by verlata** [globaleaks/GlobaLeaks#3938]
### What version of GlobaLeaks are you using?

4.14.0

### What browser(s) are you seeing the problem on?

Chrome, Firefox

### What operating system(s) are you seeing the problem on?

Windows, Linux

### Describe the issue

Changing the status of a submission is not possible.
The error report generated and sent by mail is following:

`KeyError Mapping key not found.

Traceback (most recent call last):

  File "/usr/lib/python3/dist-packages/twisted/internet/defer.py", line 190, in maybeDeferred
    result = f(*args, **kwargs)

  File "/usr/lib/python3/dist-packages/globaleaks/rest/decorators.py", line 66, in wrapper
    return f(self, *args, **kwargs)

  File "/usr/lib/python3/dist-packages/globaleaks/rest/decorators.py", line 39, in wrapper
    return f(self, *args, **kwargs)

  File "/usr/lib/python3/dist-packages/globaleaks/rest/decorators.py", line 52, in wrapper
    return f(self, *args, **kwargs)

  File "/usr/lib/python3/dist-packages/globaleaks/handlers/operation.py", line 25, in put
    return func(self, request['args'], *args, **kwargs)

  File "/usr/lib/python3/dist-packages/globaleaks/handlers/recipient/rtip.py", line 1151, in update_submission_status
    req_args['status'], req_args['substatus'], req_args['motivation'])

KeyError: 'status'`

**Comment by evilaliv3** [comment]
The bug is known and already fixed in 4.14.3
