### ISSUE TITLE
PGP KEY UPLOAD ERROR

### ISSUE THREAD

**Issue by msmannan00** [globaleaks/GlobaLeaks#3970]
### What version of GlobaLeaks are you using?

4.14.7

### What browser(s) are you seeing the problem on?

Firefox

### What operating system(s) are you seeing the problem on?

Linux

### Describe the issue

2024-01-24T13:23:56+0500 [stdout#info] [E] KeyError Mapping key not found.\n\nTraceback (most recent call last):\n\n  File "/home/morgan-freeman/Workspace/GlobaLeaks/backend/env/lib/python3.11/site-packages/twisted/python/threadpool.py", line 244, in inContext\n    result = inContext.theWork()  # type: ignore[attr-defined]\n             ^^^^^^^^^^^^^^^^^^^\n\n  File "/home/morgan-freeman/Workspace/GlobaLeaks/backend/env/lib/python3.11/site-packages/twisted/python/threadpool.py", line 260, in <lambda>\n    inContext.theWork = lambda: context.call(  # type: ignore[attr-defined]\n                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n\n  File "/home/morgan-freeman/Workspace/GlobaLeaks/backend/env/lib/python3.11/site-packages/twisted/python/context.py", line 117, in callWithContext\n    return self.currentContext().callWithContext(ctx, func, *args, **kw)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n\n  File "/home/morgan-freeman/Workspace/GlobaLeaks/backend/env/lib/python3.11/site-packages/twisted/python/context.py", line 82, in callWithContext\n    return func(*args, **kw)\n           ^^^^^^^^^^^^^^^^^\n\n  File "/home/morgan-freeman/Workspace/GlobaLeaks/backend/globaleaks/orm.py", line 186, in _wrap\n    result = function(session, *args, **kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n\n  File "/home/morgan-freeman/Workspace/GlobaLeaks/backend/globaleaks/handlers/user/__init__.py", line 179, in update_user_settings\n    user = db_user_update_user(session, tid, user_session, request)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n\n  File "/home/morgan-freeman/Workspace/GlobaLeaks/backend/globaleaks/handlers/user/__init__.py", line 162, in db_user_update_user\n    parse_pgp_options(user, request)\n\n  File "/home/morgan-freeman/Workspace/GlobaLeaks/backend/globaleaks/handlers/user/__init__.py", line 31, in parse_pgp_options\n    user.can_redact_information = request['can_redact_information']\n                                  ~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^\n\nKeyError: 'can_redact_information'\n

### Proposed solution

its a backend issue in both dev and main branch

**Comment by evilaliv3** [comment]
Fixed! thank you @msmannan00
