### ISSUE TITLE
Provide a general summary of the issue

### ISSUE THREAD

**Issue by msmannan00** [globaleaks/GlobaLeaks#3975]
### What version of GlobaLeaks are you using?

4.14.7 

### What browser(s) are you seeing the problem on?

All

### What operating system(s) are you seeing the problem on?

Linux

### Describe the issue

Issue occurs when triggering automatic https configuration on a ubuntu server. It was working perfectly in the older builds

Platform: Globaleaks
Host: 127.0.0.1 (3nwhotzufncfi7xluyjbp6xp74qcjdmxl3qtynrjvxma2ncjdoo5ubad.onion)
Version: 4.14.7

acme.messages.Error ACME error.

    https://tools.ietf.org/html/draft-ietf-appsawg-http-problem-00

    :ivar unicode typ:
    :ivar unicode title:
    :ivar unicode detail:

Traceback (most recent call last):

  File "/home/morgan-freeman/Workspace/GlobaLeaks/backend/env/lib/python3.11/site-packages/twisted/python/threadpool.py", line 244, in inContext
    result = inContext.theWork()  # type: ignore[attr-defined]
             ^^^^^^^^^^^^^^^^^^^

  File "/home/morgan-freeman/Workspace/GlobaLeaks/backend/env/lib/python3.11/site-packages/twisted/python/threadpool.py", line 260, in <lambda>
    inContext.theWork = lambda: context.call(  # type: ignore[attr-defined]
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/morgan-freeman/Workspace/GlobaLeaks/backend/env/lib/python3.11/site-packages/twisted/python/context.py", line 117, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/morgan-freeman/Workspace/GlobaLeaks/backend/env/lib/python3.11/site-packages/twisted/python/context.py", line 82, in callWithContext
    return func(*args, **kw)
           ^^^^^^^^^^^^^^^^^

  File "/home/morgan-freeman/Workspace/GlobaLeaks/backend/globaleaks/orm.py", line 186, in _wrap
    result = function(session, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/morgan-freeman/Workspace/GlobaLeaks/backend/globaleaks/orm.py", line 217, in tw
    return f(session, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/morgan-freeman/Workspace/GlobaLeaks/backend/globaleaks/handlers/admin/https.py", line 77, in db_acme_cert_request
    https_cert, https_chain = letsencrypt.request_new_certificate(hostname,
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/morgan-freeman/Workspace/GlobaLeaks/backend/globaleaks/utils/letsencrypt.py", line 79, in request_new_certificate
    client.net.account = client.new_account(new_reg)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/morgan-freeman/Workspace/GlobaLeaks/backend/env/lib/python3.11/site-packages/acme/client.py", line 630, in new_account
    response = self._post(self.directory['newAccount'], new_account)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/morgan-freeman/Workspace/GlobaLeaks/backend/env/lib/python3.11/site-packages/acme/client.py", line 101, in _post
    return [self.net.post](http://self.net.post/)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/morgan-freeman/Workspace/GlobaLeaks/backend/env/lib/python3.11/site-packages/acme/client.py", line 1269, in post
    return self._post_once(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/morgan-freeman/Workspace/GlobaLeaks/backend/env/lib/python3.11/site-packages/acme/client.py", line 1283, in _post_once
    response = self._check_response(response, content_type=content_type)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/morgan-freeman/Workspace/GlobaLeaks/backend/env/lib/python3.11/site-packages/acme/client.py", line 1128, in _check_response
    raise messages.Error.from_json(jobj)

acme.messages.Error: urn:ietf:params:acme:error:badPublicKey :: The JWS was signed by a public key the server does not support :: key size not supported: 1024

### Proposed solution

Let's Encrypt has increased their minimum recommended key size to 2048 bits or higher for security reasons.

**Comment by evilaliv3** [comment]
@msmannan00:  guess you are getting this error when running globaleaks in development mode.

In development mode for efficiency reasons we always generated a key of 1024 bits to run tests more faster but that causes incompatibility with letsencrypt.
