### ISSUE TITLE
I have received a number (3) odd reports.  These reports cause a DB-API IntegrityError and I receive 60 or so emails with error reports.

### ISSUE THREAD

**Issue by nigeltrego** [globaleaks/GlobaLeaks#4006]
### What version of GlobaLeaks are you using?

4.14.3

### What browser(s) are you seeing the problem on?

Safari

### What operating system(s) are you seeing the problem on?

macOS

### Describe the issue

I have received a number (3) odd reports.  These reports cause a DB-API IntegrityError and I receive 60 or so emails with error reports.  I have attached screen shots of the spurious reports.  The error emails contain the following text:-

Platform: 
Host: leaks.zeon.eu (rd6lbqjf25qz6eckk2ugbz56c6tav64m3m3nxo7hgqf3g32z5o7zu7ad.onion)
Version: 4.14.3

sqlalchemy.exc.IntegrityError Wraps a DB-API IntegrityError.

Traceback (most recent call last):

  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1236, in _execute_context
    cursor, statement, parameters, context

  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/default.py", line 536, in do_execute
    cursor.execute(statement, parameters)

sqlite3.IntegrityError: UNIQUE constraint failed: internaltip.tid, internaltip.progressive

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "/usr/lib/python3/dist-packages/twisted/python/threadpool.py", line 250, in inContext
    result = inContext.theWork()

  File "/usr/lib/python3/dist-packages/twisted/python/threadpool.py", line 266, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)

  File "/usr/lib/python3/dist-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)

  File "/usr/lib/python3/dist-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)

  File "/usr/lib/python3/dist-packages/globaleaks/orm.py", line 185, in _wrap
    result = function(session, *args, **kwargs)

  File "/usr/lib/python3/dist-packages/globaleaks/handlers/whistleblower/submission.py", line 300, in create_submission
    return db_create_submission(session, tid, request, user_session, client_using_tor, client_using_mobile)

  File "/usr/lib/python3/dist-packages/globaleaks/handlers/whistleblower/submission.py", line 232, in db_create_submission
    session.flush()

  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/session.py", line 2446, in flush
    self._flush(objects)

  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/session.py", line 2584, in _flush
    transaction.rollback(_capture_exception=True)

  File "/usr/lib/python3/dist-packages/sqlalchemy/util/langhelpers.py", line 67, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)

  File "/usr/lib/python3/dist-packages/sqlalchemy/util/compat.py", line 277, in reraise
    raise value

  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/session.py", line 2544, in _flush
    flush_context.execute()

  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/unitofwork.py", line 416, in execute
    rec.execute(self)

  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/unitofwork.py", line 583, in execute
    uow,

  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/persistence.py", line 245, in save_obj
    insert,

  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/persistence.py", line 1116, in _emit_insert_statements
    statement, params

  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 980, in execute
    return meth(self, multiparams, params)

  File "/usr/lib/python3/dist-packages/sqlalchemy/sql/elements.py", line 273, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)

  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1099, in _execute_clauseelement
    distilled_params,

  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1240, in _execute_context
    e, statement, parameters, cursor, context

  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1458, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)

  File "/usr/lib/python3/dist-packages/sqlalchemy/util/compat.py", line 296, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)

  File "/usr/lib/python3/dist-packages/sqlalchemy/util/compat.py", line 276, in reraise
    raise value.with_traceback(tb)

  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1236, in _execute_context
    cursor, statement, parameters, context

  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/default.py", line 536, in do_execute
    cursor.execute(statement, parameters)

sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) UNIQUE constraint failed: internaltip.tid, internaltip.progressive [SQL: 'INSERT INTO internaltip (id, tid, creation_date, update_date, context_id, operator_id, progressive, access_count, tor, mobile, score, expiration_date, reminder_date, enable_two_way_comments, enable_attachments, enable_whistleblower_identity, important, label, last_access, status, substatus, receipt_change_needed, receipt_hash, crypto_prv_key, crypto_pub_key, crypto_tip_pub_key, crypto_tip_prv_key, deprecated_crypto_files_pub_key) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)'] [parameters: ('14c9b9b5-7d24-4209-b1f6-ae1906f58008', 1, '2024-02-18 09:00:58.585821', '2024-02-18 09:00:58.585828', 'cef38ef1-1b1f-4061-affd-72946cf4c349', '', 12, 0, 0, 0, '0', '3000-01-01 00:00:00.000000', '3000-01-01 00:00:00.000000', 1, 1, 0, 0, '', '2024-02-18 09:00:58.585844', 'new', None, 0, '01j6u9ocDDMxtZGu9QDMxWoOwVrTHC9AVgd0bOWQMus=', '', '', '', '', '')] (Background on this error at: http://sqlalche.me/e/gkpj)
![Screenshot 2024-02-18 at 17 22 20](https://github.com/globaleaks/GlobaLeaks/assets/151574147/ce3a2f4c-6400-4f5d-9b1b-bb5fbdff4ba8)
![Screenshot 2024-02-18 at 17 22 13](https://github.com/globaleaks/GlobaLeaks/assets/151574147/664b020d-8ab9-43e1-b0e6-c0465c929d87)
![Screenshot 2024-02-18 at 17 21 02](https://github.com/globaleaks/GlobaLeaks/assets/151574147/818127ac-304b-474c-92d5-b4ffa904d084)

**Comment by evilaliv3** [comment]
Hello @nigeltrego 

I guess someone tried to automated reports; the exception that you received is just a controlled log that prevented damage.

You could just ignore the situation if it does not repeat.
