### ISSUE TITLE
Error on nacl.exceptions.CryptoError library

### ISSUE THREAD

**Issue by clsbn** [globaleaks/GlobaLeaks#4111]
### What version of GlobaLeaks are you using?

4.15.5

### What browser(s) are you seeing the problem on?

All

### What operating system(s) are you seeing the problem on?

macOS

### Describe the issue

Trying to download a PDF attachment of a year-old report, uploaded with the current version of Globaleaks at the time, results in an exception that causes a notification to be sent to the site administrators reporting the following:

```
..........
nacl.exceptions.CryptoError
   Base exception for all nacl related errors


Traceback (most recent call last):

 File "/usr/lib/python3/dist-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
   result = g.send(result)

 File "/usr/lib/python3/dist-packages/globaleaks/handlers/recipient/rtip.py", line 1245, in get
   filelocation = GCE.streaming_encryption_open('DECRYPT', tip_prv_key, filelocation)

 File "/usr/lib/python3/dist-packages/globaleaks/utils/crypto.py", line 307, in streaming_encryption_open
   return _StreamingEncryptionObject(mode, user_key, filepath)

 File "/usr/lib/python3/dist-packages/globaleaks/utils/crypto.py", line 137, in __init__
   self.key = _GCE.asymmetric_decrypt(self.user_key, x)

 File "/usr/lib/python3/dist-packages/globaleaks/utils/crypto.py", line 303, in asymmetric_decrypt
   return SealedBox(prv_key).decrypt(data)

 File "/usr/lib/python3/dist-packages/nacl/public.py", line 358, in decrypt
   plaintext = nacl.bindings.crypto_box_seal_open(

 File "/usr/lib/python3/dist-packages/nacl/bindings/crypto_box.py", line 317, in crypto_box_seal_open
   ensure(res == 0, "An error occurred trying to decrypt the message",

 File "/usr/lib/python3/dist-packages/nacl/exceptions.py", line 81, in ensure
   raise raising(*args)

nacl.exceptions.CryptoError: An error occurred trying to decrypt the message
```__

### Proposed solution

Downloading should also be possible with later versions of software or cryptographic libraries.

**Comment by evilaliv3** [comment]
Thank you @clsbn 

Actually you are not incurring in a bug of the current software but in a sort of corruption of your data, in which you should have incurred in August 2023 running the release 4.12.X that unfortunately was containing a bug on migration.
The bug was promptly identified, fixed and we issued immediate patches and instructions for remediation and all was documented on ticket https://github.com/globaleaks/GlobaLeaks/issues/3606 but unfortunately after one year of operations your chances to recover those files are very limited since you would need a backup of your system data of 1 year ago made before updating to release 4.12.X
