### ISSUE TITLE
When performing a large number of requests we get a cyclone error

### ISSUE THREAD

**Issue by hellais** [globaleaks/GlobaLeaks#617]
To reproduce (tested on OS): 

* Run `ab -n 10000 -c 100 http://127.0.0.1:8082/node`

* Wait for the memory consumption to go above 200-300 MB

* Kill the ab command

After a few seconds you will see globaleaks will start spitting out this insane amount of output:

```
2013-09-10 15:33:45+0200 [ ] Request closed
2013-09-10 15:33:45+0200 Cannot send error response after headers written
2013-09-10 15:33:45+0200 Unhandled error in Deferred:
2013-09-10 15:33:45+0200 Unhandled Error
	Traceback (most recent call last):
	  File "/Users/y/.virtualenvs/glbackend/lib/python2.7/site-packages/twisted/internet/defer.py", line 1126, in gotResult
	    _inlineCallbacks(r, g, deferred)
	  File "/Users/y/.virtualenvs/glbackend/lib/python2.7/site-packages/twisted/internet/defer.py", line 1116, in _inlineCallbacks
	    deferred.errback()
	  File "/Users/y/.virtualenvs/glbackend/lib/python2.7/site-packages/twisted/internet/defer.py", line 421, in errback
	    self._startRunCallbacks(fail)
	  File "/Users/y/.virtualenvs/glbackend/lib/python2.7/site-packages/twisted/internet/defer.py", line 488, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/Users/y/.virtualenvs/glbackend/lib/python2.7/site-packages/twisted/internet/defer.py", line 575, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/Users/y/.virtualenvs/glbackend/lib/python2.7/site-packages/cyclone/web.py", line 1111, in _execute_failure
	    return self._handle_request_exception(err)
	  File "/Users/y/code/GL/GLBackend/globaleaks/handlers/base.py", line 531, in _handle_request_exception
	    return self.send_error(500, exception=e)
	  File "/Users/y/.virtualenvs/glbackend/lib/python2.7/site-packages/cyclone/web.py", line 761, in send_error
	    self.finish()
	  File "/Users/y/.virtualenvs/glbackend/lib/python2.7/site-packages/cyclone/web.py", line 742, in finish
	    self.request.finish()
	  File "/Users/y/.virtualenvs/glbackend/lib/python2.7/site-packages/cyclone/httpserver.py", line 348, in finish
	    self.connection.finish()
	  File "/Users/y/.virtualenvs/glbackend/lib/python2.7/site-packages/cyclone/httpserver.py", line 117, in finish
	    assert self._request, "Request closed"
	exceptions.AssertionError: Request closed
```

**Comment by evilaliv3** [comment]
Doing a review of the ticket related to memory leaks i've found this and retested using:
ab -n 10000 -c 100 http://127.0.0.1:8082/node

as this was the test used by hellais, and the memory is no more growing at all on the /node request i consider closed this issue.
