### ISSUE TITLE
Exception from adopter AlreadyCalledError

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#647]
We received a flood / storm of exception from an adopter.

This should be properly catched and managed

Source: Linux XXXXX XXXXXX-generic #46-Ubuntu SMP Fri Jul 27 17:03:23 UTC 2012 x86_64

Version: 2.27.1
twisted.internet.defer.AlreadyCalledError None
Traceback (most recent call last):

  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 575, in _runCallbacks
    current.result = callback(current.result, *args, **kw)

  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 380, in callback
    self._startRunCallbacks(result)

  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 481, in _startRunCallbacks
    raise AlreadyCalledError

AlreadyCalledError

**Comment by evilaliv3** [comment]
closing as outdated.
