### ISSUE TITLE
Exception from GLBackend from update_node() "OverflowError: long too big to convert"

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#702]
To be investigated, tracked down and protected from this condition.

"notes: avevo inserito da qualche parte nella interfaccia di admin un campo
lungo, mi pare nella configurazione dei contesti o dei receivers."

Source: Linux remotehost 3.5.0-41-generic #64~precise1-Ubuntu SMP Thu Sep 12 16:50:04 UTC 2013 x86_64
Version: 2.28.3
OverflowError Result too large to be represented.
Traceback (most recent call last):

  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1068, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)

  File "/usr/local/lib/python2.7/dist-packages/twisted/python/failure.py", line 389, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)

  File "/data/devel/globaleaks/GLBackend/globaleaks/handlers/admin.py", line 651, in put
    yield update_node(request, self.request.language)

  File "/usr/local/lib/python2.7/dist-packages/twisted/python/threadpool.py", line 191, in _worker
    result = context.call(ctx, function, _args, *_kwargs)

  File "/usr/local/lib/python2.7/dist-packages/twisted/python/context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, _args, *_kw)

  File "/usr/local/lib/python2.7/dist-packages/twisted/python/context.py", line 81, in callWithContext
    return func(_args,_*kw)

  File "/data/devel/globaleaks/GLBackend/globaleaks/settings.py", line 621, in _wrap
    self.store.commit()

  File "/usr/local/lib/python2.7/dist-packages/storm/store.py", line 136, in commit
    self.flush()

  File "/usr/local/lib/python2.7/dist-packages/storm/store.py", line 501, in flush
    self._flush_one(obj_info)

  File "/usr/local/lib/python2.7/dist-packages/storm/store.py", line 558, in _flush_one
    self._connection.execute(expr, noresult=True)

  File "/usr/local/lib/python2.7/dist-packages/storm/database.py", line 241, in execute
    raw_cursor = self.raw_execute(statement, params)

  File "/usr/local/lib/python2.7/dist-packages/storm/databases/sqlite.py", line 159, in raw_execute
    return Connection.raw_execute(self, statement, params)

  File "/usr/local/lib/python2.7/dist-packages/storm/database.py", line 374, in raw_execute
    self._run_execution(raw_cursor, args, params, statement)

  File "/usr/local/lib/python2.7/dist-packages/storm/database.py", line 388, in _run_execution
    self._check_disconnect(raw_cursor.execute, *args)

  File "/usr/local/lib/python2.7/dist-packages/storm/database.py", line 454, in _check_disconnect
    return function(_args, *_kwargs)

OverflowError: long too big to convert
##

**Comment by NSkelsey** [comment]
Related to #1792
