### ISSUE TITLE
Unable to Open Database File trigger an unhandled exception

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#706]
Unable to Open Database File trigger an unhandled exception.

This ticket is about handling properly this specific issue, by logging it with a very big warning in the user console and by writing a proper error message in the log file files of globaleaks.

Source: Linux XXXXXXXXX 3.10.13-jb1 #3 SMP Fri Oct 4 11:51:31 CEST 2013 i686
Version: 2.28.9
sqlite3.OperationalError None
Traceback (most recent call last):

  File "/usr/lib/python2.7/dist-packages/globaleaks/jobs/delivery_sched.py", line 355, in operation
    info_created_tips = yield tip_creation()

  File "/usr/local/lib/python2.7/dist-packages/twisted/python/threadpool.py", line 191, in _worker
    result = context.call(ctx, function, *args, **kwargs)

  File "/usr/local/lib/python2.7/dist-packages/twisted/python/context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)

  File "/usr/local/lib/python2.7/dist-packages/twisted/python/context.py", line 81, in callWithContext
    return func(*args,**kw)

  File "/usr/lib/python2.7/dist-packages/globaleaks/settings.py", line 600, in _wrap
    self.store = self.get_store()

  File "/usr/lib/python2.7/dist-packages/globaleaks/settings.py", line 593, in get_store
    return zstorm.get(GLSetting.store_name)

  File "/usr/local/lib/python2.7/dist-packages/storm/zope/zstorm.py", line 177, in get
    return self.create(name, default_uri)

  File "/usr/local/lib/python2.7/dist-packages/storm/zope/zstorm.py", line 153, in create
    store = Store(database)

  File "/usr/local/lib/python2.7/dist-packages/storm/store.py", line 73, in __init__
    self._connection = database.connect(self._event)

  File "/usr/local/lib/python2.7/dist-packages/storm/database.py", line 493, in connect
    return self.connection_factory(self, event)

  File "/usr/local/lib/python2.7/dist-packages/storm/database.py", line 188, in __init__
    self._raw_connection = self._database.raw_connect()

  File "/usr/local/lib/python2.7/dist-packages/storm/databases/sqlite.py", line 192, in raw_connect
    isolation_level=None)

OperationalError: unable to open database file

**Comment by vecna** [comment]
This error is two years old, closing because is not happening since then.

**Comment by fpietrosanti** [comment]
Re-opening for handling it
