### ISSUE TITLE
Exception from adopter on get_files_receiver()

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#717]
Version: 2.27.17
TypeError Inappropriate argument type.
Traceback (most recent call last):

  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1070, in _inlineCallbacks
    result = g.send(result)

  File "/usr/lib/python2.7/dist-packages/globaleaks/handlers/tip.py", line 356, in get
    answer[\\'files\\'] = yield get_files_receiver(self.current_user[\\'user_id\\'], tip_id)

TypeError: \\'NoneType\\' object has no attribute \\'__getitem__\\'

**Comment by evilaliv3** [comment]
outdated! gotcha bitcha!
