### ISSUE TITLE
Too many open files error in /dev/shm

### ISSUE THREAD

**Issue by vecna** [globaleaks/GlobaLeaks#805]
@evilaliv3 

    2014-02-10 10:54:01+0100 IOError: [Errno 24] Too many open files: '/dev/shm/globaleaks/90ccad3b'
    2014-02-10 10:54:06+0100 Could not accept new connection (EMFILE)
    2014-02-10 10:54:06+0100 [ ] Malformed HTTP request from 127.0.0.1: [Errno 24] Too many open files: '/dev/shm/globaleaks/ee83f914'
    2014-02-10 10:54:06+0100 Exception KeyError: ('file',) in Traceback (most recent call last):
    2014-02-10 10:54:06+0100   File "/home/qq/Dev/GLBackend/globaleaks/handlers/base.py", line 114, in _on_headers
    2014-02-10 10:54:06+0100   File "/home/qq/Dev/GLBackend/globaleaks/security.py", line 45, in __init__

![failshm](https://f.cloud.github.com/assets/89555/2124205/d24d10f6-9239-11e3-890f-5e771d3f9ef1.png)

**Comment by evilaliv3** [comment]
closing as outdated.
