### ISSUE TITLE
Exception from Adopter on zipstream.py IOError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#816]
Source: Linux VPS-xxxxx 3.2.0-29-generic #46-Ubuntu SMP Fri Jul 27 17:03:23 UTC 2012 x86_64
Version: 2.54
IOError I/O operation failed.
Traceback (most recent call last):

  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1099, in _inlineCallbacks
    result = g.send(result)

  File "/usr/lib/python2.7/dist-packages/globaleaks/handlers/collection.py", line 155, in get
    for data in ZipStream(files_dict, opts[\\'compression_type\\']):

  File "/usr/lib/python2.7/dist-packages/globaleaks/utils/zipstream.py", line 227, in __iter__
    for data in self.zip_file(f[\\'path\\'], f[\\'name\\']):

  File "/usr/lib/python2.7/dist-packages/globaleaks/utils/zipstream.py", line 272, in zip_file
    with open(filename, "rb") as fp:

IOError: [Errno 2] No such file or directory: u\\'/var/globaleaks/files/submission/0MGuUJM.SOTGEZJK_e873dea0.aes\\'

**Comment by evilaliv3** [comment]
this is outdated and it didn't re-happen so probably it has been fixed.
