### ISSUE TITLE
UnicodeEncodeError Unicode encoding error

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#886]
Source: Linux XXX #1 SMP Tue Mar 18 15:21:47 CET 2014 i686
Version: 2.60.9
UnicodeEncodeError Unicode encoding error.
Traceback (most recent call last):

  File "/usr/local/lib/python2.7/dist-packages/cyclone/web.py", line 1073, in _deferred_handler
    result = function(*args, **kwargs)

  File "/usr/local/lib/python2.7/dist-packages/cyclone/web.py", line 1644, in get
    if os.path.isdir(abspath) and self.default_filename is not None:

  File "/usr/lib/python2.7/genericpath.py", line 41, in isdir
    st = os.stat(s)

UnicodeEncodeError: \\'ascii\\' codec can\\'t encode character u\\'\\\\xa0\\' in position 31: ordinal not in range(128

**Comment by evilaliv3** [comment]
this ticket is old and the error is not happening since time so probably it has been fixed.
