### ISSUE TITLE
GLBackend Exception 2.60.10 on Cannot write() after finish(). 

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#915]
Source: Linux leck 3.11.0-24-generic #41~precise1-Ubuntu SMP Wed Jun 11 13:15:06 UTC 2014 x86_64
Version: 2.60.10
RuntimeError Unspecified run-time error.
Traceback (most recent call last):

  File "/usr/local/lib/python2.7/dist-packages/cyclone/web.py", line 1073, in _deferred_handler
    result = function(*args, **kwargs)

  File "/usr/local/lib/python2.7/dist-packages/cyclone/web.py", line 1687, in get
    self.write(data)

  File "/usr/lib/python2.7/dist-packages/globaleaks/handlers/base.py", line 520, in write
    RequestHandler.write(self, chunk)

  File "/usr/local/lib/python2.7/dist-packages/cyclone/web.py", line 519, in write
    raise RuntimeError("Cannot write() after finish().  May be caused "

RuntimeError: Cannot write() after finish().  May be caused by using async operations without the @asynchronous decorator.

**Comment by evilaliv3** [comment]
this should be fixed now as all explicit .write() performed by globaleaks are now enclosed inside a try/except construct
