### ISSUE TITLE
TTLExpired error from socks5ErrorMap trigger an unhandled stackexception

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#984]
TTLExpired error from socks5ErrorMap trigger an unhandled stackexception .

This condition should be handled gracefully with a retry, properly logged to log files and avoid triggering an unhandled exception.

Source: Linux qq 3.13.0-34-generic #60-Ubuntu SMP Wed Aug 13 15:49:09 UTC 2014 i686
Version: 2.60.16
txsocksx.errors.TTLExpired
    TTL expired ( 6 )

Traceback (most recent call last):

  File "/home/qq/.virtualenvs/glenv/local/lib/python2.7/site-packages/ometa/protocol.py", line 53, in dataReceived
    self._parser.receive(data)

  File "/home/qq/.virtualenvs/glenv/local/lib/python2.7/site-packages/ometa/tube.py", line 41, in receive
    status = self._interp.receive(data)

  File "/home/qq/.virtualenvs/glenv/local/lib/python2.7/site-packages/ometa/interp.py", line 48, in receive
    for x in self.next:

  File "/home/qq/.virtualenvs/glenv/local/lib/python2.7/site-packages/ometa/interp.py", line 166, in apply
    for x in self._apply(f, ruleName, argvals):

  File "/home/qq/.virtualenvs/glenv/local/lib/python2.7/site-packages/ometa/interp.py", line 104, in _apply
    for x in rule():

  File "/home/qq/.virtualenvs/glenv/local/lib/python2.7/site-packages/ometa/interp.py", line 245, in parse_Or
    for x in self._eval(subexpr):

  File "/home/qq/.virtualenvs/glenv/local/lib/python2.7/site-packages/ometa/interp.py", line 230, in parse_And
    for x in self._eval(subexpr):

  File "/home/qq/.virtualenvs/glenv/local/lib/python2.7/site-packages/ometa/interp.py", line 423, in parse_Action
    val = eval(expr.data, self.globals, self._localsStack[-1])

  File "<string>", line 1, in <module>

  File "/home/qq/.virtualenvs/glenv/local/lib/python2.7/site-packages/txsocksx/client.py", line 153, in serverResponse
    raise e.socks5ErrorMap.get(status)()

TTLExpired
##

**Comment by vecna** [comment]
I don't know which part of code can raise this stuff, @evilaliv3 @mmaker @hellais any ideas ?

**Comment by evilaliv3** [comment]
i verified this few days ago. propbably in my case i simply powered of the network wifi that was able to cause the same behaviour.

**Comment by hellais** [comment]
This is an error being raised by `txsocksx` as the traceback indicates.

To properly handle this you should handle either all the `SOCKSError` subclasses (https://github.com/habnabit/txsocksx/blob/master/txsocksx/errors.py) or a subset of them and if it's a non permanent failure issue a retry.
As an example you can check out how we handle retries inside of ooniprobe for these sorts of cases: https://github.com/TheTorProject/ooni-probe/blob/master/ooni/oonibclient.py#L52

**Comment by evilaliv3** [comment]
thank you @hellais.

@origliante can you take care also of this as part of your duties while working on notification failures debug improval (https://github.com/globaleaks/GlobaLeaks/issues/214) and notifications unit testing (https://github.com/globaleaks/GlobaLeaks/issues/190)?

**Comment by NSkelsey** [comment]
I am going to high jack this thread with a similar issue discovered on a development node I am running. This is an issue high jack because the exception generated here is the same but it was generated via a different code path. The exception below was triggered via the evaluation of the `Exit Nodes Refresh Job` which did not exist until v2.70 series.

```
2017-09-22 07:22:12+0000 [-] Starting factory &lt;txsocksx.client.SOCKS5ClientFactory instance at 0x7f3dad9adb90&gt;
2017-09-22 07:22:14+0000 [-] Stopping factory &lt;txsocksx.client.SOCKS5ClientFactory instance at 0x7f3dad9adb90&gt;
2017-09-22 08:22:12+0000 [-] Starting factory &lt;txsocksx.client.SOCKS5ClientFactory instance at 0x7f3dadc33128&gt;
2017-09-22 08:22:17+0000 [-] [E] Job Exit Nodes Refresh died with runtime 2302.4763 [low: 831.0000, high: 49955.0000]
2017-09-22 08:22:17+0000 [-] Traceback (most recent call last):
2017-09-22 08:22:17+0000 [-]   File &quot;&#47;usr&#47;lib&#47;python2.7&#47;dist-packages&#47;globaleaks&#47;jobs&#47;base.py&quot;, line 44, in run
2017-09-22 08:22:17+0000 [-]     yield self.operation()
2017-09-22 08:22:17+0000 [-]   File &quot;&#47;usr&#47;lib&#47;python2.7&#47;dist-packages&#47;twisted&#47;internet&#47;defer.py&quot;, line 1126, in _inlineCallbacks
2017-09-22 08:22:17+0000 [-]     result = result.throwExceptionIntoGenerator(g)
2017-09-22 08:22:17+0000 [-]   File &quot;&#47;usr&#47;lib&#47;python2.7&#47;dist-packages&#47;twisted&#47;python&#47;failure.py&quot;, line 389, in throwExceptionIntoGenerator
2017-09-22 08:22:17+0000 [-]     return g.throw(self.type, self.value, self.tb)
2017-09-22 08:22:17+0000 [-]   File &quot;&#47;usr&#47;lib&#47;python2.7&#47;dist-packages&#47;globaleaks&#47;jobs&#47;exit_nodes_refresh_sched.py&quot;, line 22, in operation
2017-09-22 08:22:17+0000 [-]     yield GLSettings.appstate.tor_exit_set.update(net_agent)
2017-09-22 08:22:17+0000 [-]   File &quot;&#47;usr&#47;lib&#47;python2.7&#47;dist-packages&#47;ometa&#47;protocol.py&quot;, line 53, in dataReceived
2017-09-22 08:22:17+0000 [-]     self._parser.receive(data)
2017-09-22 08:22:17+0000 [-]   File &quot;&#47;usr&#47;lib&#47;python2.7&#47;dist-packages&#47;ometa&#47;tube.py&quot;, line 41, in receive
2017-09-22 08:22:17+0000 [-]     status = self._interp.receive(data)
2017-09-22 08:22:17+0000 [-]   File &quot;&#47;usr&#47;lib&#47;python2.7&#47;dist-packages&#47;ometa&#47;interp.py&quot;, line 48, in receive
2017-09-22 08:22:17+0000 [-]     for x in self.next:
2017-09-22 08:22:17+0000 [-]   File &quot;&#47;usr&#47;lib&#47;python2.7&#47;dist-packages&#47;ometa&#47;interp.py&quot;, line 166, in apply
2017-09-22 08:22:17+0000 [-]     for x in self._apply(f, ruleName, argvals):
2017-09-22 08:22:17+0000 [-]   File &quot;&#47;usr&#47;lib&#47;python2.7&#47;dist-packages&#47;ometa&#47;interp.py&quot;, line 104, in _apply
2017-09-22 08:22:17+0000 [-]     for x in rule():
2017-09-22 08:22:17+0000 [-]   File &quot;&#47;usr&#47;lib&#47;python2.7&#47;dist-packages&#47;ometa&#47;interp.py&quot;, line 245, in parse_Or
2017-09-22 08:22:17+0000 [-]     for x in self._eval(subexpr):
2017-09-22 08:22:17+0000 [-]   File &quot;&#47;usr&#47;lib&#47;python2.7&#47;dist-packages&#47;ometa&#47;interp.py&quot;, line 230, in parse_And
2017-09-22 08:22:17+0000 [-]     for x in self._eval(subexpr):
2017-09-22 08:22:17+0000 [-]   File &quot;&#47;usr&#47;lib&#47;python2.7&#47;dist-packages&#47;ometa&#47;interp.py&quot;, line 423, in parse_Action
2017-09-22 08:22:17+0000 [-]     val = eval(expr.data, self.globals, self._localsStack[-1])
2017-09-22 08:22:17+0000 [-]   File &quot;&lt;string&gt;&quot;, line 1, in &lt;module&gt;
2017-09-22 08:22:17+0000 [-]   File &quot;&#47;usr&#47;lib&#47;python2.7&#47;dist-packages&#47;txsocksx&#47;client.py&quot;, line 153, in serverResponse
2017-09-22 08:22:17+0000 [-]     raise e.socks5ErrorMap.get(status)()
2017-09-22 08:22:17+0000 [-] TTLExpired
2017-09-22 08:22:17+0000 [-] [E] Unhandled exception raised:
2017-09-22 08:22:17+0000 [-] [E] txsocksx.errors.TTLExpired &#92;n    TTL expired ( 6 )&#92;n    &#92;n&#92;nTraceback (most recent call last):&#92;n&#92;n  File &quot;&#47;usr&#47;lib&#47;python2.7&#47;dist-packages&#47;globaleaks&#47;jobs&#47;base.py&quot;, line 44, in run&#92;n    yield self.operation()&#92;n&#92;n  File &quot;&#47;usr&#47;lib&#47;python2.7&#47;dist-packages&#47;twisted&#47;internet&#47;defer.py&quot;, line 1126, in _inlineCallbacks&#92;n    result = result.throwExceptionIntoGenerator(g)&#92;n&#92;n  File &quot;&#47;usr&#47;lib&#47;python2.7&#47;dist-packages&#47;twisted&#47;python&#47;failure.py&quot;, line 389, in throwExceptionIntoGenerator&#92;n    return g.throw(self.type, self.value, self.tb)&#92;n&#92;n  File &quot;&#47;usr&#47;lib&#47;python2.7&#47;dist-packages&#47;globaleaks&#47;jobs&#47;exit_nodes_refresh_sched.py&quot;, line 22, in operation&#92;n    yield GLSettings.appstate.tor_exit_set.update(net_agent)&#92;n&#92;n  File &quot;&#47;usr&#47;lib&#47;python2.7&#47;dist-packages&#47;ometa&#47;protocol.py&quot;, line 53, in dataReceived&#92;n    self._parser.receive(data)&#92;n&#92;n  File &quot;&#47;usr&#47;lib&#47;python2.7&#47;dist-packages&#47;ometa&#47;tube.py&quot;, line 41, in receive&#92;n    status = self._interp.receive(data)&#92;n&#92;n  File &quot;&#47;usr&#47;lib&#47;python2.7&#47;dist-packages&#47;ometa&#47;interp.py&quot;, line 48, in receive&#92;n    for x in self.next:&#92;n&#92;n  File &quot;&#47;usr&#47;lib&#47;python2.7&#47;dist-packages&#47;ometa&#47;interp.py&quot;, line 166, in apply&#92;n    for x in self._apply(f, ruleName, argvals):&#92;n&#92;n  File &quot;&#47;usr&#47;lib&#47;python2.7&#47;dist-packages&#47;ometa&#47;interp.py&quot;, line 104, in _apply&#92;n    for x in rule():&#92;n&#92;n  File &quot;&#47;usr&#47;lib&#47;python2.7&#47;dist-packages&#47;ometa&#47;interp.py&quot;, line 245, in parse_Or&#92;n    for x in self._eval(subexpr):&#92;n&#92;n  File &quot;&#47;usr&#47;lib&#47;python2.7&#47;dist-packages&#47;ometa&#47;interp.py&quot;, line 230, in parse_And&#92;n    for x in self._eval(subexpr):&#92;n&#92;n  File &quot;&#47;usr&#47;lib&#47;python2.7&#47;dist-packages&#47;ometa&#47;interp.py&quot;, line 423, in parse_Action&#92;n    val = eval(expr.data, self.globals, self._localsStack[-1])&#92;n&#92;n  File &quot;&lt;string&gt;&quot;, line 1, in &lt;module&gt;&#92;n&#92;n  File &quot;&#47;usr&#47;lib&#47;python2.7&#47;dist-packages&#47;txsocksx&#47;client.py&quot;, line 153, in serverResponse&#92;n    raise e.socks5ErrorMap.get(status)()&#92;n&#92;nTTLExpired&#92;n
2017-09-22 08:22:17+0000 [-] Stopping factory &lt;txsocksx.client.SOCKS5ClientFactory instance at 0x7f3dadc33128&gt;
2017-09-22 08:22:17+0000 [-] Starting factory &lt;txsocksx.client.SOCKS5ClientFactory instance at 0x7f3db18515a8&gt;
2017-09-22 08:22:28+0000 [-] Starting factory &lt;txsocksx.client.SOCKS5ClientFactory instance at 0x7f3db18497e8&gt;
2017-09-22 08:22:30+0000 [-] Stopping factory &lt;txsocksx.client.SOCKS5ClientFactory instance at 0x7f3db18515a8&gt;
2017-09-22 08:22:38+0000 [-] Stopping factory &lt;txsocksx.client.SOCKS5ClientFactory instance at 0x7f3db18497e8&gt
```

which generated the following mail:

```
Version: 2.72.3

txsocksx.errors.TTLExpired
    TTL expired ( 6 )


Traceback (most recent call last):

  File "/usr/lib/python2.7/dist-packages/globaleaks/jobs/base.py", line 44, in run
    yield self.operation()

  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1126, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)

  File "/usr/lib/python2.7/dist-packages/twisted/python/failure.py", line 389, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)

  File "/usr/lib/python2.7/dist-packages/globaleaks/jobs/exit_nodes_refresh_sched.py", line 22, in operation
    yield GLSettings.appstate.tor_exit_set.update(net_agent)

  File "/usr/lib/python2.7/dist-packages/ometa/protocol.py", line 53, in dataReceived
    self._parser.receive(data)

  File "/usr/lib/python2.7/dist-packages/ometa/tube.py", line 41, in receive
    status = self._interp.receive(data)

  File "/usr/lib/python2.7/dist-packages/ometa/interp.py", line 48, in receive
    for x in self.next:

  File "/usr/lib/python2.7/dist-packages/ometa/interp.py", line 166, in apply
    for x in self._apply(f, ruleName, argvals):

  File "/usr/lib/python2.7/dist-packages/ometa/interp.py", line 104, in _apply
    for x in rule():

  File "/usr/lib/python2.7/dist-packages/ometa/interp.py", line 245, in parse_Or
    for x in self._eval(subexpr):

  File "/usr/lib/python2.7/dist-packages/ometa/interp.py", line 230, in parse_And
    for x in self._eval(subexpr):

  File "/usr/lib/python2.7/dist-packages/ometa/interp.py", line 423, in parse_Action
    val = eval(expr.data, self.globals, self._localsStack[-1])

  File "<string>", line 1, in <module>

  File "/usr/lib/python2.7/dist-packages/txsocksx/client.py", line 153, in serverResponse
    raise e.socks5ErrorMap.get(status)()

TTLExpired
```

**Comment by NSkelsey** [comment]
This error is documented within the [rfc 1928](https://tools.ietf.org/html/rfc1928#section-6) the describes a normal SOCKS 5 proxy.

**Comment by NSkelsey** [comment]
The solution here is to include `TTLExpired` in a set of handled errors for jobs and functions (the hostname check currently) that initiate connections through the tor network (when `anonymize_outgoing_connections` is `true`).

This is being handled via extending the `on_error` handler for jobs that use a tor_agent to make external requests and leaving the handling within the `HostnameTestHandler` as it is.

**Comment by evilaliv3** [comment]
I agree. Go ahead @NSkelsey

**Comment by NSkelsey** [comment]
Fixed in 4289fe1.

**Comment by fpietrosanti** [comment]
Would it be an improvement to implement also a retry mechanism on that specific TTL Expired failure? If so, going to open a ticket

**Comment by evilaliv3** [comment]
Not generically @fpietrosanti; e.g. most of the times our functionalities when failing will have their opportunity to succed in a next cycle.

Case by case we could handle something different but i would avoid to implement ourself a retry.

@habnabit: does txsocksx offer any possibility to perform connections retries "automagically"?

**Comment by NSkelsey** [comment]
Unfortunately, the exception has reappeared as of 2.72.7. Its clear though that this exception is being generated in a different job. My hypothesis is that this is an unhandled exception in one of the mail sending jobs, because the exception is generated in a thread.

```
Version: 2.72.7

txsocksx.errors.TTLExpired
    TTL expired ( 6 )


Traceback (most recent call last):

  File "/usr/lib/python2.7/dist-packages/globaleaks/jobs/base.py", line 76, in run
    yield threads.deferToThread(self.operation)

  File "/usr/lib/python2.7/dist-packages/twisted/python/threadpool.py", line 246, in inContext
    result = inContext.theWork()

  File "/usr/lib/python2.7/dist-packages/twisted/python/threadpool.py", line 262, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)

  File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)

  File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 81, in callWithContext
    return func(*args,**kw)

  File "/usr/lib/python2.7/dist-packages/globaleaks/jobs/notification_sched.py", line 266, in operation
    self.spool_emails()

  File "/usr/lib/python2.7/dist-packages/globaleaks/jobs/notification_sched.py", line 261, in spool_emails
    threads.blockingCallFromThread(reactor, self.sendmail, mail)

  File "/usr/lib/python2.7/dist-packages/twisted/internet/threads.py", line 122, in blockingCallFromThread
    result.raiseException()

  File "/usr/lib/python2.7/dist-packages/ometa/protocol.py", line 53, in dataReceived
    self._parser.receive(data)

  File "/usr/lib/python2.7/dist-packages/ometa/tube.py", line 41, in receive
    status = self._interp.receive(data)

  File "/usr/lib/python2.7/dist-packages/ometa/interp.py", line 48, in receive
    for x in self.next:

  File "/usr/lib/python2.7/dist-packages/ometa/interp.py", line 166, in apply
    for x in self._apply(f, ruleName, argvals):

  File "/usr/lib/python2.7/dist-packages/ometa/interp.py", line 104, in _apply
    for x in rule():

  File "/usr/lib/python2.7/dist-packages/ometa/interp.py", line 245, in parse_Or
    for x in self._eval(subexpr):

  File "/usr/lib/python2.7/dist-packages/ometa/interp.py", line 230, in parse_And
    for x in self._eval(subexpr):

  File "/usr/lib/python2.7/dist-packages/ometa/interp.py", line 423, in parse_Action
    val = eval(expr.data, self.globals, self._localsStack[-1])

  File "<string>", line 1, in <module>

  File "/usr/lib/python2.7/dist-packages/txsocksx/client.py", line 153, in serverResponse
    raise e.socks5ErrorMap.get(status)()

TTLExpired
```

**Comment by NSkelsey** [comment]
In fact, the stack trace shows the failure in `notification_sched`

**Comment by evilaliv3** [comment]
@NSkelsey: this could be closed?

**Comment by NSkelsey** [comment]
`TTLExpired` exceptions are handled in `FAILURES_OUTGOING_TOR` for all `ExternNetJobs` so, I would say lets reopen the issue if we see issues on clear net requests. I'd say its handled.
